### ISSUE TITLE
Error when organSummaries encounters an organ of None type

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1006]
Recent changes by #977 likely introduced a bug that causes the following error when `get_cell_count()` encounters a `cell_suspension['organ']` value that contains a `None` type.

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 348, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 156, in repository_search
    return service.get_data(entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository.py", line 80, in get_data
    return self._get_items(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 54, in _get_items
    response = self._get_data(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 33, in _get_data
    entity_type=entity_type)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 529, in transform_request
    self.add_project_summaries(final_response['hits'], es_response['hits']['hits'])
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 715, in add_project_summaries
    hit['_source']['contents'].to_dict()
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 609, in __init__
    for count in organ_cell_count],
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 609, in <listcomp>
    for count in organ_cell_count],
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 113, in create_object_from_simple_count
    self.organType = count['key']
  File "/var/task/jsonobject/base.py", line 323, in __setattr__
    super(JsonObjectBase, self).__setattr__(name, value)
  File "/var/task/jsonobject/base_properties.py", line 79, in __set__
    instance[self.name] = value
  File "/var/task/jsonobject/base.py", line 295, in __setitem__
    wrapped, unwrapped = self.__unwrap(key, value)
  File "/var/task/jsonobject/base.py", line 292, in __unwrap
    return property_.unwrap(value)
  File "/var/task/jsonobject/base_properties.py", line 200, in unwrap
    self._update(wrapped, obj)
  File "/var/task/jsonobject/properties.py", line 145, in _update
    container.extend(extension)
  File "/var/task/jsonobject/containers.py", line 42, in extend
    *map(self._wrapper.unwrap, wrapped_list)
  File "/var/task/jsonobject/base_properties.py", line 288, in unwrap
    self.assert_type(obj)
  File "/var/task/jsonobject/base_properties.py", line 275, in assert_type
    '{0!r} not of type {1!r}'.format(obj, self._type)
jsonobject.exceptions.BadValueError: None not of type (<class 'str'>, <class 'str'>)
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-628)
┆Project Name: azul
┆Issue Number: AZUL-628

**Comment by theathorn** [comment]
Demoed 5/28/19.
