### ISSUE TITLE
ScanError in prod with unexpectedly high and inconsistent # of shards

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1031]
93 instances of these last week which isn't necessarily bad. What worries me is that the reported number of shards a mix of 64, 128, 192 and 265. I would expect that to consistently be 64.

```
Scroll request has only succeeded on 254 shards out of 256.: ScanError
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 155, in aggregate
    contributions = self._read_contributions(absolute_tallies)
  File "/var/task/azul/indexer.py", line 216, in _read_contributions
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/indexer.py", line 216, in <listcomp>
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/elasticsearch/helpers/__init__.py", line 394, in scan
    (resp['_shards']['successful'], resp['_shards']['total'])
elasticsearch.helpers.ScanError: Scroll request has only succeeded on 254 shards out of 256.
```

```
Scroll request has only succeeded on 186 shards out of 192.: ScanError
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 155, in aggregate
    contributions = self._read_contributions(absolute_tallies)
  File "/var/task/azul/indexer.py", line 216, in _read_contributions
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/indexer.py", line 216, in <listcomp>
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/elasticsearch/helpers/__init__.py", line 394, in scan
    (resp['_shards']['successful'], resp['_shards']['total'])
elasticsearch.helpers.ScanError: Scroll request has only succeeded on 186 shards out of 192.
```

```
Scroll request has only succeeded on 123 shards out of 128.: ScanError
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 155, in aggregate
    contributions = self._read_contributions(absolute_tallies)
  File "/var/task/azul/indexer.py", line 216, in _read_contributions
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/indexer.py", line 216, in <listcomp>
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/elasticsearch/helpers/__init__.py", line 394, in scan
    (resp['_shards']['successful'], resp['_shards']['total'])
elasticsearch.helpers.ScanError: Scroll request has only succeeded on 123 shards out of 128.
```

```
Scroll request has only succeeded on 58 shards out of 64.: ScanError
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 155, in aggregate
    contributions = self._read_contributions(absolute_tallies)
  File "/var/task/azul/indexer.py", line 216, in _read_contributions
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/indexer.py", line 216, in <listcomp>
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/elasticsearch/helpers/__init__.py", line 394, in scan
    (resp['_shards']['successful'], resp['_shards']['total'])
elasticsearch.helpers.ScanError: Scroll request has only succeeded on 58 shards out of 64.
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-645)
┆containerName: azul
┆Issue Number: AZUL-645

**Comment by hannes-ucsc** [comment]
I think the differing number of shards can be explained by the fact that reading of contributions can occur for only one entity type (and contribution index) or a mix of entity types. We currently have four entity types (and four contributions indices). If two contributions for two types need to be read. The number of shards to read from is going to be 128, for example, not 64.

**Comment by hannes-ucsc** [comment]
We now have five contributions indices: project, samples, files, bundles, cell_suspensions

**Comment by jessebrennan** [comment]
But aren't we only dealing with 4 shards? How does that get to 64?

**Comment by hannes-ucsc** [comment]
4 aggregate index shards, 64 contribution index shards.

**Comment by jessebrennan** [comment]
Duh! That makes sense then. So should this be closed in favor of #1093?

**Comment by hannes-ucsc** [comment]
Possibly, let me ponder this a bit more.

**Comment by jessebrennan** [comment]
@hannes-ucsc, let's readdress this soon.

**Comment by hannes-ucsc** [comment]
Please elaborate. What motivates the increased urgency?

**Comment by hannes-ucsc** [comment]
500 occurrence during most recent reindexing. It's possible that #1093 fixes but I wouldn't want to close this based on an intuition. We should attempt #1093 first and then revisit this.

**Comment by hannes-ucsc** [comment]
Not seen this in ages.
