### ISSUE TITLE
IT fails at times unless reindex has been run

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1174]
https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/2518 was the first run of the  integration test after https://github.com/DataBiosphere/azul/commit/d537d817ed5d7f6678756a7b57dd9b8425c0430e had been deployed to `dev`. That commit changed the contents of index documents by replacing all `null` (`None`) values with other discrete values, like `__null__` for string properties. The test ultimately fails detecting all bundles.

The indexer logs (/aws/lambda/azul-indexer-dev-write) contain failures like this:

```
Traceback (most recent call last):
  File "/var/task/app.py", line 159, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 277, in write
    indexer.aggregate(tallies)
  File "/var/task/azul/indexer.py", line 191, in aggregate
    contributions = self._read_contributions(total_tallies)
  File "/var/task/azul/indexer.py", line 252, in _read_contributions
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/indexer.py", line 252, in <listcomp>
    contributions = [Contribution.from_index(hit) for hit in hits]
  File "/var/task/azul/transformer.py", line 181, in from_index
    source = cls.translate_fields(hit['_source'], forward=False)
  File "/var/task/azul/transformer.py", line 128, in translate_fields
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 128, in <dictcomp>
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 128, in translate_fields
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 128, in <dictcomp>
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 130, in translate_fields
    return [cls.translate_fields(val, path=path, forward=forward) for val in source]
  File "/var/task/azul/transformer.py", line 130, in <listcomp>
    return [cls.translate_fields(val, path=path, forward=forward) for val in source]
  File "/var/task/azul/transformer.py", line 128, in translate_fields
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 128, in <dictcomp>
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 130, in translate_fields
    return [cls.translate_fields(val, path=path, forward=forward) for val in source]
  File "/var/task/azul/transformer.py", line 130, in <listcomp>
    return [cls.translate_fields(val, path=path, forward=forward) for val in source]
  File "/var/task/azul/transformer.py", line 128, in translate_fields
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 128, in <dictcomp>
    return {key: cls.translate_fields(val, path=path + (key,), forward=forward) for key, val in source.items()}
  File "/var/task/azul/transformer.py", line 134, in translate_fields
    return cls.translate_field(source, path=path, forward=forward)
  File "/var/task/azul/transformer.py", line 90, in translate_field
    return {-1: None, 0: False, 1: True}[value]
KeyError: None
```

This suggests that a None value was present in a contribution. That in turn suggests that the contribution had not been written by the integration test but leaked in from the index as it was before the test was run.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-733)
┆Project Name: azul
┆Issue Number: AZUL-733

**Comment by hannes-ucsc** [comment]
The same commit passed in the sandbox but the sandbox has a bundle prefix set.

**Comment by hannes-ucsc** [comment]
… which decreases the likelihood of an stale contribution from leaking in.

**Comment by theathorn** [comment]
Workaround is to purge the queues, run `make delete`, and restart the integration test job, and re-index at the end.

**Comment by jessebrennan** [comment]
This exact issue happened again with this morning's staging deployment. The workaround was successful.

**Comment by hannes-ucsc** [comment]
@jessebrennan proposes to simply override the version of the test bundles to be `now()` since `now()` is > than any version of any existing bundle, _select_latest() would always chose the test contribution.
