### ISSUE TITLE
Unsubscribed from subscriptions made in year old deployments.

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1217]
When trying to run `make unsubscribe`, the following exception is thrown:
```
Traceback (most recent call last):
  File "scripts/subscribe.py", line 42, in <module>
    main(sys.argv[1:])
  File "scripts/subscribe.py", line 31, in main
    creds = sm.get_secret_value(SecretId=config.secrets_manager_secret_name('indexer', 'google_service_account'))
  File "/Users/geryl/PycharmProjects/azul/.venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/geryl/PycharmProjects/azul/.venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
```

**Comment by hannes-ucsc** [comment]
This is not a problem. Deployments need to be maintained and upgraded periodically.
