### ISSUE TITLE
Indexer fails with KeyError in `all_units[relative]["_type"]`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#123]
In prod, a worker handling this notification 

```
[INFO]	2018-07-22T15:18:21.157Z	187f2e46-8dc2-11e8-87d5-c9887560a16b	Worker 13 handling notification {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.biomaterial_json'}}]}}}, 'subscription_id': '7607ae86-467a-475d-b8de-ce6741a50dce', 'transaction_id': '2117db72-16f4-44df-a9b0-4b4445fac74e', 'match': {'bundle_uuid': '2ea66de1-b931-460f-867c-b61570cfce45', 'bundle_version': '2018-07-17T201902.143372Z'}}
```

fails with

```
Exception in worker thread
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/app.py", line 127, in _index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 53, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 176, in create_documents
    relative_type = all_units[relative]["_type"]
KeyError: '0918a9ba-eb5e-45bd-87b0-68b3057efa14'
```

This is the only bundle in production for which this happens, but in integration this is very frequent. In our pursuit to catch-up with metadata changes since the preview release, this is low-hanging fruit methinks.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-97)
┆Project Name: azul
┆Issue Number: AZUL-97

**Comment by caaespin** [comment]
This code seems to be out of date. Please redeploy with updated code.
