### ISSUE TITLE
Index updated analysis bundles for Reprogrammed_Dendritic_Cells project

### ISSUE THREAD

**Issue by jlzamanian** [DataBiosphere/azul#1320]
The Reprogrammed_Dendritic_Cells project was updated using AUDR simple update to fix a typo. There are analysis bundles for this project. Their metadata were updated, but the workflows were not rerun after the update.

https://data.humancellatlas.org/explore/projects/116965f3-f094-4769-9d28-ae675c1b569c

According to the tracker (and reflected in the changed text on the browser project page), Azul has indexed the 3 updated primary bundles.

https://tracker.data.humancellatlas.org/?projectUUID=116965f3-f094-4769-9d28-ae675c1b569c

According to the tracker, Azul has not indexed the 3 updated analysis bundles. 

Parth queried both the DSS and Azul to find the discrepancy. Azul has the original analysis bundles in its index.

Bundles indexed in Azul 

```json
[
    {
        "bundleUuid": "cb88115c-75ef-4e8e-bbd7-a48e18960344",
        "bundleVersion": "2019-09-26T034726.748575Z"
    },
    {
        "bundleUuid": "1307154a-0396-4f2c-a1bf-4a2bf593b1a0",
        "bundleVersion": "2019-09-26T023342.740727Z"
    },
    {
        "bundleUuid": "52245757-73ba-43a2-a78d-0eba01cb4ce1",
        "bundleVersion": "2019-09-26T022557.424404Z"
    }
]
```

Latest analysis bundles available in DSS 

```json
{
    "cb88115c-75ef-4e8e-bbd7-a48e18960344": {
        "fqid": "cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-09-26T120958.020808Z",
        "uuid": "cb88115c-75ef-4e8e-bbd7-a48e18960344",
        "version": "2019-09-26T120958"
    },
    "52245757-73ba-43a2-a78d-0eba01cb4ce1": {
        "fqid": "52245757-73ba-43a2-a78d-0eba01cb4ce1.2019-09-26T120958.022205Z",
        "uuid": "52245757-73ba-43a2-a78d-0eba01cb4ce1",
        "version": "2019-09-26T120958"
    },
    "1307154a-0396-4f2c-a1bf-4a2bf593b1a0": {
        "fqid": "1307154a-0396-4f2c-a1bf-4a2bf593b1a0.2019-09-26T120958.019770Z",
        "uuid": "1307154a-0396-4f2c-a1bf-4a2bf593b1a0",
        "version": "2019-09-26T120958"
    }
}
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-813)
┆Project Name: azul
┆Issue Number: AZUL-813

**Comment by jlzamanian** [comment]
This may be the first time a project with analysis bundles has been updated and not rerun. It will be a common use case soon.

**Comment by hannes-ucsc** [comment]
These three bundles caused three exceptions in the Azul indexer:

```
[WARNING]	2019-09-26T12:57:19.437Z	29c5b7d4-87a2-5040-966f-e1d2307a28b8	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '9c9fa9a8-c1bd-490d-a96c-b399e3ff43e0', 'subscription_id': 'a8da236e-bd30-4f2f-bb69-2e6958c7087f', 'es_query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}]}}}, 'match': {'bundle_uuid': 'cb88115c-75ef-4e8e-bbd7-a48e18960344', 'bundle_version': '2019-09-26T120958.020808Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 182, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer.py", line 114, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 484, in transform
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 740, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 734, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 702, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 595, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: '906f8f09-deaa-40bb-bf50-27d2336b2dc4.zarr!expression_matrix!expression!32.5'
```


```
[WARNING]	2019-09-26T12:57:17.544Z	ef818a4e-f384-536c-a5bc-dc48445b7e00	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'c671b223-ccff-48e9-8e90-6c10951c1575', 'subscription_id': 'a8da236e-bd30-4f2f-bb69-2e6958c7087f', 'es_query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}]}}}, 'match': {'bundle_uuid': '52245757-73ba-43a2-a78d-0eba01cb4ce1', 'bundle_version': '2019-09-26T120958.022205Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 182, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer.py", line 114, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 484, in transform
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 740, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 734, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 702, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 595, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'a3352e34-e7ae-4ed0-b580-a10c2f7a3451.zarr!expression_matrix!gene_id!4'
```

```
[WARNING]	2019-09-26T12:57:17.482Z	9833e566-3d39-508e-96af-b3608af41de2	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '6d1d8c35-3b43-44bd-b239-665d467e5d4b', 'subscription_id': 'a8da236e-bd30-4f2f-bb69-2e6958c7087f', 'es_query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}]}}}, 'match': {'bundle_uuid': '1307154a-0396-4f2c-a1bf-4a2bf593b1a0', 'bundle_version': '2019-09-26T120958.019770Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 182, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer.py", line 114, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 484, in transform
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 740, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 734, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 703, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 702, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 595, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: '0e44628a-552b-4377-a262-26ef6cdfe104.zarr!expression_matrix!expression!32.0'
```

All key errors with the key being the name of a file in a bundle. Each time a different file name.

Let's examine the first bundle:

```python
from more_itertools import one
from hca.dss import DSSClient
import json
```


```python
dss = DSSClient()
manifest = list(dss.get_bundle.iterate(uuid='cb88115c-75ef-4e8e-bbd7-a48e18960344',
                                    version='2019-09-26T120958.020808Z',
                                    replica='aws',
                                    per_page=100)) # pages of 100 files
len(manifest)
```




    500



There are 500 files in the bundle? This can't be a coincidence, it must have to do with the bug.

I determined that metadata file `analysis_file_209.json` refers to a data file not mentioned in the bundle.
Let's get the manifest entry:


```python
manifest_entry = one(f for f in manifest if f['name'] == 'analysis_file_209.json')
print(json.dumps(manifest_entry, indent=4))
```

    {
        "content-type": "application/json; dcp-type=\"metadata/file\"",
        "crc32c": "6f2c0a94",
        "indexed": true,
        "name": "analysis_file_209.json",
        "s3_etag": "16217478ca7c4b010f05507d3d308584",
        "sha1": "319dd1b8f6483f024a55b39a59f6753481d5ae0f",
        "sha256": "406a3002f3b452ba6d1c3a6f68919dd72947c92009ccf8f75b116e6029ab15dc",
        "size": 534,
        "uuid": "73c5d66e-e552-470d-887e-4b2de4079a08",
        "version": "2019-09-26T033849.713000Z"
    }


And get the metadata file's content


```python
metadata_file = dss.get_file(uuid=manifest_entry['uuid'],
                            version=manifest_entry['version'],
                            replica='aws')
print(json.dumps(metadata_file, indent=4))
```

    {
        "describedBy": "https://schema.humancellatlas.org/type/file/6.0.0/analysis_file",
        "file_core": {
            "file_name": "906f8f09-deaa-40bb-bf50-27d2336b2dc4.zarr!expression_matrix!expression!32.5",
            "format": "unknown"
        },
        "schema_type": "file",
        "provenance": {
            "document_id": "73c5d66e-e552-470d-887e-4b2de4079a08",
            "submission_date": "2019-09-26T03:13:39.036Z",
            "update_date": "2019-09-26T03:38:49.713Z",
            "schema_major_version": 6,
            "schema_minor_version": 0
        }
    }



```python
missing_file_name = metadata_file['file_core']['file_name']
missing_file_name
```




    '906f8f09-deaa-40bb-bf50-27d2336b2dc4.zarr!expression_matrix!expression!32.5'




```python
[f for f in manifest if f['name'] == missing_file_name]
```




    []



No matching manifest entries for that file name. The bundle must have been truncated.

**Comment by hannes-ucsc** [comment]
Looking at the bundle directly in the DSS bucket. It is also truncated.

```
$ aws s3api get-object --bucket org-hca-dss-prod --key bundles/cb88115c-75ef-4e8e-bbd7-a48e18960344.2019-09-26T120958.020808Z bundle.json
{
    "AcceptRanges": "bytes",
    "LastModified": "Thu, 26 Sep 2019 12:10:11 GMT",
    "ContentLength": 218996,
    "ETag": "\"8c7d69f520ac2dea5553fc0df9634090\"",
    "ContentType": "binary/octet-stream",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
$ cat bundle.json | jq '.files[].name' | wc -l
     500
```

**Comment by hannes-ucsc** [comment]
In other words, there is a metadata file in the bundle that references a data file which is not mentioned in the bundle, probably because the bundle was truncated on creation, either by DSS or by Ingest. Please file this issue with them.

**Comment by jlzamanian** [comment]
Thank you for investigating the issue and for the information on its cause.
