### ISSUE TITLE
Unable to execute successful GET request againsts repository specimens endpoint

### ISSUE THREAD

**Issue by mpanik** [DataBiosphere/azul#140]
When running locally `service` `GET http://127.0.0.1:8000/repository/specimens?from=1&size=15&filters={}`  causes `500` with message:

```
Traceback (most recent call last):
  File "/home/milan/.virtualenvs/.azul/lib/python3.7/site-packages/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/home/milan/Projects/human-cell-atlas/azul/lambdas/service/app.py", line 213, in get_specimen_data
    index="AZUL_SPECIMEN_INDEX")
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/elastic_request_builder.py", line 516, in transform_request
    facets)
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/hca_response_v5.py", line 524, in __init__
    KeywordSearchResponse.__init__(self, hits)
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/hca_response_v5.py", line 450, in __init__
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/hca_response_v5.py", line 450, in <listcomp>
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/hca_response_v5.py", line 432, in map_entries
    projects=self.make_projects(entry),
  File "/home/milan/Projects/human-cell-atlas/azul/src/azul/service/responseobjects/hca_response_v5.py", line 360, in make_projects
    project_shortname = project["project_shortname"]
KeyError: 'project_shortname'
```

I did have run reindex before running `service`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-110)
┆Project Name: azul
┆Issue Number: AZUL-110

**Comment by hannes-ucsc** [comment]
@kozbo, this is blocking Milan so I asked him to work on it.

**Comment by kozbo** [comment]
@caaespin to look at it

**Comment by hannes-ucsc** [comment]
This is happening in all shared deployments, too, including prod. Probably since I recently deployed to all of them.

https://github.com/DataBiosphere/azul/issues/147#issue-345733201

**Comment by caaespin** [comment]
@hannes-ucsc  @mpanik  here is what I’ve been able to diagnose: It appears that the ES indexes in `dev` and `prod` are using some old format (for example, they still use `hca_id` as opposed to `document_id` from the new accessor API`). In Hanne’s deployment, the index is up to date. However, in `dev` and `prod`, the index is still outdated for some reason.  

Assuming that the `dev` and `prod` indexers are up to date, then you can probably try to delete the indexes and re-index the data.

**Comment by hannes-ucsc** [comment]
Superseded by #148
