### ISSUE TITLE
Error Hitting New Dev/Integration/Staging/Prod  Environment Endpoints

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#147]
HI There,

I am trying to use the new environment endpoint however:

## Hitting

https://service.dev.explore.data.humancellatlas.org/repository/specimens?size=15
https://service.integration.explore.data.humancellatlas.org/repository/specimens?size=15
https://service.staging.explore.data.humancellatlas.org/repository/specimens?size=15
https://service.explore.data.humancellatlas.org/repository/specimens?size=15

## Gives

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 213, in get_specimen_data
    index="AZUL_SPECIMEN_INDEX")
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 516, in transform_request
    facets)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 524, in __init__
    KeywordSearchResponse.__init__(self, hits)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 450, in __init__
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 450, in <listcomp>
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 432, in map_entries
    projects=self.make_projects(entry),
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 360, in make_projects
    project_shortname = project["project_shortname"]
KeyError: 'project_shortname'

Am I hitting the correct endpoints or is there some other error.

Cheers and Thanks,
D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-113)
┆Project Name: azul
┆Issue Number: AZUL-113

**Comment by mpanik** [comment]
Related to #140

**Comment by hannes-ucsc** [comment]
Duplicates #140
