### ISSUE TITLE
Running doctests from PyCharm fails with import error

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1470]
To reproduce, open `openapi.py`, right-click the `openapi_spec` function and select _Run 'Doctest openapi_spec'_.

```
Testing started at 5:31 PM ...
/home/hannes/workspace/hca/azul/.venv.xps/bin/python /snap/pycharm-professional/171/helpers/pycharm/docrunner.py /home/hannes/workspace/hca/azul/src/azul/openapi.py::::openapi_spec
envhook.py: Setting AWS_DEFAULT_REGION to 'us-east-1'
envhook.py: Setting AWS_PROFILE to 'hca'
envhook.py: Setting AZUL_CART_EXPORT_MAX_BATCH_SIZE to '100'
envhook.py: Setting AZUL_CART_EXPORT_MIN_ACCESS_TOKEN_TTL to 'REDACTED'
envhook.py: Setting AZUL_DEBUG to '1'
envhook.py: Setting AZUL_DEPLOYMENT_STAGE to 'staging'
envhook.py: Setting AZUL_DISABLE_MULTIPART_MANIFESTS to '0'
envhook.py: Setting AZUL_DOMAIN_NAME to 'staging.explore.data.humancellatlas.org'
envhook.py: Setting AZUL_DRS_DOMAIN_NAME to 'drs.staging.data.humancellatlas.org'
envhook.py: Setting AZUL_DSS_ENDPOINT to 'https://dss.staging.data.humancellatlas.org/v1'
envhook.py: Setting AZUL_DSS_WORKERS to '8'
envhook.py: Setting AZUL_ENABLE_MONITORING to '1'
envhook.py: Setting AZUL_ES_DOMAIN to 'azul-index-dev'
envhook.py: Setting AZUL_ES_INSTANCE_COUNT to '2'
envhook.py: Setting AZUL_ES_INSTANCE_TYPE to 'r4.2xlarge.elasticsearch'
envhook.py: Setting AZUL_ES_TIMEOUT to '60'
envhook.py: Setting AZUL_ES_VOLUME_SIZE to '70'
envhook.py: Setting AZUL_FUSILLADE_ENDPOINT to 'https://auth.dev.data.humancellatlas.org'
envhook.py: Setting AZUL_INDEXER_CONCURRENCY to '64'
envhook.py: Setting AZUL_INDEX_PREFIX to 'azul'
envhook.py: Setting AZUL_RESOURCE_PREFIX to 'azul'
envhook.py: Setting AZUL_S3_BUCKET to 'azul-storage-staging'
envhook.py: Setting AZUL_SHARE_ES_DOMAIN to '1'
envhook.py: Setting AZUL_SUBDOMAIN_TEMPLATE to '{lambda_name}'
envhook.py: Setting AZUL_SUBSCRIBE_TO_DSS to '1'
envhook.py: Setting AZUL_TERRAFORM_BACKEND_BUCKET to 'org-humancellatlas-azul-dev-config'
envhook.py: Setting AZUL_URL_REDIRECT_BASE_DOMAIN_NAME to ''
envhook.py: Setting AZUL_URL_REDIRECT_FULL_DOMAIN_NAME to 'staging.url.data.humancellatlas.org'
envhook.py: Setting GOOGLE_APPLICATION_CREDENTIALS to '/home/hannes/workspace/hca/azul/../data-store/wip/gcp-credentials.dev.json'
envhook.py: Setting GOOGLE_PROJECT to 'human-cell-atlas-travis-test'
envhook.py: Setting MYPYPATH to '/home/hannes/workspace/hca/azul/stubs'
envhook.py: Setting PYENV_VERSION to '3.6.9'
envhook.py: Ignoring change in PYTHONPATH from '/home/hannes/workspace/hca/azul:/home/hannes/workspace/hca/azul/src:/home/hannes/workspace/hca/azul/scripts:/home/hannes/workspace/hca/azul/test:/home/hannes/workspace/hca/azul/stubs:/snap/pycharm-professional/171/helpers/pycharm_matplotlib_backend:/snap/pycharm-professional/171/helpers/pycharm_display:/snap/pycharm-professional/171/helpers/pycharm' to '/home/hannes/workspace/hca/azul/src:/home/hannes/workspace/hca/azul/test'
envhook.py: Setting TF_DATA_DIR to '/home/hannes/workspace/hca/azul/deployments/.active/.terraform'
envhook.py: Setting XDG_CONFIG_HOME to '/home/hannes/workspace/hca/azul/.config'
envhook.py: Setting azul_dss_query_prefix to ''
envhook.py: Setting azul_github_access_token to 'REDACTED'
envhook.py: Setting azul_github_project to 'DataBiosphere/azul'
envhook.py: Setting azul_grafana_endpoint to 'https://metrics.dev.data.humancellatlas.org'
envhook.py: Setting azul_grafana_password to 'REDACTED'
envhook.py: Setting azul_grafana_user to 'dcp-admin'
envhook.py: Setting azul_home to '/home/hannes/workspace/hca/azul'
envhook.py: Setting azul_terraform_component to ''

Traceback (most recent call last):
  File "/snap/pycharm-professional/171/helpers/pycharm/docrunner.py", line 322, in <module>
    module = loadSource(a[0])
  File "/snap/pycharm-professional/171/helpers/pycharm/docrunner.py", line 229, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "/home/hannes/.pyenv/versions/3.6.9/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hannes/workspace/hca/azul/src/azul/openapi.py", line 4, in <module>
    from azul.deployment import aws
  File "/home/hannes/workspace/hca/azul/src/azul/__init__.py", line 13, in <module>
    import boto3
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/botocore/compat.py", line 26, in <module>
    from urllib3 import exceptions
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/urllib3/connection.py", line 38, in <module>
    from .util.ssl_ import (
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/home/hannes/workspace/hca/azul/.venv.xps/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 4, in <module>
    import hmac
  File "/home/hannes/workspace/hca/azul/src/azul/hmac.py", line 3, in <module>
    import chalice
  File "/home/hannes/workspace/hca/azul/src/azul/chalice.py", line 4, in <module>
    from chalice import Chalice
ImportError: cannot import name 'Chalice'

Process finished with exit code 1
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-902)
┆Project Name: azul
┆Issue Number: AZUL-902

**Comment by achave11** [comment]
I encounter a similar issue when trying to use `AbstractService` class in `elastic_request_builder.py` I imported it as "normal" and when trying to run it I encounter the same ImportError.

**Comment by achave11** [comment]
In both cases I imported the class at the beginning of the file as 
`from azul.service import AbstractService`.
First time I tried for `CacheManifest` (recently created) to inherit from `AbstractService` in `hca_response_v5.py`.
I also tried using `AbstractService` class method in `elastic_request_builder.py`
as
```
abs_service = AbstractService()
abs_service.parse_filters(filters)
```
I ran `make deploy` in `azul/lambdas/service` and the following stack trace was produced. 
```
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 512, in main
    return cli(obj={})
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/cli/__init__.py", line 205, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 342, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 348, in _deploy
    self._validate_config(config)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/deploy/deployer.py", line 371, in _validate_config
    validate_configuration(config)
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/deploy/validate.py", line 40, in validate_configuration
    routes = config.chalice_app.routes
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/config.py", line 140, in chalice_app
    app = v()
  File "/Users/abrahamchavez/PycharmProjects/azul/.venv/lib/python3.6/site-packages/chalice/cli/factory.py", line 258, in load_chalice_app
    app = importlib.import_module('app')
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abrahamchavez/PycharmProjects/azul/lambdas/service/app.py", line 40, in <module>
    from azul.health import HealthController
  File "/Users/abrahamchavez/PycharmProjects/azul/src/azul/health.py", line 22, in <module>
    from azul.service.responseobjects.storage_service import StorageService
  File "/Users/abrahamchavez/PycharmProjects/azul/src/azul/service/__init__.py", line 6, in <module>
    from azul.service.responseobjects.elastic_request_builder import BadArgumentException
  File "/Users/abrahamchavez/PycharmProjects/azul/src/azul/service/responseobjects/elastic_request_builder.py", line 45, in <module>
    from azul.service.responseobjects.hca_response_v5 import (
  File "/Users/abrahamchavez/PycharmProjects/azul/src/azul/service/responseobjects/hca_response_v5.py", line 70, in <module>
    from azul.service import AbstractService
ImportError: cannot import name 'AbstractService'


```

**Comment by hannes-ucsc** [comment]
@achave11 it appears that the import error you post is caused by a circular import specific to your branch. I don't think it is related to this issue here.

**Comment by hannes-ucsc** [comment]
Demo by running doctests in openapi.py in staging (fails) and integration (works).
