### ISSUE TITLE
IT race condition with test notifications

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1551]
In integration_test a race condition can occur between the enabling of test mode
```
2020-02-04 22:52:58,646 INFO    MainThread: Setting environment variable AZUL_TEST_MODE to "1" on function azul-indexer-sandbox
```
and the processing of test notifications.

```
2020-02-04 22:53:03,658 WARNING MainThread: Unhandled exception in worker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/azul/azul/src/azul/azulclient.py", line 115, in attempt
    self.post_bundle(url.geturl(), notification)
  File "/builds/azul/azul/src/azul/azulclient.py", line 67, in post_bundle
    response.raise_for_status()
  File "/build/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://indexer.sandbox.dev.explore.data.humancellatlas.org/
```

Full integration_test log on Gitlab:
https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/5532

Kibana log:
```
{
  "@message": "[ERROR]\t2020-02-04T22:53:03.251Z\t982a1f58-948e-4067-baa6-bcd68340c4a7\tRejecting test notification in production mode: {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': '33'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'ba29c78b-90f4-4b4d-a407-5a3991f382de', 'match': {'bundle_uuid': '333fd797-9d97-494b-ac65-91d9193bce00', 'bundle_version': '2019-08-01T200149.270220Z'}, 'test_bundle_uuid': '8f0d3f22-dccd-403a-aea8-15c03b24ddba', 'test_bundle_version': '2020-02-04T225300.056509Z', 'test_name': 'integration-test_9fecbb76-3338-4352-b68f-6f1e80253ec8_33', 'test_uuid': '9fecbb76-3338-4352-b68f-6f1e80253ec8'}.\n",
  "@id": "35254284318649304273255834275852659652134304948828110851",
  "@timestamp": "2020-02-04T22:53:03.251Z",
  "@owner": "861229788715",
  "@log_group": "/aws/lambda/azul-indexer-sandbox",
  "@log_stream": "2020/02/04/[$LATEST]58d318afb65649ceb3a2976fc3f8e5e4"
}
```

A proposed solution would:
- return a descriptive error message with the 400 error
- resend test notifications if a 500 or this 400 error is encountered.

**Comment by theathorn** [comment]
Very infrequent.

**Comment by hannes-ucsc** [comment]
Regression from https://github.com/DataBiosphere/azul/commit/1ced16df857b91ed99f62d8cb63b48c55da08484#diff-d047e7fab8b44266d209cfe5b1f55f4aL59
