### ISSUE TITLE
InvalidClientTokenId raised when running unit tests locally

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1567]
To reproduce:
- checkout `develop` branch (currently at: f336a5a06671e2e6550b968a8921f70859545f72)
- select `dev` deployment
- run unittests for `test_index_test_mode` in test_hca_indexer.py

```
Testing started at 5:30 PM ...
/Users/daniel/azul.sc/.venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py --target test_hca_indexer.TestValidNotificationRequests.test_index_test_mode
envhook: envhook.py: Setting AWS_DEFAULT_REGION to 'us-east-1'
envhook: envhook.py: Setting AZUL_CART_EXPORT_MAX_BATCH_SIZE to '100'
envhook: envhook.py: Setting AZUL_CART_EXPORT_MIN_ACCESS_TOKEN_TTL to 'REDACTED'
envhook: envhook.py: Setting AZUL_DEBUG to '1'
envhook: envhook.py: Setting AZUL_DEPLOYMENT_STAGE to 'dev'
envhook: envhook.py: Setting AZUL_DISABLE_MULTIPART_MANIFESTS to '0'
envhook: envhook.py: Setting AZUL_DOMAIN_NAME to 'dev.singlecell.gi.ucsc.edu'
envhook: envhook.py: Setting AZUL_DRS_DOMAIN_NAME to 'drs.dev.singlecell.gi.ucsc.edu'
envhook: envhook.py: Setting AZUL_DSS_DIRECT_ACCESS to '1'
envhook: envhook.py: Setting AZUL_DSS_DIRECT_ACCESS_ROLE to 'arn:aws:iam::861229788715:role/azul-{lambda_name}-staging'
envhook: envhook.py: Setting AZUL_DSS_ENDPOINT to 'https://dss.staging.data.humancellatlas.org/v1'
envhook: envhook.py: Setting AZUL_DSS_WORKERS to '8'
envhook: envhook.py: Setting AZUL_ENABLE_MONITORING to '0'
envhook: envhook.py: Setting AZUL_ES_DOMAIN to 'azul-index-dev'
envhook: envhook.py: Setting AZUL_ES_INSTANCE_COUNT to '2'
envhook: envhook.py: Setting AZUL_ES_INSTANCE_TYPE to 'r4.xlarge.elasticsearch'
envhook: envhook.py: Setting AZUL_ES_TIMEOUT to '60'
envhook: envhook.py: Setting AZUL_ES_VOLUME_SIZE to '70'
envhook: envhook.py: Setting AZUL_FUSILLADE_ENDPOINT to 'https://auth.dev.data.humancellatlas.org'
envhook: envhook.py: Setting AZUL_INDEXER_CONCURRENCY to '64'
envhook: envhook.py: Setting AZUL_INDEXER_GOOGLE_SERVICE_ACCOUNT to 'azul-ucsc-indexer-dev'
envhook: envhook.py: Setting AZUL_INDEX_PREFIX to 'azul'
envhook: envhook.py: Setting AZUL_OWNER to 'hannes@ucsc.edu'
envhook: envhook.py: Setting AZUL_RESOURCE_PREFIX to 'azul'
envhook: envhook.py: Setting AZUL_S3_BUCKET to 'edu-ucsc-gi-singlecell-azul-storage-dev'
envhook: envhook.py: Setting AZUL_SHARE_ES_DOMAIN to '0'
envhook: envhook.py: Setting AZUL_SUBDOMAIN_TEMPLATE to '{lambda_name}'
envhook: envhook.py: Setting AZUL_SUBSCRIBE_TO_DSS to '1'
envhook: envhook.py: Setting AZUL_TERRAFORM_BACKEND_BUCKET to 'edu-ucsc-gi-singlecell-azul-config-dev'
envhook: envhook.py: Setting AZUL_URL_REDIRECT_BASE_DOMAIN_NAME to 'dev.url.singlecell.gi.ucsc.edu'
envhook: envhook.py: Setting AZUL_URL_REDIRECT_FULL_DOMAIN_NAME to 'dev.dev.url.singlecell.gi.ucsc.edu'
envhook: envhook.py: Setting GOOGLE_PROJECT to 'human-cell-atlas-travis-test'
envhook: envhook.py: Setting MYPYPATH to '/Users/daniel/azul.sc/stubs'
envhook: envhook.py: Ignoring change in PYTHONPATH from '/Users/daniel/azul.sc:/Users/daniel/azul.sc/src:/Users/daniel/azul.sc/test:/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend:/Applications/PyCharm.app/Contents/helpers/pycharm_display:/Applications/PyCharm.app/Contents/helpers/pycharm' to '/Users/daniel/azul.sc/src:/Users/daniel/azul.sc/test'
envhook: envhook.py: Setting TF_DATA_DIR to '/Users/daniel/azul.sc/deployments/.active/.terraform.'
envhook: envhook.py: Setting XDG_CONFIG_HOME to '/Users/daniel/azul.sc/.config'
envhook: envhook.py: Setting azul_dss_query_prefix to ''
envhook: envhook.py: Setting azul_github_access_token to 'REDACTED'
envhook: envhook.py: Setting azul_github_project to 'DataBiosphere/azul'
envhook: envhook.py: Setting azul_home to '/Users/daniel/azul.sc'
envhook: envhook.py: Setting azul_terraform_component to ''
Launching unittests with arguments python -m unittest test_hca_indexer.TestValidNotificationRequests.test_index_test_mode in /Users/daniel/azul.sc/test/indexer

Serving on http://localhost:0
2020-02-12 17:30:42,179 INFO    Thread-2: Received GET request to '/health/basic' without parameters.
2020-02-12 17:30:42,179 DEBUG   Thread-2: Returning 200 response without headers. See next line for the first 1024 characters of the body.
{"up": true}
127.0.0.1 - - [12/Feb/2020 17:30:42] "GET /health/basic HTTP/1.1" 200 -

Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "/Users/daniel/azul.sc/test/indexer/test_hca_indexer.py", line 1097, in test_index_test_mode
    self._create_mock_notify_queue()
  File "/Users/daniel/azul.sc/test/indexer/test_hca_indexer.py", line 1151, in _create_mock_notify_queue
    sqs.create_queue(QueueName=config.notify_queue_name)
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/daniel/azul.sc/.venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateQueue operation: The security token included in the request is invalid.


Assertion failed
```

**Comment by hannes-ucsc** [comment]
Regression from 9f79ed8875346da7a575140f769ae5f6a17b3a64

**Comment by hannes-ucsc** [comment]
This affects many or all tests that use moto.

**Comment by theathorn** [comment]
Is this complete?

**Comment by danielsotirhos** [comment]
@theathorn Yes, the PR fixing this issue was verified and then merged. https://github.com/DataBiosphere/azul/pull/1572#issuecomment-585903947
