### ISSUE TITLE
Can't run more than one test concurrently

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#159]
The ES container started for one test seems to interfere with the container started for the other. To reproduce, launch the `TestDataExtractorTestCase` which takes a few minutes. When that test is past the setup phase and actually executing a test method,  start the `TestHCAIndexer` test. The latter will succeed but the former will fail with sth like this:

```
WARNING:elasticsearch:PUT http://127.0.0.1:32814/browser_files_dev [status:N/A request:17.908s]
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 115, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

teadDownClass() prints:

```
Failure
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/cf60107d36d22fb089b240444ae05453bf0598b56566e838e28efa05c78f282c/kill

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/suite.py", line 259, in _tearDownPreviousClass
    tearDownClass()
  File "/Users/hannes/workspace/hca/azul/test/indexer/test_projects.py", line 49, in tearDownClass
    super().tearDownClass()
  File "/Users/hannes/workspace/hca/azul/test/indexer/__init__.py", line 35, in tearDownClass
    super().tearDownClass()
  File "/Users/hannes/workspace/hca/azul/test/shared.py", line 60, in tearDownClass
    cls._es_docker_container.kill()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/models/containers.py", line 246, in kill
    return self.client.api.kill(self.id, signal=signal)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/api/container.py", line 752, in kill
    self._raise_for_status(res)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Cannot kill container: cf60107d36d22fb089b240444ae05453bf0598b56566e838e28efa05c78f282c: Container cf60107d36d22fb089b240444ae05453bf0598b56566e838e28efa05c78f282c is not running")
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-119)
┆Project Name: azul
┆Issue Number: AZUL-119

**Comment by hannes-ucsc** [comment]
Cannot reproduce. I ran two ES-based tests in parallel and they both succeeded.
