### ISSUE TITLE
`KeyError: servers` when apidev.py script reloads openapi.json specs

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1643]
Reproduce:
1) Run the following command:
```
$ python scripts/apidev.py 
```

~2) Modify any definition of the swagger-editor, running on http://localhost:8787/scripts/apidev_static/swagger-editor.html?url=http://localhost:8787/scripts/openapi.json~
2) Modify the OpenAPI spec definition for method or path in `app.py` and save the changes.

3) The following is raised:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "scripts/apidev.py", line 60, in on_modified
    write_specs(self.raw_specs, self.service.app, self.service.openapi_spec)
  File "scripts/apidev.py", line 21, in write_specs
    specs = annotated_specs(raw_specs, app, openapi_spec)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/openapi/__init__.py", line 119, in annotated_specs
    clean_specs(raw_specs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/openapi/__init__.py", line 146, in clean_specs
    specs.pop('servers')
KeyError: 'servers'

```

**Comment by jessebrennan** [comment]
I am unable to recreate this issue on my branch for #1450. This ticket will need to be demoed when that ticket is demoed.

I'm not sure where this ticket should live in the mean time...

**Comment by hannes-ucsc** [comment]
I set estimate to 0 and made #1450 a blocker. This nicely reflects reality. The assignee should move this ticket along with the blocker such that they are always in the same pipeline. If they forget, we can easily catch this using these two properties (blocked and zero estimate).
