### ISSUE TITLE
Github labels are inconsistent between projects on our Zenhub board

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1656]
The labels among the projects on our *Orange* workspace in Zenhub are inconsistent. 

We should ensure that the labels including their name, description and color in every project on that workspace are consistent with those in DataBiosphere/azul which should act as the master.

The repositories that should be synchronized are:

DataBiosphere/cellxgene-fargate
HumanCellAtlas/data-portal-summary-stats
DataBiosphere/data-portal-summary-stats
HumanCellAtlas/dcp-cli
DataBiosphere/hca-metadata-api
HumanCellAtlas/metadata-api

Confirm with @NoopDog if he wants that to occur on the following projects as well:

HumanCellAtlas/data-browser
DataBiosphere/data-browser
HumanCellAtlas/data-portal
DataBiosphere/data-portal
HumanCellAtlas/data-portal-content

Ideally, the solution should come in the form of a self-contained script along with instructions on how to use. The script should have two arguments: source repository and destination repository. Each argument should be a repo slug or URL to the repo. If additional arguments are required, say, for authentication.

The source of the script should be maintained in a separate repository on the assignee's GH account.

**Comment by chmreid** [comment]
If source repo has labels A B C, and destination repo has labels D E F, it makes the most sense to have the result be the destination repo having labels A B C D E F, instead of A B C. (i.e., existing labels should be preserved.)

**Comment by hannes-ucsc** [comment]
I think so. We can add a `--delete` flag later. I also think the script should be idempotent which implies that it does silently overwrite labels of the same name in the destination.

**Comment by chmreid** [comment]
The standalone script plus a readme describing its usage is available here: https://gist.github.com/chmreid/31840023fc1d51e21a25daf5caad82b3

Please have a look at the script, once I get the OK I'll close this issue.

**Comment by hannes-ucsc** [comment]
1) This doesn't work for me:

```
(.venv) hannes@hannes-xps:~/workspace/hca/sync-github-labels$ python sync_labels.py DataBiosphere/azul DataBiosphere/hca-metadata-api
Syncing labels from DataBiosphere/azul to DataBiosphere/azul
The following labels will be created in DataBiosphere/hca-metadata-api:
 - 1 review
 - 2 reviews
 - 3 reviews
 - 4+ reviews
 - API
 - DNAStack
 - HCA
 - arch
 - broad
 - chain
 - code
 - commons
 - critical
 - dashboard
 - data
 - debt
 - demo blocked
 - demoed
 - do not close
 - doc
 - enh
 - epic
 - hold warm
 - infra
 - needs info
 - no demo
 - no pr
 - port
 - sandbox
 - security
 - spike
 - task
 - test
 - urgent
 - workaround
Okay to proceed? (Type 'y' or 'yes' to confirm):
yes
Creating label hold warm in destination repo DataBiosphere/hca-metadata-api...
Traceback (most recent call last):
  File "sync_labels.py", line 67, in sync_labels
    d.create_label(name, color, description)
  File "/home/hannes/workspace/hca/sync-github-labels/.venv/lib/python3.6/site-packages/github/Repository.py", line 1235, in create_label
    headers={"Accept": Consts.mediaTypeLabelDescriptionSearchPreview},
  File "/home/hannes/workspace/hca/sync-github-labels/.venv/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/hannes/workspace/hca/sync-github-labels/.venv/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://developer.github.com/v3/issues/labels/#create-a-label"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_labels.py", line 150, in <module>
    main()
  File "sync_labels.py", line 116, in main
    sync_labels(args.src, args.dest, args.dry_run, args.force, args.delete)
  File "sync_labels.py", line 70, in sync_labels
    raise Exception(f"Error creating label {name} in destination repo {dest_repo}")
Exception: Error creating label hold warm in destination repo DataBiosphere/hca-metadata-api
```

2) I like the interactive mode but the dash that's printed in front of every label intuitevely indicates deletion to me. I haven't tried `--delete` mode but it may make sense to use `+` for addition and `-` for deletion. 

3) This deserves its own self-contained repository: https://github.com/DataBiosphere/sync-github-labels. Please create a PR there and address my comments in that PR.

4) The README shouldn't duplicate the `--help` output. Advertise the script and its core features in the README and the refer the reader to `--help` for more information. If the README currently contains information on a particular command line option that's NOT included in `--help`, that info should be moved to `--help`. We want the README to be a tasting menu, and `--help` to be a reference.

5) I haven't checked but `--dry-run` should be mutually exclusive with `--force`, right?

**Comment by hannes-ucsc** [comment]
6. Please test your script by copying the Azul labels to a temporary repo that you own.
