### ISSUE TITLE
Unable to run lambda locally due to AWS Credential conflict

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1661]
Branch: develop
AWS Account: None set during error
```
$ aws sts get-caller-identity
Unable to locate credentials. You can configure credentials by running "aws configure".


$ make local
python .chalice/config.json.template.py .chalice/config.json
Traceback (most recent call last):
  File ".chalice/config.json.template.py", line 13, in <module>
    "iam_role_arn": f"arn:aws:iam::{aws.account}:role/{config.indexer_name}",
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/deployment.py", line 59, in account
    return self.sts.get_caller_identity()['Account']
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/Users/amar/dev/venv/venv-azul/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
make: *** [.chalice/config.json] Error 1
```

When attempting to run `cd lambdas/indexer && make local`  the error above is posted;
when attempting to have a default account set within `~/.aws/config` the following error occurs

```
arn:aws:sts::861229788715:assumed-role/dcp-developer/ajandu@ucsc.edu is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::861229788715:role/azul-indexer-staging
```

It seems that if the provided aws credential differs from what the branch/deployment is expecting this error would occur. 
Potentially a solution for this issue would be doing a comparison with `aws sts get-caller-identity | jq -r .Account` with an env value that has the expected aws_account_id that is to be used on the branch/deployment.
This could be placed within `common.mk` to ensure its applicable to make targets

I'm not sure how valid of a solution that would be, it would depend on how branches/deployments/env files  are managed within this repo.

**Comment by hannes-ucsc** [comment]
1) Clarify in README that `make local` does require a deployment.

2) Add a explicit env var called `AZUL_AWS_ACCOUNT` and a check in common.mk to ensure that the credentials match the account ID configured in that variable.
