### ISSUE TITLE
KeyError: 'R1.fastq.gz' during reindexing

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1677]
```
[WARNING] 2020-04-02T18:49:35.988Z 9484af15-707f-5e10-a21b-f8154582bdfa Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': '1b'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'a207fa66-4858-4d89-bdd1-786a8b26d085', 'match': {'bundle_uuid': '1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504', 'bundle_version': '2018-08-17T202728.071749Z'}}}.
Traceback (most recent call last):
File "/var/task/app.py", line 202, in index
contributions = indexer.transform(notification, delete=False)
File "/var/task/azul/indexer.py", line 151, in transform
metadata_files=metadata_files))
File "/var/task/azul/project/hca/transformers.py", line 565, in transform
metadata_files=metadata_files)
File "/var/task/humancellatlas/data/metadata/api.py", line 767, in __init__
self.files = from_json_vx(File, manifest=self.manifest)
File "/var/task/humancellatlas/data/metadata/api.py", line 761, in from_json_vx
return from_json(core_cls, json_entities, **kwargs)
File "/var/task/humancellatlas/data/metadata/api.py", line 730, in from_json
return {entity.document_id: entity for entity in entities}
File "/var/task/humancellatlas/data/metadata/api.py", line 730, in <dictcomp>
return {entity.document_id: entity for entity in entities}
File "/var/task/humancellatlas/data/metadata/api.py", line 729, in <genexpr>
entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
File "/var/task/humancellatlas/data/metadata/api.py", line 57, in from_json
return sub_cls(json, **kwargs)
File "/var/task/humancellatlas/data/metadata/api.py", line 648, in __init__
super().__init__(json, manifest)
File "/var/task/humancellatlas/data/metadata/api.py", line 621, in __init__
self.manifest_entry = manifest[core['file_name']]
KeyError: 'R1.fastq.gz'
```
Here is the log dump for the 60 occurrences during [this reindexing](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1524).
[logs-insights-results.csv.txt](https://github.com/DataBiosphere/azul/files/4441371/logs-insights-results.csv.txt)

**Comment by amarjandu** [comment]
Bundles Extracted: 
```cat logs-insights-results3.csv.txt | grep "^[0-9]" | awk -F'\t' '{print $4}' | cut -d ' ' -f 23- | sed s/\'/\"/g | sed 's/^/{/g' | sed 's/..$//' | jq -r ".match.bundle_uuid, .match.bundle_version" | xargs -n 2 | sed 's/ /./'``` 

```
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z

```

**Comment by amarjandu** [comment]
@jessebrennan @hannes-ucsc it appears that there are 42 non-duplicate bundles in the list, this is different from the 60 occurrences that were found. 

```
cat logs-insights-results3.csv.txt | grep "^[0-9]" | awk -F'\t' '{print $4}' | cut -d ' ' -f 23- | sed s/\'/\"/g | sed 's/^/{/g' | sed 's/..$//' | jq -r ".match.bundle_uuid, .match.bundle_version" | xargs -n 2 | sed 's/ /./' | sed 's/^/"/' | sed 's/$/",/' | uniq -u

"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
```

**Comment by amarjandu** [comment]
tombstone script: https://gist.github.com/amarjandu/4d1dda4b7648add5d3b3c69d379e85e6

**Comment by amarjandu** [comment]
**NOTE**  there was an error within the script that i was using above, it did not remove duplicates correctly.

```
cat logs-insights-results3.csv.txt | grep "^[0-9]" | awk -F'\t' '{print $4}' | cut -d ' ' -f 23- | sed s/\'/\"/g | sed 's/^/{/g' | sed 's/..$//' | jq -r ".match.bundle_uuid, .match.bundle_version" | xargs -n 2 | sed 's/ /./' |sort --unique |sed 's/^/"/' | sed 's/$/",/'
```
was used to produce 
```
"1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z",
"1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z",
"869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z",
"91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z",
"94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z",
"e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z",
```

**Comment by amarjandu** [comment]
These bundles are found within the list in #1679, no need to rerun tombstone script above.

**Comment by theathorn** [comment]
Bundles tombstoned and no more failure messages occurring - closing,
