### ISSUE TITLE
95 bundles in DSS staging fail with DSSException(404, "not_found", "Cannot find bundle!")

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1680]
The traceback:
```
not_found: Cannot find bundle! (HTTP 404). Details:
Traceback (most recent call last):
File "/var/task/chalicelib/dss/error.py", line 72, in wrapper
return func(*args, **kwargs)
File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 55, in get
raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException
: SwaggerAPIException
Traceback (most recent call last):
File "/var/task/app.py", line 175, in new_handler
return old_handler(self, event, context)
File "/var/task/chalice/app.py", line 1422, in __call__
return self.func(event_obj)
File "/var/task/app.py", line 202, in index
contributions = indexer.transform(notification, delete=False)
File "/var/task/azul/indexer.py", line 131, in transform
manifest, metadata_files = self._get_bundle(bundle_uuid, bundle_version)
File "/var/task/azul/indexer.py", line 171, in _get_bundle
num_workers=config.num_dss_workers)
File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 80, in download_bundle_metadata
for page in client.get_bundle.paginate(**kwargs):
File "/var/task/hca/util/__init__.py", line 200, in paginate
for page in self._get_raw_pages(**kwargs):
File "/var/task/hca/util/__init__.py", line 180, in _get_raw_pages
page = self._request(kwargs, url=page.links["next"]["url"] if page else None)
File "/var/task/hca/util/__init__.py", line 146, in _request
raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: not_found: Cannot find bundle! (HTTP 404). Details:
Traceback (most recent call last):
File "/var/task/chalicelib/dss/error.py", line 72, in wrapper
return func(*args, **kwargs)
File "/var/task/chalicelib/dss/api/bundles/__init__.py", line 55, in get
raise DSSException(404, "not_found", "Cannot find bundle!")
dss.error.DSSException
```

This error occurs after direct access also fails with a 404.

I determined 129 bundles because during the time span of [this reindexing](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1524) this exception occurred 950 times within the azul-indexer-dev-index lambda which retries a notification 10 times.

Note that together with #1679 this accounts for all of the bundle notifications that failed to process during the reindexing linked above.

Here is the dump of the loged failures:
[logs-insights-results.csv.txt](https://github.com/DataBiosphere/azul/files/4441438/logs-insights-results.csv.txt)

**Comment by theathorn** [comment]
Bundles tombstoned and no more failure messages occurring - closing,
