### ISSUE TITLE
Replace Files list from hits on /specimens and replace with a summary of files for the specimen.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#170]
When I hit the /specimens endpoint we get back an array of `hits` htat are specimens.

These have an embedded `files` array which contains all of the files associated with the specimen.
This files list can be very long (hundreds?) and makes the request payload much larger than it needs to be.

We do need to know:

1. How many files there are in total for the specimen.
1. How man files of each type are available.

We currently are aggregating the list of files per row in the front end code to calculate these values but we need would like to push this to the back end for speed.

The array i mean is this one:

```
"files": [
        {
          "format": "fastq.gz",
          "name": "MantonCB1_HiSeq_1_S1_L001_I1_001.fastq.gz",
          "sha1": "639b14b53d3b9c690dbf3e8337cb809bc8267b36",
          "size": 488686373,
          "uuid": "d9826c48-f7fd-42bf-80bd-d53d3f8cf35f",
          "version": "2018-03-27T163902.468088Z"
        },
        {
          "format": "fastq.gz",
          "name": "MantonCB1_HiSeq_1_S1_L001_R1_001.fastq.gz",
          "sha1": "a321e15230cf25ba5c1eb57bb26881e500e39eb4",
          "size": 1477094823,
          "uuid": "533186cb-f420-4bb9-9bfa-2ff8044f304d",
          "version": "2018-03-27T163903.004914Z"
        },
```

Instead we need something similar to what comes down for the fileTypeSummary like:

```
fileTypeSummaries": [
    {
      "fileType": "fastq.gz",
      "count": 20885,
      "totalSize": 15350291353461
    }
  ]
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-126)
┆Project Name: azul
┆Issue Number: AZUL-126

**Comment by hannes-ucsc** [comment]
@theathorn, this is very well defined. Since I closed #113 @mpanik needs more work and this would be a good ticket.

**Comment by mpanik** [comment]
@NoopDog could you please try https://service.jyo.dev.explore.data.humancellatlas.org/repository/specimens and let me know if this is what you need?

**Comment by NoopDog** [comment]
Thanks. Will take a look.
Cheers,
D

**Comment by NoopDog** [comment]
Looks good by eye, will try it with the browser today or over the weekend. Thanks, D

**Comment by NoopDog** [comment]
Hi @mpanik I got the file API working. Looks good. 

However, I did notice that if I try to page with this endpoint i get the following error:

```Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 225, in get_specimen_data
    index="AZUL_SPECIMEN_INDEX")
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 534, in transform_request
    facets)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 569, in __init__
    KeywordSearchResponse.__init__(self, hits)
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 495, in __init__
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 495, in <listcomp>
    self.map_entries(x) for x in hits], 'pagination': None}
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 468, in map_entries
    file_type_summaries = self.make_file_type_summaries(self.make_files(entry))
  File "/var/task/azul/service/responseobjects/hca_response_v5.py", line 407, in make_files
    for _file in bundle["contents"]["files"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by NoopDog** [comment]
Hi @mpanik, @theathorn 

The front end code matching the fileTypeSummaries is pushed to develop if you want to pull that and test the pagination  problem. Or you can test on https://dev.explore.data.humancellatlas.org/ as this now points to the jyo backend. 

Ping me if you have any qestions. Thanks!
D

**Comment by mpanik** [comment]
@NoopDog perfect, thanks! 
@hannes-ucsc we do have already some bundles deleted with @jyotheeshwar's [PR](https://github.com/DataBiosphere/azul/pull/157). actually this is great, otherwise we would probably miss that.

This is how the bundle shows:
```
{'uuid': 'd52046ee-93f3-4d6d-8fbf-a39c92803753', 'version': '2018-03-29T151017.801027Z', 'contents': None, 'admin_deleted': True}
```
It does not have any `contents` thus the exception.

**Comment by hannes-ucsc** [comment]
PR #224 addresses this issue but produced a regression (#251). The PR for #251 should reintroduce the changes from PR #224 and a fix for #251 on top of that. 

cc @achave11
