### ISSUE TITLE
Upgrade moto to 1.3.15 or higher

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1718]
The version we're currently on (1.3.13) is affected by https://github.com/spulec/moto/issues/2058. That import side effect is insidious and caused us [some headache](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1811) on https://github.com/DataBiosphere/azul/pull/1664 so I want to move away as soon as possible.

We can't use 1.3.14, though because of  https://github.com/DataBiosphere/azul/blob/67b0032a4b80feff04f71c89d383a055e270ed2c/requirements.dev.txt#L10 so we need to wait for 1.3.15 or whatever is next.

**Comment by natanlao** [comment]
Latest release is still 1.3.14

**Comment by melainalegaspi** [comment]
Latest release is now 1.3.16

**Comment by amarjandu** [comment]
Attempt to upgrade moto 1.3.16 or 1.3.15. If any difficulties arise suspend work on ticket. Otherwise also remove any workarounds for this issue. 

Look for fixmes, and local moto imports.

**Comment by amarjandu** [comment]
Had to use version 1.3.17.dev264  see https://github.com/spulec/moto/issues/3535

**Comment by amarjandu** [comment]
### Extra Dependencies
Unable to use `moto==1.3.17.dev264` as suggested from https://github.com/spulec/moto/issues/3535
When moto attempts to reset all backends it tries to reset backends that seem to be considered `extra`
https://github.com/spulec/moto/blob/9bfd95476b6ff55a510ea8b0ba77f98598bbf4b5/setup.py#L76

```
(.venv) specter:azul amar$ (cd test/indexer/ && python -m unittest test_health_check.TestIndexerHealthCheck)
2021-03-15 17:25:10,000 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:25:10,001 DEBUG   MainThread: Clearing cache of 'resource'
2021-03-15 17:25:10,001 INFO    MainThread: Launching container from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0
2021-03-15 17:25:10,409 INFO    MainThread: Launched container serene_khayyam from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0, with container port 9200 mapped to 127.0.0.1:54650 on the host
2021-03-15 17:25:10,409 DEBUG   MainThread: Creating ES client [127.0.0.1:54650]
...
2021-03-15 17:25:22,475 INFO    MainThread: Could not ping Elasticsearch. Retrying...
2021-03-15 17:25:23,690 INFO    MainThread: Took 13.281s to have ES reachable
2021-03-15 17:25:23,690 INFO    MainThread: Elasticsearch appears to be up.
EEEEEEEE2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:25:26,722 DEBUG   MainThread: Clearing cache of 'resource'

======================================================================
ERROR: test_basic (test_health_check.TestIndexerHealthCheck)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/test/app_test_case.py", line 96, in setUp
    super().setUp()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 167, in setUp
    moto_api_backend.reset()
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/core/models.py", line 842, in reset
    for name, backends_ in backends.named_backends():
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 96, in named_backends
    yield name, _import_backend(module_name, backends_name)
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 85, in _import_backend
    module = importlib.import_module("moto." + module_name)
  File "/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/cognitoidp/__init__.py", line 2, in <module>
    from .models import cognitoidp_backends
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/cognitoidp/models.py", line 13, in <module>
    from jose import jws
ModuleNotFoundError: No module named 'jose'
```


### Specifying Services

The install procedure from version 2.0.0 has changed to where we have to specify which services we would like to use:
https://github.com/spulec/moto/issues/3722

When trying to specify `moto[all]==1.3.17.dev264` there is an exception raised with `managedBlockchain`.

Note I am aware that 1.3.17.dev264 < 2.0.0, but 

```
(.venv) specter:azul amar$ (cd test/indexer/ && python -m unittest test_health_check.TestIndexerHealthCheck)
2021-03-15 17:11:45,759 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:11:45,760 DEBUG   MainThread: Clearing cache of 'resource'
2021-03-15 17:11:45,760 INFO    MainThread: Launching container from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0
2021-03-15 17:11:46,152 INFO    MainThread: Launched container quizzical_blackwell from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0, with container port 9200 mapped to 127.0.0.1:54509 on the host
2021-03-15 17:11:46,153 DEBUG   MainThread: Creating ES client [127.0.0.1:54509]
2021-03-15 17:11:46,163 INFO    MainThread: Could not ping Elasticsearch. Retrying...
...
2021-03-15 17:11:58,215 INFO    MainThread: Could not ping Elasticsearch. Retrying...
2021-03-15 17:11:59,475 INFO    MainThread: Took 13.322s to have ES reachable
2021-03-15 17:11:59,475 INFO    MainThread: Elasticsearch appears to be up.
EEEEEEEE2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:12:04,170 DEBUG   MainThread: Clearing cache of 'resource'
E
======================================================================
ERROR: test_basic (test_health_check.TestIndexerHealthCheck)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/test/app_test_case.py", line 96, in setUp
    super().setUp()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 167, in setUp
    moto_api_backend.reset()
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/core/models.py", line 842, in reset
    for name, backends_ in backends.named_backends():
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 98, in named_backends
    yield name, _import_backend(module_name, backends_name)
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 87, in _import_backend
    module = importlib.import_module("moto." + module_name)
  File "/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/managedblockchain/__init__.py", line 5, in <module>
    managedblockchain_backend = managedblockchain_backends["us-east-1"]
KeyError: 'us-east-1'

```

### Version 2.0.2

The same problem/s occurs for version 2.0.2
```
(.venv) specter:azul amar$ pip list | grep moto
moto                     2.0.2
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.venv) specter:azul amar$ (cd test/indexer/ && python -m unittest test_health_check.TestIndexerHealthCheck)
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:48:28,086 DEBUG   MainThread: Clearing cache of 'resource'
2021-03-15 17:48:28,086 INFO    MainThread: Launching container from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0
2021-03-15 17:48:28,488 INFO    MainThread: Launched container stupefied_napier from image docker.elastic.co/elasticsearch/elasticsearch:6.8.0, with container port 9200 mapped to 127.0.0.1:54845 on the host
2021-03-15 17:48:28,488 DEBUG   MainThread: Creating ES client [127.0.0.1:54845]
2021-03-15 17:48:28,491 INFO    MainThread: Could not ping Elasticsearch. Retrying...
...
2021-03-15 17:48:39,552 INFO    MainThread: Could not ping Elasticsearch. Retrying...
2021-03-15 17:48:40,721 INFO    MainThread: Took 12.233s to have ES reachable
2021-03-15 17:48:40,722 INFO    MainThread: Elasticsearch appears to be up.
EEEEEEEE2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'client'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'region_name'
2021-03-15 17:48:43,481 DEBUG   MainThread: Clearing cache of 'resource'

======================================================================
ERROR: test_basic (test_health_check.TestIndexerHealthCheck)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/test/app_test_case.py", line 96, in setUp
    super().setUp()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 167, in setUp
    moto_api_backend.reset()
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/core/models.py", line 842, in reset
    for name, backends_ in backends.named_backends():
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 98, in named_backends
    yield name, _import_backend(module_name, backends_name)
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/backends.py", line 87, in _import_backend
    module = importlib.import_module("moto." + module_name)
  File "/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/cognitoidp/__init__.py", line 2, in <module>
    from .models import cognitoidp_backends
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/moto/cognitoidp/models.py", line 13, in <module>
    from jose import jws
ModuleNotFoundError: No module named 'jose'
```

**Comment by amarjandu** [comment]
It looks like version 1.3.17 was abandoned due to breaking changed, see https://github.com/spulec/moto/issues/3722#issuecomment-800068362

**Comment by amarjandu** [comment]
@hannes-ucsc got it working, had to update botocore and boto3 as well, the minimum required version for moto installed with pip does not work; the KeyError above is due to the botocore module not having `managedBackend` as an available service for the partition. see https://github.com/boto/botocore/blob/848e2e5637c735430d0baff563588b433183f445/botocore/regions.py#L110

There are going to be some updates to our usage of the module in order to get tests to pass, can I get a estimate bump?

**Comment by hannes-ucsc** [comment]
Bumping estimate to account for scope creep (upgrade to moto 2.x)

**Comment by amarjandu** [comment]
https://github.com/DataBiosphere/azul/blob/develop/test/service/test_cart_export_service.py
https://github.com/DataBiosphere/azul/blob/develop/test/service/test_collection_data_access.py

Some tests that use the ResponseHelper have a bit more complicated uses of the class, might not be trivial to remove these. These tests are related to DSS functionality, might be able to stash this in the attic.

**Comment by hannes-ucsc** [comment]
Those usages of ResponseHelper should just be replaced with normal use of `responses`

**Comment by amarjandu** [comment]
Portal service exception handling needs to be updated. 
https://github.com/DataBiosphere/azul/blob/3a874aafb17fec96e67b91193a23948e9223ff58/src/azul/portal_service.py#L199

![Screen Shot 2021-03-17 at 5 23 11 PM](https://user-images.githubusercontent.com/1947534/111555524-d0c50c80-8745-11eb-973e-52627857e551.png)

Just a record of validating the recent change in moto 2.0.2.

**Comment by amarjandu** [comment]
@hannes-ucsc Ran into what appears to a bug with moto, raised issue https://github.com/spulec/moto/issues/3790

Replicated failure in 2.0.2
https://gist.github.com/amarjandu/77a7d8e33623bae1e4e5ba40dc043cb9

Observed passing in 1.3.13  
https://gist.github.com/amarjandu/fb4454e90924d3814772eca68d10dace

Waiting to hear if this is an issue with moto, or if with how we are ~holding the phone~ using the module.

**Comment by hannes-ucsc** [comment]
Nicely done reproduction on that Moto issue.
