### ISSUE TITLE
`make terraform` fails in new deployment when DSS Prod is used

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1735]
When 
`'AZUL_DSS_ENDPOINT': 'https://dss.data.humancellatlas.org/v1'`

and one runs `make terraform`, the following is observed.

```
$ make terraform
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C terraform
python /Users/abrahamchavez/PycharmProjects/Azul/azul.sc/scripts/check_branch.py
python api_gateway.tf.json.template.py api_gateway.tf.json
Traceback (most recent call last):
  File "api_gateway.tf.json.template.py", line 36, in <module>
    Lambda.for_name('indexer'),
  File "api_gateway.tf.json.template.py", line 32, in for_name
    policy=json.dumps(importlib.import_module(f'azul.{name}.policy').policy))
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/indexer/policy.py", line 86, in <module>
    f"arn:aws:s3:::{aws.dss_main_bucket(config.dss_endpoint)}/*",
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/deployment.py", line 163, in dss_main_bucket
    return self._dss_bucket(dss_endpoint, lambda_name='indexer')
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/deployment.py", line 177, in _dss_bucket
    dss_parameter = ssm.get_parameter(Name=name)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation: 
make[1]: *** [api_gateway.tf.json] Error 1
make: *** [terraform] Error 2
```
An `SSM` entry does not exist for `prod` in the lower deployments.

**Comment by jessebrennan** [comment]
Did you figure out the problem? What happened?
