### ISSUE TITLE
`make subscribe` fails against prod DSS

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1745]
`dev`: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/2061
`sandbox`: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/2077

```
$ make subscribe
python /builds/ucsc/azul/scripts/check_branch.py
if [[ $AZUL_SUBSCRIBE_TO_DSS != 0 ]]; then python scripts/subscribe.py; fi
2020-04-29 18:06:13,036 INFO    MainThread: Loaded configuration from /build/.venv/lib/python3.6/site-packages/hca/default_config.json
Traceback (most recent call last):
  File "scripts/subscribe.py", line 40, in <module>
    main(sys.argv[1:])
  File "scripts/subscribe.py", line 34, in main
    subscription.manage_subscriptions(dss_client, subscribe=options.subscribe)
  File "/builds/ucsc/azul/src/azul/subscription.py", line 21, in manage_subscriptions
    subscription_type='elasticsearch')
  File "/build/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 158, in __call__
    return self._consume_response(self._request(kwargs))
  File "/build/.venv/lib/python3.6/site-packages/hca/util/__init__.py", line 146, in _request
    raise SwaggerAPIException(response=res)
hca.util.exceptions.SwaggerAPIException: Forbidden: User is not authorized to access this resource (HTTP 403). Details:
Traceback (most recent call last):
  File "/opt/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/python/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/opt/python/lib/python3.6/site-packages/connexion/decorators/security.py", line 113, in wrapper
    token_info = token_info_func(token)
  File "/var/task/chalicelib/dss/util/security.py", line 59, in verify_jwt
    assert_authorized_issuer(unverified_token)
  File "/var/task/chalicelib/dss/util/security.py", line 98, in assert_authorized_issuer
    raise DSSForbiddenException()
dss.error.DSSForbiddenException
Makefile:15: recipe for target 'subscribe' failed
make: *** [subscribe] Error 1
```

We recently switched `sandbox`, `dev` and personal deployments to `prod` DSS AND removed the whitelist entry for the `travis-test` google project from `prod` DSS for security reasons. Unfortunately, all main Azul deployments (both sc and hca) use the same Google SA form that `travis-test` project.

As a workaround, we'll have to disable DSS subscriptions for all `dev` and `sandbox`. Subscriptions should already be disabled for personal deployments.

I doubt we'll ever need more than a workaround. But if we do, we need to revert the change that pointed the personal, `dev` and `sandbox` deployments to DSS `prod`. There just is no secure way to let those non-prod deployments subscribe to the `prod` instance of the DSS because the privilege to subscribe also implies the privilege to create bundles and files in the DSS.

**Comment by hannes-ucsc** [comment]
@amarjandu We need to find a way to remove the existing subscriptions. I tried unsubscribing but obviously that also fails with the same 403 error.

**Comment by amarjandu** [comment]
@hannes-ucsc it looks like we are using v1-subscriptions (elasticsearch) let me see if there is an easy way to remove them manually from the index; if not, I can add access for `human-cell-atlas-travis-test` to remove the subscriptions, then revoke access once this is complete. 

Another option would be to leave the subscriptions endpoints without security. But we should discuss if needed.

**Comment by amarjandu** [comment]
Removed 4 subscriptions total:
```
{"azul-ucsc-indexer-dev@human-cell-atlas-travis-test.iam.gserviceaccount.com" : 
["ca9b2640-1328-47c0-a075-444200b95875", "2b61103a-67c7-47b7-a415-9564ab2959b8"]},

{""azul-ucsc-indexer-sandbox@human-cell-atlas-travis-test.iam.gserviceaccount.com": 
["3c28f74c-8c79-4717-84f0-32b21ab2b10a", "a6efb8a4-e64c-4d6e-a764-7cf1cb1a91fc"]}

```

**Comment by hannes-ucsc** [comment]
Thank you!
