### ISSUE TITLE
Investigate other solutions for reporting coverage

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#1752]
Codecov and coveralls are both free services that have proven unreliable. We should look into other services/approaches that are more reliable, or create our own coverage script that runs as a part of the build and publishes results to github.

**Comment by melainalegaspi** [comment]
One option is to use coverage.py's html report and either upload it to a bucket or publish as a build artifact on travis/gitlab

**Comment by amarjandu** [comment]
More problems with coveralls :( 
https://travis-ci.org/github/DataBiosphere/azul/builds/707787983
```
$ coveralls

Submitting coverage to coveralls.io...

Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coveralls/api.py", line 205, in wear

    response.raise_for_status()

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coveralls/cli.py", line 85, in main

    result = coverallz.wear()

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coveralls/api.py", line 208, in wear

    raise CoverallsException('Could not submit coverage: {}'.format(e))

coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by hannes-ucsc** [comment]
Maybe we should bit the bullet and pay $25 per month https://coveralls.io/pricing.

@theathorn

**Comment by theathorn** [comment]
Let's get the 10% discount on a yearly plan for $270.

**Comment by amarjandu** [comment]
Did we ever get better service plan? 

New error occurred today:
https://travis-ci.org/github/DataBiosphere/azul/builds/725432478#L3872

**Comment by hannes-ucsc** [comment]
To be discussed at stand-up.

**Comment by achave11** [comment]
Spike: Ask service provider if we get build priority for resources assigned to generate and publish reports.

**Comment by achave11** [comment]
> Spike: Ask service provider if we get build priority for resources assigned to generate and publish reports.

Email was send to Coveralls, awaiting response.

**Comment by natanlao** [comment]
Are we collecting codecov errors here? [I have one](https://travis-ci.org/github/DataBiosphere/azul/builds/725736385#L3845):

```
==> Detecting CI provider

    Travis Detected

    Fixing merge commit SHA

==> Preparing upload

==> Processing gcov (disable by -X gcov)

==> Collecting reports

    Generating coverage xml reports for Python

    + /home/travis/build/DataBiosphere/azul/coverage.xml bytes=466945

==> Appending environment variables

    + TRAVIS_PYTHON_VERSION

    + TRAVIS_OS_NAME

==> Uploading

    .url https://codecov.io

    .query commit=316323037acca4ab094656aadb32e31717429898&branch=develop&job=725736386&pr=2244&token=<secret>&service=travis&build=9759.1&slug=DataBiosphere%2Fazul&yaml=.codecov.yml&package=py2.1.9

    Gzipping contents..

    Compressed contents to 31005 bytes

    Pinging Codecov...

Error: HTTPSConnectionPool(host='codecov.io', port=443): Max retries exceeded with url: /upload/v4?commit=316323037acca4ab094656aadb32e31717429898&branch=develop&job=725736386&pr=2244&token=[secure]&service=travis&build=9759.1&slug=DataBiosphere%2Fazul&yaml=.codecov.yml&package=py2.1.9 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1da7f68d30>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by achave11** [comment]
<img width="1511" alt="Screen Shot 2020-09-11 at 1 47 11 PM" src="https://user-images.githubusercontent.com/19215510/92971441-51245100-f435-11ea-84f4-3f543f6f30d9.png">

Obtain a response from coveralls support. It seems like the paid plan would not benefit us. How should we proceed?
