### ISSUE TITLE
Eliminate all indexing errors for DSS `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1768]
Before we migrate the contents of the DSS to TDR, we need to make sure that we can index all bundles in DSS prod. 

Perform a reindex, capture and triage all permanent indexing errors. The fix to these errors will be either to delete the offending bundle from the DSS or to modify the Azul indexer so it doesn't raise an error for them.

**Comment by hannes-ucsc** [comment]
I did a re-index over night: no failed tallies but 61 failed notifications. Failures attached. Queues were purged.

[azul-fail-dev.zip](https://github.com/DataBiosphere/azul/files/4587714/azul-fail-dev.zip)

**Comment by amarjandu** [comment]
Upon inspection of manifests for the failed notifications:

1. Generate Manifests
```cat azul-fail-dev.json  | jq  -r '.messages[] | .Body.notification.match | .bundle_uuid,.bundle_version' | xargs -n2 sh -c 'hca dss get-bundle --uuid $0 --version $1 --replica aws 1>$0.manifest 2>$0.error'```

2. Inspect for size 0 files:
```find *.manifest | xargs -n1 sh -c 'cat $0 | jq -r ".bundle| select(.files[].size==0) | (.uuid + \".\" + .version)"'```

55 of them have empty files...

```
04cdef35-5c0c-4f75-ab1b-ab66c66a6e58.2019-07-23T175423.984602Z
05fc240e-cd04-40e0-b6c2-059ba982f1de.2019-07-30T192059.629519Z
0d3477d7-e190-4e9c-a163-f8819db1f227.2019-09-09T221824.848034Z
14273b8d-bca6-4b72-be72-ca4f19623ee4.2019-09-09T221739.861168Z
170933df-4405-4e28-9611-3b0a7d165ae5.2019-07-23T175724.419005Z
24cda1ca-d588-402e-880b-b560e6167527.2019-08-01T215522.012761Z
2817d919-7ef1-42ec-b338-03674dd02feb.2019-08-05T224610.349229Z
286bfd51-a873-415b-b14e-bb6b629c9c2f.2019-08-05T225834.495519Z
2baf256c-2c15-4587-81bd-852f8a3932b4.2019-07-10T190507.501929Z
36a39838-28de-4e78-859e-d0778620c778.2019-08-05T185045.489448Z
39629ab2-fc94-4e97-902f-de4ffa23f79a.2019-08-05T184644.217873Z
3ffccaa0-56cb-463c-a2b3-6808ac1f0e9e.2019-07-10T184036.829039Z
46258a39-3db0-4a58-a07a-dcaf3b7cb4a8.2020-05-06T003717.924777Z
5131a83e-abe6-4c0b-80c4-88491a6b133c.2019-07-10T185248.245209Z
51e56940-706e-4adf-8f1b-db31308b3d8d.2019-07-30T192029.999854Z
54941366-0935-4941-9548-e86e5edc1285.2019-07-08T230621.912106Z
5640ae55-fd1e-42e5-9822-e97e6eab072d.2020-05-06T003908.835520Z
5d0b19de-3512-4192-a3e0-e2785b7112fc.2019-07-08T231648.329089Z
64bc8ed8-0ceb-49c0-9b36-3f8acfb343ba.2019-07-08T231711.917523Z
65265a38-e146-410f-9d36-fe7dc4f1b04e.2020-05-06T003551.560903Z
69db98a2-5d9c-4779-a2a9-49a271116d88.2019-09-05T182349.691081Z
6a0de4df-9962-4a6a-a29a-9ab522fe6b09.2019-09-05T185111.818094Z
6faf2454-76ad-45d1-bfbe-ed07fc2ec812.2019-09-05T182214.717461Z
716b3dd5-4104-4ebf-b85b-7bce2d6ff892.2019-07-23T175914.819925Z
81fbc171-984e-4ea2-beb9-d58607b93df3.2019-08-05T185113.345359Z
820d48c7-a150-4a3f-81a6-1ca1d2665bad.2019-07-10T192013.756332Z
845933aa-b238-4c55-a6a0-4c622c67af53.2019-08-05T184721.920593Z
8586d38e-b743-4ec5-8e74-38ab4b6c7e02.2019-09-09T221828.818745Z
85a199f1-6820-4d08-9787-6694d357b3d4.2019-07-10T183934.593670Z
8642baea-d7c6-4d14-a6ec-a46fee5871f4.2019-08-05T200407.656720Z
86d19d63-aa71-4376-88b8-81c0a13d9b1c.2019-08-05T185443.996062Z
8b5c0729-37b1-4377-ab1c-5b932de10826.2019-09-05T182154.052280Z
905b7332-568f-4bee-9b7a-4bad5665e68e.2019-07-10T190546.990820Z
98472b92-6aa4-4c27-97ad-52b9c2b531b4.2019-08-05T185110.383443Z
9c85a682-8a29-4062-8503-c45e37be5bf6.2019-07-10T190123.278032Z
a2703158-3f33-4a4a-bde6-b1ffde84e68e.2019-07-10T185853.163903Z
a2b83c29-c9ba-4b08-9b7c-14d2bd3581d6.2020-05-06T003912.913590Z
a416ef51-3c77-49b7-913a-b62080aa3786.2019-07-30T192056.427560Z
ab37c0a0-7617-42b3-8e4d-eebd201b702e.2019-08-02T190448.268469Z
b079e99c-42e7-4d9f-ae83-19f747b4adcb.2019-08-02T190138.629254Z
b5236f06-6f11-494f-b5b3-41f3fafeb88e.2019-07-23T180000.212292Z
b635b2e7-d72f-406d-9ac1-4181df36341f.2019-08-05T185024.610340Z
cab1806b-c238-41aa-ad83-5408656640fd.2019-09-05T182345.933762Z
d4303853-529f-4617-a765-76bb9c5723fa.2019-07-10T184405.638125Z
d4da4f71-02b4-437c-91ae-5219f479a175.2019-07-30T192020.496371Z
d55ce053-95e3-48a0-bec9-2d22718b6628.2019-08-05T185529.676531Z
deb7e2b6-101d-40ad-93d7-a4e922807b22.2019-07-10T190307.877273Z
e72edef7-b3de-4895-bcc2-9d1c3678d6e4.2019-08-01T223656.070705Z
eb4d5222-e363-4d91-888b-6c7b138fc059.2019-08-05T184632.417327Z
f0d40e54-7ccd-4bdb-8d4b-e40256942760.2019-07-08T231627.366031Z
f0f5d1f7-b777-431e-8618-c6f43ac7136a.2019-09-09T221719.097039Z
f5ca6a1e-a870-4474-a50f-0dbeac647b40.2019-08-01T223624.412220Z
f89b2ea9-6698-4d3b-a104-97cda08cff27.2019-08-05T225838.273291Z
f961b3fe-6e6f-4bed-9dc4-f042d3b3d91b.2019-08-05T224620.278567Z
fa09d968-3d16-4c6d-80f4-dd9a4505f4fa.2019-08-05T184718.657513Z
```


3).  6 of the bundles appear to have fairly normal manifests, and need to be further inspected

```comm -23 all_bundle_fqids empty_bundle_fqids
1bd9bdbe-33a2-4eb5-90e2-1df5fa00d504.2018-08-17T202728.071749Z
1f671207-2e4a-452e-94f0-547d696317a3.2018-08-17T202546.197851Z
869c5cd3-98fd-4947-85eb-29d1a9cbd496.2018-08-17T202940.855330Z
91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z
94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z
e78fb1d9-e6f0-4c9e-8e66-d5d64d4fa970.2018-08-17T202915.922549Z```

**Comment by amarjandu** [comment]
Tombstone Campaign: https://gist.github.com/amarjandu/7918b32f09288f05c420d38d7c05bfc5

**Comment by amarjandu** [comment]
`/aws/lambda/azul-indexer-amar-index`

Observed the following error when attempting to index the bundles:
`91b291ea-40eb-4e0b-b289-4482ce207f29.2018-08-17T202425.293015Z`
`94b4d6a7-881f-42d8-ac42-fc61153b26ac.2018-08-17T202025.771186Z`

```
'R1.fastq.gz': KeyError
Traceback (most recent call last):
File "/var/task/app.py", line 169, in new_handler
return old_handler(self, event, context)
File "/var/task/chalice/app.py", line 1422, in __call__
return self.func(event_obj)
File "/var/task/app.py", line 196, in index
contributions = indexer.transform(notification, delete=False)
File "/var/task/azul/indexer/__init__.py", line 151, in transform
metadata_files=metadata_files))
File "/var/task/azul/project/hca/transformers.py", line 571, in transform
metadata_files=metadata_files)
File "/opt/python/humancellatlas/data/metadata/api.py", line 767, in __init__
self.files = from_json_vx(File, manifest=self.manifest)
File "/opt/python/humancellatlas/data/metadata/api.py", line 761, in from_json_vx
return from_json(core_cls, json_entities, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 730, in from_json
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 730, in <dictcomp>
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 729, in <genexpr>
entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
File "/opt/python/humancellatlas/data/metadata/api.py", line 57, in from_json
return sub_cls(json, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 648, in __init__
super().__init__(json, manifest)
File "/opt/python/humancellatlas/data/metadata/api.py", line 621, in __init__
self.manifest_entry = manifest[core['file_name']]
KeyError: 'R1.fastq.gz'
```

The version stamp indicates that these bundles are old, perhaps metadata schema is causing issue? 
```
hca dss get-bundle --replica aws --uuid 91b291ea-40eb-4e0b-b289-4482ce207f29 --version 2018-08-17T202425.293015Z | jq .bundle.files[].name
"process_2.json"
"library_preparation_protocol_0.json"
"dissociation_protocol_0.json"
"sequencing_protocol_0.json"
"specimen_from_organism_0.json"
"donor_organism_0.json"
"sequence_file_0.json"
"sequence_file_1.json"
"process_0.json"
"cell_suspension_0.json"
"project_0.json"
"links.json"
"enrichment_protocol_0.json"
"process_1.json"
```

R1.fastq.gz are not present within the manifest on either bundle...

**Comment by amarjandu** [comment]
All six of the bundles have the same missing fastq errors within the `sc-dev` deployment, these were labeled as `bad-bundles`. And also to be tombstoned.

**Comment by amarjandu** [comment]
Updated Tombstone Campaign: https://gist.github.com/amarjandu/7918b32f09288f05c420d38d7c05bfc5

**Comment by amarjandu** [comment]
Tombstone Complete

**Comment by hannes-ucsc** [comment]
@amarjandu, it sounds like you addressed all 61 failing bundles by tombstoning them. If that's not the case, let me know. Otherwise, the next step is to reindex the platform-sc `dev` deployment again. Please coordinate that with me over Slack. Be sure to purge the fail queues before you start the reindex.

**Comment by amarjandu** [comment]
a reindex has been started in `sc-dev`.

**Comment by amarjandu** [comment]
reindex is complete, no failure notifications found in the failure queues.
