### ISSUE TITLE
IT fails the wrong way when notification is not sent

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1838]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/2980

tripped an assertion 

```
FAIL: test (integration_test.IntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 45, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 150, in test
    self._test_indexing()
  File "/builds/ucsc/azul/test/integration_test.py", line 172, in _test_indexing
    self._check_bundles_are_indexed(self.test_name, 'files')
  File "/builds/ucsc/azul/test/integration_test.py", line 394, in _check_bundles_are_indexed
    self.assertEqual(indexed_fqids, self.expected_fqids)
AssertionError: Items in the second set but not the first:
BundleFQID(uuid='c8472863-054f-4cb4-9f76-6b14ef3daae3', version='2020-05-26T180831.725509Z')
```

I checked the lambda logs and couldn't actually find any evidence that an addition notification was ever received for this bundle.

Indeed, there is some evidence in the test logs for DNS issues while sending out notifications:

```
2020-05-26 18:09:20,278 WARNING MainThread: Unhandled exception in worker:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f84bf0706a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/build/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='indexer.dev.singlecell.gi.ucsc.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f84bf0706a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 110, in attempt
    self.post_bundle(url.geturl(), notification)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 63, in post_bundle
    response = requests.post(indexer_url, json=notification, auth=hmac.prepare())
  File "/build/.venv/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/build/.venv/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/build/.venv/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/build/.venv/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/build/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='indexer.dev.singlecell.gi.ucsc.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f84bf0706a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

The test should 1) retry sending the notification and 2) fail right away when one or more notifications permanently failed to be sent out.

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/3451

**Comment by amarjandu** [comment]
Changes to verify exception handling works. 
```
diff --git a/src/azul/azulclient.py b/src/azul/azulclient.py
index f17ad009..9a5c941d 100644
--- a/src/azul/azulclient.py
+++ b/src/azul/azulclient.py
@@ -105,6 +105,9 @@ class AzulClient(object):
             def attempt(notification, i):
                 try:
                     logger.info("Sending notification %s to %s -- attempt %i:", notification, indexer_url, i)
+                    import random
+                    if random.randint(0,100) % 10 == 0:
+                        raise requests.ConnectionError()
                     url = urlparse(indexer_url)
                     self.post_bundle(url.geturl(), notification)
                 except requests.HTTPError as e:
@@ -123,22 +126,18 @@ class AzulClient(object):
                 nonlocal indexed
                 # @formatter:on
                 # Block until future raises or succeeds
-                exception = future.exception()
-                if exception is None:
-                    bundle_fqid, result = future.result()
-                    if result is None:
-                        indexed += 1
-                    elif isinstance(result, requests.HTTPError):
-                        status_code = result.response.status_code
-                        errors[status_code] += 1
-                        missing.append((notification, status_code))
-                    elif isinstance(result, Future):
-                        # The task scheduled a follow-on task, presumably a retry. Follow that new task.
-                        handle_future(result)
-                    else:
-                        assert False
+                bundle_fqid, result = future.result()
+                if result is None:
+                    indexed += 1
+                elif isinstance(result, requests.HTTPError):
+                    status_code = result.response.status_code
+                    errors[status_code] += 1
+                    missing.append((notification, status_code))
+                elif isinstance(result, Future):
+                    # The task scheduled a follow-on task, presumably a retry. Follow that new task.
+                    handle_future(result)
                 else:
-                    logger.warning("Unhandled exception in worker:", exc_info=exception)
+                    assert False
 
             futures = []
             for notification in notifications:

```



```
.......
ERROR
test_azul_client_error_handling (integration_test.IntegrationTest) ... 2020-06-17 12:39:10,918 INFO    MainThread: Setting environment variable AZUL_TEST_MODE to "1" on function azul-indexer-amar
/Users/amar/dev/hca/azul/test/integration_test.py:141: ResourceWarning: unclosed <ssl.SSLSocket fd=94, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.11', 57015), raddr=('100.25.113.218', 443)>
  self._set_test_mode(True)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2020-06-17 12:39:11,167 INFO    pool_0: Sending notification {} to https://indexer.amar.dev.singlecell.gi.ucsc.edu/ -- attempt 0:
2020-06-17 12:39:13,903 WARNING pool_0: Notification {}, attempt 0: retrying after error 400 Client Error: Bad Request for url: https://indexer.amar.dev.singlecell.gi.ucsc.edu/
2020-06-17 12:39:13,903 INFO    pool_1: Sending notification {} to https://indexer.amar.dev.singlecell.gi.ucsc.edu/ -- attempt 1:
2020-06-17 12:39:14,175 WARNING pool_1: Notification {}, attempt 1: retrying after error 400 Client Error: Bad Request for url: https://indexer.amar.dev.singlecell.gi.ucsc.edu/
2020-06-17 12:39:14,176 INFO    pool_1: Sending notification {} to https://indexer.amar.dev.singlecell.gi.ucsc.edu/ -- attempt 2:
2020-06-17 12:39:14,722 WARNING pool_1: Notification {}, attempt 2: retrying after error 400 Client Error: Bad Request for url: https://indexer.amar.dev.singlecell.gi.ucsc.edu/
2020-06-17 12:39:14,722 INFO    pool_1: Sending notification {} to https://indexer.amar.dev.singlecell.gi.ucsc.edu/ -- attempt 3:
2020-06-17 12:39:15,109 INFO    MainThread: Setting environment variable AZUL_TEST_MODE to "0" on function azul-indexer-amar
/Users/amar/dev/hca/azul/test/integration_test.py:144: ResourceWarning: unclosed <ssl.SSLSocket fd=94, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.11', 57021), raddr=('100.25.113.189', 443)>
  self._set_test_mode(False)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR
test_concurrent_portal_db_crud (integration_test.IntegrationTest)
Use multithreading to simulate multiple users simultaneously modifying ... 2020-06-17 12:39:15,779 INFO    MainThread: Setting environment variable AZUL_TEST_MODE to "1" on function azul-indexer-amar
.........
Omitted ResourceWarnings here.....
.........
======================================================================
ERROR: test (integration_test.IntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/test/integration_test.py", line 158, in test
    self.azul_client._index(self.test_notifications)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 147, in _index
    handle_future(future)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 129, in handle_future
    bundle_fqid, result = future.result()
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 110, in attempt
    raise requests.ConnectionError()
requests.exceptions.ConnectionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 45, in wrapped
    return method(*args, **kwargs)
  File "/Users/amar/dev/hca/azul/test/integration_test.py", line 166, in test
    self._delete_bundles(self.test_notifications)
  File "/Users/amar/dev/hca/azul/test/integration_test.py", line 237, in _delete_bundles
    self.azul_client.delete_notification(notifications)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 262, in delete_notification
    self._index(notifications, path='/delete')
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 147, in _index
    handle_future(future)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 129, in handle_future
    bundle_fqid, result = future.result()
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/amar/dev/hca/azul/src/azul/azulclient.py", line 110, in attempt
    raise requests.ConnectionError()
requests.exceptions.ConnectionError
....
```
