### ISSUE TITLE
PaginationTestCase.test_search_after_last_page fails randomly

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#205]
```
======================================================================
FAIL: test_search_after_last_page (service.test_pagination.PaginationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/DataBiosphere/azul/test/service/test_pagination.py", line 148, in test_search_after_last_page
    "search_after is not null on last page")
AssertionError: '0094346d-ca16-f939-8c9e-8b3b52caee07' is not None : search_after is not null on last page
----------------------------------------------------------------------
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-149)
┆Project Name: azul
┆Issue Number: AZUL-149

**Comment by hannes-ucsc** [comment]
```
Serving on localhost:0
127.0.0.1 - - [21/Aug/2018 07:44:50] "GET / HTTP/1.1" 200 -
azul-service-hannes - DEBUG - Parameter file_id: None
azul-service-hannes - DEBUG - Filters string is: {"file": {}}
azul-service-hannes - INFO - Extracting the filter parameter from the request
azul-service-hannes - INFO - Creating pagination
azul-service-hannes - DEBUG - Pagination: 

azul-service-hannes - INFO - Creating ElasticTransformDump object
INFO:dashboardService.elastic_request_builder.ElasticTransformDump:Creating an instance of ElasticTransformDump
azul-service-hannes - INFO - Creating the API response
INFO:dashboardService.elastic_request_builder.ElasticTransformDump:Transforming /specimens request
INFO:elasticsearch:GET http://127.0.0.1:32783/browser_files_dev/_search [status:200 request:0.263s]
INFO:dashboardService.elastic_request_builder.ElasticTransformDump:length of es_hits: 0
INFO:dashboardService.elastic_request_builder.ElasticTransformDump:Creating FileSearchResponse
INFO:dashboardService.api_response.EntryFetcher:Creating the entries in ApiResponse
INFO:dashboardService.elastic_request_builder.ElasticTransformDump:Returning the final response for transform_request()
127.0.0.1 - - [21/Aug/2018 07:44:51] "GET /repository/files?sort=entryId&order=desc HTTP/1.1" 200 -

Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/hannes/workspace/hca/azul/test/service/test_pagination.py", line 84, in test_search_after_page1
    self.assert_page1_correct(json_response)
  File "/Users/hannes/workspace/hca/azul/test/service/test_pagination.py", line 36, in assert_page1_correct
    json_response['hits'][num_hits - 1]['entryId'],
IndexError: list index out of range
```

From a local run of the tests.

**Comment by GPelayo** [comment]
The error above is from test_search_after_page1() and this ticket only covers test_search_after_last_page(). Will this ticket cover all tests in PaginationTestCase?
