### ISSUE TITLE
TestDataExtractorTestCase.test_hca_extraction is failing indeterminately

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#207]
FAIL: test_hca_extraction (indexer.test_projects.TestDataExtractorTestCase)

Traceback (most recent call last):
  File "/home/travis/build/DataBiosphere/azul/test/indexer/test_projects.py", line 71, in test_hca_extraction
    _assert_number_of_files()
  File "/home/travis/build/DataBiosphere/azul/src/azul/__init__.py", line 204, in call
    return func(*args, **kwargs)
  File "/home/travis/build/DataBiosphere/azul/test/indexer/test_projects.py", line 67, in _assert_number_of_files
    self.assertEqual(776, total_files["count"])
AssertionError: 776 != 742

**Comment by alex-hancock** [comment]
I've been mussing around with this a bit, 10 seconds is insufficient to correct the failures. Also, this test is taking almost four minutes at this point, is there a way to speed it up, or is the concept of the test inherently time-consuming?

**Comment by alex-hancock** [comment]
I have been running the test with no other changes than increasing the `eventually` timeout parameter to 15 seconds, and this seems sufficient to pass thus far. 

That's probably enough to close the ticket reliably, but it might be better to have a sub-test for each bundle and check incrementally.

**Comment by alex-hancock** [comment]
Possibly use the `refresh` parameter [here](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.index)

**Comment by alex-hancock** [comment]
Decision reached with Hannes:
1. Add the refresh parameter as "waitFor" in index and bulk commands in `indexer.py`
2. Surgically neuter the `eventually` method to remove retries. 
3. Create a ticket referencing these changes so we can decide at a later date to keep the refresh parameters or return to the `eventually` paradigm (with this augmented value)
