### ISSUE TITLE
Unexpected warnings raised when testing

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2077]
This seems to be only happening on my and @danielsotirhos's personal dev machines.

To reproduce, create a new virtual environment, and run `make requirements`. Then run a test, for example 

```
python -m unittest service.test_repository_specimen
```
will fail with:
```
.E
======================================================================
ERROR: tearDownClass (service.test_repository_specimen.RepositorySpecimenEndpointTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jesse/gi/azul/test/service/test_repository_specimen.py", line 22, in tearDownClass
    super().tearDownClass()
  File "/home/jesse/gi/azul/test/es_test_case.py", line 69, in tearDownClass
    super().tearDownClass()
  File "/home/jesse/gi/azul/test/docker_container_test_case.py", line 98, in tearDownClass
    super().tearDownClass()
  File "/home/jesse/gi/azul/test/app_test_case.py", line 81, in tearDownClass
    super().tearDownClass()
  File "/home/jesse/gi/azul/test/azul_test_case.py", line 130, in tearDownClass
    super().tearDownClass()
  File "/home/jesse/gi/azul/test/azul_test_case.py", line 68, in tearDownClass
    assert not caught_warnings, list(map(str, caught_warnings))
AssertionError: ["{message : ImportWarning('Not importing directory /home/jesse/gi/azul/.venv/lib/python3.8/site-packages/zope: missing __init__'), category : 'ImportWarning', filename : '<frozen importlib._bootstrap_external>', lineno : 489, line : None}", "{message : ImportWarning('Not importing directory /home/jesse/gi/azul/.venv/lib/python3.8/site-packages/google: missing __init__'), category : 'ImportWarning', filename : '<frozen importlib._bootstrap_external>', lineno : 489, line : None}", "{message : ImportWarning('Not importing directory /home/jesse/gi/azul/.venv/lib/python3.8/site-packages/google/logging: missing __init__'), category : 'ImportWarning', filename : '<frozen importlib._bootstrap_external>', lineno : 489, line : None}", "{message : ImportWarning('Not importing directory /home/jesse/gi/azul/.venv/lib/python3.8/site-packages/google/cloud: missing __init__'), category : 'ImportWarning', filename : '<frozen importlib._bootstrap_external>', lineno : 489, line : None}"]
----------------------------------------------------------------------
Ran 1 test in 13.593s
FAILED (errors=1)

```

**Comment by jessebrennan** [comment]
A work around is to run `pip install -U setuptools`

**Comment by hannes-ucsc** [comment]
See also: https://github.com/zopefoundation/zope.interface/issues/68

Before we attempt to address this, I would like to understand if `make test` also produces this on a developer's machine. If it does, I want to understand why it's not happening on CI and if it does not, I would like to understand why not.

**Comment by jessebrennan** [comment]
I ran `make test` locally and it passed, even though I have the older version of setup tools:
```
pip list | grep setuptools
setuptools               40.1.0
```

After this succeeded, I tried running `python -m unittest service.test_repository_specimen` again and it still fails.

**Comment by hannes-ucsc** [comment]
OK, that explains why it's passing on Gitlab. Next step is to figure out why `coverage run -m unittest discover test --verbose` emits warnings while `python -m unittest …` does not. To do so I would remove `coverage` from the picture. Alternatively, it's also possible that one of the other tests has the side effect of disabling the warnings.

**Comment by jessebrennan** [comment]
I ran `coverage -m unittest service.test_repository_specimen` and the test still failed (though that's different than the experiment you were describing).

**Comment by jessebrennan** [comment]
The ImportWarning will be suppressed if any tests that use moto are also run. I don't understand the mechanism for how.

**Comment by jessebrennan** [comment]
I've managed to get a stack trace for when the import warning is being raised:

```
args=(ImportWarning('Not importing directory /home/jesse/gi/azul/.venv/lib/python3.8/site-packages/zope: missing __init__'), <class 'ImportWarning'>, '<frozen importlib._bootstrap_external>', 489, None, None) kwargs={}
  File "/snap/pycharm-professional/211/plugins/python/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/snap/pycharm-professional/211/plugins/python/helpers/pycharm/teamcity/unittestpy.py", line 310, in run
    return super(TeamcityTestRunner, self).run(test)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 114, in run
    self._handleClassSetUp(test, result)
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/home/jesse/gi/azul/test/service/test_repository_specimen.py", line 20, in setUpClass
    super().setUpClass()
  File "/home/jesse/gi/azul/test/indexer/__init__.py", line 59, in setUpClass
    super().setUpClass()
  File "/home/jesse/gi/azul/test/es_test_case.py", line 38, in setUpClass
    super().setUpClass()
  File "/home/jesse/gi/azul/test/app_test_case.py", line 88, in setUpClass
    cls.app_module = load_app_module(cls.lambda_name(), unit_test=True)
  File "/home/jesse/gi/azul/src/azul/modules.py", line 45, in load_app_module
    return load_module(path, f'lambdas.{lambda_name}.app', module_attributes)
  File "/home/jesse/gi/azul/src/azul/modules.py", line 36, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/lambdas/service/app.py", line 40, in <module>
    from azul import (
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/src/azul/drs.py", line 35, in <module>
    from azul import (
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/src/azul/dss.py", line 26, in <module>
    from hca.dss import (
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/hca/__init__.py", line 2, in <module>
    from . import dss, upload, auth
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/hca/dss/__init__.py", line 24, in <module>
    from hca.dss.util import iter_paths, object_name_builder, hardlink, atomic_overwrite
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/hca/dss/util/__init__.py", line 9, in <module>
    from ...util.compat import scandir
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/hca/util/__init__.py", line 109, in <module>
    from ._docs import _pagination_docstring, _streaming_docstring, _md2rst, _parse_docstring
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/hca/util/_docs.py", line 5, in <module>
    from docutils.parsers.rst import Parser as RSTParser
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 75, in <module>
    from docutils.parsers.rst import states
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 116, in <module>
    from docutils.parsers.rst import directives, languages, tableparser, roles
  File "<frozen importlib._bootstrap>", line 1042, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/docutils/parsers/rst/roles.py", line 78, in <module>
    from docutils.utils.code_analyzer import Lexer, LexerError
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/docutils/utils/code_analyzer.py", line 12, in <module>
    from pkg_resources import DistributionNotFound as ResourceError
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3106, in <module>
    def _initialize_master_working_set():
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3131, in _initialize_master_working_set
    tuple(
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3132, in <genexpr>
    dist.activate(replace=False)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2640, in activate
    declare_namespace(pkg)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2177, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2097, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 489, in _find_module_shim
  File "/home/jesse/.pyenv/versions/3.8.3/lib/python3.8/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/home/jesse/gi/azul/test/azul_test_case.py", line 39, in print_warning
    traceback.print_stack()
```

**Comment by jessebrennan** [comment]
I couldn't reproduce this on the latest develop. A `git bisect` proved that 4ad2d0d3b655f714e088ad86afdc9f28dd405d3c resolves this issue incidentally (without updating setuptools)

**Comment by jessebrennan** [comment]
When `pkg_resources` is imported for the first time, some code runs that may raise the warnings we are experiencing. If `pkg_resources` is imported for the first time during the test, the test will fail because of warning catching.

I haven't figured out why the import may happen in different places, but I think this sufficiently explains the problem. The work-around is the correct fix in my opinion.

**Comment by jessebrennan** [comment]
The [bug that was blocking this](https://github.com/DataBiosphere/azul/issues/2261) has been closed.
