### ISSUE TITLE
AttributeError encountered while running `make local` on Service

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2112]
Running a `make local` on Service works …
```
$ make local
python .chalice/config.json.template.py .chalice/config.json
Creating .chalice/config.json
chalice local
Serving on http://127.0.0.1:8000
```
… until an endpoint is hit.
```
$ curl http://127.0.0.1:8000/index/projects
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/chalice/app.py", line 1112, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 1095, in get_project_data
    return repository_search('projects', project_id)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 844, in repository_search
    catalog = app.catalog
AttributeError: 'LocalChalice' object has no attribute 'catalog'

```

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "add a test that reproduces it"

**Comment by achave11** [comment]
In similar proximity, the following error was observed.

```
Caught exception for <function get_project_data at 0x1133a78b0>
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/chalice/app.py", line 1112, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 1095, in get_project_data
    return repository_search('projects', project_id)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 843, in repository_search
    validate_repository_search(query_params)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 602, in validate_repository_search
    validate_params(params, **{
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 805, in validate_params
    validator(param_value)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 687, in validate_filters
    validate_facet(facet)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 713, in validate_facet
    if facet_name not in app.service_config.translation:
AttributeError: 'LocalChalice' object has no attribute 'service_config'
127.0.0.1 - - [04/Aug/2020 20:30:10] "GET /index/projects?filters={%22genusSpecies%22:{%22is%22:[%22Homo%20sapiens%22]}}&size=15 HTTP/1.1" 500 -

```

**Comment by achave11** [comment]
Hannes and I found a solution and we agreed I would be addressing this ticket.

**Comment by achave11** [comment]
PR in [DataBiosphere/azul-chalice](https://github.com/DataBiosphere/azul-chalice/pull/1)

**Comment by hannes-ucsc** [comment]
The azul-chalice PR has been merged and tag https://github.com/DataBiosphere/azul-chalice/releases/tag/1.14.0%2B5 has been created. Azul needs to be updated to depend on the tagged version,
