### ISSUE TITLE
`make reindex` fails due to unexpected event source mapping state `Updating`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2132]
https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/6070

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/azul/azul/src/azul/queues.py", line 313, in _manage_sqs_push
    raise NotImplementedError(state)
NotImplementedError: Updating
```

**Comment by hannes-ucsc** [comment]
Freebie of #2080.
