### ISSUE TITLE
Travis tests fail because Elasticsearch Docker container is not found

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2148]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/models/containers.py", line 765, in run
    container = self.create(image=image, command=command,
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0")
```

The stack trace was taken from this build: https://travis-ci.org/github/DataBiosphere/azul/builds/717331422

**Comment by melainalegaspi** [comment]
@hannes-ucsc:" Transient infrequent error that we can't fix easily anyways."

**Comment by jessebrennan** [comment]
This occurred again https://github.com/DataBiosphere/azul/issues/2684#issuecomment-801411147
