### ISSUE TITLE
Service responds with 500 error if invalid catalog is specified

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2158]
I assume this should be a 4xx error.

Request: https://service.dev.singlecell.gi.ucsc.edu/index/files?catalog=foo

response:

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1112, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1074, in get_data
    return repository_search('files', file_id)
  File "/var/task/app.py", line 849, in repository_search
    return service.get_data(catalog, entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository_service.py", line 86, in get_data
    return self._get_items(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 62, in _get_items
    response = self._get_data(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 43, in _get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 545, in transform_request
    service_config = self.service_config(catalog)
  File "/var/task/azul/service/elasticsearch_service.py", line 93, in service_config
    return self._service_config or self.metadata_plugin(catalog).service_config()
  File "/var/task/azul/indexer/document_service.py", line 39, in metadata_plugin
    return MetadataPlugin.load(catalog).create()
  File "/var/task/azul/plugins/__init__.py", line 87, in load
    plugin_package_name = config.plugin_name(catalog, plugin_type_name)
  File "/var/task/azul/__init__.py", line 618, in plugin_name
    return self.catalogs[catalog_name][plugin_type]
KeyError: 'foo'
```

**Comment by amarjandu** [comment]
This ticket should be resolved with the validation modifications for #1465.

```
2020-08-14 14:12:30,738 INFO    Thread-3: Received GET request to '/index/samples' with parameters {"catalog": "JesseIsCool", "size": "1"}.
2020-08-14 14:12:30,739 DEBUG   Thread-3: Returning 400 response without headers. See next line for the first 1024 characters of the body.
{"Code": "BadRequestError", "Message": "BadRequestError: Invalid input for {'name': 'catalog', 'value': 'JesseIsCool'}, must be within ['test']"}
127.0.0.1 - - [14/Aug/2020 14:12:30] "GET /index/samples?catalog=JesseIsCool&size=1 HTTP/1.1" 400 -
```
