### ISSUE TITLE
Error caused by filter: 'assayType' is null

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2191]
Specifying a filter of `filters={"assayType":{"is":[null]}}` causes an error on all browsers (HCA dev, HCA prod, SC dev)

[https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters={"assayType":{"is":[null]}}&size=15&sort=projectTitle&order=asc](https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%22assayType%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc)

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1112, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1095, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 849, in repository_search
    return service.get_data(catalog, entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository_service.py", line 86, in get_data
    return self._get_items(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 62, in _get_items
    response = self._get_data(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 43, in _get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 586, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/opt/python/elasticsearch_dsl/search.py", line 702, in execute
    es.search(
  File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/python/elasticsearch/client/__init__.py", line 851, in search
    return self.transport.perform_request(
  File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 'No value specified for terms query')
```

[https://service.explore.data.humancellatlas.org/repository/projects?filters={"assayType":{"is":[null]}}&size=15&sort=projectTitle&order=asc](https://service.explore.data.humancellatlas.org/repository/projects?filters=%7B%22assayType%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc)
```
{
"Code": "InternalServerError",
"Message": "An internal server error occurred."
}
```

It should be noted that this does not occur with other facets such as `{"donorDisease":{"is":[null]}}`

[https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters={"donorDisease":{"is":[null]}}&size=15&sort=projectTitle&order=asc)](https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%22donorDisease%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc)

**Comment by amarjandu** [comment]
this will not be ported to `hca/` branches

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Assay type is an imagining-specific property and do not currently have imaging bundles in DCP2. Postponing until we have imaging bundles."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Consider the changes we've recently made with respect to nested index fields as part of #3682."
