### ISSUE TITLE
Unable to re-register Service Account with SAM

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2246]
I was messing with my service account shared credentials for #2143 .
I ended up deleting the underlying Service Account while still having the secrets stored in the secret manager, and registered with SAM. 
Due to the invalid keys, i ran:
 ```
make -C terraform validate
cd terraform
terraform destroy -target=google_service_account.indexer &&  terraform apply -target=google_service_account.indexer
```` 
 I get an error when trying to run `make sam` for the registration. 

```
(.venv) Specter:terraform amar$ make sam
python /Users/amar/dev/hca/azul/scripts/register_sam.py
2020-09-10 09:39:35,608 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 37, in <module>
    main()
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 23, in main
    tdr.register_with_sam()
  File "/Users/amar/dev/hca/azul/src/azul/tdr.py", line 134, in register_with_sam
    raise RuntimeError('Unexpected response during SAM registration', response.data)
RuntimeError: ('Unexpected response during SAM registration', b'{"causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.model.WorkbenchException","message":"Cannot update googleSubjectId for user [REDACTED] because user does not exist or the googleSubjectId has already been set for this user","source":"sam","stackTrace":[{"className":"org.broadinstitute.dsde.workbench.sam.directory.PostgresDirectoryDAO","fileName":"PostgresDirectoryDAO.scala","lineNumber":842,"methodName":"$anonfun$setGoogleSubjectId$1"},{"className":"org.broadinstitute.dsde.workbench.sam.directory.PostgresDirectoryDAO","fileName":"PostgresDirectoryDAO.scala","lineNumber":835,"methodName":"$anonfun$setGoogleSubjectId$1$adapted"},{"className":"org.broadinstitute.dsde.workbench.sam.db.DbReference","fileName":"DbReference.scala","lineNumber":75,"methodName":"$anonfun$inLocalTransaction$1"},{"className":"scalikejdbc.DBConnection","fileName":"DBConnection.scala","lineNumber":335,"methodName":"$anonfun$localTx$3"},{"className":"scalikejdbc.DBConnection","fileName":"DBConnection.scala","lineNumber":300,"methodName":"rollbackIfThrowable"},{"className":"scalikejdbc.DBConnection","fileName":"DBConnection.scala","lineNumber":329,"methodName":"localTx"},{"className":"scalikejdbc.DBConnection","fileName":"DBConnection.scala","lineNumber":324,"methodName":"localTx$"},{"className":"scalikejdbc.NamedDB","fileName":"NamedDB.scala","lineNumber":20,"methodName":"localTx"},{"className":"org.broadinstitute.dsde.workbench.sam.db.DbReference","fileName":"DbReference.scala","lineNumber":74,"methodName":"inLocalTransaction"},{"className":"org.broadinstitute.dsde.workbench.sam.util.DatabaseSupport","fileName":"DatabaseSupport.scala","lineNumber":26,"methodName":"$anonfun$runInTransaction$2"},{"className":"cats.effect.internals.IORunLoop$","fileName":"IORunLoop.scala","lineNumber":87,"methodName":"cats$effect$internals$IORunLoop$$loop"},{"className":"cats.effect.internals.IORunLoop$","fileName":"IORunLoop.scala","lineNumber":41,"methodName":"startCancelable"},{"className":"cats.effect.internals.IOBracket$BracketStart","fileName":"IOBracket.scala","lineNumber":90,"methodName":"run"},{"className":"cats.effect.internals.Trampoline","fileName":"Trampoline.scala","lineNumber":67,"methodName":"cats$effect$internals$Trampoline$$immediateLoop"},{"className":"cats.effect.internals.Trampoline","fileName":"Trampoline.scala","lineNumber":35,"methodName":"startLoop"},{"className":"cats.effect.internals.TrampolineEC$JVMTrampoline","fileName":"TrampolineEC.scala","lineNumber":90,"methodName":"super$startLoop"},{"className":"cats.effect.internals.TrampolineEC$JVMTrampoline","fileName":"TrampolineEC.scala","lineNumber":90,"methodName":"$anonfun$startLoop$1"},{"className":"scala.runtime.java8.JFunction0$mcV$sp","fileName":"JFunction0$mcV$sp.java","lineNumber":12,"methodName":"apply"},{"className":"scala.concurrent.BlockContext$","fileName":"BlockContext.scala","lineNumber":81,"methodName":"withBlockContext"},{"className":"cats.effect.internals.TrampolineEC$JVMTrampoline","fileName":"TrampolineEC.scala","lineNumber":90,"methodName":"startLoop"},{"className":"cats.effect.internals.Trampoline","fileName":"Trampoline.scala","lineNumber":43,"methodName":"execute"},{"className":"cats.effect.internals.TrampolineEC","fileName":"TrampolineEC.scala","lineNumber":42,"methodName":"execute"},{"className":"cats.effect.internals.IOBracket$BracketStart","fileName":"IOBracket.scala","lineNumber":70,"methodName":"apply"},{"className":"cats.effect.internals.IOBracket$BracketStart","fileName":"IOBracket.scala","lineNumber":50,"methodName":"apply"},{"className":"cats.effect.internals.IORunLoop$","fileName":"IORunLoop.scala","lineNumber":141,"methodName":"cats$effect$internals$IORunLoop$$loop"},{"className":"cats.effect.internals.IORunLoop$RestartCallback","fileName":"IORunLoop.scala","lineNumber":366,"methodName":"signal"},{"className":"cats.effect.internals.IORunLoop$RestartCallback","fileName":"IORunLoop.scala","lineNumber":387,"methodName":"apply"},{"className":"cats.effect.internals.IORunLoop$RestartCallback","fileName":"IORunLoop.scala","lineNumber":330,"methodName":"apply"},{"className":"cats.effect.internals.IOShift$Tick","fileName":"IOShift.scala","lineNumber":36,"methodName":"run"},{"className":"java.util.concurrent.ThreadPoolExecutor","fileName":"ThreadPoolExecutor.java","lineNumber":1149,"methodName":"runWorker"},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":"ThreadPoolExecutor.java","lineNumber":624,"methodName":"run"},{"className":"java.lang.Thread","fileName":"Thread.java","lineNumber":748,"methodName":"run"}]}')```
```

This may become problematic if someone tries to refresh their keys, it should not effect merging of #2143 because of the potential change in the `google_service_account.account_id`. ie. `azul_ucsc_indexer_amar` -> `azul_ucsc_amar`

**Comment by amarjandu** [comment]
potential solutions might include:

1. Retrieval of the SA key registered with SAM, and comparison with what is currently in the secret manager, then appropriate registration/removal of the old key from within SAM.
2. always delete the SA-key with SAM, and register the one stored in the secret manager.

**Comment by hannes-ucsc** [comment]
> make terraform destroy -target=google_service_account.indexer && make terraform apply -target=google_service_account.indexer

Is not a valid make invocation.

Since this is a relatively exotic corner case, the steps for reproduction need to be solid.

**Comment by amarjandu** [comment]
whoops, typo.
omit the `make`
make sure the current working dir is `$AZUL_HOME/terraform`
```
cd terraform
terraform destroy -target=google_service_account.indexer &&  terraform apply -target=google_service_account.indexer
```

**Comment by hannes-ucsc** [comment]
Before running `terraform` in the `terraform` directory, certain make targets need to be invoked.

We need a complete sequence of steps to reproduce the problem in the description, not a partial one, spread over multiple comments.

**Comment by amarjandu** [comment]
This was also observed with @natanlao deployment. see this comment: https://github.com/DataBiosphere/azul/pull/2210#issuecomment-696895819

**Comment by amarjandu** [comment]
@hannes-ucsc -"Because amar has done the majority of the spike work, he should get the credit and be assigned the ticket"

**Comment by theathorn** [comment]
Freebie of #2143.

**Comment by theathorn** [comment]
@hannes-ucsc to provide demo instructions.

**Comment by hannes-ucsc** [comment]
For demo, 

1) show that incarnation count appears in SA name,
2) destroy SA using `terraform destroy` and
3) prove that it's gone. 
4) Run `make package deploy` to repair. Should fail in `sam` target.
5) Show incremented incarnation count in error message
6) Add SA to Jade stewards group.
7) Run `make package deploy` again.
