### ISSUE TITLE
Snapshot hca_dev_20200907_ebi17fix___20200910_updated has bad metadata

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2255]
Fail queue

```
{
    "queue": "https://queue.amazonaws.com/122796619775/azul-notifications_fail-sandbox",
    "messages": [
        {
            "MessageId": "7420686e-5a1c-41ea-9629-3a7461beebe8",
            "ReceiptHandle": "AQEBPrR2M68866A5G5ZD8Zphebg7INAVxnilrlpSYh7lF/5Rg/hOKcwuNjzYXYaKcvn0hU+0hdENoTEFWz5QJRboZY9unP7tFlTz/RorKYD+qwgSPYFY7QNcTeWDcEpPzvxBf0F+7Xuntk7w6zKcEdOg0DBoE4Lw3QZqgFwjVx8WZsa9P18tdo46DX3Rfs2X7ZsEe8zaahNe/XZjxQ7mc2LtGf2DtcimI3piGZg7wcO1OZf/nCEPhwvLYOvPbfkwzZf+6uPPYy6cJSpryPfXd3oPDiNsjSaGpC64vtvbB4q0AWMn++5K7qxKkUgefpRz2gKY/OKoK+IdfJww7cclleyCk2QHYYrpX9/9cBt6zjcS30FC5OG2ezmgUKb5o2ECD0dWgJvhh6mq6F29oY1rBj57V5bwB/UkaQxFzggmi56N6a8=",
            "MD5OfBody": "f934f23928c40d5a55d9627defaf8c38",
            "Body": {
                "catalog": "it2ebi",
                "action": "add",
                "notification": {
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "fcf3bb1f-f530-4d89-b52d-d33d7d0b18c0",
                    "match": {
                        "bundle_uuid": "5573151b-5bd7-4c90-a78f-50bb5f62a610",
                        "bundle_version": "2020-07-08T09:13:55.582000Z"
                    }
                }
            },
            "Attributes": {
                "SenderId": "AROARZFZ7W77S5XNVN6D6:azul-indexer-sandbox",
                "ApproximateFirstReceiveTimestamp": "1599844307974",
                "ApproximateReceiveCount": "12",
                "SentTimestamp": "1599844307974"
            },
            "_Attributes": {
                "SentTimestamp": "2020-09-11T10:11:47.974000-07:00",
                "ApproximateFirstReceiveTimestamp": "2020-09-11T10:11:47.974000-07:00"
            }
        }
    ]
}
```

Lambda log message

```
[WARNING] 2020-09-11T17:59:09.663Z 73ae5b81-ad95-52ba-84ec-0c5410b0014e Worker failed to handle message {'catalog': 'it2ebi', 'action': 'add', 'notification': {'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'fcf3bb1f-f530-4d89-b52d-d33d7d0b18c0', 'match': {'bundle_uuid': '5573151b-5bd7-4c90-a78f-50bb5f62a610', 'bundle_version': '2020-07-08T09:13:55.582000Z'}}}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 177, in transform
return self.index_service.transform(catalog, bundle, delete)
File "/var/task/azul/indexer/index_service.py", line 171, in transform
transformer: Transformer = transformer_cls.create(bundle, deleted=delete)
File "/var/task/azul/plugins/metadata/hca/transform.py", line 89, in create
return cls(bundle, deleted)
File "/var/task/azul/plugins/metadata/hca/transform.py", line 95, in __init__
self.api_bundle = api.Bundle(uuid=bundle.uuid,
File "/opt/python/humancellatlas/data/metadata/api.py", line 807, in __init__
self.protocols = from_json_vx(Protocol)
File "/opt/python/humancellatlas/data/metadata/api.py", line 802, in from_json_vx
return from_json(core_cls, json_entities, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 771, in from_json
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 771, in <dictcomp>
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 770, in <genexpr>
entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
File "/opt/python/humancellatlas/data/metadata/api.py", line 58, in from_json
return sub_cls(json, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 530, in __init__
super().__init__(json)
File "/opt/python/humancellatlas/data/metadata/api.py", line 494, in __init__
super().__init__(json)
File "/opt/python/humancellatlas/data/metadata/api.py", line 106, in __init__
super().__init__(json)
File "/opt/python/humancellatlas/data/metadata/api.py", line 63, in __init__
provenance = json.get('hca_ingest') or json['provenance']
KeyError: 'provenance'
```

**Comment by hannes-ucsc** [comment]
At least one `sequencing_protocol` entity is missing the `provenance` property:

$ bq query --use_legacy_sql=false --format=json 'SELECT content FROM `broad-jade-dev-data.hca_dev_20200907_ebi17fix___20200910_updated.sequencing_protocol` WHERE sequencing_protocol_id = "827999bd-35ad-4a36-aea2-9b38061dfaea"' | jq -r '.[0].content' | jq
Waiting on bqjob_r27d12fd83aba3b89_000001747f04dbc8_1 ... (0s) Current status: DONE   
{
  "describedBy": "https://schema.staging.data.humancellatlas.org/type/protocol/sequencing/10.1.0/sequencing_protocol",
  "schema_type": "protocol",
  "protocol_core": {
    "protocol_id": "sequencing",
    "protocol_name": "sequencing_protocol",
    "protocol_description": "Protocol for sequencing"
  },
  "instrument_manufacturer_model": {
    "text": "Illumina HiSeq 4000",
    "ontology": "EFO:0008563",
    "ontology_label": "Illumina HiSeq 4000"
  },
  "paired_end": false,
  "method": {
    "text": "tag based single cell RNA sequencing",
    "ontology": "EFO:0008440",
    "ontology_label": "tag based single cell RNA sequencing"
  }
}

**Comment by theathorn** [comment]
New snapshot at hca_dev_20200907_ebi17fix___20200914.

**Comment by hannes-ucsc** [comment]
Freebie of #2256.

**Comment by hannes-ucsc** [comment]
Now I'm getting duplicate rows (same UUID, same version):

```
$ bq query --use_legacy_sql=false 'SELECT version FROM `broad-jade-dev-data.hca_dev_20200907_ebi17fix___20200914.specimen_from_organism` WHERE specimen_from_organism_id = "b8912f33-12a7-4bf8-9f25-e91fbc77517c"'
Waiting on bqjob_r5b4fa8da2204073f_000001748f5169f5_1 ... (0s) Current status: DONE   
+---------------------+
|       version       |
+---------------------+
| 2020-08-13 10:24:30 |
| 2020-08-13 10:24:30 |
+---------------------+
```
