### ISSUE TITLE
Sort by 'Analysis Protocol' causes error with DCP2 catalog selected

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2275]
With the `DCP2` catalog selected (a catalog containing no analysis bundles), sorting by `Analysis Protocol` (aka `hits.protocol.workflow`) causes an `elasticsearch.exceptions.RequestError`.

https://service.dev.singlecell.gi.ucsc.edu/index/samples?size=15&sort=workflow&order=asc&catalog=dcp2

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1112, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1093, in get_sample_data
    return repository_search('samples', sample_id)
  File "/var/task/app.py", line 860, in repository_search
    return service.get_data(catalog, entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository_service.py", line 86, in get_data
    return self._get_items(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 62, in _get_items
    response = self._get_data(catalog, entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository_service.py", line 43, in _get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 626, in transform_request
    raise e
  File "/var/task/azul/service/elasticsearch_service.py", line 612, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/opt/python/elasticsearch_dsl/search.py", line 702, in execute
    es.search(
  File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/python/elasticsearch/client/__init__.py", line 851, in search
    return self.transport.perform_request(
  File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [contents.analysis_protocols.workflow.keyword] in order to sort on')
```

**Comment by theathorn** [comment]
In the dev Data Browser, select the DCP Catalog and then click on the "Analysis Protocol" column to reverse the sort order.
The exception error and stack trace are then displayed to the user.
Since all the 23 values are "Unspecified" the sort request should do nothing (i.e. the project order is unchanged).

**Comment by amarjandu** [comment]
@danielsotirhos 
Just to showcase that the changes are working...
![Screen Shot 2020-11-02 at 9 43 37 AM](https://user-images.githubusercontent.com/1947534/97900714-ecc49600-1cef-11eb-9699-b590c5e8f803.png)

I was unsure about adding tests, are there canned dcp2 bundles that can be inspected during a unit-test? It seems like this could also fall under the integration-test, but it might be brittle depending on if the bundles at a later time begin to include a workflow.

**Comment by amarjandu** [comment]
this will not be ported to `hca/` branches
