### ISSUE TITLE
TDR's `HEAD /api/repository/v1/snapshots` returns 502 on occasion

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2310]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6317

```
make sam
make[2]: Entering directory '/builds/ucsc/azul/terraform'
python /builds/ucsc/azul/scripts/register_sam.py
2020-09-28 18:11:51,807 INFO    MainThread: Google service account previously registered with SAM.
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/register_sam.py", line 37, in <module>
    main()
  File "/builds/ucsc/azul/scripts/register_sam.py", line 24, in main
    tdr.verify_authorization()
  File "/builds/ucsc/azul/src/azul/tdr.py", line 159, in verify_authorization
    raise RuntimeError('Unexpected response from TDR service', response.status)
RuntimeError: ('Unexpected response from TDR service', 502)
make[2]: *** [Makefile:55: sam] Error 1
make[2]: Leaving directory '/builds/ucsc/azul/terraform'
make[1]: *** [Makefile:39: auto_apply] Error 2
make: *** [Makefile:83: auto_deploy] Error 2
```

If this occurs, it persists for several hours.

**Comment by hannes-ucsc** [comment]
Retry doesn't help.

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6324

**Comment by theathorn** [comment]
From Ruchi: The data repo dev env (which we asked @Hannes and team not to use during the big snapshot creation is now ready to be hammered). We've resized the env (3 K8s pods) and isolated it (from running the development unit/integration tests) -- so feel free to use again.!

**Comment by theathorn** [comment]
Not observing this anymore.
