### ISSUE TITLE
Analysis subgraph in `hca_ucsc_files_20201001_optimusb` has invalid project UUID

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2339]
```json
{
    "queue": "https://queue.amazonaws.com/122796619775/azul-notifications_fail-dev",
    "messages": [
        {
            "MessageId": "1245de1b-15f7-4ed9-adb7-c4c0bd30637d",
            "ReceiptHandle": "AQEB73RTfIVdoOeWJH7F1fJ+xnX4MlLEp4Izy/c1M7FmbSX5iBSO557Iu7S9QRiZtc6sVId3WxDKP2GDWi2J1FSMjA0zdGNMlM/sirrRmUw3AK8nv6cEzjsoiLF7waDAelEfWWYqBHmR6JTd88eT2ZGy+e9RStK9wmhYfPD99RN0CVGtis/7GMQocJslailKsKVs21wL+0d41QtB2wZJO8U97DazW3wMaPQLc1ekRIscHFByRWxXfvhnjMwUPSwFVvtzV8WsBmRF7Vmhy5DGxt3KsQNW4RiAdOwtTwmcMR6LQMQXnX3JXVgDHIS+gvUiN+H4VPaDGpyK41QIh2DejFWeHl3CYxLb2og7I16IWDTBrjuxUGSpc/hXE9v8hGDu17mOTk0CsfEh+UbOdftG1n7sQw==",
            "MD5OfBody": "42fcd83ae181b7f043ced721592a23e3",
            "Body": {
                "action": "add",
                "notification": {
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "328b9ffb-db37-429a-af1b-e4c270c71153",
                    "match": {
                        "bundle_uuid": "82d6b80c-7ab3-5416-b700-4e5e70cb22a7",
                        "bundle_version": "2020-08-10T21:24:26.174274Z"
                    }
                },
                "catalog": "dcp2"
            },
            "Attributes": {
                "SenderId": "AROARZFZ7W77VNWF46R45:azul-indexer-dev-contribute",
                "ApproximateFirstReceiveTimestamp": "1602136103246",
                "ApproximateReceiveCount": "11",
                "SentTimestamp": "1602136103246"
            },
            "_Attributes": {
                "SentTimestamp": "2020-10-07T22:48:23.246000-07:00",
                "ApproximateFirstReceiveTimestamp": "2020-10-07T22:48:23.246000-07:00"
            }
        }
    ]
}
```

```
[WARNING] 2020-10-08T16:10:28.169Z 44f33c14-394c-5a61-8ebb-6bed05612453 Worker failed to handle message {'action': 'add', 'notification': {'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '328b9ffb-db37-429a-af1b-e4c270c71153', 'match': {'bundle_uuid': '82d6b80c-7ab3-5416-b700-4e5e70cb22a7', 'bundle_version': '2020-08-10T21:24:26.174274Z'}}, 'catalog': 'dcp2'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 172, in transform
bundle = self.repository_plugin(catalog).fetch_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 117, in fetch_bundle
bundle = self.emulate_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 237, in emulate_bundle
reject(bool(entity_ids),
File "/var/task/azul/__init__.py", line 1061, in reject
raise exception(*args)
azul.RequirementError: Required entities not found in hca_ucsc_files_20201001_optimusb.project: {'test-project'}```
```

**Comment by jessebrennan** [comment]
@hannes-ucsc "see if sub-graph still causes issues"

**Comment by danielsotirhos** [comment]
Confirmed analysis subgraph in `hca_ucsc_files_20201001_optimusb` is not in the current dcp2 catalog snapshot `hca_dev_20200819___20201109_optimus`.

```
SELECT * FROM hca_ucsc_files_20201001_optimusb.links
WHERE links_id = '82d6b80c-7ab3-5416-b700-4e5e70cb22a7'
```

```
[
  {
    "datarepo_row_id": "06f7a4ea-7c1e-4c7e-b786-7e0053a292d7",
    "links_id": "82d6b80c-7ab3-5416-b700-4e5e70cb22a7",
    "version": "2020-08-10 21:24:26.174274 UTC",
    "project_id": "test-project",
    "content": "{\"describedBy\":\"https://schema.humancellatlas.org/system/2.1.1/links\",\"links\":[{\"inputs\":[{\"input_id\":\"5821aa3d-5a1f-459c-a75a-81a3ece52234\",\"input_type\":\"sequence_file\"},{\"input_id\":\"3b951f3a-5bf4-4fe6-92c5-c9987c8b9f5a\",\"input_type\":\"sequence_file\"},{\"input_id\":\"e269484e-62b8-4d16-a113-dc83e6ddb69a\",\"input_type\":\"sequence_file\"},{\"input_id\":\"7877e5fb-0e0d-458f-87b9-4daa56fd51c4\",\"input_type\":\"sequence_file\"},{\"input_id\":\"90153d08-6fd0-420f-b864-d0fa3889ce5c\",\"input_type\":\"sequence_file\"},{\"input_id\":\"0c258cab-91f3-47ef-8dc2-6735bf8126bb\",\"input_type\":\"sequence_file\"},{\"input_id\":\"c2a0c0af-cee3-4119-a549-5c1d33ca8806\",\"input_type\":\"sequence_file\"},{\"input_id\":\"58c0f8de-a740-4f41-8e4d-471401ce486a\",\"input_type\":\"sequence_file\"},{\"input_id\":\"be80dc33-c512-4de5-9086-c07fd05a0007\",\"input_type\":\"sequence_file\"},{\"input_id\":\"aa55afb1-cb98-4364-a5f2-ea11b126a26a\",\"input_type\":\"sequence_file\"},{\"input_id\":\"db017ec8-4545-4f22-8500-9903d1d35dab\",\"input_type\":\"sequence_file\"},{\"input_id\":\"77f08bb9-7877-4d64-a7ac-ca2535c6494b\",\"input_type\":\"sequence_file\"}],\"link_type\":\"process_link\",\"outputs\":[{\"output_id\":\"b34b000b-b4a1-52cd-bde4-7deedbb00a5e\",\"output_type\":\"analysis_file\"},{\"output_id\":\"6fb69eb8-63c3-583b-b014-ac1841ba7028\",\"output_type\":\"analysis_file\"}],\"process_id\":\"32466e8d-e6a7-455a-9d30-408bea689b4e\",\"process_type\":\"analysis_process\",\"protocols\":[{\"protocol_id\":\"a7d5a4b3-302e-52e0-837d-27bc1ef265ba\",\"protocol_type\":\"analysis\"}]}],\"schema_type\":\"links\",\"schema_version\":\"2.1.1\"}"
  }
]
```


```
SELECT * FROM hca_dev_20200819___20201109_optimus.links
WHERE links_id = '82d6b80c-7ab3-5416-b700-4e5e70cb22a7'
```

```
This query returned no results.
```
