### ISSUE TITLE
scripts/kibana_proxy.py does not automatically pull images

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/azul#2367]
Running `scripts/kibana_proxy.py` will result in an error if any of the three images used in the script are not present at runtime:

```
$ python scripts/kibana_proxy.py 
2020-10-20 12:15:01,393 INFO    MainThread: Found credentials in environment variables.
2020-10-20 12:15:01,394 INFO    MainThread: Getting domain endpoint
2020-10-20 12:15:01,413 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=proxy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/kibana_proxy.py", line 160, in <module>
    main(sys.argv[1:])
  File "scripts/kibana_proxy.py", line 155, in main
    KibanaProxy(options).run()
  File "scripts/kibana_proxy.py", line 66, in run
    proxy = client.containers.create('cllunsford/aws-signing-proxy',
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/api/container.py", line 411, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/api/container.py", line 422, in create_container_from_config
    return self._result(res, True)
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/natan/DataBiosphere/azul/.venv/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: cllunsford/aws-signing-proxy:latest")
```

This issue can be resolved by manually pulling the images (e.g., `docker pull cllunsford/aws-signing-proxy:latest`).

**Comment by natanlao** [comment]
Potential approaches:
* Document this in `python scripts/kibana_proxy.py --help`
* Automatically pull images in script
* (Or, this is actually common knowledge, does not need to be addressed, and this issue can be closed.)

**Comment by hannes-ucsc** [comment]
> Automatically pull images in script

Let's do that.
