### ISSUE TITLE
test_concurrent_portal_db_crud overloads S3 API

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2399]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7201#L1428

```
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 650, in test_concurrent_portal_db_crud
    self.assertTrue(all(f.result() is None for f in futures))
  File "/builds/ucsc/azul/test/integration_test.py", line 650, in <genexpr>
    self.assertTrue(all(f.result() is None for f in futures))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 643, in run
    portal_service._crud(lambda db: list(db) + [mock_entry])
  File "/builds/ucsc/azul/src/azul/portal_service.py", line 140, in _crud
    self._write_db(db, version)
  File "/builds/ucsc/azul/src/azul/portal_service.py", line 184, in _write_db
    response = self.client.put_object(Bucket=config.portal_db_bucket,
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SlowDown) when calling the PutObject operation (reached max retries: 4): Please reduce your request rate.
```

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7206

**Comment by melainalegaspi** [comment]
Look at this together with #2400

**Comment by melainalegaspi** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/11158

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/pull/2840#issuecomment-789478458
