### ISSUE TITLE
Error caused by filter: 'donorCount' is null

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2420]
https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%22donorCount%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1150, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 898, in repository_search
    return service.get_data(catalog=catalog,
  File "/var/task/azul/service/index_query_service.py", line 66, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 620, in transform_request
    raise e
  File "/var/task/azul/service/elasticsearch_service.py", line 606, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/opt/python/elasticsearch_dsl/search.py", line 702, in execute
    es.search(
  File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/python/elasticsearch/client/__init__.py", line 851, in search
    return self.transport.perform_request(
  File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 'No value specified for terms query')

```

Service Error is also seen on `DCP1`:

https://service.explore.data.humancellatlas.org/repository/projects?filters=%7B%22donorCount%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc

```
{"Code":"InternalServerError","Message":"An internal server error occurred."}
```

Related to #2191

**Comment by amarjandu** [comment]
@hannes-ucsc @danielsotirhos  in this case should filtering with `{"donorCount": 'is': [null]}`  return the same hits as filtering with `{"donorCount": 'is': [0]}` ?

**Comment by hannes-ucsc** [comment]
No. The former should only yield project that have no donor count. There may be no projects that fit the bill. The latter should only find projects where the donor count is 0. Null means "unknown", "unspecified" or "not applicable". IOW, a count of null doesn't mean there are no donors, it means we don't know how many donors there are. A count of 0 means there are no donors.

**Comment by amarjandu** [comment]
this will not be ported to `hca/` branches

**Comment by amarjandu** [comment]
for  filters = {'organPart' : {'is': [None]}}
the translated_filters is correctly translated with a `null_str`: 
![Screen Shot 2020-11-13 at 2.29.29 PM.png](https://images.zenhubusercontent.com/5bfc94ffa6759a229d994558/7985fb80-1d08-4206-8d44-454f56eb8a55)

for  filters = {'donorCount' : {'is': [None]}} 
the translation does not occur:
![Screen Shot 2020-11-13 at 2.31.45 PM.png](https://images.zenhubusercontent.com/5bfc94ffa6759a229d994558/a12ef95b-8699-44eb-9228-3a08336ee01e)
