### ISSUE TITLE
Bad subgraph in snapshot hca_dev_20201023_ebiv4___20201106_optimus

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2457]
```
{
    "queue": "https://queue.amazonaws.com/122796619775/azul-notifications_fail-dev",
    "messages": [
        {
            "MessageId": "e6342059-8414-4eda-95dd-8d459fc2d58c",
            "ReceiptHandle": "AQEB5SL6R86/r2DOa9NlYWY+q6ADIl3xU08ytQ8ygXT9gFJQyS66IPiHcSGBYjfMQLXLMAfXM1oW7QRnWR6KHWfaQ8j+2xEMtSPmno8CYfPh0EjQdgEU7H5XaYgdqP8ULuDhUE85/SY/QuBeQOOJnsrfwTFSAIcVFA6dAiAiOuZZHmm/s6ohXqHqkxt5eSZfgRKV4cikNZhGRjTSM7yHmSNIJXepekoqhhr3WlXKhnPivfLuFaCJxUtvDe482AyJRZYRhWNp26qQ/wzxR8PPSJt44dejrI++vDf2+1NQ80tml6k2bqjaC7vB0FYxI8n+GabiMhiE6JyHoKqywcliPWELU+4nFxh/wwS2K2fIiz10WS3aoCoMOnCf2HyV3dXV+c1Isge9jjyspGDt5S+VL5rnmZ10dWWFkxmrx8/t41GDAj4=",
            "MD5OfBody": "52b48b19b59084a60f5fc1b0528425ba",
            "Body": {
                "action": "add",
                "notification": {
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "9cf1085a-c143-452b-ac61-e28a7dbee860",
                    "match": {
                        "bundle_uuid": "14c7a4c3-b01f-5923-afa5-ad2ce304ee6d",
                        "bundle_version": "2020-10-26T09:37:17.517006Z"
                    }
                },
                "catalog": "dcp2ebi"
            },
            "Attributes": {
                "SenderId": "AROARZFZ7W77VNWF46R45:azul-indexer-dev-contribute",
                "ApproximateFirstReceiveTimestamp": "1605081227064",
                "ApproximateReceiveCount": "11",
                "SentTimestamp": "1605081227064"
            },
            "_Attributes": {
                "SentTimestamp": "2020-11-10T23:53:47.064000-08:00",
                "ApproximateFirstReceiveTimestamp": "2020-11-10T23:53:47.064000-08:00"
            }
        }
    ]
}
```

**Comment by hannes-ucsc** [comment]
Same subgraph was also in the dcp2 catalog and https://github.com/DataBiosphere/azul/issues/2430 covers that.

**Comment by hannes-ucsc** [comment]
I am assuming the cause is the same as in #2430. Assigning to @danielsotirhos to coordinate the necessary deletion with BI.

**Comment by danielsotirhos** [comment]
Subgraph `14c7a4c3-b01f-5923-afa5-ad2ce304ee6d` is the correct UUID for the contributor-generated matrices addition to project `a815c84b-8999-433f-958e-422c0720e00d`. 
See: [Links.json file in staging area](https://console.cloud.google.com/storage/browser/_details/broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp2ebi/links/14c7a4c3-b01f-5923-afa5-ad2ce304ee6d_2020-10-26T09:37:17.517006Z_a815c84b-8999-433f-958e-422c0720e00d.json)
See: [Spreadsheet for adapter](https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit?ts=5f762d26#gid=671636652) listing the file for the `a815c84b` project.


The Cloudwatch logs for this subgraph indicate that the project `a815c84b` does not exist for the subgraph to be stitched to.
```
[WARNING] 2020-11-11T20:22:33.891Z 5a63c1a3-92b1-5655-a15f-9985d88a018d Worker failed to handle message {'action': 'add', 'notification': {'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '9cf1085a-c143-452b-ac61-e28a7dbee860', 'match': {'bundle_uuid': '14c7a4c3-b01f-5923-afa5-ad2ce304ee6d', 'bundle_version': '2020-10-26T09:37:17.517006Z'}}, 'catalog': 'dcp2ebi'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 172, in transform
bundle = self.repository_plugin(catalog).fetch_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 122, in fetch_bundle
bundle = self.emulate_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 217, in emulate_bundle
raise e
File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 298, in _retrieve_entities
require(not missing,
File "/var/task/azul/__init__.py", line 1050, in require
reject(not condition, *args, exception=exception)
File "/var/task/azul/__init__.py", line 1065, in reject
raise exception(*args)
azul.RequirementError: Required entities not found in hca_dev_20201023_ebiv4___20201106_optimus.project: {'a815c84b-8999-433f-958e-422c0720e00d'}
```

An entry for project `a815c84b` is found in the projects table of `datarepo_hca_dev_20201001_ebi17v3` and in the links table for subgraphs `f6f023c2-1b29-4c8e-9ef9-3540a5bde660` and `39a15db8-97d6-4aa8-9906-6eaea6d3f379`.

in `datarepo_hca_dev_20201023_ebiv4` and `hca_dev_20201023_ebiv4___20201106_optimus` however the only mention of the project is in the links table for the `14c7a4c3` subgraph, with no match in the projects table.

**Comment by hannes-ucsc** [comment]
I think the a815c84b-8999-433f-958e-422c0720e00d has been removed by EBI in response to a QC issue raised by @kbergin.

https://humancellatlas.slack.com/archives/C01360XN04S/p1602605511085600

We should remove the 14c7a4c3-b01f-5923-afa5-ad2ce304ee6d subgraph from the CGM staging area and soft-delete it and create a new snapshot.

I will kick of a discussion with @raaidbroad about preventing this case via validation in the importer.

**Comment by danielsotirhos** [comment]
Removed the following `a815c84b` project files from the `gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp2ebi` staging area:

```
- data/a815c84b-8999-433f-958e-422c0720e00d.GSE104276_all_pfc_2394_UMI_count_NOERCC.xls.gz 
- descriptors/supplementary_file/036389c0-f69b-5c8d-a001-674e040e9c10_2020-10-26T09:37:17.517006Z.json 
- links/14c7a4c3-b01f-5923-afa5-ad2ce304ee6d_2020-10-26T09:37:17.517006Z_a815c84b-8999-433f-958e-422c0720e00d.json 
- metadata/supplementary_file/036389c0-f69b-5c8d-a001-674e040e9c10_2020-10-26T09:37:17.517006Z.json 
```

**Comment by hannes-ucsc** [comment]
Please coordinate the soft-deletion of that subgraph and the creation of a new snapshot with BI.

**Comment by theathorn** [comment]
Snapshot hca_dev_20201023_ebiv4___20201121 with the requested soft deletes and a re-import of DCP/2 CGMs is available.

**Comment by danielsotirhos** [comment]
Confirmed removal of subgraph `14c7a4c3-b01f-5923-afa5-ad2ce304ee6d` in the latest snapshot `hca_dev_20201023_ebiv4___20201121`.

```
SELECT * FROM `broad-jade-dev-data.hca_dev_20201023_ebiv4___20201121.links` 
WHERE links_id = '14c7a4c3-b01f-5923-afa5-ad2ce304ee6d'

# This query returned no results.
```

Same query against previous snapshot `hca_dev_20201023_ebiv4___20201106_optimus`:
```
SELECT * FROM `broad-jade-dev-data.hca_dev_20201023_ebiv4___20201106_optimus.links` 
WHERE links_id = '14c7a4c3-b01f-5923-afa5-ad2ce304ee6d'

[
  {
    "datarepo_row_id": "c7d39fd3-8ede-4480-9b5b-4b6fee489bcf",
    "links_id": "14c7a4c3-b01f-5923-afa5-ad2ce304ee6d",
    "version": "2020-10-26 09:37:17.517006 UTC",
    "project_id": "a815c84b-8999-433f-958e-422c0720e00d",
    "content": "{\"describedBy\":\"https://schema.humancellatlas.org/system/2.1.1/links\",\"schema_type\":\"links\",\"schema_version\":\"2.1.1\",\"links\":[{\"link_type\":\"supplementary_file_link\",\"entity\":{\"entity_type\":\"project\",\"entity_id\":\"a815c84b-8999-433f-958e-422c0720e00d\"},\"files\":[{\"file_id\":\"036389c0-f69b-5c8d-a001-674e040e9c10\",\"file_type\":\"supplementary_file\"}]}]}"
  }
]
```
