### ISSUE TITLE
7 subgraphs in snapshot `hca_prod_20201120_dcp2___20201122` have ambiguous versions of `sequence_file`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2508]
List of subgraph UUIDs from fail queue:

1b19d618-a412-413a-acd6-fb9053b1e5df
668f669a-e618-44bc-bf0e-53ab1ca3de1f
be0dddfd-5b70-48f6-b6bd-ba4f43868cb8
85f6d419-f938-4adf-8c28-df42c051d46c
0658d9aa-bd5a-4957-99f7-576d2871b72e
eab0aeb5-593d-41b3-b96c-66d13ada0991
83ed57f4-9743-4f08-abfe-d2ebb8d9ff91

Related error in CloudWatch:

```
[ERROR] 2020-11-24T15:28:52.805Z 651b59fe-9665-5248-bb14-01c9bebf35d5 TDR worker failed to retrieve entities of type 'sequence_file'
Traceback (most recent call last):
File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 270, in _retrieve_entities
rows = self._query_latest_version(f'''
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 165, in _query_latest_version
return [self._choose_one_version(group) for _, group in groups]
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 165, in <listcomp>
return [self._choose_one_version(group) for _, group in groups]
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 169, in _choose_one_version
return one(versioned_items)
File "/opt/python/more_itertools/more.py", line 529, in one
raise too_long or ValueError('too many items in iterable (expected 1)')
ValueError: too many items in iterable (expected 1)
```

This occurs 70 times (7 bundles * 10 retries).

**Comment by hannes-ucsc** [comment]
The replacement snapshot (`hca_prod_20201120_dcp2___20201124`) was indexed without errors so this is verified as fixed.
