### ISSUE TITLE
DCP/1 matrices fail to download, 'drs_path' is None

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2553]
On `Files` tab of `prod` browser https://dcp2.data.humancellatlas.org/explore/files?catalog=dcp1&filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22A%20single-cell%20transcriptome%20atlas%20of%20the%20adult%20human%20retina%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%228185730f-4113-40d3-9cc3-929271784c2b%22%5D%7D%5D

attempt to download `8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.csv.zip` with URL https://service.azul.data.humancellatlas.org/fetch/dss/files/538faa28-3235-5e4b-a998-5672e2d964e8?version=2020-11-23T21%3A01%3A12.275120Z&catalog=dcp1 gives error:

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1573, in fetch_dss_files
    return fetch_repository_files(file_uuid)
  File "/var/task/app.py", line 1719, in fetch_repository_files
    body = _repository_files(file_uuid, fetch=True)
  File "/var/task/app.py", line 1750, in _repository_files
    return app.repository_controller.download_file(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 78, in download_file
    download.update(plugin)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 417, in update
    assert self.drs_path is not None
AssertionError
```

Same result for other DCP/1 matrices.

**Comment by theathorn** [comment]
I have downloaded a DCP/1 matrix from dcp2.data and did a successful binary compare with the same file from the DCP/1 website.
