### ISSUE TITLE
Disallow empty catalogs in config.catalogs

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2623]
when modifying catalogs within an environment file its possible to end up an empty catalog within the configuration.

``` python
        'AZUL_CATALOGS': 'dcp2:repository/tdr:metadata/hca,'
                         'it2:repository/tdr:metadata/hca,',
```

The trailing  `,` within the string that composes the catalog ` 'it2:repository/tdr:metadata/hca,',` causes blank catalogs to be  present in the config.

```python
from azul import config
config.catalogs.items()
dict_items([('dcp2', {'repository': 'tdr', 'metadata': 'hca'}), ('it2', {'repository': 'tdr', 'metadata': 'hca'}), ('', {})])
```

This can cause deployment errors, and potentially unexpected behaviors if missed. 

```
(.venv) Specter:azul amar$ make sam
python /Users/amar/dev/hca/azul/scripts/register_sam.py
2020-12-14 11:08:20,442 INFO    MainThread: Found credentials in environment variables.
2020-12-14 11:08:21,510 INFO    MainThread: Google service account previously registered with SAM.
Traceback (most recent call last):
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 34, in <module>
    main()
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 27, in main
    for source in set(map(config.tdr_source, tdr_catalogs)):
  File "/Users/amar/dev/hca/azul/scripts/register_sam.py", line 25, in <genexpr>
    if plugins['repository'] == 'tdr'
KeyError: 'repository'
make: *** [sam] Error 1
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Should actually use ','.join(...) instead."

**Comment by melainalegaspi** [comment]
@amarjandu please reverify that this is still an issue. @hannes-ucsc thinks he already fixed it.

**Comment by amarjandu** [comment]
Yes leaving a trailing `,` in the catalog string will cause a ValueError when accessing config.catalogs

```
...
envhook.py: Setting AZUL_CATALOGS to 'hca:dcp2:repository/tdr:metadata/hca,hca:dcp2ebi:repository/tdr:metadata/hca,hca:it2:repository/tdr:metadata/hca,hca:it2ebi:repository/tdr:metadata/hca,'
....
from azul import config
config.catalogs.items() 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 503, in catalogs
    catalogs = {
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 512, in <dictcomp>
    for atlas, catalog, *plugins in map(splitter(':'), catalogs)
ValueError: not enough values to unpack (expected at least 2, got 1)```

**Comment by hannes-ucsc** [comment]
An invalid input leads to an error message. Isn't that the expected behavior? If not, what is?

Also note, @amarjandu, the main deployment now use `','.join()` to make this configuration mistake less likely to occur.

```python
        'AZUL_CATALOGS': ','.join([
            'hca:dcp2:repository/tdr:metadata/hca',
            'hca:dcp2ebi:repository/tdr:metadata/hca',
            'hca:it2:repository/tdr:metadata/hca',
            'hca:it2ebi:repository/tdr:metadata/hca'
        ]),
```

**Comment by amarjandu** [comment]
@hannes-ucsc Yes, invalid input leaded to an error is the expected behavior.
I did not want to close this out myself if there was anything else that you might have wanted to bring up about this issue, I was planning on suggesting to close the issue at standup.
