### ISSUE TITLE
Error creating AWS Secrets Manager secret for personal deployment

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2637]
```
Error: Error running command 'python /home/jesse/gi/azul/scripts/provision_credentials.py google-key --build 'azul-ucsc-0-jesse1@human-cell-atlas-travis-test.iam.gserviceaccount.com'': exit status 1. Output: 2020-12-17 14:14:41,595 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "/home/jesse/gi/azul/scripts/provision_credentials.py", line 181, in <module>
    args.func(credentials_provisioner, args)
  File "/home/jesse/gi/azul/scripts/provision_credentials.py", line 49, in provision_google_from_args
    self.provision_google(args.build, args.email)
  File "/home/jesse/gi/azul/scripts/provision_credentials.py", line 66, in provision_google
    self._create_secret(secret_name)
  File "/home/jesse/gi/azul/scripts/provision_credentials.py", line 90, in _create_secret
    self.secrets_manager.create_secret(Name=name)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the CreateSecret operation: You can't create this secret because a secret with this name is already scheduled for deletion.
```

This happened while updating my personal deployment. I may have done something peculiar that caused this to start, ~but rerunning `make deploy` proves this is reproducible on my machine.~

**Comment by jessebrennan** [comment]
On rerunning deploy, I got
```
Error: Error creating service account: googleapi: Error 409: Service account azul-ucsc-1-jesse1 already exists within project projects/human-cell-atlas-travis-test., alreadyExists

  on authentication.tf.json line 24, in resource[0].google_service_account[0].azul:
  24:                     }
```

**Comment by jessebrennan** [comment]
Re-running `make deploy` eventually led me to https://github.com/DataBiosphere/azul#unable-to-re-register-service-account-with-sam

Which after several more deploys eventually required me authorize my new service account with SAM. This done, everything seems to be working.

I'm closing this issue as invalid, since rerunning will solve this and/or lead you to a documented troubleshooting guide. Unfortunately I still don't know what caused this to begin with :/

**Comment by jessebrennan** [comment]
Reopening because @noah-aviel-dove suggested that perhaps documentation could be improved. Likely this would take the form of an entry in the troubleshooting guide.

My only hesitation about doing this is that we don't actually know what causes this directly. It may not happen again (at least in exactly the way I experienced it) and so we can't yet reproduce it.

We can discuss more at triage.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Spike to confirm whether reproduction is to delete and then recreate in quick succession."

@amarjandu :"Try incrementing incarnation counter."

**Comment by jessebrennan** [comment]
To reproduce:
- First, deployment should be up to date
  ```
  source environment
  _preauth
  make package
  make deploy
- next, destroy google service account
  ```
  cd terraform
  make init
  terraform destroy -target=google_service_account.azul
  cd ..
  ```
- Next deployment update should fail with SAM error
  ```
  make package
  make deploy
  ```
- Increment incarnation counter, then update environ and redeploy 
  ```
  source environment
  _preauth
  make package
  make deploy
  ```
The last deploy should fail with the originally reported error.

**Comment by jessebrennan** [comment]
Once the original error is encountered, you can simply rerun `make deploy`. Then you will end up with 
```
Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
make link_health_checks
make[2]: Entering directory '/home/jesse/gi/azul/terraform'
python /home/jesse/gi/azul/scripts/manage_health_checks.py --link
2020-12-21 15:27:43,293 INFO    MainThread: Found credentials in environment variables.
2020-12-21 15:27:43,723 INFO    MainThread: DCP wide health check does not exist for jesse1
make[2]: Leaving directory '/home/jesse/gi/azul/terraform'
make grafana
make[2]: Entering directory '/home/jesse/gi/azul/terraform'
python /home/jesse/gi/azul/scripts/update_grafana.py
2020-12-21 15:27:43,983 INFO    MainThread: Skipping publishing of Grafana dashboard
make[2]: Leaving directory '/home/jesse/gi/azul/terraform'
make[1]: Leaving directory '/home/jesse/gi/azul/terraform'
make sam
make[1]: Entering directory '/home/jesse/gi/azul'
python /home/jesse/gi/azul/scripts/register_sam.py
2020-12-21 15:27:45,269 INFO    MainThread: Found credentials in environment variables.
2020-12-21 15:27:50,174 INFO    MainThread: Google service account successfully registered with SAM.
Traceback (most recent call last):
  File "/home/jesse/gi/azul/scripts/register_sam.py", line 34, in <module>
    main()
  File "/home/jesse/gi/azul/scripts/register_sam.py", line 29, in main
    tdr.check_api_access(source)
  File "/home/jesse/gi/azul/src/azul/terra.py", line 211, in check_api_access
    raise self._insufficient_access(resource)
azul.RequirementError: The service account (SA) 'azul-ucsc-7-jesse1@human-cell-atlas-travis-test.iam.gserviceaccount.com' is not authorized to access snapshot 'hca_dev_20200819___20201105_optimusb' via the TDR API or that resource does not exist. Make sure that it exists, that the SA is registered with SAM and has been granted read access to the resource.
make[1]: *** [Makefile:95: sam] Error 1
make[1]: Leaving directory '/home/jesse/gi/azul'
make: *** [Makefile:86: deploy] Error 2
```

Which is solved by requesting that your new service account be added to the `azul-dev` Terra group.

**Comment by jessebrennan** [comment]
Since this sequence of errors always follow the SAM error, my planned fix is to enhance the troubleshooting documentation for the SAM error to explain how to resolve this. I'll wait for @hannes-ucsc's approval before carying this forward however.

**Comment by hannes-ucsc** [comment]
As discussed on parking lot, @jessebrennan to tighten reproduction based on @amarjandu's findings, and to move forward with either preventing the delayed deletion or work around it by retrying the creation.
