### ISSUE TITLE
Compact manifest for dcp2 catalog fails when filtered on file formats

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#2649]
The request …
```
http 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp2&filters={"fileFormat":{"is":["bam","csv","csv.gz","docx","fastq","h5","h5ad","loom","mtx.gz","pdf","Robj","tar","tar.gz","tsv","tsv.gz","txt","txt.gz","xlsx","zip"]}}&format=compact'
```

… fails when following the redirect. 

```
HTTP/1.1 500 Internal Server Error
…

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1465, in start_manifest_generation_fetch
    wait_time, manifest = handle_manifest_generation_request()
  File "/var/task/app.py", line 1504, in handle_manifest_generation_request
    return async_service.start_or_inspect_manifest_generation(app.self_url(),
  File "/var/task/azul/service/async_manifest_service.py", line 92, in start_or_inspect_manifest_generation
    time_or_manifest = self._get_manifest_status(token['execution_id'], request_index)
  File "/var/task/azul/service/async_manifest_service.py", line 154, in _get_manifest_status
    raise StateMachineError(status, output)
azul.service.step_function_helper.StateMachineError: ('Failed to generate manifest', 'FAILED', None)
```

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-service-dev-manifest  
start-time: 2020-12-18T23:23:10.000Z  
end-time: 2020-12-18T23:37:18.000Z  
query-string:
```
fields @timestamp, @message
| filter @requestId like "f178da11-417f-4ab1-8c23-0689ab0a9a89"
| sort @timestamp asc
| limit 45
```

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
</tr></thead>
<tbody><tr>
<td>2020-12-18 23:23:53.993</td>
<td>START RequestId: f178da11-417f-4ab1-8c23-0689ab0a9a89 Version: $LATEST<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:54.007</td>
<td>[INFO]	2020-12-18T23:23:54.7Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:54.116</td>
<td>[INFO]	2020-12-18T23:23:54.116Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Cached manifest not found: manifests/f98bdf91-5607-5d20-983d-e84066c4c386.tsv<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:54.162</td>
<td>[DEBUG]	2020-12-18T23:23:54.162Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Creating ES client [search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:54.187</td>
<td>[INFO]	2020-12-18T23:23:54.186Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:54.323</td>
<td>[INFO]	2020-12-18T23:23:54.322Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/azul_v2_dev_dcp2_files_aggregate/_search?scroll=5m&amp;size=1000 [status:200 request:0.125s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:56.712</td>
<td>[INFO]	2020-12-18T23:23:56.712Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.125s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:58.089</td>
<td>[INFO]	2020-12-18T23:23:58.88Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.166s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:23:59.546</td>
<td>[INFO]	2020-12-18T23:23:59.546Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.124s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:01.053</td>
<td>[INFO]	2020-12-18T23:24:01.53Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.164s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:02.843</td>
<td>[INFO]	2020-12-18T23:24:02.843Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.301s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:04.341</td>
<td>[INFO]	2020-12-18T23:24:04.341Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.132s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:05.924</td>
<td>[INFO]	2020-12-18T23:24:05.923Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.191s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:07.643</td>
<td>[INFO]	2020-12-18T23:24:07.642Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.333s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:09.305</td>
<td>[INFO]	2020-12-18T23:24:09.305Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.218s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:10.812</td>
<td>[INFO]	2020-12-18T23:24:10.812Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.140s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:12.303</td>
<td>[INFO]	2020-12-18T23:24:12.303Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.117s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:13.760</td>
<td>[INFO]	2020-12-18T23:24:13.759Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.127s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:15.120</td>
<td>[INFO]	2020-12-18T23:24:15.119Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.128s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:16.695</td>
<td>[INFO]	2020-12-18T23:24:16.694Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.129s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:18.311</td>
<td>[INFO]	2020-12-18T23:24:18.310Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.268s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:24:20.390</td>
<td>[INFO]	2020-12-18T23:24:20.390Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.167s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.443</td>
<td>[WARNING]	2020-12-18T23:36:52.443Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:404 request:0.071s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.474</td>
<td>[INFO]	2020-12-18T23:36:52.474Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	DELETE https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll [status:404 request:0.031s]<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.478</td>
<td>[ERROR]	2020-12-18T23:36:52.474Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Upload hmLpgYeT3F3zrqXtXyBuZIk8xlRisVuIG0ZZW.X6qvOLghbhyc_8sGOyZiY8kqiocJuBU2o6S3dawiA6nZX74g6giq1FonC8ujYsRbreYdLSWN1PDdOW4CPqt6bh.5PwuJHX4MbKWgCGsYe303jXdEc6oa5Z.mybNqA47cWaMD4-: Error detected within the MPU context.<br/>Traceback (most recent call last):<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 279, in _generate_manifest<br/>    base_name = generator.write_to(text_buffer)<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 739, in write_to<br/>    for hit in self._create_request().scan():<br/>  File &quot;/opt/python/elasticsearch_dsl/search.py&quot;, line 723, in scan<br/>    for hit in scan(<br/>  File &quot;/opt/python/elasticsearch/helpers/actions.py&quot;, line 443, in scan<br/>    resp = client.scroll(<br/>  File &quot;/opt/python/elasticsearch/client/utils.py&quot;, line 84, in _wrapped<br/>    return func(*args, params=params, **kwargs)<br/>  File &quot;/opt/python/elasticsearch/client/__init__.py&quot;, line 1373, in scroll<br/>    return self.transport.perform_request(<br/>  File &quot;/opt/python/elasticsearch/transport.py&quot;, line 351, in perform_request<br/>    status, headers_response, data = connection.perform_request(<br/>  File &quot;/opt/python/elasticsearch/connection/http_requests.py&quot;, line 161, in perform_request<br/>    self._raise_error(response.status_code, raw_data)<br/>  File &quot;/opt/python/elasticsearch/connection/base.py&quot;, line 229, in _raise_error<br/>    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(<br/>elasticsearch.exceptions.NotFoundError: NotFoundError(404, &#39;search_phase_execution_exception&#39;, &#39;No search context found for id [100290778]&#39;)</td>
</tr>
<tr>
<td>2020-12-18 23:36:52.478</td>
<td>[INFO]	2020-12-18T23:36:52.478Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Upload hmLpgYeT3F3zrqXtXyBuZIk8xlRisVuIG0ZZW.X6qvOLghbhyc_8sGOyZiY8kqiocJuBU2o6S3dawiA6nZX74g6giq1FonC8ujYsRbreYdLSWN1PDdOW4CPqt6bh.5PwuJHX4MbKWgCGsYe303jXdEc6oa5Z.mybNqA47cWaMD4-: Aborting<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.741</td>
<td>[WARNING]	2020-12-18T23:36:52.741Z	f178da11-417f-4ab1-8c23-0689ab0a9a89	Upload hmLpgYeT3F3zrqXtXyBuZIk8xlRisVuIG0ZZW.X6qvOLghbhyc_8sGOyZiY8kqiocJuBU2o6S3dawiA6nZX74g6giq1FonC8ujYsRbreYdLSWN1PDdOW4CPqt6bh.5PwuJHX4MbKWgCGsYe303jXdEc6oa5Z.mybNqA47cWaMD4-: Aborted<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.745</td>
<td>END RequestId: f178da11-417f-4ab1-8c23-0689ab0a9a89<br/></td>
</tr>
<tr>
<td>2020-12-18 23:36:52.745</td>
<td>REPORT RequestId: f178da11-417f-4ab1-8c23-0689ab0a9a89	Duration: 778746.24 ms	Billed Duration: 778747 ms	Memory Size: 1024 MB	Max Memory Used: 214 MB	Init Duration: 1861.86 ms	<br/></td>
</tr>
</tbody></table>

**Comment by danielsotirhos** [comment]
The manifest generation failing with a broad filter (all file types) appears to be caused by exceeding the 15 minute timeout configured for manifest generation.

Unfortunately the logs surrounding the originally reported error are a bit hard to filter through due to multiple manifest requests being made within a short time. With further repeated tests however I was able to locate the logs of when the manifest generation was requested and when it failed and in these cases it was just over 15 minutes when the error occurred. (Note: These tests were for a "dcp1" catalog manifest because the manifest generation succeeded (failed to fail) for the "dcp2" catalog)

```
1608588399752   2020-12-21T14:06:39.752 dcp1 {"fileFormat":{"is":["bam","csv","csv.gz","docx","fastq","h5","h5ad","loom","mtx.gz","pdf","Robj","tar","tar.gz","tsv","tsv.gz","txt","txt.gz","xlsx","zip"]}}
1608589377781   2020-12-21T14:22:57.781 Caught exception for <function start_manifest_generation_fetch at 0x7f2b4f93c700>
=> 16.30 min

1608591592269   2020-12-21T14:59:52.269 dcp1 {"fileFormat":{"is":["bai","bam","csv","csv.gz","docx","fastq","fastq.gz","matrix","npy","npz","pdf","results","txt","unknown"]}}
1608592516730   2020-12-21T15:15:16.730 Caught exception for <function start_manifest_generation_fetch at 0x7f3e2eebe700>
=> 15.41 min

1608594253495   2020-12-21T15:44:13.495 dcp1 {"fileFormat":{"is":["bai","bam","csv","csv.gz","docx","fastq","fastq.gz","matrix","npy","npz","pdf","results","txt","unknown"]}}
1608595175786   2020-12-21T15:59:35.786 Caught exception for <function start_manifest_generation_fetch at 0x7f3509130700>
=> 15.37 min

1608653538573   2020-12-22T08:12:18.573 dcp1 {"fileFormat":{"is":["bam","csv","csv.gz","docx","fastq","h5","h5ad","loom","mtx.gz","pdf","Robj","tar","tar.gz","tsv","tsv.gz","txt","txt.gz","xlsx","zip"]}}
1608654451137   2020-12-22T08:27:31.137 Caught exception for <function start_manifest_generation_fetch at 0x7fac455ab700>
=> 15.21 min
```

**Comment by danielsotirhos** [comment]
Further log combing found timeout messages for my attempts, however no such log message is found for the 2020-12-18 error in the ticket description. 

```
1608588399752   2020-12-21T14:06:39.752 dcp1 {"fileFormat":{"is":["bam","csv","csv.gz","docx","fastq","h5","h5ad","loom","mtx.gz","pdf","Robj","tar","tar.gz","tsv","tsv.gz","txt","txt.gz","xlsx","zip"]}}
1608589307316   2020-12-21T14:21:47.316 Task timed out after 900.10 seconds
1608589377781   2020-12-21T14:22:57.781 Caught exception for <function start_manifest_generation_fetch at 0x7f2b4f93c700>

1608591592269   2020-12-21T14:59:52.269 dcp1 {"fileFormat":{"is":["bai","bam","csv","csv.gz","docx","fastq","fastq.gz","matrix","npy","npz","pdf","results","txt","unknown"]}}
1608591604904   2020-12-21T15:00:04.904 dcp1 {"fileFormat":{"is":["bai","bam","csv","csv.gz","docx","fastq","fastq.gz","matrix","npy","npz","pdf","results","txt","unknown"]}}
1608592507199   2020-12-21T15:15:07.199 Task timed out after 900.10 seconds
1608592516730   2020-12-21T15:15:16.730 Caught exception for <function start_manifest_generation_fetch at 0x7f3e2eebe700>
1608592519608   2020-12-21T15:15:19.608 Task timed out after 900.10 seconds

1608594253495   2020-12-21T15:44:13.495 dcp1 {"fileFormat":{"is":["bai","bam","csv","csv.gz","docx","fastq","fastq.gz","matrix","npy","npz","pdf","results","txt","unknown"]}}
1608595167358   2020-12-21T15:59:27.358 Task timed out after 900.08 seconds
1608595175786   2020-12-21T15:59:35.786 Caught exception for <function start_manifest_generation_fetch at 0x7f3509130700>

1608653538573   2020-12-22T08:12:18.573 dcp1 {"fileFormat":{"is":["bam","csv","csv.gz","docx","fastq","h5","h5ad","loom","mtx.gz","pdf","Robj","tar","tar.gz","tsv","tsv.gz","txt","txt.gz","xlsx","zip"]}}
1608654443409   2020-12-22T08:27:23.409 Task timed out after 900.09 seconds
1608654451137   2020-12-22T08:27:31.137 Caught exception for <function start_manifest_generation_fetch at 0x7fac455ab700>
```

**Comment by melainalegaspi** [comment]
Triage to discuss next steps.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :" @danielsotirhos and I are clueless as to improve the hotfix any further. The hotfix truncates large entries arbitrarily, causing data loss."

**Comment by noah-aviel-dove** [comment]
I don't think this should be closed while we have outstanding FIXME's for it
https://github.com/DataBiosphere/azul/blob/2036eb064172410b7c047edf21e9235fa9343fa5/src/azul/service/manifest_service.py#L1321

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The FIXME @noah-aviel-dove is referring to precedes a workaround for this issue, not a permanent fix. The workaround arbitrarily selects the first 100 values. We need a better solution that is not lossy."

**Comment by hannes-ucsc** [comment]
We truncate fields in other places, too, so maybe the workaround IS a permanent solution. We need to consolidate the thresholds of truncation (#3725), reevaluate if the solution for #3248 makes the truncation in the manifest code redundant and remove the truncation and the FIXME or just the FIXME if the truncation in the manifest is still needed.

**Comment by dsotirho-ucsc** [comment]
Moving ticket to `Triage` to consolidate with tickets similar to this.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Not directly related to manifest size."

**Comment by hannes-ucsc** [comment]
… but there is still a FIXME referring to this issue: https://github.com/DataBiosphere/azul/blob/6d000278a48a37000ca644a657a474d4b86b3347/src/azul/service/manifest_service.py#L1124

**Comment by hannes-ucsc** [comment]
Unable to reproduce.
