### ISSUE TITLE
Hitting the service in a fresh deployment gives 500, not 404

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#265]
When hitting the service in a fresh deployment where the ES indices don't exist, we raise a 500. We should be raising a 404. This could also happen in an existing deployment if A) the indices have been deleted or B) the index names have changed, as was done in https://github.com/DataBiosphere/azul/pull/231.

Example: DCP-wide test build https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/5865

I don't have 100% proof for the 500 but this 404 from ES is not handled and will very likely cause 500 being sent to the client. Step one would be to reproduce this by deleting the indices in an deployment and hitting the service.

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 225, in get_specimen_data
    entity_type='specimens')
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 488, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-177)
┆Project Name: azul
┆Issue Number: AZUL-177

**Comment by hannes-ucsc** [comment]
@GPelayo re your question about reproduction this morning: It was already mention in the original description: 

> Step one would be to reproduce this by deleting the indices in an deployment and hitting the service.

**Comment by GPelayo** [comment]
@hannes-ucsc, OK I wasn't sure I had to test on a completely new deployment or an already existing one. The ticket states the issue happens on a fresh deployment.
