### ISSUE TITLE
TDR plugin fails to fetch bundle if `version` is specified as None

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2714]
The following request …
```
$ http "https://service.dev.singlecell.gi.ucsc.edu/repository/files/a599297a-dc69-4ef4-8f53-7036455f4ae5?catalog=dcp2"
HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 142
Content-Type: application/json
Date: Thu, 14 Jan 2021 18:51:17 GMT
Via: 1.1 4d0d70ec0eabd0560d63af069388e374.cloudfront.net (CloudFront)
X-Amz-Cf-Id: -txC4KoiZPpBWEuR_HZ1I-1Sib9YoboFA1NI5t9eHnWVRA9DTF_nTA==
X-Amz-Cf-Pop: LAX50-C2
X-Amzn-Trace-Id: Root=1-600092a5-4dcff481368ccb0770e005d7;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: ZJvZ5FxQoAMFoXQ=
x-amzn-RequestId: dea3481d-7a2c-4252-8470-32e53ba51ae8

{
    "Code": "NotFoundError",
    "Message": "NotFoundError: Unable to find file 'a599297a-dc69-4ef4-8f53-7036455f4ae5', version None in catalog 'dcp2'"
}
```
… fails, although the `file_uuid` is valid, note the `version None`.

A similar failure was encountered when running @jessebrennan `can_tdr_bundle` script, if a version isn't provided …
```
$ python scripts/can_tdr_bundle.py --catalog dcp2 --uuid a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32
2021-01-13 16:31:34,207 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "scripts/can_tdr_bundle.py", line 73, in <module>
    main(sys.argv[1:])
  File "scripts/can_tdr_bundle.py", line 51, in main
    bundle = download_bundle(args.catalog, fqid)
  File "scripts/can_tdr_bundle.py", line 57, in download_bundle
    bundle = repository_plugin.fetch_bundle(fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 121, in fetch_bundle
    bundle = self.emulate_bundle(bundle_fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 186, in emulate_bundle
    entities, links_jsons = self._stitch_bundles(bundle_fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 221, in _stitch_bundles
    links_json = self._retrieve_links(bundle)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 259, in _retrieve_links
    links = one(self._run_sql(f'''
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 152, in _run_sql
    return self.tdr.run_sql(query)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/terra.py", line 266, in run_sql
    return job.result()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 129, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3098, in _blocking_poll
    super(QueryJob, self)._blocking_poll(timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 107, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 85, in _done_or_raise
    if not self.done(**kwargs):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3079, in done
    self._query_results = self._client._get_query_results(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1286, in _get_query_results
    resource = self._call_api(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/platform-hca-dev/queries/af6bf964-0281-4d0e-8ebc-9e3c1f567399?maxResults=0&location=US&prettyPrint=false: Invalid timestamp: 'None'

(job ID: af6bf964-0281-4d0e-8ebc-9e3c1f567399)

                                                                 -----Query Job SQL Follows-----                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            SELECT JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, links_id, project_id, version, content, BYTE_LENGTH(content) AS content_size
   3:            FROM broad-jade-dev-data.hca_dev_20201203___20201210.links
   4:            WHERE links_id = 'a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32'
   5:                AND version = TIMESTAMP('None')
   6:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
``` 
… a failure is observed with similar `Invalid timestamp: 'None'` i.e. `version=None`.
When consulting with @danielsotirhos, he confirmed that by removing `AND version = TIMESTAMP('None')` the request
was successful.

**Comment by theathorn** [comment]
@hannes-ucsc to specify solution.

**Comment by hannes-ucsc** [comment]
OK, there are two separate issues here. One is about files, the other about bundles. We should not conflate them and the solution might be different for either.

@achave11 please split the files use case into a separate issue and post the relevant service log entries as well. And please make this issue about the bundles use case exclusively.

**Comment by hannes-ucsc** [comment]
Actually, let's split this into two new tickets and close this one, @achave11.

**Comment by achave11** [comment]
Issue related to files is invalid. I made a mistake when using the `repository` path endpoints. I was using the `entryId` field returned in the response for `/index/files` as the uuid for the `repository` endpoints. I needed to use the `files` field content to determine the file uuid and version.

**Comment by hannes-ucsc** [comment]
Got it. So then we just need a replacement ticket for bundles.

**Comment by achave11** [comment]
Closing in favor of https://github.com/DataBiosphere/azul/issues/2717.
