### ISSUE TITLE
TDR Plugin `_retrieve_links` fails if `links_id.version` is set to None

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2717]
When running `scripts/can_tdr_bundle.py`…
```
$ python scripts/can_tdr_bundle.py --catalog dcp2 --uuid a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32
```
… a BadRequest error is produced.
```
2021-01-15 10:12:58,948 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "scripts/can_tdr_bundle.py", line 73, in <module>
    main(sys.argv[1:])
  File "scripts/can_tdr_bundle.py", line 51, in main
    bundle = download_bundle(args.catalog, fqid)
  File "scripts/can_tdr_bundle.py", line 57, in download_bundle
    bundle = repository_plugin.fetch_bundle(fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 121, in fetch_bundle
    bundle = self.emulate_bundle(bundle_fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 186, in emulate_bundle
    entities, links_jsons = self._stitch_bundles(bundle_fqid)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 221, in _stitch_bundles
    links_json = self._retrieve_links(bundle)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 259, in _retrieve_links
    links = one(self._run_sql(f'''
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/plugins/repository/tdr/__init__.py", line 152, in _run_sql
    return self.tdr.run_sql(query)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/terra.py", line 266, in run_sql
    return job.result()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 129, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3098, in _blocking_poll
    super(QueryJob, self)._blocking_poll(timeout=timeout)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 107, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 85, in _done_or_raise
    if not self.done(**kwargs):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3079, in done
    self._query_results = self._client._get_query_results(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1286, in _get_query_results
    resource = self._call_api(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/platform-hca-dev/queries/5e3f1c2f-1273-4762-b5fd-ddcafcf1f3de?maxResults=0&location=US&prettyPrint=false: Invalid timestamp: 'None'

(job ID: 5e3f1c2f-1273-4762-b5fd-ddcafcf1f3de)

                                                                 -----Query Job SQL Follows-----                                                                  

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            SELECT links_id, version, content, project_id, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, BYTE_LENGTH(content) AS content_size
   3:            FROM broad-jade-dev-data.hca_dev_20201203___20201210.links
   4:            WHERE links_id = 'a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32'
   5:                AND version = TIMESTAMP('None')
   6:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
```

When using the script by providing a UUID as input and omitting version…
```
links_id = BundleFQID(uuid=a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32, version=None)
```
… BundleFQID sets version to None. Which causes a BadRequest error when the query is executed in `_retrieve_links` method of Plugin for TDR.

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to outline a solution.

**Comment by hannes-ucsc** [comment]
I don't want to make version in BundleFQID optional. It would affect too many places in the code base.

fetch_bundle should be changed to

```diff
Index: src/azul/plugins/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/__init__.py b/src/azul/plugins/__init__.py
--- a/src/azul/plugins/__init__.py	(revision dc202ee2c273cee1bff823ee2b930d5d8fe0addc)
+++ b/src/azul/plugins/__init__.py	(date 1611195794936)
@@ -168,7 +168,7 @@
         raise NotImplementedError
 
     @abstractmethod
-    def fetch_bundle(self, bundle_fqid: BundleFQID) -> Bundle:
+    def fetch_bundle(self, *, uuid: str, version: Optional[str]) -> Bundle:
         raise NotImplementedError
 
     @abstractmethod
```

The DSS implementation sorta already supports a missing version but it doesn't set the version to the loaded version, it just asserts that the passed-in version is the same as the loaded one. The TDR implementation should query the bundle by UUID only (ignoring the version), fail if multiple versions are returned (even if one of them is the requested version), and assert that the only existing version is the passed in version unless no version was passed in.

**Comment by hannes-ucsc** [comment]
Not exactly easy.
