### ISSUE TITLE
Storage service fails to upload file with tags

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2724]
This bug was encountered in the process of developing #2052 (#1430). I created a separate issue to simplify that PR. I believe this never came up before because this code path was never used.

To reproduce:
```
Python 3.8.3 (default, Dec  4 2020, 12:30:22) 
[GCC 9.3.0] on linux
>>> from azul.service.storage_service import StorageService
>>> from tempfile import NamedTemporaryFile
>>> storage_service = StorageService()
>>> with NamedTemporaryFile('w') as f:
...     f.write('some contents')
...     storage_service.upload(file_path=f.name, object_key='DELETEME', tagging={'foo': 'bar'})
...     
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/home/jesse/gi/azul/src/azul/service/storage_service.py", line 82, in upload
    self.client.upload_file(Filename=file_path,
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 276, in upload_file
    future = self._manager.upload(
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/s3transfer/manager.py", line 294, in upload
    self._validate_all_known_args(extra_args, self.ALLOWED_UPLOAD_ARGS)
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/s3transfer/manager.py", line 433, in _validate_all_known_args
    raise ValueError(
ValueError: Invalid extra_args key 'Tagging', must be one of: ACL, CacheControl, ContentDisposition, ContentEncoding, ContentLanguage, ContentType, Expires, GrantFullControl, GrantRead, GrantReadACP, GrantWriteACP, Metadata, RequestPayer, ServerSideEncryption, StorageClass, SSECustomerAlgorithm, SSECustomerKey, SSECustomerKeyMD5, SSEKMSKeyId, WebsiteRedirectLocation
```

**Comment by jessebrennan** [comment]
@hannes-ucsc I just confirmed that this does indeed still block #1430.
