### ISSUE TITLE
Tests in AzulChaliceLocalIntegrationTest fail in sandbox

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2744]
Tests within `AzulChaliceLocalIntegrationTest` class [failed](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/9460#L1808) in recent `sandbox` run for PR #2711.

```
======================================================================
FAIL: test_local_chalice_index_endpoints (integration_test.AzulChaliceLocalIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 885, in test_local_chalice_index_endpoints
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 404
======================================================================
FAIL: test_local_filtered_index_endpoints (integration_test.AzulChaliceLocalIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 893, in test_local_filtered_index_endpoints
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 404
----------------------------------------------------------------------
Ran 10 tests in 469.656s
FAILED (failures=2, skipped=3)
Serving on http://127.0.0.1:8000
make: *** [Makefile:166: integration_test] Error 1
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Abraham to investigate hypothesis that this is caused by a race condition and that the deployment is incomplete. "

**Comment by achave11** [comment]
This IT failures was observed in approximate time range with an accidental deployment to the `sandbox` stage by a team member. This caused a mismatch in the contents of the `sandbox` deployment, leading to [this failure](https://github.com/DataBiosphere/azul/issues/2744#issue-796632354).
