### ISSUE TITLE
Remote reindex failure: RepositoryPlugin.sources is not JSON serializable 

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2761]
```
$ make reindex
python /home/nadove/PycharmProjects/azul-sc/scripts/check_branch.py
python scripts/reindex.py --delete --index --purge --partition-prefix-length=2
2021-02-03 23:43:13,044 INFO    MainThread: Found credentials in environment variables.
2021-02-03 23:43:13,668 INFO    MainThread: Disabling lambdas ...
...
2021-02-03 23:44:33,247 INFO    MainThread: Queuing notifications for reindexing ...
2021-02-03 23:44:33,247 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44400'.
2021-02-03 23:44:36,118 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44401'.
2021-02-03 23:44:36,119 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44402'.
2021-02-03 23:44:36,119 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44403'.
2021-02-03 23:44:36,120 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44404'.
2021-02-03 23:44:36,120 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44405'.
2021-02-03 23:44:36,120 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44406'.
2021-02-03 23:44:36,121 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44407'.
2021-02-03 23:44:36,121 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44408'.
2021-02-03 23:44:36,121 INFO    MainThread: Remote reindexing of catalog 'dcp2', partition '44409'.
Traceback (most recent call last):
  File "scripts/reindex.py", line 126, in <module>
    main(sys.argv[1:])
  File "scripts/reindex.py", line 116, in main
    azul.remote_reindex(catalog, args.prefix, args.partition_prefix_length)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/azulclient.py", line 230, in remote_reindex
    entries = [
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/azulclient.py", line 231, in <listcomp>
    dict(Id=str(i), MessageBody=json.dumps(message))
  File "/home/nadove/.pyenv/versions/3.8.3/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/nadove/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/nadove/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/nadove/.pyenv/versions/3.8.3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
Makefile:119: recipe for target 'reindex' failed
make: *** [reindex] Error 1
```

**Comment by hannes-ucsc** [comment]
This was inadvertently fixed by f65dbb7c (merge commit 8ccc8136) as part of #2749, PR #2760.

**Comment by hannes-ucsc** [comment]
The successful reindex on `dev` for the merge commit is sufficient proof:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/9652#L249

**Comment by hannes-ucsc** [comment]
Shouldn't close before this lands on prod.
