### ISSUE TITLE
Return 400 if `filters` or `sort` parameter is malformed

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#280]
Enforce the following constraints on the filters parameter: In each facet filter, the `is` key is present. It's value is either None or a list of facet values. In each facet filter, the `is` key is the only key. There are no other keys.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-185)
┆Project Name: azul
┆Issue Number: AZUL-185

**Comment by hannes-ucsc** [comment]
Passing a bad field name for `sort` also raises a 500 instead of a 400:

https://service.dev.explore.data.humancellatlas.org/repository/specimens?filters=%7B%22file%22%3A%7B%22disease%22%3A%7B%22is%22%3A%5B%22glioblastoma%22%2C%22H%20syndrome%22%5D%7D%2C%22libraryConstructionApproach%22%3A%7B%22is%22%3A%5B%22Smart-seq2%22%5D%7D%7D%7D&size=15&sort=fileName&order=asc

https://github.com/DataBiosphere/azul/issues/702

**Comment by hannes-ucsc** [comment]
Also:

```
$ http "https://service.dev.explore.data.humancellatlas.org/repository/projects?filters={'file':{'project':{'is':'barista_seq'}}}"
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 1968
Content-Type: text/plain
Date: Thu, 18 Apr 2019 17:23:01 GMT
Via: 1.1 032d42677fbf05c24a4bb71369581429.cloudfront.net (CloudFront)
X-Amz-Cf-Id: OVrUw3BeHuWgZLvlqP1GXjKpspodOfnsY3bxe3WkFD9SSqJOR-x39Q==
X-Amzn-Trace-Id: Root=1-5cb8b275-a70cdb7637e90f75dac9f396;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: YWDSXHY_oAMFSfw=
x-amzn-RequestId: 9e396696-61fe-11e9-9998-790cf8d12a34

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 300, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 155, in repository_search
    return service.get_data(entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository.py", line 80, in get_data
    return self._get_items(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 54, in _get_items
    response = self._get_data(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 33, in _get_data
    entity_type=entity_type)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 502, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', '[terms] query does not support [contents.projects.project_shortname.keyword]')
```

vs the correct usage


```
$ http "https://service.dev.explore.data.humancellatlas.org/repository/projects?filters={'file':{'project':{'is':['barista_seq']}}}"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 4468
Content-Type: application/json
Date: Thu, 18 Apr 2019 17:25:27 GMT
Via: 1.1 8008015354a3ca72f56c382a1d1cfe9f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: AdrNeBWiNFXOQ_8jIgdY14vsu_0lJnNAnOxn-Ao0fTiE-fuM7mUIFA==
X-Amzn-Trace-Id: Root=1-5cb8b307-e62db5800e5eab006b6c8480;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: YWDpNFJpoAMFsqg=
x-amzn-RequestId: f56190a7-61fe-11e9-8df0-878f8ec3a9d9

{
    "hits": [
        {
            "cellSuspensions": [],
            "entryId": "ae5237b4-633f-403a-afc6-cb87e6f90db1",
            "fileTypeSummaries": [
                {
                    "count": 6,
---8<----
omitted
---8<----


   },
        "publicationTitle": {
            "terms": [
                {
                    "count": 1,
                    "term": null
                }
            ],
            "total": 0,
            "type": "terms"
        },
        "selectedCellType": {
            "terms": [
                {
                    "count": 1,
                    "term": null
                }
            ],
            "total": 0,
            "type": "terms"
        }
    }
}

$
```
