### ISSUE TITLE
Missing `analysis_process` entities in snapshot hca_dev_20201203___20210219

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2873]
The subgraphs:

```
{
  "bundle_uuid": "c12a6ca2-3234-5182-ad0b-f8c2fb881ab5",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "ae338c4e-650f-545b-8631-3c8d755aa2f9",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "40733888-3b9f-500e-84fd-1a18a64aadbe",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
{
  "bundle_uuid": "9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185",
  "bundle_version": "2020-12-03T00:00:01.000000Z"
}
```

The error:
```
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 175, in transform
bundle = plugin.fetch_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 217, in fetch_bundle
bundle = self._emulate_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 305, in _emulate_bundle
raise e
File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 390, in _retrieve_entities
require(not missing,
File "/var/task/azul/__init__.py", line 1108, in require
reject(not condition, *args, exception=exception)
File "/var/task/azul/__init__.py", line 1123, in reject
raise exception(*args)
azul.RequirementError: Required entities not found in broad-jade-dev-data.hca_dev_20201203___20210219.analysis_process: {'ac9f702c-89c0-4251-b0a7-08ca3b1f9912'}
```

**Comment by hannes-ucsc** [comment]
https://humancellatlas.slack.com/archives/C01360XN04S/p1619130414247900

**Comment by theathorn** [comment]
Still present in snapshot hca_dev_20201203__20210507.

**Comment by jessebrennan** [comment]
This seems to be resolved. There were no failures during the last dev reindex.
