### ISSUE TITLE
Sandbox builds fail because of outdated requirements without changes to `requirements.*`

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2899]
This has happened to the two builds (separate PRs) I've tried in the `sandbox` today:

- https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/12362
- https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/12629

```
$ make check_clean
git diff --exit-code && git diff --cached --exit-code
diff --git a/requirements.dev.trans.txt b/requirements.dev.trans.txt
index 8fb3a13..e06ce34 100644
--- a/requirements.dev.trans.txt
+++ b/requirements.dev.trans.txt
@@ -1,11 +1,11 @@
 argh==0.26.2
 arrow==0.12.1
-aws-sam-translator==1.33.0
+aws-sam-translator==1.35.0
 aws-xray-sdk==2.6.0
-cfn-lint==0.44.1
+cfn-lint==0.47.2
 click==7.1.2
 colorama==0.4.1
-configargparse==1.2.3
+configargparse==1.3
 datetime==4.3
 decorator==4.4.2
 docker-pycreds==0.4.0
@@ -14,13 +14,13 @@ enum-compat==0.0.3
 flask-basicauth==0.2.0
 flask==1.1.2
 geventhttpclient==1.4.4
-google-auth-httplib2==0.0.4
-greenlet==0.4.17
-httplib2==0.18.1
+google-auth-httplib2==0.1.0
+greenlet==1.0.0
+httplib2==0.19.0
 itsdangerous==1.1.0
 jsondiff==1.1.2
-jsonpatch==1.28
-jsonpickle==1.4.2
+jsonpatch==1.31
+jsonpickle==2.0.0
 junit-xml==1.9
 mccabe==0.6.1
 mock==4.0.3
@@ -35,12 +35,12 @@ pycodestyle==2.6.0
 pyflakes==2.2.0
 pyrsistent==0.17.3
 python-jose==3.2.0
-pyzmq==20.0.0
+pyzmq==22.0.3
 smmap2==3.0.1
-smmap==3.0.4
-sshpubkeys==3.1.0
+smmap==4.0.0
+sshpubkeys==3.3.1
 uritemplate==3.0.1
-websocket-client==0.57.0
+websocket-client==0.58.0
 xmltodict==0.12.0
 zope.event==4.5.0
 zope.interface==5.2.0
diff --git a/requirements.trans.txt b/requirements.trans.txt
index 0e34bb5..07b8ccf 100644
--- a/requirements.trans.txt
+++ b/requirements.trans.txt
@@ -1,36 +1,38 @@
 argcomplete==1.12.2
 atomicwrites==1.4.0
 bagit==1.7.0
-cachetools==4.2.0
+cachetools==4.2.1
 certifi==2020.12.5
 chardet==3.0.4
 commonmark==0.9.1
 crc32c==2.2
 dcplib==2.1.2
 docutils==0.15.2
-google-api-core==1.24.1
-google-auth-oauthlib==0.4.2
-google-cloud-core==1.5.0
+google-api-core==1.26.1
+google-auth-oauthlib==0.4.3
+google-cloud-core==1.6.0
 google-resumable-media==0.5.1
-googleapis-common-protos==1.52.0
+googleapis-common-protos==1.53.0
 idna==2.8
-jinja2==2.11.2
+jinja2==2.11.3
 jsonpointer==1.14
 jsonschema==3.2.0
 markupsafe==1.1.1
 oauthlib==3.1.0
 orderedmultidict==1.0.1
-protobuf==3.14.0
+packaging==20.9
+protobuf==3.15.6
 puremagic==1.4
 pycparser==2.20
+pyparsing==2.4.7
 python-dateutil==2.8.1
-pytz==2020.5
+pytz==2021.1
 requests-oauthlib==1.3.0
 s3transfer==0.2.1
 six==1.15.0
 tenacity==5.0.4
 text-unidecode==1.3
-tqdm==4.55.0
+tqdm==4.59.0
 tweak==1.0.3
 tzlocal==2.1
 wrapt==1.12.1
make: *** [Makefile:170: check_clean] Error 1
```
---

For the first build, I tried updating requirements and was greeted with a new error, which I assume is related:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/12565
```
  File "/build/.venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 362, in configure_mtls_channel
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/register_sam.py", line 43, in <module>
    main()
  File "/builds/ucsc/azul/scripts/register_sam.py", line 39, in main
    tdr.check_bigquery_access(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 288, in check_bigquery_access
    tables = list(bigquery.list_tables(source.bq_name, max_results=1))
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 369, in _next_page
    response = self._get_next_page_response()
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 418, in _get_next_page_response
    return self.api_request(
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 472, in api_request
    response = self._make_request(
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 336, in _make_request
    return self._do_request(
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 374, in _do_request
    return self.http.request(
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/_http.py", line 157, in http
    return self._client._http
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/client.py", line 187, in _http
    self._http_internal.configure_mtls_channel(self._client_cert_source)
  File "/build/.venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 365, in configure_mtls_channel
    six.raise_from(new_exc, caught_exc)
  File "<string>", line 3, in raise_from
google.auth.exceptions.MutualTLSChannelError: No module named 'OpenSSL'
make[1]: *** [Makefile:95: sam] Error 1
make[1]: Leaving directory '/builds/ucsc/azul'
make: *** [Makefile:91: auto_deploy] Error 2
```

**Comment by jessebrennan** [comment]
I can run `make sam` locally after updating the requirements and reproduce the issue, which means that one of the new requirements is causing this. My tentative work around will be to pin PySSL as a dependency.

**Comment by jessebrennan** [comment]
Fixing the requirements has caused a new failure to crop up during integration tests. This error was not resolved by an early reindex.

The test failure:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/12723

and the log message from the lambda:

```
[ERROR] 2021-03-16T17:29:22.485Z 900dec80-e940-4d84-b8ef-f64552565357 Caught exception for <function get_sample_data at 0x7f0e798afc10>
Traceback (most recent call last):
File "/var/task/azul/indexer/document.py", line 428, in translate_fields
field_type = field_types[key]
KeyError: 'sample_specimens'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 1192, in get_sample_data
return repository_search('samples', sample_id)
File "/var/task/app.py", line 947, in repository_search
return service.get_data(catalog=catalog,
File "/var/task/azul/service/index_query_service.py", line 67, in get_data
response = self.transform_request(catalog=catalog,
File "/var/task/azul/service/elasticsearch_service.py", line 627, in transform_request
hits = self.translate_fields(catalog, hits, forward=False)
File "/var/task/azul/indexer/document_service.py", line 99, in translate_fields
return Document.translate_fields(doc, self.field_types(catalog), forward=forward)
File "/var/task/azul/indexer/document.py", line 440, in translate_fields
return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
File "/var/task/azul/indexer/document.py", line 440, in <listcomp>
return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
File "/var/task/azul/indexer/document.py", line 433, in translate_fields
new_doc[key] = cls.translate_fields(val, field_type, forward=forward, path=(*path, key))
File "/var/task/azul/indexer/document.py", line 430, in translate_fields
raise KeyError(f'Key {key!r} not defined in field_types')
KeyError: "Key 'sample_specimens' not defined in field_types"
```

**Comment by noah-aviel-dove** [comment]
Happened again: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/13307
