### ISSUE TITLE
DefaultCredentialsError when AZUL_TDR_WORKERS to > 1

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2910]
Not a very good reproduction but the best I have ATM:

Setting `AZUL_TDR_WORKERS` to `'8'` and running 

```
import os
os.environ['AZUL_DEBUG'] = '2'
from azul.indexer.index_controller import IndexController
from azul.logging import configure_script_logging
configure_script_logging()
c = IndexController()
m = {
                "action": "add",
                "notification": {
                    "source": {
                        "id": "a9b3ba0b-e17b-4404-a686-3c8c33899d12",
                        "name": "tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210302"
                    },
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "50e97f10-697d-46cb-8fcf-584f7b7cac24",
                    "match": {
                        "bundle_uuid": "6a4dda81-d6c9-5be8-8608-c685eef62754",
                        "bundle_version": "2021-02-04T10:00:00.000000Z"
                    }
                },
                "catalog": "dcp3"
            }
n = m['notification']
cs = c.transform('dcp3', n, False)
```

yields

```
Traceback (most recent call last):
  File "<input>", line 25, in <module>
  File "/home/hannes/workspace/hca/azul/src/azul/indexer/index_controller.py", line 175, in transform
    bundle = plugin.fetch_bundle(bundle_fqid)
  File "/home/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr/__init__.py", line 217, in fetch_bundle
    bundle = self._emulate_bundle(bundle_fqid)
  File "/home/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr/__init__.py", line 314, in _emulate_bundle
    raise e
  File "/home/hannes/.pyenv/versions/3.8.3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr/__init__.py", line 397, in _retrieve_entities
    rows = self._query_latest_version(source, f'''
  File "/home/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr/__init__.py", line 269, in _query_latest_version
    iter_rows = self._run_sql(query)
  File "/home/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr/__init__.py", line 248, in _run_sql
    return self.tdr.run_sql(query)
  File "/home/hannes/workspace/hca/azul/src/azul/terra.py", line 314, in run_sql
    job: QueryJob = self._bigquery(self.credentials.project_id).query(query)
  File "/home/hannes/workspace/hca/azul/src/azul/terra.py", line 306, in _bigquery
    return bigquery.Client(project=project)
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 176, in __init__
    super(Client, self).__init__(
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/cloud/client.py", line 278, in __init__
    Client.__init__(self, credentials=credentials, client_options=client_options, _http=_http)
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/cloud/client.py", line 153, in __init__
    credentials, _ = google.auth.default(scopes=scopes)
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/auth/_default.py", line 454, in default
    credentials, project_id = checker()
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/auth/_default.py", line 221, in _get_explicit_environ_credentials
    credentials, project_id = load_credentials_from_file(
  File "/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/google/auth/_default.py", line 107, in load_credentials_from_file
    raise exceptions.DefaultCredentialsError(
google.auth.exceptions.DefaultCredentialsError: File /tmp/tmpahoyyb8o was not found.
```

The bundle in the notification is very big (stitched) so the repro will take a long time. Besides, the bundle uses a prod snapshot. But I think any bundle in any snapshot will do.

**Comment by hannes-ucsc** [comment]
I have the feeling this 

https://github.com/DataBiosphere/azul/blob/e29d099ac31ef46b3732c2afd5e684c951e78304/src/azul/terra.py#L303

should be `@cache_per_thread`.

**Comment by noah-aviel-dove** [comment]
Unable to reproduce. Tried bundle `{'bundle_uuid': '4e5e4138-6687-4569-bb7a-56ee77d316ec', 'bundle_version': '2019-10-04T09:43:31.875342Z'}` from snapshot `{'id': '4641bafb-5190-425b-aea9-9c7b125515c8', 'name': 'tdr:broad-jade-dev-data:snapshot/hca_dev_20201217_test4___20210126'}` in catalog `dcp2`, and the transformation succeeded.

**Comment by noah-aviel-dove** [comment]
Reproduced on my second attempt. Passed 20 consecutive times after applying changes.

**Comment by noah-aviel-dove** [comment]
Can still reproduce issue after fix is applied.
