### ISSUE TITLE
`make format` hangs if it has insufficient permissions

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2989]
To reproduce run

```
chmod ug-w -R .
make format
```
Don't forget to shut down the rogue docker container. Also fix your permissions with `chmod ug+w -R .`

This is the log
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
PyCharm 2019.2.3, build PC-192.6817.19 Formatter
Apr 15, 2021 10:33:16 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
2021-04-15 22:33:18,213 [   3290]  ERROR - llij.ide.plugins.PluginManager - Cannot modify a read-only file '/home/developer/azul/terraform/modules.tf.json.template.py'. 
com.intellij.util.IncorrectOperationException: Cannot modify a read-only file '/home/developer/azul/terraform/modules.tf.json.template.py'.
        at com.intellij.psi.impl.CheckUtil.checkWritable(CheckUtil.java:47)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:188)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:173)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:159)
        at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:154)
        at com.intellij.formatting.commandLine.FileSetFormatter.lambda$reformatFile$0(FileSetFormatter.java:136)
        at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:368)
        at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:125)
        at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
        at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
        at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263)
        at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:320)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
        at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:322)
        at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:263)
        at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:245)
        at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:127)
        at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:368)
        at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:360)
        at com.intellij.formatting.commandLine.FileSetFormatter.reformatFile(FileSetFormatter.java:134)
        at com.intellij.formatting.commandLine.FileSetFormatter.processFile(FileSetFormatter.java:104)
        at com.intellij.formatting.commandLine.FileSetProcessor.processEntry(FileSetProcessor.java:75)
        at com.intellij.formatting.commandLine.FileSetProcessor.processFiles(FileSetProcessor.java:24)
        at com.intellij.formatting.commandLine.FileSetFormatter.processFiles(FileSetFormatter.java:86)
        at com.intellij.formatting.commandLine.FormatterStarter.main(FormatterStarter.java:95)
        at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
        at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-04-15 22:33:18,215 [   3292]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2019.2.3  Build #PC-192.6817.19 
2021-04-15 22:33:18,215 [   3292]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2021-04-15 22:33:18,215 [   3292]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2021-04-15 22:33:18,227 [   3304]  ERROR - llij.ide.plugins.PluginManager - Last Action:  
Apr 15, 2021 10:33:23 PM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/developer/.java/.userPrefs/prefs.xml
2021-04-15 22:33:24,761 [   9838]   WARN - llij.ide.plugins.PluginManager - MultiUser Git not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,763 [   9840]   WARN - llij.ide.plugins.PluginManager - Task Management not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,763 [   9840]   WARN - llij.ide.plugins.PluginManager - Android Resource Value Viewer not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,763 [   9840]   WARN - llij.ide.plugins.PluginManager - Flyme not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,764 [   9841]   WARN - llij.ide.plugins.PluginManager - Certificate Decoder not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,764 [   9841]   WARN - llij.ide.plugins.PluginManager - Gherkin not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,764 [   9841]   WARN - llij.ide.plugins.PluginManager - Socket Client not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,764 [   9841]   WARN - llij.ide.plugins.PluginManager - IdeaVimExtension not loaded: since build 192.7142.36 > PC-192.6817.19 
2021-04-15 22:33:24,765 [   9842]   WARN - llij.ide.plugins.PluginManager - Stack Search not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,765 [   9842]   WARN - llij.ide.plugins.PluginManager - Settings Repository not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,765 [   9842]   WARN - llij.ide.plugins.PluginManager - yFiles not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,766 [   9843]   WARN - llij.ide.plugins.PluginManager - JS GraphQL not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,766 [   9843]   WARN - llij.ide.plugins.PluginManager - ClangFormat not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,767 [   9844]   WARN - llij.ide.plugins.PluginManager - Tailwind Formatter not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,767 [   9844]   WARN - llij.ide.plugins.PluginManager - Requirements not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,767 [   9844]   WARN - llij.ide.plugins.PluginManager - Bazel not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,768 [   9845]   WARN - llij.ide.plugins.PluginManager - Submit to INGInious not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,768 [   9845]   WARN - llij.ide.plugins.PluginManager - Java Memory Killer not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,768 [   9845]   WARN - llij.ide.plugins.PluginManager - Android Resource Tool not loaded: since build 192.7142 > PC-192.6817.19 
2021-04-15 22:33:24,768 [   9845]   WARN - llij.ide.plugins.PluginManager - FlutterAssetSync not loaded: since build 192.7142 > PC-192.6817.19 

```

**Comment by hannes-ucsc** [comment]
Unlikely to occur IRL.
