### ISSUE TITLE
Running `reindex.py` locally fails

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3013]
When running…
```
$ python scripts/reindex.py --prefix efa4 --catalog dcp1 --index
```
… the following error is encountered.

```
2021-04-26 11:12:24,169 INFO    MainThread: Found credentials in environment variables.
2021-04-26 11:12:24,842 INFO    MainThread: Queuing notifications for reindexing ...
2021-04-26 11:12:55,142 INFO    MainThread: Purchased 100 BigQuery slots, commitment name: 'projects/platform-hca-dev/locations/US/capacityCommitments/16221270199109327158'
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "Requested slot capacity (100) for this reservation exceeds unallocated capacity (0)."
        debug_error_string = "{"created":"@1619460775.450231000","description":"Error received from peer ipv4:172.217.14.106:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Requested slot capacity (100) for this reservation exceeds unallocated capacity (0).","grpc_status":9}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/reindex.py", line 185, in <module>
    main(sys.argv[1:])
  File "scripts/reindex.py", line 168, in main
    slot_manager.ensure_slots_active()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/bigquery_reservation.py", line 107, in ensure_slots_active
    self.reservation_name = self._create_reservation().name
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/bigquery_reservation.py", line 159, in _create_reservation
    reservation = self._client.create_reservation(reservation=reservation,
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/cloud/bigquery_reservation_v1/services/reservation_service/client.py", line 519, in create_reservation
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.FailedPrecondition: 400 Requested slot capacity (100) for this reservation exceeds unallocated capacity (0).
```

Attempting to run the same command once more gave the following error…
```
$ python scripts/reindex.py --prefix efa4 --catalog dcp1 --index
2021-04-26 11:15:36,010 INFO    MainThread: Found credentials in environment variables.
2021-04-26 11:15:36,687 INFO    MainThread: Queuing notifications for reindexing ...
Traceback (most recent call last):
  File "scripts/reindex.py", line 185, in <module>
    main(sys.argv[1:])
  File "scripts/reindex.py", line 167, in main
    slot_manager = SlotManager()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/bigquery_reservation.py", line 49, in __init__
    self.refresh()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/bigquery_reservation.py", line 61, in refresh
    self.has_active_slots()
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/src/azul/bigquery_reservation.py", line 92, in has_active_slots
    raise RequirementError('BigQuery slot commitment state is '
azul.RequirementError: ('BigQuery slot commitment state is inconsistent: some, but not all resources are missing', {'projects/platform-hca-dev/locations/US/capacityCommitments/16221270199109327158', None})
```

**Comment by melainalegaspi** [comment]
@noah-aviel-dove spike to check validity.

**Comment by noah-aviel-dove** [comment]
The second error is expected following the failed reservation creation.

**Comment by noah-aviel-dove** [comment]
There is no `dcp1` catalog in my deployment. I can't reproduce the error if I replace `dcp1` with `dcp2`.

**Comment by noah-aviel-dove** [comment]
On subsequent attempts I am seeing a lot of latency and even 503 errors coming from the BigQuery reservation API.

**Comment by hannes-ucsc** [comment]
The 503s maybe masking the reproduction. From yesterday's demo I think that we need to make this code more resilient by making it idempotent and by making it produce the same state of commitment/, reservation and assignment that one would get if one were to buy the slots interactively on the console. IIRC, that is a two step process: purchase the slots and change the default reservation to 100.

**Comment by hannes-ucsc** [comment]
I'm deprioritizing this. We need to focus on the oversight demo.
