### ISSUE TITLE
Scheduled pipeline in GitLab `sell_unused_slots` is failing

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3021]
The scheduled pipeline has been failing since 04/27/21 15:03 PDT

[Most recent job fail](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/18949)

```
$ python3 scripts/sell_unused_slots.py
Traceback (most recent call last):
  File "scripts/sell_unused_slots.py", line 158, in <module>
    main(sys.argv[1:])
  File "scripts/sell_unused_slots.py", line 147, in main
    slot_manager = SlotManager(dry_run=args.dry_run)
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 49, in __init__
    self.refresh()
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 59, in refresh
    setattr(self, f'{resource_type}_name', self._single_resource_name(pager))
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 140, in _single_resource_name
    require(not extras,
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1084, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1099, in reject
    raise exception(*args)
azul.RequirementError: ('Too many resources in path (should be 0 or 1)', 'projects/platform-hca-dev/locations/US', ['projects/platform-hca-dev/locations/US/capacityCommitments/12498976798487925936', 'projects/platform-hca-dev/locations/US/capacityCommitments/9816896044436880723'])
```

**Comment by melainalegaspi** [comment]
@noah-aviel-dove spike to evaluate if we can fix this in the Google Cloud console.

**Comment by noah-aviel-dove** [comment]
It has been fixed via the google cloud console. 
```
c$ python3 scripts/sell_unused_slots.py 
2021-04-28 11:50:07,448 INFO    MainThread: Found credentials in environment variables.
2021-04-28 11:50:09,073 INFO    MainThread: No slots are currently reserved.
```

**Comment by hannes-ucsc** [comment]
The work for #3013 should prevent manually purchased and assigned slots from interfering with the scheduled selling of unused slots.
