### ISSUE TITLE
Three subgraphs in prod dcp5 lack `donor_organism.genus_species`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3041]
… in project `e5d45579-1f5b-48c3-b568-320d93e7ca72`, short name `CD4_T_cells_in_brain`.

This is the first time someone actually omitted the optional `genus_species` property from a `donor_organism` entity. Azul and the metadata API depend on that property. Two years ago, I've opened a ticket requesting to make that property mandatory:

https://github.com/HumanCellAtlas/metadata-schema/issues/999

There was tentative agreement but no subsequent activity on implementing it. The ticket is in the "icebox". It was only a matter of time before a wrangler/submitter unintentionally fell into that trap.

The log message for one of the subgraphs:

```
[WARNING] 2021-05-05T05:07:25.384Z 2a4ff606-96f3-5bb1-82d9-af0abcce7c9b Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '8ab15f7b-ec0f-433a-b6fb-28cbe0fb8dc3', 'name': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210504_dcp5:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '1102764b-eb59-48ea-a391-afb7324a1093', 'match': {'bundle_uuid': 'e24356b6-baca-40b1-b160-f5eb12b9f05b', 'bundle_version': '2021-03-30T13:43:53.291000Z'}}, 'catalog': 'dcp5'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 180, in transform
return self.index_service.transform(catalog, bundle, delete)
File "/var/task/azul/indexer/index_service.py", line 173, in transform
transformer: Transformer = transformer_cls.create(bundle, deleted=delete)
File "/var/task/azul/plugins/metadata/hca/transform.py", line 383, in create
return cls(bundle, deleted)
File "/var/task/azul/plugins/metadata/hca/transform.py", line 389, in __init__
self.api_bundle = api.Bundle(uuid=bundle.uuid,
File "/opt/python/humancellatlas/data/metadata/api.py", line 947, in __init__
self.biomaterials = from_json_vx(Biomaterial)
File "/opt/python/humancellatlas/data/metadata/api.py", line 944, in from_json_vx
return from_json(core_cls, json_entities, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 911, in from_json
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 911, in <dictcomp>
return {entity.document_id: entity for entity in entities}
File "/opt/python/humancellatlas/data/metadata/api.py", line 908, in <genexpr>
core_cls.from_json(entity, manifest_entry, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 106, in from_json
return sub_cls(json, metadata_manifest_entry, **kwargs)
File "/opt/python/humancellatlas/data/metadata/api.py", line 350, in __init__
self.genus_species = {ontology_label(gs) for gs in content['genus_species']}
KeyError: 'genus_species'
```

The fail queue:

```json
{
    "queue": "https://queue.amazonaws.com/542754589326/azul-notifications_fail-prod",
    "messages": [
        {
            "MessageId": "884a55fd-48ea-4530-9a5d-43f5deaf04c9",
            "ReceiptHandle": "AQEBjEy2E/giXIuIQ0mLDZb4oim7BDkUfJmLIQiEz2AVl9pDbQRH1L/FzJdNCUd6Lgwn82ZrenEr2HWM2gJG1Rb2kDPoY/h3jKipJabV+1vyEgx48ejqC9iYMNXAVeB4jMBVJjTT9wnu4BY7zO0Auw00/UczKfsAWs8GjbtT1Tb2ac+Pvwz+0MZ0GF05s1Ku/yAQm6udzxPhqreAqXMIbiWZFLaorkjPMIVMYn+JN4aYl3t5EYXJlsTmGT0AFHkEHNs8wOOdWe7eYkUJdFi2+ftWqrMIwIYMIw8l84zaTwyQXZCVOmymRLa128f6sUatZwvKYoRAquBwxVzTAJTC0mZRoCXF0HMuf3kXq3BWoiboeafrBIxFTkzUjGQ7ys5yvk1t4cQa3Tmqi1gpZD7h1/Wxq62OcuFbKxNdPUwsVZLdkX8=",
            "MD5OfBody": "ab0a6d7165e59caa4c0b94574398adf6",
            "Body": {
                "action": "add",
                "notification": {
                    "source": {
                        "id": "8ab15f7b-ec0f-433a-b6fb-28cbe0fb8dc3",
                        "name": "tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210504_dcp5:"
                    },
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "4d4d9932-f64b-47c9-ab80-93f67642e208",
                    "match": {
                        "bundle_uuid": "72b0eedb-3264-4cc7-a37e-62ec2751af96",
                        "bundle_version": "2021-03-30T13:43:53.249000Z"
                    }
                },
                "catalog": "dcp5"
            },
            "Attributes": {
                "SenderId": "AROAX4XVRZKHHXD45CIX7:azul-indexer-prod-contribute",
                "ApproximateFirstReceiveTimestamp": "1620176210251",
                "ApproximateReceiveCount": "12",
                "SentTimestamp": "1620176210251"
            },
            "_Attributes": {
                "SentTimestamp": "2021-05-04T17:56:50.251000-07:00",
                "ApproximateFirstReceiveTimestamp": "2021-05-04T17:56:50.251000-07:00"
            }
        },
        {
            "MessageId": "761bf9c0-f29b-41fa-bc17-c711e3a6d61f",
            "ReceiptHandle": "AQEBrJtHPoIzB/GPSyQMeD7X3VOpQ40h7llU9+elVVR1TRDbcrlcMg6gWVJL2Ck8k41bZbLHDCHeL0Kams3CYvJ2xfvpTGx5kS/eLvHKyEFjpk9btJTIHXGFAXLOnnhqBbqckb75fIaj1YJaQraEkXUc2lpm9g4h8rfJsgQheh6qRINoIJn2BZO+UNCBbU8Akx0NdgfTSEmA9oPUE+/EyH8SJu9WTX8nXvMHKjVRmoOig7M+U5mpbTMuEvsE33wvM6eDWmR0vqOVNOMhIFMIML37FgLKUedKKwlKUsZgAFzowK4KFikopsCQfMMQK2ylDbIGkDEfbuE8q5s5kuzRVtOtE8/lDs11t1IUO8A2oSC3Em8sPscu3Z3qEfFR3OhJXIZrcLlluIV30QEUxQVtfheGruuaqDdIuvex0g9xL4ZQxfA=",
            "MD5OfBody": "3eb2b557e860dcbebb7c7e3d2c5cbdee",
            "Body": {
                "action": "add",
                "notification": {
                    "source": {
                        "id": "8ab15f7b-ec0f-433a-b6fb-28cbe0fb8dc3",
                        "name": "tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210504_dcp5:"
                    },
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "1102764b-eb59-48ea-a391-afb7324a1093",
                    "match": {
                        "bundle_uuid": "e24356b6-baca-40b1-b160-f5eb12b9f05b",
                        "bundle_version": "2021-03-30T13:43:53.291000Z"
                    }
                },
                "catalog": "dcp5"
            },
            "Attributes": {
                "SenderId": "AROAX4XVRZKHHXD45CIX7:azul-indexer-prod-contribute",
                "ApproximateFirstReceiveTimestamp": "1620176236377",
                "ApproximateReceiveCount": "12",
                "SentTimestamp": "1620176236377"
            },
            "_Attributes": {
                "SentTimestamp": "2021-05-04T17:57:16.377000-07:00",
                "ApproximateFirstReceiveTimestamp": "2021-05-04T17:57:16.377000-07:00"
            }
        },
        {
            "MessageId": "82a88500-ee5f-4c97-9ed6-00843f914d1a",
            "ReceiptHandle": "AQEBGi2UGi9FbGaTC0aCWkYku4eVlpTMo0lPz0nSu2msdNTze5R27pCvogIR6ToFaQtPWRjoggPCow4c0DHd2VMoLeLZq24vWQNkye97TTv7r03r3ba51gl0O8ykJpawKqLh8SuuXq0DYFdBjwthDvrMsD+3EgMAEoeusbcPjtX14pFDPgInYGmCRyyUcItR5iec1ZmxuWZ7IpM5LS/9admNsWwfBRwzzWsA1COPssYBiosikzrlFs9YgfQgkYcNKJk/UtqYTtYqSyJ3puRBCbkQ8SgN07QJx0KirByCeqr0EN5KPS2Fva5Bh3tDuVXO7plybZQ9oBE6O6pfg9b+JUQe/4Wv0wxKiuQdIdCw7QgKiZ2l9br/cCDtY3t5HqPOcMuK+C9WgRdZoqej46a+NuE0EPCwplpJ5WEG5OqiZZY4rBg=",
            "MD5OfBody": "6f3011e1386228fd2089d0531470ab1d",
            "Body": {
                "action": "add",
                "notification": {
                    "source": {
                        "id": "8ab15f7b-ec0f-433a-b6fb-28cbe0fb8dc3",
                        "name": "tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210504_dcp5:"
                    },
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "a845fc43-639c-4b46-b74c-c4dfe7ad019e",
                    "match": {
                        "bundle_uuid": "b2904469-c241-4fb3-98ba-bff982cf7e1e",
                        "bundle_version": "2021-03-30T13:43:53.263000Z"
                    }
                },
                "catalog": "dcp5"
            },
            "Attributes": {
                "SenderId": "AROAX4XVRZKHHXD45CIX7:azul-indexer-prod-contribute",
                "ApproximateFirstReceiveTimestamp": "1620176207727",
                "ApproximateReceiveCount": "11",
                "SentTimestamp": "1620176207727"
            },
            "_Attributes": {
                "SentTimestamp": "2021-05-04T17:56:47.727000-07:00",
                "ApproximateFirstReceiveTimestamp": "2021-05-04T17:56:47.727000-07:00"
            }
        }
    ]
}
```

One of the donor_organism entities:

```
{
    "describedBy": "https://schema.humancellatlas.org/type/biomaterial/15.5.0/donor_organism",
    "schema_type": "biomaterial",
    "biomaterial_core": {
        "biomaterial_id": "adult_wt1_mouse",
        "biomaterial_description": "Adult wild-type mouse.",
        "ncbi_taxon_id": [
            10090
        ]
    },
    "sex": "unknown",
    "is_living": "no",
    "development_stage": {
        "text": "adult",
        "ontology": "EFO:0001272",
        "ontology_label": "adult"
    },
    "provenance": {
        "document_id": "1a5489a2-18b6-4712-84f9-2ef8b5ff509b",
        "submission_date": "2021-03-30T13:43:51.862Z",
        "update_date": "2021-03-30T13:43:55.539Z",
        "schema_major_version": 15,
        "schema_minor_version": 5
    }
}
```

**Comment by theathorn** [comment]
Freebie of #3075.

**Comment by hannes-ucsc** [comment]
This is not a freebie of #3075. This is an issue with a `prod` snapshot while #3075 is about a `dev` snapshot. This still happens in `prod` for dcp5 but is fixed in dcp6. We can close this when the `dcp5` catalog is removed.

**Comment by theathorn** [comment]
Obsoleted by #3085.
