### ISSUE TITLE
Running unit tests separately trips warnings assertion

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3060]
```
$ (cd test; python -m unittest service.test_response.TestListCatalogsResponse)
... snip mo stuff  ...
======================================================================
ERROR: tearDownClass (service.test_response.TestListCatalogsResponse)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hannes/workspace/hca/azul/test/app_test_case.py", line 90, in tearDownClass
    super().tearDownClass()
  File "/home/hannes/workspace/hca/azul/test/azul_test_case.py", line 154, in tearDownClass
    super().tearDownClass()
  File "/home/hannes/workspace/hca/azul/test/azul_test_case.py", line 92, in tearDownClass
    assert not caught_warnings, list(map(str, caught_warnings))
AssertionError: ['{message : DeprecationWarning("the imp module is deprecated in favour of importlib; see the module\'s documentation for alternative uses"), category : \'DeprecationWarning\', filename : \'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/boto/plugin.py\', lineno : 40, line : None}', '{message : ResourceWarning("unclosed file <_io.TextIOWrapper name=\'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/moto/ec2/resources/instance_types.json\' mode=\'r\' encoding=\'UTF-8\'>"), category : \'ResourceWarning\', filename : \'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/moto/ec2/models.py\', lineno : 137, line : None}', '{message : ResourceWarning("unclosed file <_io.TextIOWrapper name=\'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/moto/ec2/resources/amis.json\' mode=\'r\' encoding=\'UTF-8\'>"), category : \'ResourceWarning\', filename : \'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/moto/ec2/models.py\', lineno : 140, line : None}', '{message : DeprecationWarning("Using or importing the ABCs from \'collections\' instead of from \'collections.abc\' is deprecated since Python 3.3, and in 3.9 it will stop working"), category : \'DeprecationWarning\', filename : \'/home/hannes/workspace/hca/azul/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py\', lineno : 367, line : None}']

----------------------------------------------------------------------
Ran 1 test in 1.883s

FAILED (errors=1)
```

**Comment by hannes-ucsc** [comment]
Same happens when running test in PyCharm.

This raises the question as to why `make test` on CI does not trip the assertion. My current hypothesis is that these warnings are side effects of module loading and that `make test` coincidentally runs the tests in an order that causes these modules to be loaded **outside** the `catchwarnings` CM that `AzulTestCase` sets up.

**Comment by theathorn** [comment]
Spike to come up with an idea.

**Comment by amarjandu** [comment]
Have to checkout `76eb7a8f01300af9e406a31088fc057975673165` to replicate failures.
Dependencies might have been updated from #1718

**Comment by amarjandu** [comment]
Another failure was found in `test/service/test_app_logging.py`, however this one is not able to be replicated in the terminal, can only be replicated in PyCharm.

```
(.venv) CBSEspecter:azul amar$ (cd test && python -m unittest service.test_app_logging.TestServiceAppLogging )
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 11:58:02,496 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 11:58:02,497 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 11:58:02,497 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 11:58:02,497 DEBUG   MainThread: Clearing cache of 'resource'
Serving on http://localhost:0
2021-05-27 11:58:08,772 INFO    Thread-2: Received GET request for '/health/basic', with query null and headers {"host": "127.0.0.1:59545", "user-agent": "python-requests/2.22.0", "accept-encoding": "gzip, deflate", "accept": "*/*", "connection": "keep-alive"}.
2021-05-27 11:58:08,772 INFO    Thread-2: Did not authenticate request.
2021-05-27 11:58:08,773 DEBUG   Thread-2: Returning 200 response with headers {}. See next line for the first 1024 characters of the body.
{"up": true}
127.0.0.1 - - [27/May/2021 11:58:08] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:58:08] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:58:08] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:58:08] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:58:08] "GET /health/basic HTTP/1.1" 200 -
.2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 11:58:09,292 DEBUG   MainThread: Clearing cache of 'resource'

----------------------------------------------------------------------
Ran 1 test in 6.801s

OK
(.venv) CBSEspecter:azul amar$ (cd test && python -m unittest /Users/amar/dev/hca/azul/test/service/test_app_logging.py)
2021-05-27 11:58:57,297 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 11:58:57,297 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 11:58:57,298 DEBUG   MainThread: Clearing cache of 'resource'
Serving on http://localhost:0
2021-05-27 11:59:03,491 INFO    Thread-2: Received GET request for '/health/basic', with query null and headers {"host": "127.0.0.1:59556", "user-agent": "python-requests/2.22.0", "accept-encoding": "gzip, deflate", "accept": "*/*", "connection": "keep-alive"}.
2021-05-27 11:59:03,491 INFO    Thread-2: Did not authenticate request.
2021-05-27 11:59:03,491 DEBUG   Thread-2: Returning 200 response with headers {}. See next line for the first 1024 characters of the body.
{"up": true}
127.0.0.1 - - [27/May/2021 11:59:03] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:59:03] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:59:03] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:59:03] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 11:59:03] "GET /health/basic HTTP/1.1" 200 -
.2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 11:59:03,506 DEBUG   MainThread: Clearing cache of 'resource'

----------------------------------------------------------------------
Ran 1 test in 6.213s

OK
```

**Comment by amarjandu** [comment]
```
(.venv) CBSEspecter:azul amar$ coverage run -m unittest discover

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Coverage.py warning: No data was collected. (no-data-collected)
(.venv) CBSEspecter:azul amar$ PYTHONWARNINGS=always coverage run -m unittest discover
/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/botocore/awsrequest.py:624: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class HeadersDict(collections.MutableMapping):

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Coverage.py warning: No data was collected. (no-data-collected)
```

Strange that a deprecation warning was emitted although no tests were ran, these warnings appear to be emitted but not printed to the screen.

**Comment by amarjandu** [comment]
Able to replicate the newly found warning:
```
(.venv) CBSEspecter:azul amar$ (cd test && PYTHONWARNINGS=always python -m unittest /Users/amar/dev/hca/azul/test/service/test_app_logging.py)
/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/tweak/__init__.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class Config(collections.MutableMapping):
/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/tenacity/_asyncio.py:37: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def call(self, fn, *args, **kwargs):
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 17:10:25,761 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 17:10:25,762 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 17:10:25,762 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 17:10:25,762 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 17:10:25,762 DEBUG   MainThread: Clearing cache of 'resource'
Serving on http://localhost:0
2021-05-27 17:10:32,335 INFO    Thread-2: Received GET request for '/health/basic', with query null and headers {"host": "127.0.0.1:62839", "user-agent": "python-requests/2.22.0", "accept-encoding": "gzip, deflate", "accept": "*/*", "connection": "keep-alive"}.
2021-05-27 17:10:32,335 INFO    Thread-2: Did not authenticate request.
2021-05-27 17:10:32,335 DEBUG   Thread-2: Returning 200 response with headers {}. See next line for the first 1024 characters of the body.
{"up": true}
127.0.0.1 - - [27/May/2021 17:10:32] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 17:10:32] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 17:10:32] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 17:10:32] "GET /health/basic HTTP/1.1" 200 -
127.0.0.1 - - [27/May/2021 17:10:32] "GET /health/basic HTTP/1.1" 200 -
.2021-05-27 17:10:32,852 DEBUG   MainThread: Clearing cache of '_dss_bucket'
2021-05-27 17:10:32,852 DEBUG   MainThread: Clearing cache of '_es_domain_status'
2021-05-27 17:10:32,852 DEBUG   MainThread: Clearing cache of '_service_account_creds'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'client'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'get_hmac_key_and_id_cached'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'permissions_boundary'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'permissions_boundary_arn'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'permissions_boundary_tf'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'region_name'
2021-05-27 17:10:32,853 DEBUG   MainThread: Clearing cache of 'resource'

----------------------------------------------------------------------
Ran 1 test in 7.097s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>
```

**Comment by amarjandu** [comment]
It appears that `unittest discovery` will trigger warnings when loading the tests
(see caution section https://docs.python.org/3/library/unittest.html#test-discovery)

Because the warnings module only emits the warnings once (default setting), and this is done during discovery not when the tests are running, we can get inconsistent reporting of a warning. (https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS)

It's strange that there are no warnings emitted when the unittest discovery is loading tests, they might be silently ignored during the load phase. Deprecation warnings seem to not be working as https://github.com/python/cpython/blob/ee7637596d8de25f54261bbeabc602d31e74f482/Lib/unittest/main.py#L85 

It appears that some DeprecationWarnings are also raised by the `envhook` which PyCharm is using, this can be seen when running `service.test_response.TestListCatalogsResponse` with `PYTHONWARNINGS=always` set in the env.
