### ISSUE TITLE
Build does not detect invalid values in MetadataPlugin.field_mapping

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3071]
It's possible to deploy with an invalid translation value in ServiceConfig, the issue with the value will not be known until a client attempts to use the translation key in a request.

```
http 'https://service.amar.dev.singlecell.gi.ucsc.edu/index/files?catalog=dcp2&sort=sourceSpec'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 490
Content-Type: text/plain
Date: Mon, 24 May 2021 15:29:08 GMT
Via: 1.1 6d77342eb60c8ea96903996368766612.cloudfront.net (CloudFront)
X-Amz-Cf-Id: FWDOBsYtNy9RikDL9yQSFq2OUC8EPv2mCrMOwyct2WyxSbpALDWaXw==
X-Amz-Cf-Pop: SFO53-C1
X-Amzn-Trace-Id: Root=1-60abc644-63f531ae22d49499100e2f58;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: f1vqvHNIoAMFSnw=
x-amzn-RequestId: 6a4c416b-e348-45d3-8e30-da29e9bc826d

Traceback (most recent call last):
  File "/var/task/azul/indexer/document_service.py", line 70, in field_type
    field_types = field_types[p]
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1136, in get_data
    return repository_search('files', file_id)
  File "/var/task/app.py", line 897, in repository_search
    return service.get_data(catalog=catalog,
  File "/var/task/azul/service/index_query_service.py", line 67, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 602, in transform_request
    es_search = self._apply_paging(catalog, es_search, pagination)
  File "/var/task/azul/service/elasticsearch_service.py", line 371, in _apply_paging
    field_type = self.field_type(catalog, tuple(pagination['sort'].split('.')))
  File "/var/task/azul/indexer/document_service.py", line 72, in field_type
    raise type(e)('Path not represented in field_types', path)
KeyError: ('Path not represented in field_types', ('sources', 'name'))
```

Raised from https://github.com/DataBiosphere/azul/pull/3047#discussion_r636464552

**Comment by hannes-ucsc** [comment]
Lacks concrete steps to reproduce.
