### ISSUE TITLE
Swagger UI breaks if AZUL_GOOGLE_OAUTH2_CLIENT_ID is not set

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3088]
I forgot to follow the upgrade instructions for #2951 and that broke the Swagger UI page of my deployment and was detected during the IT only.

```
$ http 'https://service.hannes.dev.singlecell.gi.ucsc.edu/'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 314
Content-Type: text/plain
Date: Fri, 28 May 2021 16:38:41 GMT
Via: 1.1 f1f23e31a920ab1b12fcfa84d5ce673e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: es9MwNiH9RqO_XUhC15zGZQNW9E7-joDHhFTR-Sy7jPcjxqAkl8yFA==
X-Amz-Cf-Pop: LAX3-C3
X-Amzn-Trace-Id: Root=1-60b11c91-3cd48a000d5da83c06bda859;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: ADFmuGNhIAMFexg=
x-amzn-RequestId: e457c284-3b89-46d4-837e-037105899f9f

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 453, in swagger_ui
    'OAUTH2_CLIENT_ID': config.google_oauth2_client_id,
  File "/var/task/azul/__init__.py", line 817, in google_oauth2_client_id
    return os.environ['AZUL_GOOGLE_OAUTH2_CLIENT_ID']
  File "/var/lang/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AZUL_GOOGLE_OAUTH2_CLIENT_ID'
```

**Comment by hannes-ucsc** [comment]
@danielsotirhos foresaw issues with this during the review of the PR but it wasn't acted on:

https://github.com/DataBiosphere/azul/pull/2999#discussion_r622417850

**Comment by hannes-ucsc** [comment]
Since we will not be able to enforce any authentication in production until we've gained NIST-800 compliance and have a peering agreement with Broad, we should make the variable optional and enable/disable OAuth 2.0 authentication. Once we have compliance and peering, #2978 will prevent us from accidentally leaking access controlled metadata to anonymous users if authentication is disabled by unsetting AZUL_GOOGLE_OAUTH2_CLIENT_ID.

**Comment by hannes-ucsc** [comment]
For demo, show the effect of toggling `AZUL_GOOGLE_OAUTH2_CLIENT_ID` between set and unset in a personal deployment.
