### ISSUE TITLE
Swagger UI is broken on `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3090]
```
$ http 'https://service.azul.data.humancellatlas.org/'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 533
Content-Type: text/plain
Date: Fri, 28 May 2021 16:49:23 GMT
Via: 1.1 8bea8b04906ba221e865eddf4b64cf2f.cloudfront.net (CloudFront)
X-Amz-Cf-Id: YBOPmQk4G5X1qlpvs79nNIZT46oF7Kn-FLbOJM1rRorThci7rt96QQ==
X-Amz-Cf-Pop: LAX3-C4
X-Amzn-Trace-Id: Root=1-60b11f13-620adf800f2713643e243e19;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: ADHLAGz4IAMFxGA=
x-amzn-RequestId: 922e8094-49a3-48e4-bd57-c1a58cdae250

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 453, in swagger_ui
    'OAUTH2_CLIENT_ID': config.google_oauth2_client_id,
  File "/var/task/azul/__init__.py", line 821, in google_oauth2_client_id
    return os.environ['AZUL_GOOGLE_OAUTH2_CLIENT_ID']
  File "/var/lang/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AZUL_GOOGLE_OAUTH2_CLIENT_ID'
```

Related to https://github.com/DataBiosphere/azul/issues/3088

Also causes IT to fail

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/2831

**Comment by hannes-ucsc** [comment]
Set the variable in `deployments/prod/environment.py` to `473200283737-h5e1l7neunbuesrtgjf8b12lb7o3jf1m.apps.googleusercontent.com` and add a FIXME referring to #3088 to unset it again.

**Comment by hannes-ucsc** [comment]
To work around this, I manually set the variable on the `azul-service-prod` lambda function. Until this ticket lands in `prod`, the workaround will be need to be performed after every deployment to `prod`.
