### ISSUE TITLE
Colliding module names cause incorrect modules to be loaded

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3133]
Naming a module in `src/azul` that has been also defined in the python library https://github.com/python/cpython/tree/main/Lib can cause the wrong module to be loaded at runtime.

This was observed in https://github.com/DataBiosphere/azul/pull/3109 when attempting to `import json` within the `src/azul/__init__.py` file. 

```
Failure
Traceback (most recent call last):
  File "/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/Users/amar/dev/hca/azul/test/indexer/__init__.py", line 107, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/es_test_case.py", line 38, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/app_test_case.py", line 81, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 147, in setUpClass
    cls._mock_catalogs()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 197, in _mock_catalogs
    assert config.default_catalog == cls.catalog
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 538, in default_catalog
    return first(self.catalogs)
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 529, in catalogs
    for catalog_spec in json.loads(os.environ['AZUL_CATALOGS']):
AttributeError: module 'azul.json' has no attribute 'loads'
```

See the patch below for a replication with another stdlib module `email`, it behaves in the same way. 

```
Index: src/azul/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/__init__.py b/src/azul/__init__.py
--- a/src/azul/__init__.py	(revision e16b47004d196a551c8ff0591be70be16c172c94)
+++ b/src/azul/__init__.py	(date 1623438319612)
@@ -1,3 +1,5 @@
+import email
+print(email.__file__)
 import functools
 import logging
 import os
@@ -525,6 +527,8 @@
         package name.
         """
         catalogs = os.environ['AZUL_CATALOGS'].split(',')
+        print(email.__file__)
+        foo = email.message_from_string('foo')
         catalogs = {
             catalog: self.Catalog(
                 name=catalog,
Index: src/azul/chalice.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/chalice.py b/src/azul/chalice.py
--- a/src/azul/chalice.py	(revision e16b47004d196a551c8ff0591be70be16c172c94)
+++ b/src/azul/chalice.py	(date 1623437405543)
@@ -35,6 +35,9 @@
     LambdaContext,
     MutableJSON,
 )
+from azul.email import (
+    foo,
+)
 
 log = logging.getLogger(__name__)
 
Index: src/azul/email.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/email.py b/src/azul/email.py
new file mode 100644
--- /dev/null	(date 1623361145593)
+++ b/src/azul/email.py	(date 1623361145593)
@@ -0,0 +1,5 @@
+import email
+
+
+def foo():
+    print(email.message_from_string('s'))
```

Failure seen below.

```
Launching unittests with arguments python -m unittest test_request_validation.RequestParameterValidationTest in /Users/amar/dev/hca/azul/test/service

/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/email/__init__.py
/Users/amar/dev/hca/azul/src/azul/email.py


Ran 0 tests in 0.014s

FAILED (errors=1)

Failure
Traceback (most recent call last):
  File "/Users/amar/.pyenv/versions/3.8.3/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp
    setUpClass()
  File "/Users/amar/dev/hca/azul/test/indexer/__init__.py", line 107, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/es_test_case.py", line 38, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/app_test_case.py", line 81, in setUpClass
    super().setUpClass()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 146, in setUpClass
    cls._mock_catalogs()
  File "/Users/amar/dev/hca/azul/test/azul_test_case.py", line 192, in _mock_catalogs
    assert config.default_catalog == cls.catalog
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 550, in default_catalog
    return first(self.catalogs)
  File "/Users/amar/dev/hca/azul/.venv/lib/python3.8/site-packages/boltons/cacheutils.py", line 610, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 531, in catalogs
    foo = email.message_from_string('foo')
AttributeError: module 'azul.email' has no attribute 'message_from_string'
```

It can be seen from the error output that during module imports in the `__init__.py` file the email module is in reference to the stdlib, but at runtime this changes to the `azul.email` module.

**Comment by amarjandu** [comment]
Some suggestions have been raised to address this issue, either:
 
1. Rename all colliding module names in `src/azul`
2. Move classes that require the use of stdlib modules out of the `src/azul/__init__.py`

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to reproduce.

**Comment by hannes-ucsc** [comment]
This all boils down to the fact that importing `src/azul/foo.py` via `import azul.foo` or `from azul.foo import bar` makes an entry called `foo` in the `azul` module. If that entry is initialized to point to `foo` from the runtime library when `src/azul/__init__.py` is loaded, it is then *overwritten* to point to `src/azul/foo.py` instead. This can cause an array of issues, some obvious, some more subtle.

The statement `from azul import foo` does *not* overwrite the module reference if `azul` already defines a `foo` entry. If it doesn't, the statement will load `src/azul/foo.py` and add an `foo` entry to the `azul` module.

So—keeping in mind that `src/azul/__init__.py` contains `import logging`—the overwrite occurs here

![image](https://user-images.githubusercontent.com/5143256/137820520-1f6886e4-2b67-40b5-b5e6-e53792b16ed0.png)

but does not occur here

![image](https://user-images.githubusercontent.com/5143256/137820685-b603e2c4-8769-45c6-99f3-6a9d0e67d233.png)

However, when an entry doesn't exist, one is added, pointing to the module.

![image](https://user-images.githubusercontent.com/5143256/137820864-3982435c-babd-4644-a29b-0f9567682b45.png)

**Comment by melainalegaspi** [comment]
Moving to Debt due to assignee being overloaded.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce with `email` and `azul.email` as in the OP's example.
