### ISSUE TITLE
`make sam` fails due to ambiguous response from TDR

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3193]
Running `make sam` should reproduce this in the `dev` deployment.

If we modifying the exception to show the failed response 
```
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 9506935d1a65b9aa57bdc9621212ca4bff4b5c7d)
+++ b/src/azul/terra.py	(date 1625166603557)
@@ -279,7 +279,7 @@
                         f'Failed to access {resource} after resolving its ID to {snapshot_id!r}')
                 return json.loads(response.data)
             else:
-                raise RequirementError('Ambiguous response from TDR API', endpoint)
+                raise RequirementError('Ambiguous response from TDR API', endpoint, response)
         elif response.status == 401:
             raise self._insufficient_access(endpoint)
         else:
```

we get:
```
$ make sam 
python /home/jesse/gi/azul.operator/scripts/register_sam.py
2021-07-01 12:17:26,595 INFO    MainThread: Found credentials in shared credentials file: ~/.aws/credentials
2021-07-01 12:17:27,223 DEBUG   MainThread: _request('POST', 'https://sam.dsde-dev.broadinstitute.org/register/user/v1', fields=None, headers={'Authorization': 'Bearer ya29.c.KqIBBgj3j1ryJsghVPS0jO_p0AiuiBtBixBwrwo6SKHUzfCg-mF5cfGsiVaBsSQo5jB7BOjeguMRLwA6oyA8iCBg8wEfPHivVIzu-DfW6YJomYlKD2CGO7aexrM9-wu3dktskI0-U_qaTl9Lwr32S1OhM7hqEZWszLLZuv9ZEbR3Rt8yNS3WGaqPHGGgSxYhc2tgPBf0wxM5LjgeyAtWr2Bb2oee'}, body='')
2021-07-01 12:17:27,716 DEBUG   MainThread: _request(…) -> b'{"causes":[],"message":"user CreateWorkbenchUser(2625167047538e4f17b0e,114747665175892263081,azul-ucsc-0-sandbox@platform-hca-dev.iam.gserviceaccount.com,None) already exists","source":"sam","stackTrace":[],"statusCode":409}'
2021-07-01 12:17:27,717 INFO    MainThread: Google service account previously registered with SAM.
2021-07-01 12:17:27,719 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'filter': 'hca_dev_20201023_ebiv4___20210302', 'limit': '2'}, headers=None, body=None)
2021-07-01 12:17:28,041 DEBUG   MainThread: _request(…) -> b'{"total":23,"filteredTotal":1,"items":[{"id":"c5cfdcda-995d-4f6e-94b7-e0532f6d83ca","name":"hca_dev_20201023_ebiv4___20210302","description":"Create snapshot hca_dev_20201023_ebiv4___20210302","createdDate":"2021-03-03T22:26:15.120177Z","profileId":"390...'
Traceback (most recent call last):
  File "/home/jesse/gi/azul.operator/scripts/register_sam.py", line 43, in <module>
    main()
  File "/home/jesse/gi/azul.operator/scripts/register_sam.py", line 33, in main
    api_project = tdr.lookup_source_project(source)
  File "/home/jesse/gi/azul.operator/src/azul/terra.py", line 246, in lookup_source_project
    return self._lookup_source(source)['dataProject']
  File "/home/jesse/gi/azul.operator/src/azul/terra.py", line 282, in _lookup_source
    raise RequirementError('Ambiguous response from TDR API', endpoint, response)
azul.RequirementError: ('Ambiguous response from TDR API', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', {'total': 23, 'filteredTotal': 1, 'items': [{'id': 'c5cfdcda-995d-4f6e-94b7-e0532f6d83ca', 'name': 'hca_dev_20201023_ebiv4___20210302', 'description': 'Create snapshot hca_dev_20201023_ebiv4___20210302', 'createdDate': '2021-03-03T22:26:15.120177Z', 'profileId': '390e7a85-d47f-4531-b612-165fc977d3bd', 'storage': [{'region': 'us', 'cloudResource': 'bigquery', 'cloudPlatform': 'gcp'}, {'region': 'us-central1', 'cloudResource': 'bucket', 'cloudPlatform': 'gcp'}, {'region': 'us-central1', 'cloudResource': 'firestore', 'cloudPlatform': 'gcp'}]}]})
make: *** [Makefile:91: sam] Error 1
```

Here's the response, formatted nicely:
```
{
    "total": 23,
    "filteredTotal": 1,
    "items": [
        {
            "id": "c5cfdcda-995d-4f6e-94b7-e0532f6d83ca",
            "name": "hca_dev_20201023_ebiv4___20210302",
            "description": "Create snapshot hca_dev_20201023_ebiv4___20210302",
            "createdDate": "2021-03-03T22:26:15.120177Z",
            "profileId": "390e7a85-d47f-4531-b612-165fc977d3bd",
            "storage": [
                {
                    "region": "us",
                    "cloudResource": "bigquery",
                    "cloudPlatform": "gcp"
                },
                {
                    "region": "us-central1",
                    "cloudResource": "bucket",
                    "cloudPlatform": "gcp"
                },
                {
                    "region": "us-central1",
                    "cloudResource": "firestore",
                    "cloudPlatform": "gcp"
                }
            ]
        }
    ]
}
```
`

**Comment by jessebrennan** [comment]
We probably just need to replace 'total' with 'filteredTotal'.
