### ISSUE TITLE
can_bundle.py fails with `No repository using this source`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3201]
```
$ python scripts/can_bundle.py -s tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2__20210701_dcp7 -b 219162c9-a0e0-4716-9107-4be7e3aedb03 -v 2021-06-09T19:31:55.482000Z
Traceback (most recent call last):
  File "scripts/can_bundle.py", line 99, in <module>
    main(sys.argv[1:])
  File "scripts/can_bundle.py", line 63, in main
    bundle = fetch_bundle(args.source, args.uuid, args.version)
  File "scripts/can_bundle.py", line 80, in fetch_bundle
    raise ValueError('No repository using this source')
ValueError: No repository using this source

$ git log -1
commit ade732a6a70831f3bd4b3e2074eb945b613025c0 (HEAD -> prod, gitlab.dcp2.prod/prod, github/prod)
Merge: 8c7f2067 a377b00f
Author: jesse <brennan@ucsc.edu>
Date:   Fri Jul 2 16:26:59 2021 -0700

    [r] Add dcp7 on prod (#3197, PR #3198)
```

**Comment by hannes-ucsc** [comment]
Invalid, forgot to add final semicolon.
