### ISSUE TITLE
A sequence_file entity with file_source fails requirement check

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3202]
Affected subgraphs:

- `02e69c25-71e2-48ca-a87b-e256938c6a98`
- `39fdb0ae-9a00-4829-a581-e7cb59798f02`

```
[WARNING] 2021-07-03T06:50:53.305Z b99eb884-079c-54d6-b9f0-e1de0d7d6b0b Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '83752bf1-44fa-46d8-abec-0f5982e21cdd', 'spec': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2__20210701_dcp7:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'de3a701e-6da2-4154-83a1-8620d2e341da', 'match': {'bundle_uuid': '39fdb0ae-9a00-4829-a581-e7cb59798f02', 'bundle_version': '2021-06-28T14:21:18.691000Z'}}, 'catalog': 'dcp7'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 153, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 188, in transform
return self.index_service.transform(catalog, bundle, delete)
File "/var/task/azul/indexer/index_service.py", line 174, in transform
contributions.extend(transformer.transform())
File "/var/task/azul/plugins/metadata/hca/transform.py", line 1411, in transform
matrices=[
File "/var/task/azul/plugins/metadata/hca/transform.py", line 1414, in <listcomp>
if Submitter.category_for_file(file) == SubmitterCategory.internal
File "/var/task/azul/plugins/metadata/hca/transform.py", line 379, in category_for_file
require(isinstance(file, self.category.file_types), file, self)
File "/var/task/azul/__init__.py", line 1087, in require
reject(not condition, *args, exception=exception)
File "/var/task/azul/__init__.py", line 1102, in reject
raise exception(*args)
azul.RequirementError: (SequenceFile(document_id=UUID('6b94ce38-27b9-460e-ab1b-bceb18275c71'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='sequence_file_4.json', s3_etag=None, sha1=None, sha256='', size=629, url=None, uuid=UUID('6b94ce38-27b9-460e-ab1b-bceb18275c71'), version='2021-06-28T14:21:17.456000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.456Z', update_date='2021-06-28T14:25:27.696Z', format='fastq', to_processes={UUID('da317018-1b0b-4e4f-b508-2c1c7d049507'): Process(document_id=UUID('da317018-1b0b-4e4f-b508-2c1c7d049507'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/process"', crc32c='', indexed=True, name='process_11.json', s3_etag=None, sha1=None, sha256='', size=343, url=None, uuid=UUID('da317018-1b0b-4e4f-b508-2c1c7d049507'), version='2021-06-28T14:21:18.755000Z', is_stitched=False), submission_date='2021-06-28T14:21:18.755Z', update_date='2021-06-28T14:21:39.847Z', process_id='exp2', process_name=None, output_biomaterials={}, output_files={UUID('4d64269d-bd3f-46c1-a179-1c27e1caeb30'): AnalysisFile(document_id=UUID('4d64269d-bd3f-46c1-a179-1c27e1caeb30'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_1.json', s3_etag=None, sha1=None, sha256='', size=549, url=None, uuid=UUID('4d64269d-bd3f-46c1-a179-1c27e1caeb30'), version='2021-06-28T14:21:17.929000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.929Z', update_date='2021-06-28T14:22:59.879Z', format='mtx', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='55189345', indexed=False, name='experiment2_mouse_pbs_scp_matrix.mtx', s3_etag='738b071be0c056fe5cc01460b2908836-2', sha1='052478f56b3bafac30cc2dede1600633ac56e530', sha256='bff4eabd5df1ab167efc180791d7d189fc3c79f216450cffacab2cb763e3c171', size=87863503, url=None, uuid=UUID('9601aedb-6de9-4a32-8bd9-ed8b78b256e1'), version='2021-06-28T14:21:17.929000Z', is_stitched=False), content_description={'Gene expression matrix'}, file_source='SCP', matrix_cell_count=3402), UUID('6ccd1b16-d3a9-4ba4-9dda-99aa882dfc2c'): AnalysisFile(document_id=UUID('6ccd1b16-d3a9-4ba4-9dda-99aa882dfc2c'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_2.json', s3_etag=None, sha1=None, sha256='', size=509, url=None, uuid=UUID('6ccd1b16-d3a9-4ba4-9dda-99aa882dfc2c'), version='2021-06-28T14:21:17.941000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.941Z', update_date='2021-06-28T14:22:53.631Z', format='tsv', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='cb0ebb55', indexed=False, name='experiment2_mouse_pbs_scp_genes.tsv', s3_etag='cf3e64f665fe6159bdc5bf4321d4d8cb', sha1='4f3d433480449f70d9d3095e1ae9d93881eb9c7f', sha256='f49a568c569b330d7215fcf4a2bcf02d7aff08f8ab414a03059db859b9e3e054', size=547824, url=None, uuid=UUID('6b8fc3ff-4e32-4f2c-97ae-d634066f87db'), version='2021-06-28T14:21:17.941000Z', is_stitched=False), content_description={'Gene identifier'}, file_source='SCP', matrix_cell_count=None), UUID('004d18f2-f23c-4fd1-af2e-f0a6a9e13cc9'): AnalysisFile(document_id=UUID('004d18f2-f23c-4fd1-af2e-f0a6a9e13cc9'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_0.json', s3_etag=None, sha1=None, sha256='', size=482, url=None, uuid=UUID('004d18f2-f23c-4fd1-af2e-f0a6a9e13cc9'), version='2021-06-28T14:21:17.953000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.953Z', update_date='2021-06-28T14:22:53.630Z', format='tsv', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='f345df0c', indexed=False, name='experiment2_mouse_pbs_scp_barcodes.tsv', s3_etag='03a8156f979f3e0e9d88e26fcde6e2f5', sha1='d94027cbd01ca96ef5d926aa6b06f332c22e00f6', sha256='7313b430ea480a928fc42dcbe297a96e577a4b8def5acd500e5cf7aab7498285', size=57834, url=None, uuid=UUID('50d634ef-77b0-4339-a9c3-9a83bd9e5ab6'), version='2021-06-28T14:21:17.953000Z', is_stitched=False), content_description={'barcodes file'}, file_source='SCP', matrix_cell_count=3402), UUID('ad3f7b5e-77ed-4df1-a9af-5355f7951af4'): AnalysisFile(document_id=UUID('ad3f7b5e-77ed-4df1-a9af-5355f7951af4'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_3.json', s3_etag=None, sha1=None, sha256='', size=504, url=None, uuid=UUID('ad3f7b5e-77ed-4df1-a9af-5355f7951af4'), version='2021-06-28T14:21:17.965000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.965Z', update_date='2021-06-28T14:22:59.987Z', format='txt', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='b8c266c7', indexed=False, name='experiment2_mouse_pbs_scp_X_diffmap_pca_coords.txt', s3_etag='e3c262117b366ac8dd8f70f1ec836965', sha1='a50df977aac20684d2e3b27ac8a21feff8240a01', sha256='335d0e738c2b28ffea73c03c89a85d05d02dbdb6efc8769276533380d5916791', size=184842, url=None, uuid=UUID('43f5d587-8891-45ec-b415-8e82b33fec7d'), version='2021-06-28T14:21:17.965000Z', is_stitched=False), content_description={'diffmap pca coordinates'}, file_source='SCP', matrix_cell_count=3402), UUID('cde6359a-a2b0-421d-a898-c53278c21399'): AnalysisFile(document_id=UUID('cde6359a-a2b0-421d-a898-c53278c21399'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_5.json', s3_etag=None, sha1=None, sha256='', size=490, url=None, uuid=UUID('cde6359a-a2b0-421d-a898-c53278c21399'), version='2021-06-28T14:21:17.977000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.977Z', update_date='2021-06-28T14:22:57.053Z', format='txt', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='5ebb84c6', indexed=False, name='experiment2_mouse_pbs_scp_X_tsne_coords.txt', s3_etag='078f88af590b20e672210ac06f349f66', sha1='baa69f67ae57d988de7ce9db6f6f8a082175e204', sha256='c48c80f86597468dbb1c8e5cfacd46ca37ab18203e4285e787314a9afce4e7dc', size=193841, url=None, uuid=UUID('4a8b396c-7f26-4b6b-b06c-e445bff36ab3'), version='2021-06-28T14:21:17.977000Z', is_stitched=False), content_description={'tsne coordinates'}, file_source='SCP', matrix_cell_count=3402), UUID('c61a76f4-aebe-4a18-b272-e2e78307bb4a'): AnalysisFile(document_id=UUID('c61a76f4-aebe-4a18-b272-e2e78307bb4a'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/file"', crc32c='', indexed=True, name='analysis_file_4.json', s3_etag=None, sha1=None, sha256='', size=486, url=None, uuid=UUID('c61a76f4-aebe-4a18-b272-e2e78307bb4a'), version='2021-06-28T14:21:17.989000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.989Z', update_date='2021-06-28T14:22:56.844Z', format='txt', to_processes={}, manifest_entry=ManifestEntry(content_type='application/octet-stream; dcp-type=data; dcp-type=data', crc32c='a161ac05', indexed=False, name='experiment2_mouse_pbs_scp_metadata.txt', s3_etag='d98cf4712057af4eae7962bf2a6bfb23', sha1='a4542eeacc1523ef4d984123809af9a08d3e171e', sha256='b7fbb04eef7332f2bd51e6e52d360cd00aa9e3408fabaf430bd3564d8ac4b31f', size=264733, url=None, uuid=UUID('04f754f4-1c3c-4eac-a64f-c1a0937cae06'), version='2021-06-28T14:21:17.989000Z', is_stitched=False), content_description={'expression matrix'}, file_source='SCP', matrix_cell_count=3402)}, protocols={UUID('89808d14-a99e-47d2-82cd-ff9621a32206'): AnalysisProtocol(document_id=UUID('89808d14-a99e-47d2-82cd-ff9621a32206'), submitter_id=None, metadata_manifest_entry=ManifestEntry(content_type='application/json; dcp-type="metadata/protocol"', crc32c='', indexed=True, name='analysis_protocol_0.json', s3_etag=None, sha1=None, sha256='', size=1270, url=None, uuid=UUID('89808d14-a99e-47d2-82cd-ff9621a32206'), version='2021-06-28T14:21:17.435000Z', is_stitched=False), submission_date='2021-06-28T14:21:17.435Z', update_date='2021-06-28T14:21:34.155Z', protocol_id='snRNAseq_data_analysis', protocol_name='snRNAseq data analysis')})}, manifest_entry=ManifestEntry(content_type='binary/octet-stream; dcp-type=data; dcp-type=data', crc32c='0b7968e1', indexed=False, name='mouse_cortex_S2_L001_I1_001.fastq', s3_etag='72356e1061ae68e3a7be385124c5e322-28', sha1='b47b2bb455f5df72a1929678f1fbd3bbbd14cbea', sha256='f59d61941571d8f64c54ca537511fa6688488771bde7c522838da98c8839a038', size=1856426785, url=None, uuid=UUID('3cd05b67-22cf-4bea-988a-7a1fb8104fa9'), version='2021-06-28T14:21:17.456000Z', is_stitched=False), content_description={'DNA sequence'}, file_source='GEO', read_index='index1', lane_index=1), <Submitter.geo: ('21b9424e-4043-5e80-85d0-1f0449430b57', 'GEO', <SubmitterCategory.external: (<class 'humancellatlas.data.metadata.api.AnalysisFile'>, <class 'humancellatlas.data.metadata.api.SupplementaryFile'>)>)>)
```

**Comment by theathorn** [comment]
@hannes-ucsc "Solution is either to remove the requirement that file_source and submitter_id only occur in supplementary and analysis file entities, or to make the requirement specific only to submitter_id such that file_source is allowed to occur in any file entity".

**Comment by hannes-ucsc** [comment]
For demo, show that the affected subgraphs were successfully indexed in prod.
