### ISSUE TITLE
AttributeError for matrix_cell_count in SequenceFile

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3224]
The same subgraphs as in #3202 still fail to be indexed, at a later stage.

- `39fdb0ae-9a00-4829-a581-e7cb59798f02`
- `02e69c25-71e2-48ca-a87b-e256938c6a98`

```
[WARNING] 2021-07-10T02:17:01.659Z 797a4bef-df85-5fef-8138-128cdabeb841 Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '08755a99-c8f0-420a-9d21-4dca10b40ba5', 'spec': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '3bc6fafa-a77b-4899-964e-328bac420fbb', 'match': {'bundle_uuid': '02e69c25-71e2-48ca-a87b-e256938c6a98', 'bundle_version': '2021-06-28T14:21:18.700000Z'}}, 'catalog': 'dcp7'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 153, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 189, in transform
return self.index_service.transform(catalog, bundle, delete)
File "/var/task/azul/indexer/index_service.py", line 174, in transform
contributions.extend(transformer.transform())
File "/var/task/azul/plugins/metadata/hca/transform.py", line 1410, in transform
contributor_matrices=[
File "/var/task/azul/plugins/metadata/hca/transform.py", line 1411, in <listcomp>
self._matrices(file)
File "/var/task/azul/plugins/metadata/hca/transform.py", line 1001, in _matrices
matrix_cell_count = file.matrix_cell_count
AttributeError: 'SequenceFile' object has no attribute 'matrix_cell_count'
```

**Comment by hannes-ucsc** [comment]
I'm estimating this as 0 because it could easily have been found during #3202 by testing the affected bundle. I didn't want to pull that ticket back into progress because the symptom is different.

**Comment by hannes-ucsc** [comment]
For demo: https://github.com/DataBiosphere/azul/issues/3202#issuecomment-876780720
