### ISSUE TITLE
'NoneType' object has no attribute 'generate_signed_url'

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3226]
This issue causes file downloads to fail from dev browser

```
Request URL
https://service.dev.singlecell.gi.ucsc.edu/fetch/repository/files/a5dbbf6b-ab9d-5166-9e04-02bc97fa6c97?catalog=dcp2&version=2020-12-03T10%3A39%3A17.144517Z

Error Message
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1711, in fetch_repository_files
    body = _repository_files(file_uuid, fetch=True)
  File "/var/task/app.py", line 1747, in _repository_files
    return app.repository_controller.download_file(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 190, in download_file
    download.update(plugin)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 545, in update
    signed_url = blob.generate_signed_url(expiration=expiration,
AttributeError: 'NoneType' object has no attribute 'generate_signed_url'
```

and IT failures on personal deployment

```
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='it2ebi')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 171, in subTest
    yield
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 498, in _test_repository_files
    response = self._check_endpoint(endpoint=config.service_endpoint(),
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 364, in _check_endpoint
    return self._get_url_content(url.url)
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 370, in _get_url_content
    return self._get_url(url).data
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 386, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/Users/daniel/repo/azul3/test/integration_test.py", line 394, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response\n    response = view_function(**function_args)\n  File "/var/task/app.py", line 1711, in fetch_repository_files\n    body = _repository_files(file_uuid, fetch=True)\n  File "/var/task/app.py", line 1747, in _repository_files\n    return app.repository_controller.download_file(catalog=app.catalog,\n  File "/var/task/azul/service/repository_controller.py", line 190, in download_file\n    download.update(plugin)\n  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 545, in update\n    signed_url = blob.generate_signed_url(expiration=expiration,\nAttributeError: \'NoneType\' object has no attribute \'generate_signed_url\'\n')
```

**Comment by jessebrennan** [comment]
Also see @NoopDog's report https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1626039916090300

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Spike to determine if TDR is conforming to the DRS standard still. Tighten requirements around parsing the DRS URL."

**Comment by hannes-ucsc** [comment]
For demo, show that file downloads from Data Browser in `dev` and `prod` work. Wait with demo until ticket is in `prod`.
