### ISSUE TITLE
`load_script` raises `ModuleNotFoundError: No module named 'args'`

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3249]
Probably the same underlying problem as https://github.com/DataBiosphere/azul/issues/3189.

```
>>> from azul.modules import load_script
>>> load_script('can_bundle')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nadove/work/ucsc_gi/azul-sc/src/azul/modules.py", line 54, in load_script
    return load_module(path, script_name)
  File "/home/nadove/work/ucsc_gi/azul-sc/src/azul/modules.py", line 40, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nadove/work/ucsc_gi/azul-sc/scripts/can_bundle.py", line 18, in <module>
    from args import (
ModuleNotFoundError: No module named 'args'
```

**Comment by noah-aviel-dove** [comment]
Adding `scripts` to `sys.path` functions as a workaround but defeats the point of the using `load_script` in the first place.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Just move `args.py` to `source/azul`. Same with any other code that's imported from the `scripts` directory".

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce the issue.
