### ISSUE TITLE
Integration test `_assert_catalog_complete` fails

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3267]
It appears that some expected FQIDs aren't available after the indexing job has completed.
Ticket is similar to [Aggregates left over after deletion #2330](https://github.com/DataBiosphere/azul/issues/2330) but not the same.
Failed `_assert_catalog_complete` IT runs:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24939
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24758

```
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='it2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 682, in _assert_catalog_complete
    self.assertSetEqual(indexed_fqids, expected_fqids)
AssertionError: Items in the second set but not the first:
SourcedBundleFQID(uuid='fd6e4429-7059-4597-a273-8e941c9653cd', version='2021-03-15T21:20:55.937000Z', source=TDRSourceRef(id='fae2ed64-aadc-447a-bee9-ab27598cf45d', spec=TDRSourceSpec(prefix='', project='broad-jade-dev-data', name='hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622', is_snapshot=True)))
```

**Comment by noah-aviel-dove** [comment]
I suspect this is caused by https://github.com/DataBiosphere/azul/pull/3103 since the integration tests weren't changed to account for the implicit filters being added to the `/index/*` endpoints. There are so few bundles in the mock managed access snapshot that they easily could have slipped through the `IndexingIntegrationTest`'s random bundle selection, allowing the tests to pass when merging the PR. That's an oversight on my part. Assuming I'm correct, the easiest way to fix this would be to provide service account credentials when making the requests to the `index/*` endpoints.

**Comment by danielsotirhos** [comment]
Until this ticket is resolved, IT on GitLab dev will fail if it randomly picks one of the managed access bundles:
`27921d71-998a-4f14-bbd1-124ef32c074e`
`608544f7-248f-4c66-8d59-20432a7e78a0`
`cf8517ce-47e0-46c9-89de-284c52fa834d`
`fd6e4429-7059-4597-a273-8e941c9653cd`

Latest instance: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26328
Bundle chosen: `cf8517ce-47e0-46c9-89de-284c52fa834d`

**Comment by hannes-ucsc** [comment]
Once the resolution lands, no more builds should fail like this. Removing `expected` flag.

For demo, two weeks after resolution lands, and show that no builds failed for this reason.

**Comment by amarjandu** [comment]
seen again here https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/28948

**Comment by jessebrennan** [comment]
This happened again with the same PR https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/28954

**Comment by jessebrennan** [comment]
#3418 failed in the sandbox due to this. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/29113
