### ISSUE TITLE
Integration test fails with `botocore.exceptions.NoCredentialsError`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3269]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24945
```
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 141, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 257, in test_indexing
    self.azul_client.index(catalog=catalog.name,
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 188, in index
    handle_future(future)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 170, in handle_future
    bundle_fqid, result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 154, in attempt
    self.post_bundle(indexer_url.url, notification)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 85, in post_bundle
    response = requests.post(indexer_url, json=notification, auth=hmac.prepare())
  File "/builds/ucsc/azul/src/azul/hmac.py", line 76, in prepare
    key, key_id = aws.get_hmac_key_and_id()
  File "/builds/ucsc/azul/src/azul/deployment.py", line 192, in get_hmac_key_and_id
    response = self.secretsmanager.get_secret_value(SecretId=config.secrets_manager_secret_name('indexer', 'hmac'))
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/build/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/build/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/build/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/build/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/build/.venv/lib/python3.8/site-packages/botocore/signers.py", line 162, in sign
    auth.add_auth(request)
  File "/build/.venv/lib/python3.8/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by melainalegaspi** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/41763

**Comment by hannes-ucsc** [comment]
Extremely rare. Moving to icebox.
