### ISSUE TITLE
Filtering with invalid query gives 500 response

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3280]
For example this URL https://service.dev.singlecell.gi.ucsc.edu/index/samples?catalog=dcp2&filters=%7B%0A%20%20%22fileSource%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%22tdr%3Abroad-jade-dev-data%3Asnapshot%2Fhca_dev_20201203___20210219%3A42%22%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&size=10&sort=sampleId&order=asc

which uses these filters (**notice the double array**):
```
{
  "fileSource": {
    "is": [
      [
        "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:"
      ]
    ]
  }
}
```

Gets this response:

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1230, in get_sample_data
    return repository_search('samples', sample_id, filter_sources=True)
  File "/var/task/app.py", line 983, in repository_search
    return service.get_data(catalog=catalog,
  File "/var/task/azul/service/index_query_service.py", line 85, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 620, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/opt/python/elasticsearch_dsl/search.py", line 702, in execute
    es.search(
  File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/python/elasticsearch/client/__init__.py", line 851, in search
    return self.transport.perform_request(
  File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', '[terms] unknown token [END_ARRAY] after [contents.files.source.keyword]')
```

~This happens because the translation mapping is wrong:
https://github.com/DataBiosphere/azul/blob/052859b1458dea01417a07880b6b74f6ed92462a/src/azul/plugins/metadata/hca/__init__.py#L132~

~and should map to `contents.files.sources`. The problem is deeper than this though... it seems like the field types are wrong.~ I'm looking into it.

Edit: Status code should be 400. Invalid parameters should not penetrate the systems that deeply, in this case all the way to ES.

**Comment by jessebrennan** [comment]
This issue should probably be closed as invalid because I assumed `fileSource` was referencing the repository source where the file came from. I'll wait for triage before doing anything further.

**Comment by jessebrennan** [comment]
It turned out there was an issue in the query which caused the 500 error. I edited the description. We _may_ still wish to fix this and make sure Azul fails more gracefully.

**Comment by hannes-ucsc** [comment]
Retriaging because this could be of security concern.
