### ISSUE TITLE
/repository/files/summary is returning a 500 in `prod`

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#330]
https://service.explore.data.humancellatlas.org/repository/files/summary?filters=%7B%7D

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 341, in get_summary
    response = es_td.transform_summary(filters=filters)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 381, in transform_summary
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-215)
┆Project Name: azul
┆Issue Number: AZUL-215

**Comment by hannes-ucsc** [comment]
Regression from f3329693fffd8269a6ee59d97227d11c99903362. I should have reindexed `prod` after yesterday's deployment just like we did in #266. I did that now and indices under their new names are being populated as I write this. The above URL is working.
