### ISSUE TITLE
TDR query fails with syntax error

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3305]
The query produced by `_list_links_ids` currently causes a syntax error if the project name contains digits.

![Screen Shot 2021-08-06 at 10 39 16 AM](https://user-images.githubusercontent.com/46407464/128550595-f47e8981-86a9-4e24-a464-6f019869b51e.png)

To resolve, the queries produced by `_list_links_ids` and other methods in `repository/tdr/__init__.py` should enclose the full table name in back-quotes (`).

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/6407
```
2021-08-06 16:35:59,885 INFO    MainThread: Listing bundles with prefix 'de' in source TDRSourceRef(id='a61115e1-ddf4-431a-8315-2cb4cb7cf87a', spec=TDRSourceSpec(prefix='', project='tdr-prd1-4265bbdb', name='hca_prod_20201120_dcp2___20210730_dcp8', is_snapshot=True)).
2021-08-06 16:35:59,885 DEBUG   MainThread: Query: "\n            SELECT links_id, version\n            FROM tdr-prd1-4265bbdb.hca_prod_20201120_dcp2___20210730_dcp8.links\n            WHERE STARTS_WITH(links_id, 'de')\n        "
ERROR
test_openapi (integration_test.OpenAPIIntegrationTest) ... ok
test_concurrent_portal_db_crud (integration_test.PortalRegistrationIntegrationTest)
Use multithreading to simulate multiple users simultaneously modifying ... skipped 'Test would pollute portal DB'
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 141, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 235, in test_indexing
    catalogs: List[Catalog] = [
  File "/builds/ucsc/azul/test/integration_test.py", line 237, in <listcomp>
    notifications=self._prepare_notifications(catalog) if index else {})
  File "/builds/ucsc/azul/test/integration_test.py", line 591, in _prepare_notifications
    bundle_fqids = list(chain.from_iterable(
  File "/builds/ucsc/azul/test/integration_test.py", line 592, in <genexpr>
    self.azul_client.list_bundles(catalog, source, prefix)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 213, in list_bundles
    return plugin.list_bundles(source, prefix)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 234, in list_bundles
    bundle_fqids = self._list_links_ids(source, prefix)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 281, in _list_links_ids
    current_bundles = self._query_latest_version(source.spec, f'''
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 294, in _query_latest_version
    iter_rows = self._run_sql(query)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 273, in _run_sql
    return self.tdr.run_sql(query)
  File "/builds/ucsc/azul/src/azul/terra.py", line 437, in run_sql
    result = job.result()
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Missing whitespace between literal and alias at [3:31]
(job ID: 0f736fc4-5f29-4f3d-a90a-4056bf269a36)
                          -----Query Job SQL Follows-----                           
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            SELECT links_id, version
   3:            FROM tdr-prd1-4265bbdb.hca_prod_20201120_dcp2___20210730_dcp8.links
   4:            WHERE STARTS_WITH(links_id, 'de')
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
----------------------------------------------------------------------
Ran 11 tests in 34.396s
FAILED (errors=1, skipped=4)
make: *** [Makefile:168: integration_test] Error 1
Cleaning up file based variables
00:01
```

**Comment by hannes-ucsc** [comment]
Can you add link to failing Gitlab job, please?
