### ISSUE TITLE
AssertionError: `'https' != 'gs'` during IT in `prod`

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3320]
The prod promotion of tickets:
- [#3157](https://github.com/DataBiosphere/azul/issues/3157) (PR [#3168](https://github.com/DataBiosphere/azul/pull/3168))
- [#2414](https://github.com/DataBiosphere/azul/issues/2414) (PR [#3112](https://github.com/DataBiosphere/azul/pull/3112))
- [#3137](https://github.com/DataBiosphere/azul/issues/3137), (PR [#3186](https://github.com/DataBiosphere/azul/pull/3186))
- [#2957](https://github.com/DataBiosphere/azul/issues/2957) (PR [#3245](https://github.com/DataBiosphere/azul/pull/3245))

failed IT and was rolled back.

Errors from [integration test on GitLab](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/6703):
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='it7', format='terra.bdbag', attempts=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 337, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 449, in _check_terra_bdbag
    self.assertEqual('https', furl(access.url).scheme)
AssertionError: 'https' != 'gs'
- https
+ gs


======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='it7')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 504, in _test_repository_files
    response = self._check_endpoint(endpoint=config.service_endpoint(),
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in _check_endpoint
    return self._get_url_content(url.url)
  File "/builds/ucsc/azul/test/integration_test.py", line 374, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 390, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 398, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response\n    response = view_function(**function_args)\n  File "/var/task/app.py", line 1722, in fetch_repository_files\n    body = _repository_files(file_uuid, fetch=True)\n  File "/var/task/app.py", line 1760, in _repository_files\n    return app.repository_controller.download_file(catalog=catalog,\n  File "/var/task/azul/service/repository_controller.py", line 191, in download_file\n    download.update(plugin, authentication)\n  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 523, in update\n    require(\'X-Goog-Signature\' in args, args)\n  File "/var/task/azul/__init__.py", line 1132, in require\n    reject(not condition, *args, exception=exception)\n  File "/var/task/azul/__init__.py", line 1147, in reject\n    raise exception(*args)\nazul.RequirementError: {}\n')

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='it8', format='terra.bdbag', attempts=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 337, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 449, in _check_terra_bdbag
    self.assertEqual('https', furl(access.url).scheme)
AssertionError: 'https' != 'gs'
- https
+ gs


======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='it8')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 504, in _test_repository_files
    response = self._check_endpoint(endpoint=config.service_endpoint(),
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in _check_endpoint
    return self._get_url_content(url.url)
  File "/builds/ucsc/azul/test/integration_test.py", line 374, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 390, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 398, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response\n    response = view_function(**function_args)\n  File "/var/task/app.py", line 1722, in fetch_repository_files\n    body = _repository_files(file_uuid, fetch=True)\n  File "/var/task/app.py", line 1760, in _repository_files\n    return app.repository_controller.download_file(catalog=catalog,\n  File "/var/task/azul/service/repository_controller.py", line 191, in download_file\n    download.update(plugin, authentication)\n  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 523, in update\n    require(\'X-Goog-Signature\' in args, args)\n  File "/var/task/azul/__init__.py", line 1132, in require\n    reject(not condition, *args, exception=exception)\n  File "/var/task/azul/__init__.py", line 1147, in reject\n    raise exception(*args)\nazul.RequirementError: {}\n')

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='it1', format='terra.bdbag', attempts=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 337, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 449, in _check_terra_bdbag
    self.assertEqual('https', furl(access.url).scheme)
AssertionError: 'https' != 'gs'
- https
+ gs


======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='it1')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 504, in _test_repository_files
    response = self._check_endpoint(endpoint=config.service_endpoint(),
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in _check_endpoint
    return self._get_url_content(url.url)
  File "/builds/ucsc/azul/test/integration_test.py", line 374, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 390, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 398, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response\n    response = view_function(**function_args)\n  File "/var/task/app.py", line 1722, in fetch_repository_files\n    body = _repository_files(file_uuid, fetch=True)\n  File "/var/task/app.py", line 1760, in _repository_files\n    return app.repository_controller.download_file(catalog=catalog,\n  File "/var/task/azul/service/repository_controller.py", line 191, in download_file\n    download.update(plugin, authentication)\n  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 523, in update\n    require(\'X-Goog-Signature\' in args, args)\n  File "/var/task/azul/__init__.py", line 1132, in require\n    reject(not condition, *args, exception=exception)\n  File "/var/task/azul/__init__.py", line 1147, in reject\n    raise exception(*args)\nazul.RequirementError: {}\n')

======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='it0lungmap', format='terra.bdbag', attempts=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 337, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 449, in _check_terra_bdbag
    self.assertEqual('https', furl(access.url).scheme)
AssertionError: 'https' != 'gs'
- https
+ gs


======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='it0lungmap')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 504, in _test_repository_files
    response = self._check_endpoint(endpoint=config.service_endpoint(),
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in _check_endpoint
    return self._get_url_content(url.url)
  File "/builds/ucsc/azul/test/integration_test.py", line 374, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 390, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 398, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (500, 'Internal Server Error', b'Traceback (most recent call last):\n  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response\n    response = view_function(**function_args)\n  File "/var/task/app.py", line 1722, in fetch_repository_files\n    body = _repository_files(file_uuid, fetch=True)\n  File "/var/task/app.py", line 1760, in _repository_files\n    return app.repository_controller.download_file(catalog=catalog,\n  File "/var/task/azul/service/repository_controller.py", line 191, in download_file\n    download.update(plugin, authentication)\n  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 523, in update\n    require(\'X-Goog-Signature\' in args, args)\n  File "/var/task/azul/__init__.py", line 1132, in require\n    reject(not condition, *args, exception=exception)\n  File "/var/task/azul/__init__.py", line 1147, in reject\n    raise exception(*args)\nazul.RequirementError: {}\n')
```

Error from Cloudwatch when a file download was attempted from the Data Browser:

```
[ERROR] 2021-08-12T00:23:31.985Z 583326b2-ec51-4197-a07f-9d483dd95942 Caught exception for <function fetch_repository_files at 0x7f9cc4331040>
Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 1722, in fetch_repository_files
body = _repository_files(file_uuid, fetch=True)
File "/var/task/app.py", line 1760, in _repository_files
return app.repository_controller.download_file(catalog=catalog,
File "/var/task/azul/service/repository_controller.py", line 191, in download_file
download.update(plugin, authentication)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 523, in update
require('X-Goog-Signature' in args, args)
File "/var/task/azul/__init__.py", line 1132, in require
reject(not condition, *args, exception=exception)
File "/var/task/azul/__init__.py", line 1147, in reject
raise exception(*args)
azul.RequirementError: {}
```

**Comment by noah-aviel-dove** [comment]
Looks like this is due to the changes made by https://github.com/DataBiosphere/azul/issues/3245, and a difference in behavior of the DRS endpoints between TDR's dev and prod deployments. Specifically, prod doesn't seem to implement the resolution of GS URLs into signed HTTPS URLs.

**Comment by theathorn** [comment]
Freebie of #2957.

**Comment by hannes-ucsc** [comment]
I'm [restored](https://github.com/DataBiosphere/azul/pull/3245#event-5152848812) the branch for #2957 and expecting an additional commit on that branch with a fix for this issue. We can't reopen PR #3245 so an new PR for that branch should be opened and connected to this issue and #2957.

**Comment by noah-aviel-dove** [comment]
This ended up being fixed by the TDR promotion so I'm not sure it still should be attached to this PR.

**Comment by jessebrennan** [comment]
When integration tests pass in `prod` I will close this.

**Comment by jessebrennan** [comment]
Integration test in `prod` pass https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/7306
