### ISSUE TITLE
`circuit_breaking_exception` during `prod` reindex

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3357]
All 169 of these errors resolved eventually:

```
('cc4c1052-4553-4ade-9d6a-0bb9f2106a51', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('10fc8e37-a6c7-42c2-88e7-6dfa5e16ad19', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('48081e1a-e99c-4f92-b215-2b4214aacd97', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('a2e8b985-ab00-4f2e-a6f1-862a2ccaa933', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('06237001-bd07-48f2-88f8-73dd47430254', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('0b3c97b2-19a4-40d9-bde5-02cd6a4a7724', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('cbf165b3-c3ac-4694-a5c5-74eddb8524e2', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('86dcc0b1-8de4-4577-bd77-bdc466214c21', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('7ab0a0bd-e6a4-442d-aa56-b306c08fec9b', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('efac13a0-d366-4bed-ad5d-843c779d8178', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1ce2dbb7-85a2-4e54-a0e7-aa6471bd5645', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('e3eba7f5-fbaa-49f0-b0b6-978112bb7a2a', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('c1048339-105e-46cb-a2f0-7db30dfc1416', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('1cafa498-e81a-4af0-902c-51825fbed9e2', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('0ebf11a5-9176-43a8-acac-53f36db9fb94', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ec227276-86d8-4a62-af60-64aaf94f8d4d', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('289ece4f-2fa7-43ea-b3ca-2549ba0f05af', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ef672ed9-cab3-428c-83b3-ef9336b248bc', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('b0377aeb-b250-456b-a822-238ab85f0365', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('1cb92817-edc6-4b6b-be63-de2b7b86e892', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('22e79334-70b1-47cd-9600-4ee0b515b3a0', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('5a8cf497-1b6e-4a68-a3ce-7b369c2b843d', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ff1559bf-4b75-4474-93ef-405143623e28', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('f1a306c9-40c7-40eb-927a-d30d3a008a98', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('98279ecd-ca3d-4873-b246-df21d0106e7e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('9617945b-dc33-4614-b9e8-86bb120525e9', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('ec5bf17b-91b3-496d-8e1e-dffc018b6fb2', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('97cf70d5-6206-46ee-b4fc-3b48ed1f9eb4', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('cb6d0c06-4209-4201-bcf5-a96978425228', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('afc78fd6-7476-4d30-89a3-a9b4ab8a4798', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b7476f02-3f7f-4161-93c3-64e31e9b8f0e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('c037e924-f729-4e49-924b-7351b7ff2122', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('44a3505c-3db6-4023-b6c2-be44129fb2be', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('c150c832-c66b-4b24-bbea-097bb4eecde9', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('96466da4-9bf0-45fa-931a-f3fdd876c534', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('cb5acda2-5579-422d-99df-c4a19ab41c3a', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('883a09dc-9e66-4952-ba93-e7e4b3e60683', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('7d2de616-2342-4605-9c96-cbca08131f82', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('bd8d8033-ff92-4bda-92d7-9a953f791751', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1f57e964-7afa-4c55-ae54-56cff6082df6', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('c7cbd57c-67b6-44dd-9fec-5993f86bbb9c', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('8c4a5cee-6bce-4e0a-b65c-21e65eb21a14', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('ef1427f5-45e1-4c9b-8f88-bac1ddb97451', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('68d9e8d2-d386-4504-8ce9-2e7f518c92e1', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('c12c44a1-8f59-4356-a1ec-5e77b871b6bc', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('22ea5686-b718-4756-8b75-4006893f9600', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ec7f4bcb-0e1d-4a2d-ae27-57e4186d8820', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('f65841a2-4e6d-406c-b8a0-aaf21d0bb2dc', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('0c71b6f1-3c11-4fb1-be80-df9f0039fd7f', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ae2c173f-de63-4a43-95ba-4982ac141105', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1e327176-9f87-4797-b969-77371d43e373', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('f11ab7d3-4fbf-4806-bc40-0f5f2d94683e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('40fd3998-f0b2-4996-a0f4-81473c888933', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('c1c10a33-d989-4baf-ace9-68cfc76aefd9', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('09d6c395-6394-4e23-bdb0-4b55100375d7', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('789dcddc-66a8-41f8-bea6-22e32bd4c120', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('4deebe79-b604-445c-bfc0-5a6007abaa4b', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('44cd5d92-99b5-4386-9c12-9f4504870b48', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('284a1ee5-52df-4234-aafd-037f42eeef30', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1cd5b29a-8d7b-4818-8520-8f54fbba71c0', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('049fdd1c-9dfa-429a-bf82-860f00f58c6f', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('b3106d6d-bdf0-42eb-993a-71dace71a88e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('5a9ec969-4e31-4faf-8861-ed7573b88679', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('5e5ac170-1000-4ee9-894a-b55ad9fe425e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('a12b4978-54d7-4f92-9442-95b911f1c349', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('c661b4cd-e3ea-4108-a36d-3c7d887ea282', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('312cba64-354d-435d-ab7d-d23ff6cb6fe4', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('bb0bcb13-2f3c-463b-8bfb-259c9eea6275', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('88fc7a50-5b39-4648-9e18-48956816014c', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('cef2213d-ffa6-4552-a27c-e621a3f8ad31', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('4afe8374-68f8-4a9f-bb6a-60df79ef1c12', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('2ef62e00-c761-4027-b39c-a42918e35b48', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('09042eb9-3347-40fb-bafd-f9f1b48ba059', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('2184392a-5ac0-44a1-a94d-14c6fa558301', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('440f2c4f-30d3-4d1a-bb97-3a7e7130af9b', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('9640a234-b5fa-465f-8628-a5485f952cb2', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('1f52707c-eb26-46d1-920c-9e729b469d7c', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('c1198c1f-65bd-40c2-8e6f-d2ae2c9d7ca1', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('dc8fe40e-afb8-4780-8752-21051e6fe24f', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('6f5b3f1d-c2c2-4456-942b-2ec35cf0b578', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('22608941-8687-4581-a1a9-768c3023e80f', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1cd57c6d-b85d-45cc-8460-f527bd34128f', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('bedc59c8-68c2-4514-ada6-1164fbcafbb3', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('81d98cff-96bf-4fab-97ad-b6bb807d0926', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('a3478a18-ca7d-4d15-aa05-a929d5cac8de', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('d4d9b435-b884-4e4b-846a-92f76ba0aa19', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('8c381109-ae01-4478-a7dc-ed8f47ed723e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b5345174-ab43-493c-8e24-3a5edc6e5b36', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('ec7dd0c6-8130-4e4b-8614-e78166b644bf', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('efc6a318-b177-4f72-8230-85d59d53b3f8', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('f7add5aa-dede-46d6-b666-4b71ebb3e280', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('a4d90a74-b414-4634-a99b-fa2f0320c68e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('887a8186-2d7e-4f9a-9648-123a0de5bf19', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('061e723b-d8df-4469-9fd9-44ce027e7ea0', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('5943fa17-c70a-48bd-bdf3-91ade6fbab93', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('44c97130-af7e-4bc1-8032-2158f68dcccf', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('d4f6949b-dab1-4ad6-9bbb-c142b4f58d88', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('af9e8bc8-ef32-4eb5-a71d-f681ef9f3c4c', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('d4ed3c33-0ca0-493f-98c7-f88e3c577098', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('01ed3130-009c-486b-a457-9685562de4a8', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('0b80ac42-2535-4e71-a9b2-ad7131cd31c5', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('74ec0e3a-187c-4e66-a22a-bdcd6008fa9d', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b04ce607-a89c-47bc-a24f-d766cbeb7f14', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('44cd588a-fca6-4ee1-a155-4cdf70799757', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('b604d164-de67-4860-9df4-89abbb0faa39', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('8907096e-fc66-4edd-89a4-ba871aa3da1f', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('48b7a6bc-4043-43b3-ba27-b1cdf928d24e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('e76f28b8-3f49-4d41-b5ce-f99c9db87d80', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('58cdda28-fb67-46d5-819e-c27d72fcfcdf', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('0c195169-0201-4157-ae7f-a121a9a3db34', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('21c0e0e3-e3d8-4778-a3b8-df83fe91ef9e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('23de8d8e-e07f-4aeb-a209-baf78fe1d183', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ef9ee279-6f8b-45ea-adb0-ad81883a7194', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('edab0e58-4f94-4616-ae7a-5483848518a5', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b7e59a95-48ca-45dc-bcf5-0f832339947c', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('cbb1dcbb-87ed-45e5-a484-55110b68ed26', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('23b9da6d-31f1-4939-b9c0-3d747279ca86', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('23db520a-a2d3-4ede-8830-cfb1f043033e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('883a0d66-734d-4633-a0b0-7a2310600b52', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('23df1970-3f13-472c-9f59-92f61dcfb3a9', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('d4ec1a07-72d5-4be3-9c15-cb2de6644324', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('dd5e45a1-14b7-4469-935b-94d75c1582e3', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('f34c4847-644b-4cf6-a955-99d2b239a5e8', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('0637528d-0b19-439a-974b-e512850fc246', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1baffdc7-0efb-4b98-9509-8597bfaa4d6e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('2eca525c-7441-4e8b-8f9e-a82d6d41de71', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('e6a4a4b6-35bd-40ea-97c8-aa0238059502', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('09493f57-e6ec-421c-96ec-ccba882508c5', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('48635425-3ebc-444b-ba35-cf1ddad21902', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('c1a401ce-05aa-486e-9977-3888608370cb', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b18da95f-1e47-4dd4-a0de-5e52faa68170', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('dc8c013c-27a9-4770-b067-ec198e0276f2', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('5a62187c-bea6-4f30-95df-a2535ac43dbc', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('883710c1-5fda-473a-a603-96ff693ca0b6', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('efcb1901-2378-4227-9124-7924fd7efcc0', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('9aa2a633-3b32-4916-b67a-8e815b9703b5', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('23207904-ff86-44af-9320-b6e812a09bbc', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('b30a9095-ddd6-4371-8b25-4be48cfc5ad4', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1f159db5-a395-4043-9362-df12a002171e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('06e488e6-2be1-4912-8863-296433eab5d4', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('88faf596-7215-483a-8c79-9fb0f340e14b', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('dc9209e7-09ca-4071-b352-15b7024ec857', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('ddea29c6-9da8-4eb8-92e5-3036bec89f1a', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('1c1f6ad8-6d70-4b56-b221-e6a99f93c908', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('c11b3294-11fa-4cb6-9055-67a4db581505', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('f301a4a7-1dda-4631-96ca-8199730e474b', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('1c945a07-cd87-4c4e-a300-cee36431db28', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('7adeade8-208a-4bd6-998a-9ca16c45f159', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('5a374a4e-7811-4629-aab2-789e8b103edf', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('f1f95673-0fb7-4810-851b-a64fbbf4eef6', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('a4ff247d-0000-4d32-9e66-2b28ed1061b7', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('a5b97f6d-3a8d-45d1-921d-3f296fe05de8', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('b43fb38c-5da5-4a45-b530-890d4207cbe4', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('0e458d40-c4c7-4a03-a97c-a78953727bb8', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('e7dbd9d7-c700-4ed8-bced-8e475cdbef2e', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('21b0538f-d017-4057-95b7-cac2fad1955c', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('ed7f32fa-9fbe-4bf6-a01f-8a4aae56dda7', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('06676b64-f464-48c4-9989-af1079de3c53', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('59f3aac6-fec2-4abe-bc02-716e22ac465f', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('0728a2bf-b07a-496d-b08d-cf6fab8e53d3', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('b5251e6c-e30b-4633-8ba4-0ea3fe62cb1a', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('440f6907-d7b3-4456-aece-ae0dfedd6e5a', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('f668bfa4-42ff-424d-8fdf-80c25d544f3e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('6eb5d642-0995-41b2-840f-642c5adf7dd4', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('28295e60-bb47-4d38-bbe2-3c6c44644850', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1cce98ca-11d1-45da-844d-55b19559243e', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('1bcce2f8-fdf3-4d60-b926-f64140f337a8', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('4450817f-2823-4ebd-9a70-73b52804d815', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')
('3f8b8b08-aced-4604-9141-575c96034fd1', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:')

```

```
[WARNING] 2021-08-20T11:16:44.718Z c9dd0e4b-6147-5160-a6f9-57d2f073ef3f There was a general error with document ContributionCoordinates(entity=EntityReference(entity_type='files', entity_id='a1b262a9-40f1-46bd-87b7-8df02f11345b'), aggregate=False, bundle=BundleFQID(uuid='c661b4cd-e3ea-4108-a36d-3c7d887ea282', version='2019-08-01T20:01:47.186241Z'), deleted=False): TransportError(429, 'circuit_breaking_exception', {'error': {'root_cause': [{'type': 'circuit_breaking_exception', 'reason': '[parent] Data too large, data for [<http_request>] would be [16407834041/15.2gb], which is larger than the limit of [16287753830/15.1gb], real usage: [16407826224/15.2gb], new bytes reserved: [7817/7.6kb]', 'bytes_wanted': 16407834041, 'bytes_limit': 16287753830}], 'type': 'circuit_breaking_exception', 'reason': '[parent] Data too large, data for [<http_request>] would be [16407834041/15.2gb], which is larger than the limit of [16287753830/15.1gb], real usage: [16407826224/15.2gb], new bytes reserved: [7817/7.6kb]', 'bytes_wanted': 16407834041, 'bytes_limit': 16287753830}, 'status': 429}). Total # of errors: 1, giving up.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_service.py", line 583, in _write_individually
method(refresh=self.refresh, **doc.to_index(self.catalog, self.field_types))
File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
return func(*args, params=params, **kwargs)
File "/opt/python/elasticsearch/client/__init__.py", line 350, in index
return self.transport.perform_request(
File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
status, headers_response, data = connection.perform_request(
File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
self._raise_error(response.status_code, raw_data)
File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [16407834041/15.2gb], which is larger than the limit of [16287753830/15.1gb], real usage: [16407826224/15.2gb], new bytes reserved: [7817/7.6kb]')
```

**Comment by theathorn** [comment]
Dup of #3315.
