### ISSUE TITLE
`Too Many Requests /_bulk` fail during `prod` reindex

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3358]
Bundles that failed:
```
('927e2488-a03e-4c4e-9e97-7e095223584c', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('46f6a11f-88ba-453c-a08d-27fa8ed5184a', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('927e2488-a03e-4c4e-9e97-7e095223584c', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')

```

```
[WARNING] 2021-08-20T01:00:58.038Z 5a06f87a-2c8c-598c-8681-a1e2d36fa537 Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '08755a99-c8f0-420a-9d21-4dca10b40ba5', 'spec': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '15947856-9736-4059-ba72-3de27e81cc74', 'match': {'bundle_uuid': '46f6a11f-88ba-453c-a08d-27fa8ed5184a', 'bundle_version': '2021-06-04T07:09:38.054000Z'}}, 'catalog': 'dcp7'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 155, in contribute
tallies = self.index_service.contribute(catalog, contributions)
File "/var/task/azul/indexer/index_service.py", line 201, in contribute
writer.write(contributions)
File "/var/task/azul/indexer/index_service.py", line 576, in write
self._write_bulk(documents)
File "/var/task/azul/indexer/index_service.py", line 613, in _write_bulk
for success, info in response:
File "/opt/python/elasticsearch/helpers/actions.py", line 218, in streaming_bulk
for data, (ok, info) in zip(
File "/opt/python/elasticsearch/helpers/actions.py", line 113, in _process_bulk_chunk
raise e
File "/opt/python/elasticsearch/helpers/actions.py", line 109, in _process_bulk_chunk
resp = client.bulk("
".join(bulk_actions) + "
", *args, **kwargs)
File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
return func(*args, params=params, **kwargs)
File "/opt/python/elasticsearch/client/__init__.py", line 1556, in bulk
return self.transport.perform_request(
File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
status, headers_response, data = connection.perform_request(
File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
self._raise_error(response.status_code, raw_data)
File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(429, '429 Too Many Requests /_bulk')
```

**Comment by jessebrennan** [comment]
All of these passed when re-fed after reindexing had finished.

**Comment by hannes-ucsc** [comment]
In that case, this will be fixed by the resolution for #3315 and is therefore a duplicate of that.

**Comment by theathorn** [comment]
Dup of #3315.
