### ISSUE TITLE
400 Bad request from BigQuery during integration test

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3364]
This happened during IT on `sandbox`, `dev`, and `prod`. It's possible this is a temporary outage because all of these tests were run at approximate the same time at ~11am.

```
[ERROR] BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/platform-hca-dev/queries/ba61ab7f-94ed-4c42-8fe7-f1a3756b83cd?maxResults=0&location=US&prettyPrint=false: The job encountered an internal error during execution and was unable to complete successfully.

(job ID: ba61ab7f-94ed-4c42-8fe7-f1a3756b83cd)

-----Query Job SQL Follows-----

| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
1:
2: SELECT BYTE_LENGTH(content) AS content_size, sequence_file_id, JSON_EXTRACT_SCALAR(content, "$.file_core.file_name") AS file_name, content, version, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, descriptor, file_id
3: FROM `broad-jade-dev-data.hca_dev_20201203___20210524_lattice.sequence_file`
4: WHERE sequence_file_id = "09973dd3-77e5-4397-bc24-71283172ef01" OR sequence_file_id = "6f869019-15f6-4a94-b86a-65512f7258a1"
5:
| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
Traceback (most recent call last):
  File "/var/task/app.py", line 119, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 1459, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 152, in contribute_retry
    app.index_controller.contribute(event, retry=True)
  File "/var/task/azul/indexer/index_controller.py", line 153, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 184, in transform
    bundle = plugin.fetch_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 242, in fetch_bundle
    bundle = self._emulate_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 339, in _emulate_bundle
    raise e
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 422, in _retrieve_entities
    rows = self._query_latest_version(source, f'''
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 294, in _query_latest_version
    iter_rows = self._run_sql(query)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 273, in _run_sql
    return self.tdr.run_sql(query)
  File "/var/task/azul/terra.py", line 440, in run_sql
    result = job.result()
  File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/opt/python/google/api_core/future/polling.py", line 130, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/opt/python/google/cloud/bigquery/job.py", line 3098, in _blocking_poll
    super(QueryJob, self)._blocking_poll(timeout=timeout)
  File "/opt/python/google/api_core/future/polling.py", line 108, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/opt/python/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/opt/python/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/opt/python/google/api_core/future/polling.py", line 86, in _done_or_raise
    if not self.done(**kwargs):
  File "/opt/python/google/cloud/bigquery/job.py", line 3079, in done
    self._query_results = self._client._get_query_results(
  File "/opt/python/google/cloud/bigquery/client.py", line 1286, in _get_query_results
    resource = self._call_api(
  File "/opt/python/google/cloud/bigquery/client.py", line 556, in _call_api
    return call()
  File "/opt/python/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/opt/python/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/opt/python/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
```

**Comment by noah-aviel-dove** [comment]
Weird that `The job encountered an internal error during execution and was unable to complete successfully.` is a 40x and not a 50x.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This seems to have been a rare occurrence. Closing."
