### ISSUE TITLE
TransportErrors are increasing on `prod` during aggregation and causing failures

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3367]
Here's a histogram that includes that last couple reindexes. The most recent reindex was only dcp8 catalog. The one before was everything.

![transport-aggregate-prod](https://user-images.githubusercontent.com/10734740/130667048-597ac785-ca53-4832-a579-1fadf927b89f.png)

and here's an example of one such exception

```
[ERROR] TransportError: TransportError(429, '429 Too Many Requests /_search/scroll')
Traceback (most recent call last):
  File "/var/task/app.py", line 119, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 1459, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 134, in aggregate
    app.index_controller.aggregate(event)
  File "/var/task/azul/indexer/index_controller.py", line 229, in aggregate
    self.index_service.aggregate(tallies)
  File "/var/task/azul/indexer/index_service.py", line 243, in aggregate
    contributions = self._read_contributions(total_tallies)
  File "/var/task/azul/indexer/index_service.py", line 370, in _read_contributions
    contributions = [
  File "/var/task/azul/indexer/index_service.py", line 370, in <listcomp>
    contributions = [
  File "/opt/python/elasticsearch/helpers/actions.py", line 443, in scan
    resp = client.scroll(
  File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/python/elasticsearch/client/__init__.py", line 1373, in scroll
    return self.transport.perform_request(
  File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review @jessebrennan findings.

**Comment by hannes-ucsc** [comment]
It appears that the 429s are the only real issue here because the counts of the other ones are negligible. 

The hypothesis is that they are all caused by the `parent` circuit breaker firing. The Traceback sometimes does and sometimes does not indicate that breaker being the cause, I think the _search requests it does not. The `parent` circuit breaker looks at the JVM heap so reducing the heap pressure should alleviate this. Before we increase the cluster memory (either increase # nodes or beef up the node's instance type, we should see if reducing the # of shards sufficiently reduces the memory pressure. That's covered in #3630.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "After switching to paged retrieval of contributions instead of using scan() , we are observing a very low number of transport errors."
