### ISSUE TITLE
Implicit filter on `sourceId` collides with explicit one

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3372]
This code is broken:

https://github.com/DataBiosphere/azul/blob/384e116600587714ec4a37e8a30563ae288d6bc3/src/azul/service/index_query_service.py#L46

~For one,~ see https://github.com/DataBiosphere/azul/issues/3372#issuecomment-910017734 below

```
$ curl -s 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?catalog=dcp2&filters=%7B%0A%20%20%22sourceId%22%3A%20%7B%0A%20%20%20%20%20%22intersects%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%5Bnull%2C%20null%5D%0A%20%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%22sourceSpec%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22tdr%3Abroad-jade-dev-data%3Asnapshot%2Fhca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622%3A%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&size=99&sort=sourceId&order=asc' | jq .hits[].sources
[
  {
    "sourceId": "fae2ed64-aadc-447a-bee9-ab27598cf45d",
    "sourceSpec": "tdr:broad-jade-dev-data:snapshot/hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622:"
  }
]
```

Secondly, that section assumes that the response property is called `sourceId`, even though the mapping between index and response property names is supposed to be encapsulated in plugin config. That encapsulation is leaky at the moment (changing the static configuration often requires dependent changes to other parts of code) but any security-sensitive code should be hardened against someone inadvertently changing that mapping to, say, map `sourceId` to some other index field.

**Comment by noah-aviel-dove** [comment]
This is not a valid reproduction of the bug described in the ticket title because the implicit source filter is not applied to the `/index/projects` endpoint. However, the code in question is still broken because when the same set of filters is provided to an endpoint where the implicit filter is applied, it results in a 500 error:
```
$ curl -s 'https://service.dev.singlecell.gi.ucsc.edu/index/bundles?catalog=dcp2&filters=%7B%0A%20%20%22sourceId%22%3A%20%7B%0A%20%20%20%20%20%22intersects%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%5Bnull%2C%20null%5D%0A%20%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%22sourceSpec%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%22tdr%3Abroad-jade-dev-data%3Asnapshot%2Fhca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622%3A%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&size=99&sort=sourceId&order=asc'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1236, in get_bundle_data
    return repository_search('bundles', bundle_id, filter_sources=True)
  File "/var/task/app.py", line 981, in repository_search
    return service.get_data(catalog=catalog,
  File "/var/task/azul/service/index_query_service.py", line 88, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 598, in transform_request
    es_search = self._create_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 303, in _create_request
    filters = self._translate_filters(catalog, filters, field_mapping)
  File "/var/task/azul/service/elasticsearch_service.py", line 131, in _translate_filters
    assert isinstance(one(value.values()), list)
  File "/opt/python/more_itertools/more.py", line 529, in one
    raise too_long or ValueError('too many items in iterable (expected 1)')
ValueError: too many items in iterable (expected 1)
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce [@noah-aviel-dove's valid reproduction](https://github.com/DataBiosphere/azul/issues/3372#issuecomment-910017734) and show that the sources filter can only use the `is` relation.
