### ISSUE TITLE
A crashed portal DB IT causes subsequent IT runs to fail

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3376]
The test failed during this `sandbox` build https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/27348 but I highly suspect it's unrelated to the PR. It failed again on a second retry with the same result https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/27379.

```
======================================================================
FAIL: test_concurrent_portal_db_crud (integration_test.PortalRegistrationIntegrationTest)
Use multithreading to simulate multiple users simultaneously modifying
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 142, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 847, in test_concurrent_portal_db_crud
    self.assertEqual(old_entries, self.old_db)
AssertionError: Lists differ: [] != [{'portal_id': 'foo', 'integrations': [{'i[11322 chars]=3'}]
Second list contains 66 additional elements.
First extra element 0:
{'portal_id': 'foo', 'integrations': [{'integration_id': 'bar', 'entity_type': 'project', 'integration_type': 'get', 'entity_ids': ['baz']}], 'mock-count': 'task=0;op=0'}
Diff is 16456 characters long. Set self.maxDiff to None to see it.
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to reset portal db in integration test prior to running the portal db test but after backing up the db."

**Comment by hannes-ucsc** [comment]
For demo, crash test (put sleep into code and send SIGKILL to process). Show that DB has test left-overs. Run test again without crashing it. Show that DB is reset.
