### ISSUE TITLE
Convert datetime values to strings before indexing

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3416]
Contents of a contribution are expected to be of type `MutableJSON`. To avoid the issues caused by having `datetime` values stored in the contents of a contribution, convert `datetime` values to strings during transformation before the contributions are written to the index, and keep the values as strings when read from the index.

**Comment by danielsotirhos** [comment]
This issue was discovered during implementation #3303 when the `matrices` and `contributor_matrices` inner entities were expanded to contain all the fields of the `file` inner entity instead of a small subset. Two of the previoulsly absent fields were `update_date` and `submission_date`. During aggregation, these `datetime` fields caused an AssertionError to be raised by the `SetOfDictAccumulator`. This exception can be manually replicated as shown below.

Note: Implementation of ticket #3303 has moved on to use a `DictAccumulator` instead of the `SetOfDictAccumulator`, so this error will once again not be observable in the existing code, however the need for this ticket as detailed in the ticket description is still valid.

```
>>> from azul.indexer.aggregate import SetOfDictAccumulator
>>> from operator import itemgetter
>>> from datetime import datetime
>>> a = SetOfDictAccumulator(max_size=100, key=itemgetter('uuid'))
>>> a.accumulate({'uuid': '1', 'update_date': '20210101T00:00:00Z'})  # works with a string
True
>>> a.accumulate({'uuid': '2', 'update_date': datetime(2021, 1, 1)})  # fails with a datetime
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/daniel/repo/azul1/src/azul/indexer/aggregate.py", line 160, in accumulate
    return super().accumulate(freeze(value))
  File "/Users/daniel/repo/azul1/src/azul/json_freeze.py", line 31, in freeze
    return frozendict((k, freeze(v)) for k, v in x.items())
  File "/Users/daniel/repo/azul1/src/azul/vendored/frozendict/__init__.py", line 57, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
  File "/Users/daniel/repo/azul1/src/azul/json_freeze.py", line 31, in <genexpr>
    return frozendict((k, freeze(v)) for k, v in x.items())
  File "/Users/daniel/repo/azul1/src/azul/json_freeze.py", line 37, in freeze
    assert False, f'Cannot handle values of type {type(x)}'
AssertionError: Cannot handle values of type <class 'datetime.datetime'>
```
