### ISSUE TITLE
catalog source string not sufficient for can_bundle.py script

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3436]
With the refactoring of the catalog source strings by https://github.com/DataBiosphere/azul/issues/2750 , the source strings listed in `environment.py` and/or in the output of `_refresh` is not sufficient as is for use with the `can_bundle.py` script.  To  use the script now the user must manually compose the source string by combining the source value from the `environment.py` +  `/` + `AZUL_PARTITION_PREFIX_LENGTH`.

```
(.venv) daniel@Crispin ~/repo/azul2 $ _select dev
remove .active? y
envhook.py: Currently disabled because the ENVHOOK environment variable is set to 0.
export_environment.py: Loading environment from deployments/dev/environment.local.py
export_environment.py: Loading environment from deployments/dev/environment.py
export_environment.py: Loading environment from environment.py
...
export_environment.py: Setting AZUL_DEPLOYMENT_STAGE to dev
export_environment.py: Setting AZUL_CATALOGS to '{"dcp2": {"atlas": "hca", "internal": false, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}, "dcp2ebi": {"atlas": "hca", "internal": false, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}, "lungmap": {"atlas": "lungmap", "internal": false, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}, "it2": {"atlas": "hca", "internal": true, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}, "it2ebi": {"atlas": "hca", "internal": true, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}, "it3lungmap": {"atlas": "lungmap", "internal": true, "plugins": {"metadata": {"name": "hca"}, "repository": {"name": "tdr"}}}}'
export_environment.py: Setting AZUL_PARTITION_PREFIX_LENGTH to 2
export_environment.py: Setting AZUL_TDR_SOURCES to tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:,tdr:broad-jade-dev-data:snapshot/hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622:
export_environment.py: Setting AZUL_TDR_DCP2EBI_SOURCES to tdr:broad-jade-dev-data:snapshot/hca_dev_20201023_ebiv4___20210302:
export_environment.py: Setting AZUL_TDR_IT2EBI_SOURCES to tdr:broad-jade-dev-data:snapshot/hca_dev_20201023_ebiv4___20210302:
export_environment.py: Setting AZUL_TDR_LUNGMAP_SOURCES to tdr:broad-jade-dev-data:snapshot/lungmap_dev_20210412__20210414:
export_environment.py: Setting AZUL_TDR_IT3LUNGMAP_SOURCES to tdr:broad-jade-dev-data:snapshot/lungmap_dev_20210412__20210414:
export_environment.py: Setting AZUL_TDR_SERVICE_URL to https://jade.datarepo-dev.broadinstitute.org
export_environment.py: Setting AZUL_SAM_SERVICE_URL to https://sam.dsde-dev.broadinstitute.org
...
export_environment.py: Setting project_root to /Users/daniel/repo/azul2
All AWS interactions initiated in this shell will use temporary session credentials from now on. Use '_deauth' or run 'source environment' again to revert the effect of this command.
lrwxr-xr-x  1 daniel  staff  3 Sep 16 10:44 .active -> dev

(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ python scripts/can_bundle.py -s 'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:' -b df9d55e0-02fc-0603-7b55-fc6ed2200824 -v 2021-05-24T16:47:59.709248Z
Traceback (most recent call last):
  File "scripts/can_bundle.py", line 100, in <module>
    main(sys.argv[1:])
  File "scripts/can_bundle.py", line 63, in main
    bundle = fetch_bundle(args.source, args.uuid, args.version)
  File "scripts/can_bundle.py", line 81, in fetch_bundle
    raise ValueError('No repository using this source')
ValueError: No repository using this source
(.venv) daniel@Crispin ~/repo/azul2 $
```

With debug output added to `can_bundle.py`:
```
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ python scripts/can_bundle.py -s 'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:' -b df9d55e0-02fc-0603-7b55-fc6ed2200824 -v 2021-05-24T16:47:59.709248Z
Checking dcp2 sources  {'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2', 'tdr:broad-jade-dev-data:snapshot/hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622:/2'}
Checking dcp2ebi sources  {'tdr:broad-jade-dev-data:snapshot/hca_dev_20201023_ebiv4___20210302:/2'}
Checking lungmap sources  {'tdr:broad-jade-dev-data:snapshot/lungmap_dev_20210412__20210414:/2'}
Checking it2 sources  {'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:/2', 'tdr:broad-jade-dev-data:snapshot/hca_dev_20210621_managedaccess_4298b4de92f34cbbbbfe5bc11b8c2422__20210622:/2'}
Checking it2ebi sources  {'tdr:broad-jade-dev-data:snapshot/hca_dev_20201023_ebiv4___20210302:/2'}
Checking it3lungmap sources  {'tdr:broad-jade-dev-data:snapshot/lungmap_dev_20210412__20210414:/2'}
Traceback (most recent call last):
  File "scripts/can_bundle.py", line 100, in <module>
    main(sys.argv[1:])
  File "scripts/can_bundle.py", line 63, in main
    bundle = fetch_bundle(args.source, args.uuid, args.version)
  File "scripts/can_bundle.py", line 81, in fetch_bundle
    raise ValueError('No repository using this source')
ValueError: No repository using this source
(.venv) daniel@Crispin ~/repo/azul2 $
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
