### ISSUE TITLE
Coveralls is failing across builds

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3446]
For at least these two PRs, coveralls fails with some sort of configuration error. Retrying the build did not seem to fix anything.

https://github.com/DataBiosphere/azul/pull/3444
https://github.com/DataBiosphere/azul/pull/3397

```
Run pip install coveralls==3.0.1
Collecting coveralls==3.0.1
  Downloading coveralls-3.0.1-py2.py3-none-any.whl (13 kB)
Collecting docopt>=0.6.1
  Downloading docopt-0.6.2.tar.gz (25 kB)
Collecting coverage<6.0,>=4.1
  Downloading coverage-5.5-cp38-cp38-manylinux2010_x86_64.whl (245 kB)
Collecting requests>=1.0.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Using legacy 'setup.py install' for docopt, since package 'wheel' is not installed.
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, docopt, coverage, coveralls
    Running setup.py install for docopt: started
    Running setup.py install for docopt: finished with status 'done'
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.6 coverage-5.5 coveralls-3.0.1 docopt-0.6.2 idna-3.2 requests-2.26.0 urllib3-1.26.6
Submitting coverage to coveralls.io...
Could not submit coverage: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/coveralls/api.py", line 257, in wear
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/coveralls/api.py", line 260, in wear
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```

**Comment by amarjandu** [comment]
I've been seeing this issue on my PR since Friday, perhaps coveralls is hitting some performance issues.

<img width="737" alt="Screen Shot 2021-09-20 at 11 14 56 AM" src="https://user-images.githubusercontent.com/1947534/134053248-c1f6d95d-e012-49dc-8607-d6d335927ef1.png">

**Comment by amarjandu** [comment]
https://status.coveralls.io/

**Comment by jessebrennan** [comment]
This incident is supposed to be resolved now https://status.coveralls.io/incidents/8zbjrwpb4frv

I'm re-running one of my builds to validate this.

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1632240236286000
