### ISSUE TITLE
Unable to filter on `accessions`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3505]
When attempting to use the filter 
```
{
    "accessions": {
        "is": [
            {
                "namespace": "array_express",
                "accession": "E-GEOD-84133"
            }
        ]
    }
}
```
The following traceback is returned

```
(.venv) CBSEspecter:azul amar$ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?catalog=dcp2&filters=%7B%0A%20%20%22accessions%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%22namespace%22%3A%20%22array_express%22%2C%20%22accession%22%3A%22E-GEOD-84133%22%7D%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&size=10&sort=projectTitle&order=asc'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 450
Content-Type: text/plain
Date: Wed, 06 Oct 2021 22:42:08 GMT
Via: 1.1 c361075814ee65e6523d12c5af3e7995.cloudfront.net (CloudFront)
X-Amz-Cf-Id: xA6QoGiREmGnq2jpdzczCao7ZwtLGXOGGyORgi-VBenS8zR_1ifjBw==
X-Amz-Cf-Pop: SFO5-C1
X-Amzn-Trace-Id: Root=1-615e263f-0ea98a484378b6fb1161ba1c;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: Gzrp8FxGoAMFtCw=
x-amzn-RequestId: 7372c89f-8d53-4cf6-b971-8e217d80d827

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1233, in get_project_data
    return repository_search('projects', project_id, filter_sources=False)
  File "/var/task/app.py", line 971, in repository_search
    return service.get_data(catalog=catalog,
  File "/var/task/azul/service/index_query_service.py", line 91, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 609, in transform_request
    es_search = self._create_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 304, in _create_request
    filters = self._translate_filters(catalog, filters, field_mapping)
  File "/var/task/azul/service/elasticsearch_service.py", line 132, in _translate_filters
    value = {
  File "/var/task/azul/service/elasticsearch_service.py", line 133, in <dictcomp>
    key: [field_type.to_index(v) for v in val]
  File "/var/task/azul/service/elasticsearch_service.py", line 133, in <listcomp>
    key: [field_type.to_index(v) for v in val]
AttributeError: 'dict' object has no attribute 'to_index'
```

As a user I would expect that accessions would be filterable to answer questions like `show me all projects that have accessions with the namespace "array_express"`

**Comment by theathorn** [comment]
Making high priority due to external user request.
