### ISSUE TITLE
Analysis subgraph exceeds ES request size limit

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#3527]
The newly added snapshot `tdr:datarepo-dev-560ee3d1:snapshot/hca_dev_83f5188e3bf749569544cea4f8997756__20210929_20211007` contains a problematic subgraph:

```
{
"bundle_uuid": "f4a19d21-7691-5d90-afc9-fcdd462e7529",
"bundle_version": "2021-10-06T17:32:00.000000Z"
}
```
```
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 155, in contribute
tallies = self.index_service.contribute(catalog, contributions)
File "/var/task/azul/indexer/index_service.py", line 201, in contribute
writer.write(contributions)
File "/var/task/azul/indexer/index_service.py", line 576, in write
self._write_bulk(documents)
File "/var/task/azul/indexer/index_service.py", line 613, in _write_bulk
for success, info in response:
File "/opt/python/elasticsearch/helpers/actions.py", line 218, in streaming_bulk
for data, (ok, info) in zip(
File "/opt/python/elasticsearch/helpers/actions.py", line 113, in _process_bulk_chunk
raise e
File "/opt/python/elasticsearch/helpers/actions.py", line 109, in _process_bulk_chunk
resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped
return func(*args, params=params, **kwargs)
File "/opt/python/elasticsearch/client/__init__.py", line 1556, in bulk
return self.transport.perform_request(
File "/opt/python/elasticsearch/transport.py", line 351, in perform_request
status, headers_response, data = connection.perform_request(
File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request
self._raise_error(response.status_code, raw_data)
File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(413, '{"Message":"Request size exceeded 104857600 bytes"}')
```

**Comment by achave11** [comment]
Latest reindex with fix to issue completed successfully. No notifications found in the fail queue.
