### ISSUE TITLE
Remove AZUL_PARTITION_PREFIX_LENGTH

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3530]
Trying to specify sources that use the default partition prefix length (ppl) can be awkward to use in practice.

The configuration for the deployment shows the source without a ppl specified.
```
from azul import config
config.catalogs['dcp2'].sources
{
...
dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5',  # <- no ppl specified
...
}
```

When attempting to use this sources as it specified within the configuration (no ppl) the script errors out.
```
(.venv) CBSEspecter:azul amar$ python scripts/reindex.py --index --source 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5' --catalog dcp2
2021-10-15 10:07:56,285 DEBUG   MainThread: Source glob 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5' matched sources [] in catalog 'dcp2'
2021-10-15 10:07:56,285 WARNING MainThread: Source(s) not found in any catalog: {'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5'}
Traceback (most recent call last):
  File "scripts/reindex.py", line 204, in <module>
    main(sys.argv[1:])
  File "scripts/reindex.py", line 148, in main
    require(any(sources_by_catalog.values()),
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 1192, in require
    reject(not condition, *args, exception=exception)
  File "/Users/amar/dev/hca/azul/src/azul/__init__.py", line 1211, in reject
    raise exception(*args)
azul.RequirementError: No valid sources specified for any catalog
```

The default ppl must be specified to match the source.
```
(.venv) CBSEspecter:azul amar$ python scripts/reindex.py --index --source 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0' --catalog dcp2 --no-slots
2021-10-15 10:25:36,794 DEBUG   MainThread: Source glob 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0' matched sources ['tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0'] in catalog 'dcp2'
2021-10-15 10:25:36,821 INFO    MainThread: Found credentials in environment variables.
2021-10-15 10:25:37,467 INFO    MainThread: Queuing notifications for reindexing ...
2021-10-15 10:25:37,468 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'filter': 'hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902', 'limit': '2'}, headers=None, body=None)
2021-10-15 10:25:38,220 DEBUG   MainThread: _request(…) -> b'{"total":139,"filteredTotal":1,"items":[{"id":"19510524-bbb9-4883-9228-fcbee947d27e","name":"hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","description":"Create snapshot hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","create...'
2021-10-15 10:25:38,221 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots/19510524-bbb9-4883-9228-fcbee947d27e', fields=None, headers=None, body=None)
2021-10-15 10:25:38,665 DEBUG   MainThread: _request(…) -> b'{"id":"19510524-bbb9-4883-9228-fcbee947d27e","name":"hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","description":"Create snapshot hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","createdDate":"2021-09-02T20:28:26.817671Z","so...'
2021-10-15 10:25:38,666 INFO    MainThread: Remotely reindexing prefix '' of source 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0' into catalog 'dcp2'
2021-10-15 10:25:39,311 DEBUG   MainThread: Queue azul-notifications-amar has 5 message(s) (0 available, 5 in flight and 0 delayed).
2021-10-15 10:25:39,399 DEBUG   MainThread: Queue azul-notifications_retry-amar has 0 message(s) (0 available, 0 in flight and 0 delayed).
2021-10-15 10:25:39,499 DEBUG   MainThread: Queue azul-tallies-amar.fifo has 0 message(s) (0 available, 0 in flight and 0 delayed).
2021-10-15 10:25:39,604 DEBUG   MainThread: Queue azul-tallies_retry-amar.fifo has 16 message(s) (0 available, 16 in flight and 0 delayed).
2021-10-15 10:25:39,604 INFO    MainThread: Counting 21 messages in 4 queues.
2021-10-15 10:25:39,604 INFO    MainThread: Message count history (most recent first) is [21].
```

Alternatively the wildcard `*` can be specified to match the source.
```
(.venv) CBSEspecter:azul amar$ python scripts/reindex.py --index --source 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:*' --catalog dcp2 --no-slots
2021-10-15 10:26:25,219 DEBUG   MainThread: Source glob 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:*' matched sources ['tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0'] in catalog 'dcp2'
2021-10-15 10:26:25,246 INFO    MainThread: Found credentials in environment variables.
2021-10-15 10:26:25,892 INFO    MainThread: Queuing notifications for reindexing ...
2021-10-15 10:26:25,893 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'filter': 'hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902', 'limit': '2'}, headers=None, body=None)
2021-10-15 10:26:26,640 DEBUG   MainThread: _request(…) -> b'{"total":139,"filteredTotal":1,"items":[{"id":"19510524-bbb9-4883-9228-fcbee947d27e","name":"hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","description":"Create snapshot hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","create...'
2021-10-15 10:26:26,641 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots/19510524-bbb9-4883-9228-fcbee947d27e', fields=None, headers=None, body=None)
2021-10-15 10:26:27,105 DEBUG   MainThread: _request(…) -> b'{"id":"19510524-bbb9-4883-9228-fcbee947d27e","name":"hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","description":"Create snapshot hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902","createdDate":"2021-09-02T20:28:26.817671Z","so...'
2021-10-15 10:26:27,105 INFO    MainThread: Remotely reindexing prefix '' of source 'tdr:datarepo-dev-0abea017:snapshot/hca_dev_6072616c87944b208f52fb15992ea5a4__20210827_20210902:b5/0' into catalog 'dcp2'
```

**Comment by amarjandu** [comment]
additional problems raised by the default partition prefix https://github.com/databiosphere/azul/issues/3544
