### ISSUE TITLE
/repository/files/summary is failing on dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#354]
_From @NoopDog on September 26, 2018 15:47_

https://service.dev.explore.data.humancellatlas.org/repository/files/summary?filters=%7B%7D

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 136, in get_data
    filters['file']['fileId'] = {"is": [file_id]}
KeyError: 'file'

_Copied from original issue: HumanCellAtlas/data-browser#245_

**Comment by hannes-ucsc** [comment]
_From @NoopDog on September 26, 2018 16:10_

moved to azul repo. closing.  https://github.com/DataBiosphere/azul/issues/353

**Comment by Ben-Wu** [comment]
@hannes-ucsc Wasn't the this endpoint removed here https://github.com/DataBiosphere/azul/pull/244 and `/repository/summary/files` was added?  So what's happening now is it's looking for a file with the id `summary`.
