### ISSUE TITLE
`deploy` job failed during `post_deploy` step in sandbox PR

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3556]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/31658#L5001
```
2021-10-18 19:10:50,757 DEBUG   MainThread: _request(…) -> b'{"message":"Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached","errorDetail":null}'
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 75, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 70, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 41, in verify_sources
    verify_source(source)
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 45, in verify_source
    tdr.check_api_access(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 437, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 446, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 536, in _check_response
    raise RequirementError('Unexpected response from TDR API', response.status)
azul.RequirementError: ('Unexpected response from TDR API', 500)
make[1]: *** [Makefile:91: post_deploy] Error 1
```

**Comment by achave11** [comment]
This issue wasn't raised in a consecutive [retry](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/31667#L1926).

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43820

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44485

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44625

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This hasn't occurred in months."
