### ISSUE TITLE
Download manifest crashes in `dev` for certain (large?) searches

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#356]
On https://dev.explore.data.humancellatlas.org/, (which points to https://service.integration.explore.data.humancellatlas.org for the back end)

1. Select Organ: Brain and File Format: Bam
1. Select "Download Manifest"
1. Select "Download Manifest"
1. the download fails with `{"message": "Internal server error"}`

The link in the browser window after the fail is listed below.

https://service.integration.explore.data.humancellatlas.org/repository/files/export?filters=%7B%22file%22:%7B%22organ%22:%7B%22is%22:%5B%22brain%22%5D%7D,%22fileFormat%22:%7B%22is%22:%5B%22bam%22%5D%7D%7D%7D&format=tarball

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-230)
┆Project Name: azul
┆Issue Number: AZUL-230

**Comment by theathorn** [comment]
@hannes-ucsc and  I believe this relates to work done by DNAStack in relation to SOW-4 Milestone 1.5 "Implement browser download Manifest with support for large file sets".

**Comment by shiroyuki** [comment]
I tried to replicate the same issue on my local machine but everything worked as expected.

So, I tried to hit the endpoint on the integration deployment directly and inspected into the CloudWatch log. Here is what I find.

<img width="1485" alt="screen shot 2018-09-28 at 12 23 51 pm" src="https://user-images.githubusercontent.com/226612/46221269-9e778880-c31a-11e8-9741-6da3f67d04a8.png">

> I see **HTTP 502** response from the endpoint.

<img width="1489" alt="screen shot 2018-09-28 at 12 24 09 pm" src="https://user-images.githubusercontent.com/226612/46221268-9e778880-c31a-11e8-8c37-479dff162641.png">

> The header indicates that CloudFront isssues **HTTP 502**. (The response body is misleading.)

<img width="1351" alt="screen shot 2018-09-28 at 12 25 14 pm" src="https://user-images.githubusercontent.com/226612/46221267-9e778880-c31a-11e8-9e36-75268222c64f.png">

> The log message indicates `body size is too long`. It just doesn't say who complains about the size.

Apparently, CloudFront imposes [the response size to be up to 20 GB](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html). So, I think compressing the raw response body with something like **gzip** will fix the issue. (FYI, #299 is still open).

**Comment by shiroyuki** [comment]
After further investigation, we believe that `body size is too long` is due to [the limitation on Lambda functions for web requests and sync invocation](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).

> ### AWS Lambda Limits
> #### AWS Lambda Resource Limits per Invocation
> | Resource | Limits |
> | --- | --- |
> | ... | ... |
> | Invoke request body payload size (RequestResponse/synchronous invocation) NOTE: The response body payload also must adhere to this limit. | 6 MB |

This limit (response body payload) is unfortunately non-increasable.

Hence, *while I'm writing a test code to confirm the issue*, I believe that we have at least two solutions to resolve this issue.

### Option 1: Migrate the download API from Lambda

We can set up a Flask app with the download API and deploy it to Elastic Container Service (ECS).

**Additional Requirements:**
* ECS requires a set of EC2 instances running 24/7.

**Pros:**
* No changes in the web service deployed Lambda
* Minimal code changes in `azul` package (in term of how the data is returned)
* Avoid other limits imposed on Lambda functions.

**Cons:**
* Increase the operational cost due to a set of EC2 instances to maintain.

### Option 2: Use S3 pre-signed URLs

So, instead of having the Lambda function respond the request direct, the Lambda function can push the content to a secure S3 bucket and then redirect the client to [a pre-signed URL](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html#generating-presigned-urls) to download the content.

**Additional Requirements:**
* A S3 bucket
* The code may need additional configuration with credentials to S3 buckets

**Pros:**
* No changes in architecture (everything is on Lambda)
* Avoid most of Lambda limits, except memory allocation.

**Cons:**
* Some Lambda limits still applies.

(@shiroyuki is confirming the issue.)

**Comment by hannes-ucsc** [comment]
Looks good. I think the signed URLs solution is simpler. We would only need to provision a bucket with a life-cycle rule using Terraform, stream the manifest to an object in S3, sign the URL and return a permanent redirect to it. That's no more than 50 lines of code. Very low risk. The key question (pun intended) is what we chose as the key for the object in S3. We could just do a pseudo-random one or hash all the request inputs to enable sharing of manifests.

We should estimate the bandwidth between a Lambda and an S3 bucket. Given that and the max. request time of 30s we can establish a max. size for the manifest. That's the first thing I would like to know: how big a manifest can we produce within 30s on Lambda.

**Comment by hannes-ucsc** [comment]
> se v4 UUID (and perhaps with other combination of random strings

Can you elaborate? My current thinking is that the key is either pseudo-random (in which case a v4 UUID is sufficient) or a deterministic hash of the manifest parameters (to allow for sharing).

> For this experiment, we will need to temporarily provision a private bucket.

Go for it. To state the obvious, the bucket needs to be in the same region as the lambda.

**Comment by shiroyuki** [comment]
@hannes-ucsc Personally I believe v4 UUID is easy to work with and good enough. I just wonder if there are other options.

By the way, I have done the experiment. Here is the data based on 200 requests where each request writes 100 MB of data to S3 with `s3_client.put_object`.

#### TRANSFER RATES (MB/s) ON 100 REQUESTS
| Min | Max | Average | Median |
| --- | --- | --- | --- |
| 10.766 MB/s | 58.000 MB/s | 42.229 MB/s | 43.314 MB/s |

#### ESTIMATE FILE SIZE (MB) IN LIMITED TIME

| Time Limit | Minimum | Average | Median |
| --- | --- | --- | --- |
| 5 SECONDS | 53.83 MB | 211.14 MB | 216.57 MB
| 10 SECONDS | 107.66 MB | 422.29 MB | 433.14 MB
| 15 SECONDS | 161.49 MB | 633.43 MB | 649.71 MB
| **20 SECONDS** | **215.31 MB** | 844.57 MB | 866.28 MB
| 25 SECONDS | 269.14 MB | 1055.72 MB | 1082.85 MB

So, to be conservative in this case, we can somehow guarantee that **the user can download the data within 200 MB without running into the 30-second time limit** with some room of the bottleneck at ElasticSearch.

<img width="1112" alt="screen shot 2018-10-01 at 4 17 46 pm" src="https://user-images.githubusercontent.com/226612/46313430-d807f800-c595-11e8-8c44-2623febc78d7.png">

**Comment by hannes-ucsc** [comment]
200MB should cover current manifest sizes. It's important that we stream the results from ES to the bucket. If we don't, it may take 20s to consume the ES results, leaving only 10s to store them in S3. In a future version we could even make that overlapping such that we're already requesting a manifest page from ES while the previous one is still streaming to S3.

**Comment by shiroyuki** [comment]
The implementation with Option 2 (pre-signed URLs) apparently provides a usable result. Based on the preliminary analysis and discussion with @hannes-ucsc, the bottleneck is in ES query where Python's ElasticSearch DSL sequentially scans each page of search result.

Here is the stat on the prototype.

> Please note that the size of the data we have on S3 is too small to prove that this approach would definitely help us mitigate the problem.

|     | Lowest (sec) | Highest (sec) | Average (sec) | Median (sec) |
| --- | ------ | ------- | ------- | ------ |
| ES Query Runtime | 1.198 | 1.532 | 1.304 | 1.290 |
| S3 Data Transfer Runtime | 0.053 | 0.284 | 0.098 | 0.089 |
| Total Runtime (without Network Latency) | 0.053 | 0.284 | 0.098 | 0.089 |

<img width="1113" alt="screen shot 2018-10-03 at 1 36 41 pm" src="https://user-images.githubusercontent.com/226612/46429233-eb40d200-c713-11e8-8cb8-42ae298177b6.png">

When we break down, here is the data regarding to the S3 data transfer runtime.
<img width="1113" alt="screen shot 2018-10-03 at 1 36 01 pm" src="https://user-images.githubusercontent.com/226612/46429235-eb40d200-c713-11e8-94b8-d5dc6f577df4.png">

When we break down, here is the data regarding to the ES query runtime.
<img width="1113" alt="screen shot 2018-10-03 at 1 35 19 pm" src="https://user-images.githubusercontent.com/226612/46429236-ebd96880-c713-11e8-91a9-cd1378ae2716.png">

**Comment by theathorn** [comment]
Evaluate enabling gzip compression as an alternative to putting the response in an S3 bucket.

**Comment by shiroyuki** [comment]
@hannes-ucsc, here is an update.

While I am still trying to figure out what is going on with `moto`. In order to confirm that **moto 1.3.6** does not work, I write a sample script.

```python
import logging
import boto3
from moto import mock_s3

def sample():
    with mock_s3():
        logger = logging.getLogger('sample')

        conn = boto3.resource('s3')
        conn.create_bucket(Bucket='sample')

        s3_client = boto3.client('s3')

        logger.warning(f'sample: (1) Using {str(s3_client._endpoint)}')

        s3_client.get_object(Bucket='sample', Key='something')

sample()
```

While I'm expecting `NoSuchKey` error, I got `requests.exceptions.ConnectionError`, which indicated that it still tried to make an outbound request to AWS instead.

```
→ python3 sample.py 
Traceback (most recent call last):
  File "sample.py", line 18, in <module>
    sample()
  File "sample.py", line 10, in sample
    conn.create_bucket(Bucket='sample')
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 173, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 157, in create_request
    operation_name=operation_model.name)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/signers.py", line 148, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/signers.py", line 227, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 508, in get_frozen_credentials
    self._refresh()
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 416, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 432, in _protected_refresh
    metadata = self._refresh_using()
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 556, in fetch_credentials
    return self._get_cached_credentials()
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 566, in _get_cached_credentials
    response = self._get_credentials()
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/credentials.py", line 688, in _get_credentials
    return client.assume_role(**kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 572, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 543, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused: POST https://sts.amazonaws.com/
```

This is just FYI as I am still looking into why it does not work.

Also, FYI, the current iteration of the PR now using `mock.patch`.

**Comment by shiroyuki** [comment]
@hannes-ucsc So, it seems that when **moto** is in used, `requests.get` (and probably including other methods) is also patched and none of requests is getting sent. From the traceback below, you will see that after the last invocation of `r = adapter.send(requet, **kwargs)` in `requests/sessions.py`, the execution is in `responses.py` (from **responses** used by **moto**).

```
======================================================================
ERROR: test_manifest (service.test_request_validation.FacetNameValidationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jnopporn/Projects/databiosphere/azul/test/service/test_request_validation.py", line 225, in test_manifest
    response = requests.get(url)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 572, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 543, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused: GET http://127.0.0.1:49662/repository/files/export?filters=%7B%22file%22%3A%7B%7D%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jnopporn/Projects/databiosphere/azul/test/service/test_request_validation.py", line 230, in test_manifest
    response = requests.get(url)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 572, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/responses.py", line 543, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused: GET http://127.0.0.1:49662/repository/files/export?filters=%7B%22file%22%3A%7B%7D%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/moto/core/models.py", line 75, in wrapper
    result = func(*args, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/.venv/lib/python3.7/site-packages/moto/core/models.py", line 75, in wrapper
    result = func(*args, **kwargs)
  File "/Users/jnopporn/Projects/databiosphere/azul/test/service/test_request_validation.py", line 245, in test_manifest
    raise Exception('Unexpected Error')
Exception: Unexpected Error

----------------------------------------------------------------------
```

In my opinion, while I agree with you that using **moto** with `test_storage_service.py` is the way to go, doing the same thing in `test_request_validation.py` might be a bit tricky.

What is your thought on this? Should we keep the docker approach only for this test?

**Comment by hannes-ucsc** [comment]
You won't be able to get rid of `requests` that easily.

**Comment by Ben-Wu** [comment]
Adding `responses.add_passthru('http://')` allows the test to run using moto in PR https://github.com/DataBiosphere/azul/pull/411
