### ISSUE TITLE
Lambda layer fails to upload to storage bucket (NoSuchBucket)

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3639]
Occurred while trying to setup the `prod2` instance.
Lambda Layer attempts to upload to a bucket that has not been setup.
 
```bash
(.venv) CBSEspecter:PROD amar$ make -C terraform plan
python /Users/amar/dev/hca/PROD/scripts/check_branch.py
python providers.tf.json.template.py providers.tf.json
Creating providers.tf.json
python backend.tf.json.template.py backend.tf.json
Creating backend.tf.json
terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 2.20.3...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.0...
- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...


Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512



Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512



Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512



Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512


Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
python api_gateway.tf.json.template.py api_gateway.tf.json
Creating api_gateway.tf.json
python authentication.tf.json.template.py authentication.tf.json
Creating authentication.tf.json
python cloudwatch.tf.json.template.py cloudwatch.tf.json
python common.tf.json.template.py common.tf.json
Creating common.tf.json
python dynamo.tf.json.template.py dynamo.tf.json
Creating dynamo.tf.json
python elasticsearch.tf.json.template.py elasticsearch.tf.json
python lambda_layer.tf.json.template.py lambda_layer.tf.json
Creating lambda_layer.tf.json
python modules.tf.json.template.py modules.tf.json
Creating modules.tf.json
python route53_health_check.tf.json.template.py route53_health_check.tf.json
python s3.tf.json.template.py s3.tf.json
Creating s3.tf.json
python sqs.tf.json.template.py sqs.tf.json
Creating sqs.tf.json
python step_function.tf.json.template.py step_function.tf.json
Creating step_function.tf.json
/Library/Developer/CommandLineTools/usr/bin/make -C /Users/amar/dev/hca/PROD/lambdas
/Library/Developer/CommandLineTools/usr/bin/make -C layer package
python /Users/amar/dev/hca/PROD/scripts/check_branch.py
python .chalice/config.json.template.py .chalice/config.json
Creating .chalice/config.json
rm -rf vendor
unzip /Users/amar/dev/hca/PROD/lambdas/.wheels/jsonobject-0.9.9-cp38-cp38-linux_x86_64.whl -d vendor
Archive:  /Users/amar/dev/hca/PROD/lambdas/.wheels/jsonobject-0.9.9-cp38-cp38-linux_x86_64.whl
  inflating: vendor/jsonobject/__init__.py
  inflating: vendor/jsonobject/api.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject/base.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject/base_properties.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject/containers.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject/exceptions.py
  inflating: vendor/jsonobject/properties.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject/utils.cpython-38-x86_64-linux-gnu.so
  inflating: vendor/jsonobject-0.9.9.dist-info/LICENSE
  inflating: vendor/jsonobject-0.9.9.dist-info/METADATA
  inflating: vendor/jsonobject-0.9.9.dist-info/WHEEL
  inflating: vendor/jsonobject-0.9.9.dist-info/top_level.txt
  inflating: vendor/jsonobject-0.9.9.dist-info/RECORD
python /Users/amar/dev/hca/PROD/scripts/stage_layer.py
2021-11-10 12:49:13,822 INFO    MainThread: Checking for dependencies layer package at s3://edu-ucsc-gi-azul-dcp2-prod-storage-prod2/lambda_layers/cd7b4788efe93aabea835ae0840edff47bdeac20.zip.
2021-11-10 12:49:13,850 INFO    MainThread: Found credentials in environment variables.
2021-11-10 12:49:14,328 INFO    MainThread: Generating new layer package ...
2021-11-10 12:49:14,328 DEBUG   MainThread: Generating requirements file for layer ...
2021-11-10 12:49:14,329 DEBUG   MainThread: Filtering out vendored requirements [Requirement(name='jsonobject', version='0.9.9', git=False)]
2021-11-10 12:49:14,330 DEBUG   MainThread: Removing Chalice's deployment cache at '/Users/amar/dev/hca/PROD/lambdas/layer/.chalice/deployments'
2021-11-10 12:49:14,330 INFO    MainThread: Running ['chalice', 'package', PosixPath('/Users/amar/dev/hca/PROD/lambdas/layer/.chalice/terraform')]
Creating deployment package.
2021-11-10 12:50:02,898 INFO    MainThread: Packaging /Users/amar/dev/hca/PROD/lambdas/layer/.chalice/terraform/layer.zip
2021-11-10 12:50:07,065 INFO    MainThread: Uploading layer package to S3 ...
Traceback (most recent call last):
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/s3transfer/tasks.py", line 332, in _main
    response = client.create_multipart_upload(
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amar/dev/hca/PROD/scripts/stage_layer.py", line 31, in <module>
    main(sys.argv[1:])
  File "/Users/amar/dev/hca/PROD/scripts/stage_layer.py", line 26, in main
    layer.update_layer()
  File "/Users/amar/dev/hca/PROD/src/azul/lambda_layer.py", line 111, in update_layer
    self.s3.upload_file(str(layer_zip), config.lambda_layer_bucket, self.object_key)
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/Users/amar/dev/hca/PROD/.venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 285, in upload_file
    raise S3UploadFailedError(
boto3.exceptions.S3UploadFailedError: Failed to upload /Users/amar/dev/hca/PROD/lambdas/layer/.chalice/terraform/layer.zip to edu-ucsc-gi-azul-dcp2-prod-storage-prod2/lambda_layers/cd7b4788efe93aabea835ae0840edff47bdeac20.zip: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist
make[2]: *** [package] Error 1
make[1]: *** [layer] Error 2
make: *** [lambdas] Error 2
(.venv) CBSEspecter:PROD amar$
```

**Comment by amarjandu** [comment]
Also note that a lambda layer should not be deployed when `make -C terraform plan` is ran.

**Comment by amarjandu** [comment]
Consider moving the `layers` to the config bucket under the prefix `layers/{AZUL_DEPLOYMENT_STAGE}`, rather than the deployment storage bucket.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Move layer to deployment specific location within config bucket. What the exact path is remains to be determined."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
