### ISSUE TITLE
Freak bundles exceed size limit on SQS message batch

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#365]
```
[WARNING]	2018-10-02T00:43:45.938Z	03a0871b-596d-56af-bf29-d337985bc8f3	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.biomaterial_json'}}]}}}, 'subscription_id': '64ee919d-39d3-45de-a347-892723aa6612', 'transaction_id': '8c4a3b83-26ce-4afe-b5f1-c5568142a645', 'match': {'bundle_uuid': '4afbb0ea-81ad-49dc-9b12-9f77f4f50be8', 'bundle_version': '2018-03-29T090403.442059Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 123, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 63, in index
    self.document_handler(indexable_documents)
  File "/var/task/app.py", line 149, in handle_documents
    for i, doc in enumerate(batch)])
  File "/var/task/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/task/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/var/task/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BatchRequestTooLong: An error occurred (AWS.SimpleQueueService.BatchRequestTooLong) when calling the SendMessageBatch operation: Batch requests cannot be longer than 262144 bytes. You have sent 323435 bytes.
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-236)
┆Project Name: azul
┆Issue Number: AZUL-236

**Comment by hannes-ucsc** [comment]
This could be addressed by catching BatchRequestTooLong and resubmitting messages individually if it occurs.
