### ISSUE TITLE
`test_snapshot_listing` IT fails with less than 6 snapshots (#3662)

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3662]
The `dcp10` catalog in `prod2` only specifies 2 sources within the configuration, the test does not account for the total number of snapshots being less than the page count.

```
======================================================================
FAIL: test_snapshot_listing (integration_test.IndexingIntegrationTest)
Test with a small page size to be sure paging works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/amar/dev/hca/PROD/test/azul_test_case.py", line 154, in wrapped
    return method(*args, **kwargs)
  File "/Users/amar/dev/hca/PROD/test/integration_test.py", line 289, in test_snapshot_listing
    self.assertGreater(len(paged_snapshots), page_size)
AssertionError: 2 not greater than 5

----------------------------------------------------------------------
```

Full `IT` run https://gitlab.dev.singlecell.gi.ucsc.edu/-/snippets/21

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "Test needs to be smarter and dynamically choose the page size so that there are 2 pages."

**Comment by amarjandu** [comment]
This test wont fail anymore because there are now 12 snapshots that available to the service account.
