### ISSUE TITLE
`previous` link broken with page size of one

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3732]
I found this while working on #3715. The command below requests the first page of size one, follows the link to the next page and then attempts to follow the `previous` link on that second page. It is expected to return the first page but instead yields a 500 response.

```
$ curl -vs $(curl -s $(curl -s 'https://service.azul.data.humancellatlas.org/index/files?filters=%7B%7D&sort=fileName&order=asc&catalog=dcp12&size=1' | jq -r .pagination.next) | jq -r .pagination.previous)
*   Trying 13.35.121.9:443...
* Connected to service.azul.data.humancellatlas.org (13.35.121.9) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=service.azul.data.humancellatlas.org
*  start date: Oct 19 00:00:00 2021 GMT
*  expire date: Nov 16 23:59:59 2022 GMT
*  subjectAltName: host "service.azul.data.humancellatlas.org" matched cert's "service.azul.data.humancellatlas.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55f853c4d5e0)
> GET /index/files?catalog=dcp12&filters=%7B%22sourceId%22%3A+%7B%22is%22%3A+%5B%22a71a8575-1ba0-4895-b8b9-3685a8c056d1%22%5D%7D%7D&sort=fileName&order=asc&size=1&search_before=%22%5C%2200027d78-bcde-444c-b51c-b7446cdf9ea9_qc.bam.bai%5C%22%22&search_before_uid=doc%23f1671e87-3e05-57a0-aaa7-384d750691cd HTTP/2
> Host: service.azul.data.humancellatlas.org
> user-agent: curl/7.74.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500 
< content-type: text/plain
< content-length: 984
< date: Tue, 11 Jan 2022 20:35:07 GMT
< x-amzn-requestid: add1f094-269e-4696-8614-175cbc863303
< access-control-allow-origin: *
< access-control-allow-headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
< x-amz-apigw-id: LzF-1E2hIAMFs0A=
< x-amzn-trace-id: Root=1-61dde9f8-450be86e79ebd23762b43cfa;Sampled=0
< x-cache: Error from cloudfront
< via: 1.1 208eb126ebe99fd5accb034c84a1eeca.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C1
< x-amz-cf-id: YMjhl9dy8drIxU5BFSolSFyoEMrMULduBIhuMdY5loi0o5D4STCyGA==
< 
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1206, in get_data
    return repository_search('files', file_id)
  File "/var/task/app.py", line 970, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 77, in search
    response = self.service.get_data(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 80, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 669, in transform_request
    paging = self._generate_paging_dict(catalog, filters, es_response_dict, pagination)
  File "/var/task/azul/service/elasticsearch_service.py", line 473, in _generate_paging_dict
    search_after = es_hits[0]['sort']
IndexError: list index out of range
```

With a page size of 2 it works:

```
hannes@hannes-xps:~$ curl -vs $(curl -s $(curl -s 'https://service.azul.data.humancellatlas.org/index/files?filters=%7B%7D&sort=fileName&order=asc&catalog=dcp12&size=2' | jq -r .pagination.next) | jq -r .pagination.previous) | jq | head
*   Trying 13.35.121.80:443...
* Connected to service.azul.data.humancellatlas.org (13.35.121.80) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4985 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=service.azul.data.humancellatlas.org
*  start date: Oct 19 00:00:00 2021 GMT
*  expire date: Nov 16 23:59:59 2022 GMT
*  subjectAltName: host "service.azul.data.humancellatlas.org" matched cert's "service.azul.data.humancellatlas.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x558ebde465e0)
} [5 bytes data]
> GET /index/files?catalog=dcp12&filters=%7B%22sourceId%22%3A+%7B%22is%22%3A+%5B%22a71a8575-1ba0-4895-b8b9-3685a8c056d1%22%5D%7D%7D&sort=fileName&order=asc&size=2&search_before=%220002c6a2-eea8-4e55-a122-642888777d4d_qc.bam%22&search_before_uid=doc%23d90b23a8-6ee4-5ff9-96a9-751ed400313d HTTP/2
> Host: service.azul.data.humancellatlas.org
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 200 
< content-type: application/json
< content-length: 206118
< date: Tue, 11 Jan 2022 20:35:53 GMT
< x-amzn-requestid: 0c5651c0-5e18-4ff3-95d7-6c02b17d66bd
< access-control-allow-origin: *
< access-control-allow-headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
< x-amz-apigw-id: LzGF2EYEIAMFytQ=
< x-amzn-trace-id: Root=1-61ddea25-07bcae3f2e8e71f0518e5187;Sampled=0
< x-cache: Miss from cloudfront
< via: 1.1 4d573cd6a6c0581b92beae04909c3dce.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO5-C1
< x-amz-cf-id: YRUeC5ZLQFhJyUpfyiRVKL5PSS2A3NsNbl5RmyHVagPWcnEiTgQ9JA==
< 
{ [15938 bytes data]
* Connection #0 to host service.azul.data.humancellatlas.org left intact
{
  "hits": [
    {
      "protocols": [
        {
          "submissionDate": "2021-11-15T19:11:22.000000Z",
          "updateDate": null,
          "workflow": [
            "MultiSampleSmartSeq2_v2.2.6",
            "SmartSeq2SingleSample_v5.1.5"
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce on `prod`.
