### ISSUE TITLE
BdBag mainfest request with no filters fails

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#3778]
The requests …
```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?format=terra.bdbag'
HTTP/1.1 200 OK
…
{
    "CommandLine": {
        "bash": "curl 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiOTQ3NmZiYmMtNTNlMS00MDg4LWExMmYtNmI4NDU2ZmY0NjFmIiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D'",
        "cmd.exe": "curl.exe \"https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiOTQ3NmZiYmMtNTNlMS00MDg4LWExMmYtNmI4NDU2ZmY0NjFmIiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D\""
    },
    "Location": "https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiOTQ3NmZiYmMtNTNlMS00MDg4LWExMmYtNmI4NDU2ZmY0NjFmIiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D",
    "Retry-After": 1,
    "Status": 301
}
```
… failed after requesting the provided URL. 
```
HTTP/1.1 500 Internal Server Error
…
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1489, in fetch_file_manifest
    return _file_manifest(fetch=True)
  File "/var/task/app.py", line 1509, in _file_manifest
    return app.manifest_controller.get_manifest_async(self_url=app.self_url(),
  File "/var/task/azul/service/manifest_controller.py", line 137, in get_manifest_async
    token_or_state = self.async_service.inspect_generation(token)
  File "/var/task/azul/service/async_manifest_service.py", line 99, in inspect_generation
    raise StateMachineError(status, output)
azul.service.step_function_helper.StateMachineError: ('Failed to generate manifest', 'FAILED', None)
```
The [step function execution](https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:122796619775:execution:azul-manifest-dev:9476fbbc-53e1-4088-a12f-6b8456ff461f) for this request yield the following ExecutionFailed output:
```
{
  "error": "OSError",
  "cause": {
    "errorMessage": "[Errno 28] No space left on device",
    "errorType": "OSError",
    "stackTrace": [
      "  File \"/var/task/chalice/app.py\", line 1564, in __call__\n    return self.handler(event_obj)\n",
      "  File \"/var/task/chalice/app.py\", line 1517, in __call__\n    return self._original_func(event.to_dict(), event.context)\n",
      "  File \"/var/task/app.py\", line 1520, in generate_manifest\n    return app.manifest_controller.get_manifest(event)\n",
      "  File \"/var/task/azul/service/manifest_controller.py\", line 74, in get_manifest\n    result = self.service.get_manifest(format_=ManifestFormat(state['format_']),\n",
      "  File \"/var/task/azul/service/manifest_service.py\", line 375, in get_manifest\n    partition = generator.write(object_key, partition)\n",
      "  File \"/var/task/azul/service/manifest_service.py\", line 1031, in write\n    file_path, base_name = self.create_file()\n",
      "  File \"/var/task/azul/service/manifest_service.py\", line 1461, in create_file\n    self._samples_tsv(samples_tsv)\n",
      "  File \"/var/task/azul/service/manifest_service.py\", line 1639, in _samples_tsv\n    bundle_tsv_writer.writerow(row)\n",
      "  File \"/var/lang/lib/python3.8/csv.py\", line 154, in writerow\n    return self.writer.writerow(self._dict_to_list(rowdict))\n"
    ]
  }
}
```
However the execution report logs in CW did not indicate the step function execution went over the allot memory.
```
REPORT RequestId: 53b4a349-0e3f-4bdc-b8f9-31df2300765e Duration: 248876.90 ms Billed Duration: 248877 ms Memory Size: 2048 MB Max Memory Used: 1444 MB Init Duration: 1922.80 ms
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc to evaluate.

**Comment by hannes-ucsc** [comment]
Good catch. The temporary disk space of the Lambda function is running out, not the RAM. It is limited to 512 MB (look for `/tmp`):

https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html 

If we decide to support BDBag long term, we should find a way to compose the BDBag in memory or even stream it.

**Comment by hannes-ucsc** [comment]
BDBag has largely been replaced with PFB.
