### ISSUE TITLE
AssertionError in _generate_paging_dict

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3786]
```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/files?filters=%7B%7D&size=25&catalog=dcp2'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1225, in get_data
    return repository_search('files', file_id)
  File "/var/task/app.py", line 989, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 76, in search
    response = self.service.get_data(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 72, in get_data
    response = self.transform_request(catalog=catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 714, in transform_request
    paging = self._generate_paging_dict(catalog,
  File "/var/task/azul/service/elasticsearch_service.py", line 483, in _generate_paging_dict
    assert total['relation'] == 'eq'
AssertionError
```

**Comment by hannes-ucsc** [comment]
```
$ curl -s 'https://service.dev.singlecell.gi.ucsc.edu/version' | jq .git
{
  "commit": "a7a5abf1fdd295547cca1d13ffdd37e8d40d2f15",
  "dirty": false
}
$ curl -s 'https://service.dev.singlecell.gi.ucsc.edu/index/files?filters=%7B%7D&size=25&catalog=dcp2' | jq .pagination
{
  "count": 25,
  "total": 115168,
  "size": 25,
  "next": "https://service.dev.singlecell.gi.ucsc.edu/index/files?catalog=dcp2&filters=%7B%7D&search_after=%5B%22012319CORTEX_HHT_S3_L007_R1_001.fastq.gz%22%2C+%2214e3540b-737b-4a67-b7a9-e7d3a8bdf222%22%5D&sort=fileName&order=asc&size=25",
  "previous": null,
  "pages": 4607,
  "sort": "fileName",
  "order": "asc"
}
```
