### ISSUE TITLE
`scripts/kibana_proxy.py` fails to connect to ES 

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3787]
Unable to use `kibana_proxy.py` to interface with ES, see below.

```
CBSEspecter:azul amar$ python scripts/kibana_proxy.py
2022-01-26 14:14:02,536 INFO    MainThread: Found credentials in environment variables.
2022-01-26 14:14:02,536 INFO    MainThread: Getting domain endpoint
2022-01-26 14:14:03,595 INFO    ThreadPoolExecutor-0_2: proxy: Listening on :5603
2022-01-26 14:14:06,802 INFO    ThreadPoolExecutor-0_4: cerebro: WARNING: An illegal reflective access operation has occurred
2022-01-26 14:14:06,803 INFO    ThreadPoolExecutor-0_4: cerebro: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cerebro/lib/com.google.inject.guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
2022-01-26 14:14:06,803 INFO    ThreadPoolExecutor-0_4: cerebro: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
2022-01-26 14:14:06,803 INFO    ThreadPoolExecutor-0_4: cerebro: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2022-01-26 14:14:06,803 INFO    ThreadPoolExecutor-0_4: cerebro: WARNING: All illegal access operations will be denied in a future release
2022-01-26 14:14:08,536 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:kibana@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,578 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:elasticsearch@6.8.0","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,585 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:console@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,592 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:interpreter@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,600 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:metrics@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,611 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:tile_map@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:08,788 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:08Z","tags":["status","plugin:timelion@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
2022-01-26 14:14:09,292 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:09Z","tags":["warning"],"pid":1,"kibanaVersion":"6.8.0","nodes":[{"version":"7.10.2","http":{}},{"version":"7.10.2","http":{}}],"message":"You're running Kibana 6.8.0 with some different versions of Elasticsearch. Update Kibana or Elasticsearch to the same version to prevent compatibility issues: v7.10.2 @ (undefined), v7.10.2 @ (undefined)"}
2022-01-26 14:14:09,380 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:09Z","tags":["status","plugin:elasticsearch@6.8.0","info"],"pid":1,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
2022-01-26 14:14:09,478 INFO    ThreadPoolExecutor-0_3: kibana: {"type":"log","@timestamp":"2022-01-26T22:14:09Z","tags":["fatal","root"],"pid":1,"message":"Error: Index .kibana_1 belongs to a version of Kibana that cannot be automatically migrated. Reset it or use the X-Pack upgrade assistant.\n    at assertIsSupportedIndex (/usr/share/kibana/src/server/saved_objects/migrations/core/elastic_index.js:246:15)\n    at Object.fetchInfo (/usr/share/kibana/src/server/saved_objects/migrations/core/elastic_index.js:52:12)"}
2022-01-26 14:14:09,482 INFO    ThreadPoolExecutor-0_3: kibana:
2022-01-26 14:14:09,482 INFO    ThreadPoolExecutor-0_3: kibana:  FATAL  Error: Index .kibana_1 belongs to a version of Kibana that cannot be automatically migrated. Reset it or use the X-Pack upgrade assistant.
2022-01-26 14:14:09,483 INFO    ThreadPoolExecutor-0_3: kibana:
2022-01-26 14:14:10,377 INFO    ThreadPoolExecutor-0_4: cerebro: [info] play.api.Play - Application started (Prod) (no global state)
2022-01-26 14:14:11,063 INFO    ThreadPoolExecutor-0_4: cerebro: [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:5602
2022-01-26 14:14:13,132 INFO    ThreadPoolExecutor-0_1: Now open Kibana at http://127.0.0.1:5601/ and open Cerebro at http://127.0.0.1:5602/#/overview?host=http://localhost:5603 (or paste in http://localhost:5603)
```

<img width="963" alt="Screen Shot 2022-01-26 at 2 17 34 PM" src="https://user-images.githubusercontent.com/1947534/151256360-5f42179b-8e12-432f-9505-821ffcf80064.png">

**Comment by hannes-ucsc** [comment]
This fixes it

```diff
Index: scripts/kibana_proxy.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/kibana_proxy.py b/scripts/kibana_proxy.py
--- a/scripts/kibana_proxy.py	(revision ab6f2e75b5dde63a15cabcc30626e77747cd46f1)
+++ b/scripts/kibana_proxy.py	(date 1643305169015)
@@ -90,7 +90,7 @@
                                           },
                                           ports={port: port for port in (kibana_port, cerebro_port, proxy_port)})
             containers.append(proxy)
-            kibana = self.create_container('docker.elastic.co/kibana/kibana-oss:6.8.0',
+            kibana = self.create_container('docker.elastic.co/kibana/kibana-oss:7.10.2',
                                            name='kibana',
                                            auto_remove=True,
                                            detach=True,
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
