### ISSUE TITLE
SerializationError during aggregation

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3812]
A particular batch of ten tallies (see repro script for which batch) causes a truncation of the response from ES. This is the significant log line from CloudWatch:

```
[WARNING] 2022-01-31T20:16:48.693Z 54ebca26-0695-5476-9b52-9054435900b8 Failed to aggregate tallies: dict_values([[DocumentTally(entity=CataloguedEntityReference(entity_type='bundles', entity_id='1ff434bc-1e06-4393-bd96-d900cbb4f043', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='bundles', entity_id='65fb0556-5c44-4469-927c-61f27f81d1ac', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='cell_suspensions', entity_id='1b4b6475-b1d3-4559-9bf8-ac84fe68056e', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='files', entity_id='312d3dcd-ae0f-44c9-9689-192448b340ca', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='files', entity_id='68f2d720-20f6-4528-820b-9f1d1260ff0c', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='files', entity_id='9ab411aa-7f98-485e-a08c-288d5365e355', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='files', entity_id='d1164695-0037-4ca3-b1ed-77e1b8388652', catalog='dcp1'), num_contributions=1, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='projects', entity_id='5b328561-4a97-40ac-b7ad-6a90fc59d374', catalog='dcp12'), num_contributions=6, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='samples', entity_id='5e55b109-4a62-420d-ab8d-92fac12656c1', catalog='dcp12'), num_contributions=6, attempts=9)], [DocumentTally(entity=CataloguedEntityReference(entity_type='samples', entity_id='76fb9be1-9dcd-4f2e-a14c-86f23969a1de', catalog='dcp12'), num_contributions=6, attempts=9)]])
Traceback (most recent call last):
File "/opt/python/elasticsearch/serializer.py", line 120, in loads
return json.loads(s)
File "/var/lang/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/var/lang/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/var/lang/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 371414080 (char 371414079)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 263, in aggregate
self.index_service.aggregate(tallies)
File "/var/task/azul/indexer/index_service.py", line 395, in aggregate
contributions = self._read_contributions(total_tallies)
File "/var/task/azul/indexer/index_service.py", line 529, in _read_contributions
contributions = [
File "/var/task/azul/indexer/index_service.py", line 529, in <listcomp>
contributions = [
File "/opt/python/elasticsearch/helpers/actions.py", line 524, in scan
resp = client.search(
File "/opt/python/elasticsearch/client/utils.py", line 152, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
File "/opt/python/elasticsearch/client/__init__.py", line 1658, in search
return self.transport.perform_request(
File "/opt/python/elasticsearch/transport.py", line 402, in perform_request
data = self.deserializer.loads(
File "/opt/python/elasticsearch/serializer.py", line 166, in loads
return deserializer.loads(s)
File "/opt/python/elasticsearch/serializer.py", line 122, in loads
raise SerializationError(s, e)
elasticsearch.exceptions.SerializationError: ('{"_scroll_id":"FGluY2x1...snip...REVETGc=",
"took":356,
"timed_out":false,
"_shards":{"total":185,"successful":185,"skipped":0,"failed":0},
"hits":{"total":{"value":1169,"relation":"eq"},
"max_score":null,
"hits":[{"_index":"azul_v2_prod_dcp12_projects","_type":"_doc","_id":"5b328561-4a97-40ac-b7ad-6a90fc59d374_00df54a7-2616-4263-b14b-1f17e5a157ec_2021-11-22T11:14:07.712000Z_exists","_score":null,"_source":{"entity_id":"5b328561-4a97-40ac-b7ad-6a90fc59d374","contents":...snip...
```

(truncated and line breaks added for readability)

I was able to reliably reproduce this locally using the following script with `prod` checked out and selected:

```python
from azul.indexer.document import CataloguedEntityReference
from azul.indexer.index_controller import DocumentTally
from azul.indexer.index_service import IndexService
from azul.logging import (
    configure_script_logging,
)

configure_script_logging()

tallies = [
    DocumentTally(entity=CataloguedEntityReference(entity_type='bundles',
                                                   entity_id='1ff434bc-1e06-4393-bd96-d900cbb4f043',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='bundles',
                                                   entity_id='65fb0556-5c44-4469-927c-61f27f81d1ac',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='cell_suspensions',
                                                   entity_id='1b4b6475-b1d3-4559-9bf8-ac84fe68056e',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='files',
                                                   entity_id='312d3dcd-ae0f-44c9-9689-192448b340ca',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='files',
                                                   entity_id='68f2d720-20f6-4528-820b-9f1d1260ff0c',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='files',
                                                   entity_id='9ab411aa-7f98-485e-a08c-288d5365e355',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='files',
                                                   entity_id='d1164695-0037-4ca3-b1ed-77e1b8388652',
                                                   catalog='dcp1'),
                  num_contributions=1,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='projects',
                                                   entity_id='5b328561-4a97-40ac-b7ad-6a90fc59d374',
                                                   catalog='dcp12'),
                  num_contributions=6,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='samples',
                                                   entity_id='5e55b109-4a62-420d-ab8d-92fac12656c1',
                                                   catalog='dcp12'),
                  num_contributions=6,
                  attempts=9),
    DocumentTally(entity=CataloguedEntityReference(entity_type='samples',
                                                   entity_id='76fb9be1-9dcd-4f2e-a14c-86f23969a1de',
                                                   catalog='dcp12'),
                  num_contributions=6,
                  attempts=9)
]

tallies = {
    tally.entity: tally.num_contributions
    for tally in tallies
}

service = IndexService()

service._read_contributions(tallies)

```

The script raises the same exception.

It looks like ES is returning a content length header promising 400MiB but the exhaustively reading from the socket yields fewer bytes than that (3/4 approximately).

Another user of ES (not AWS OpenSearch) [reported](https://github.com/elastic/elasticsearch-py/issues/805) the same exception being caused by a faulty proxy. I'm sure Amazon proxies ES as well so it may be that Amazon truncates the response. From the stacktrace it is evident that the response is being read using `scan()`. I think that the large response is caused by a single document, so making the scan()-size smaller won't help.

**Comment by hannes-ucsc** [comment]
@amarjandu [reported on Slack](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1643741830363459?thread_ts=1643735864.856479&cid=C705Y6G9Z) that processing each tally individually succeeded in one attempt for nine of the tallies, and two attempts for one (the `projects` tally in the batch).

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce in prod.
