### ISSUE TITLE
Transient failure while running IT in sandbox deployment

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3834]
The `managed_access` subtest in `test_indexing` fails occasionally for the IT GitLab job. This was [observed](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/38929#L1558) in a recent `sandbox` deployment pipeline.
```
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 520, in one
    value = next(it)
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 272, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 938, in _test_managed_access
    public_bundle = one(response['hits'])['entryId']
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 522, in one
    raise too_short or ValueError('too few items in iterable (expected 1)')
ValueError: too few items in iterable (expected 1)
----------------------------------------------------------------------
Ran 16 tests in 734.115s
FAILED (errors=1, skipped=3)
make: *** [Makefile:168: integration_test] Error 1
```

**Comment by melainalegaspi** [comment]
@noah-aviel-dove spike to evaluate.

**Comment by noah-aviel-dove** [comment]
This is a bug that occurs when the managed access IT filters the /index/bundles/ endpoint for sources that are configured for the IT catalog but had none of their bundles indexed during the IT. Proposed fix (verified with the seed from the linked GitLab failure):

```diff
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision fd296f5e90ab365e8d6acf7fdb5ddea54931891b)
+++ b/test/integration_test.py	(date 1644540604202)
@@ -931,7 +931,7 @@
                 for bundle in hits
                 if len(bundle['sources']) == 1
             ]
-            filters = {'sourceId': {'is': [first(public_source_ids)]}}
+            filters = {'sourceId': {'is': [first(public_source_ids & indexed_source_ids)]}}
             params = {'size': 1, 'catalog': catalog, 'filters': json.dumps(filters)}
             bundles_url = furl(service, path='index/bundles', args=params)
             response = self._get_url_json(str(bundles_url))
```

**Comment by achave11** [comment]
This failure now prevents IT in GL `dev` to pass. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/39050
