### ISSUE TITLE
Missing indices for dcp13 in prod2 caused unindexed tallies

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#3881]
After promoting `prod2` with the new dcp13 catalog, the following command…
```
python scripts/reindex.py --catalogs dcp13 --index
```
… was intended for indexing only the dcp13 catalog. However, I failed to recall the changes in [ Fix: make create fails on fully populated indices (#3862) #3863 ](https://github.com/DataBiosphere/azul/pull/3863) et all and their potential influence in this. After verifying the cause of the failure in the logs…
```
<span>

@message | [ERROR] RuntimeError:  ('Malformed document', {'_index':  'azul_v2_prod2_dcp13_bundles_aggregate', '_type': None, '_id':  '9fab6aeb-6b2f-421f-9c61-a31feb70825c', 'error': {'root_cause':  [{'type': 'index_not_found_exception', 'reason': 'no such index  [azul_v2_prod2_dcp13_bundles_aggregate]', 'resource.type':  'index_expression', 'resource.id':  'azul_v2_prod2_dcp13_bundles_aggregate', 'index_uuid': '_na_', 'index':  'azul_v2_prod2_dcp13_bundles_aggregate'}], 'type':  'index_not_found_exception', 'reason': 'no such index  [azul_v2_prod2_dcp13_bundles_aggregate]', 'resource.type':  'index_expression', 'resource.id':  'azul_v2_prod2_dcp13_bundles_aggregate', 'index_uuid': '_na_', 'index':  'azul_v2_prod2_dcp13_bundles_aggregate'}})Traceback (most recent call last):  File "/var/task/app.py", line 120, in new_handler    return old_handler(self, event, context)  File "/var/task/chalice/app.py", line 1564, in __call__    return self.handler(event_obj)  File "/var/task/app.py", line 144, in aggregate_retry    app.index_controller.aggregate(event, retry=True)  File "/var/task/azul/indexer/index_controller.py", line 275, in aggregate    self.index_service.aggregate(tallies)  File "/var/task/azul/indexer/index_service.py", line 425, in aggregate    old_aggregates = self._read_aggregates(tallies)  File "/var/task/azul/indexer/index_service.py", line 500, in _read_aggregates    return {a.coordinates.entity: a for a in aggregates()}  File "/var/task/azul/indexer/index_service.py", line 500, in <dictcomp>    return {a.coordinates.entity: a for a in aggregates()}  File "/var/task/azul/indexer/index_service.py", line 490, in aggregates    raise RuntimeError('Malformed document', doc)
-- | --
@timestamp | 1645117316850
_id | 9fab6aeb-6b2f-421f-9c61-a31feb70825c
_index | azul_v2_prod2_dcp13_bundles_aggregate
_type | None
error.index | azul_v2_prod2_dcp13_bundles_aggregate
error.index_uuid | _na_
error.reason | no such index [azul_v2_prod2_dcp13_bundles_aggregate]
error.resource.id | azul_v2_prod2_dcp13_bundles_aggregate
error.resource.type | index_expression
error.root_cause.0.index | azul_v2_prod2_dcp13_bundles_aggregate
error.root_cause.0.index_uuid | _na_
error.root_cause.0.reason | no such index [azul_v2_prod2_dcp13_bundles_aggregate]
error.root_cause.0.resource.id | azul_v2_prod2_dcp13_bundles_aggregate
error.root_cause.0.resource.type | index_expression
error.root_cause.0.type | index_not_found_exception
error.type | index_not_found_exception

</span>
```
… and confirmed that the aggregate indices were missing …
<img width="872" alt="Screen Shot 2022-02-17 at 10 21 49 AM" src="https://user-images.githubusercontent.com/19215510/154546652-0c4af59f-83e1-4d35-b21d-82a8f3232786.png">

I went ahead and created the aggregate indices for the `dcp13` catalog and re-fed the tallies from the fail queue to the tallies queue.

**Comment by achave11** [comment]
In retrospect, the command should have read:
```
python scripts/reindex.py --catalogs dcp13 --index --create
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "I think the contribution indices were created because automatic index creation is enabled. The aggregate indexes weren't created because we first query them before writing to them and the query is what's failing. The solution is to disable automatic index creation on the cluster."

**Comment by achave11-ucsc** [comment]
This is a freebie of #5675.

**Comment by hannes-ucsc** [comment]
Freebie is closed.
