### ISSUE TITLE
Manifests fail due to joiner in metadata

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3888]
IT and general manifest request for `compact` and `terra.bdbag` are failing. After inspecting some of the failed step function executions there are also requests for `curl` format manifests that are failing.
```
[ERROR] AssertionError
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1564, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1517, in __call__
    return self._original_func(event.to_dict(), event.context)
  File "/var/task/app.py", line 1613, in generate_manifest
    return app.manifest_controller.get_manifest(event)
  File "/var/task/azul/service/manifest_controller.py", line 74, in get_manifest
    result = self.service.get_manifest(format_=ManifestFormat(state['format_']),
  File "/var/task/azul/service/manifest_service.py", line 372, in get_manifest
    partition = generator.write(object_key, partition)
  File "/var/task/azul/service/manifest_service.py", line 976, in write
    partition = self.write_page_to(partition, output=text_buffer)
  File "/var/task/azul/service/manifest_service.py", line 1331, in write_page_to
    self._extract_fields(entities, column_mapping, row)
  File "/var/task/azul/service/manifest_service.py", line 782, in _extract_fields
    column_value += [
  File "/var/task/azul/service/manifest_service.py", line 783, in <listcomp>
    validate(convert(field_name, field_sub_value))
  File "/var/task/azul/service/manifest_service.py", line 769, in validate
    assert stripped_joiner not in field_value
```

**Comment by achave11** [comment]
prod2-dcp12 malformed project:
```
{
source_spec: "tdr:datarepo-6ab76705:snapshot/hca_prod_5116c0818be749c58ce073b887328aa9__20220117_dcp2_20220120_dcp12:/0",
project_uuid: "5116c081-8be7-49c5-8ce0-73b887328aa9"
bundle_uuid: [
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"71255848-8fe5-4c12-8b1b-b34774debb13"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"2a5b85d2-e9c1-4007-bbcf-3d249b750981"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"1569025c-4924-4322-a415-7e4730937850"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"c8bd43b5-226b-45e2-80e2-6eab562f3401"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"981edc91-dda2-48a2-875f-30c3310d332f"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"5e2fd3a1-6807-47c6-a2c7-4241c10f5420"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"82760519-a2a4-4048-bfbb-94b7b01a72eb"
"155a72e2-e6c0-4c7d-a653-79c103bb7205"
"1569025c-4924-4322-a415-7e4730937850"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"06fd9dd9-a81d-4408-82e9-ad2131ab0570"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"1569025c-4924-4322-a415-7e4730937850"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"981edc91-dda2-48a2-875f-30c3310d332f"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"604f4ac7-ecd0-440d-b45b-46ab8e45cee8"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"981edc91-dda2-48a2-875f-30c3310d332f"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"1569025c-4924-4322-a415-7e4730937850"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"29a1cbc0-1fdb-4eaf-ac75-f92e6e1092e6"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"981edc91-dda2-48a2-875f-30c3310d332f"
"9f651c57-5c46-44bd-8db0-4719bffc1fa1"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"9c6d2e1f-403b-4e7b-ac99-dbf830958f8f"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
]
file_uuid: [
"74b5e882-d690-414b-a994-095e0e4248f2"
"2591413e-5629-4f1e-bbbe-8ecd03dc1c4d"
"430ad5a9-52dd-415e-830a-8f8c06c4e846"
"c653cd16-183a-475b-9497-a5e65298c950"
"c414f4ac-a7dc-4bbe-9f3c-84a1f7a0d004"
"b7735c28-6352-4ac6-9b43-d1d4e7e52707"
"118a7c40-f971-4b85-8d19-6e7d056d882c"
"4ad13248-78cc-4ddb-b568-2d807d07fb55"
"62b36e67-be58-47b2-b976-7c0be535adae"
"6d2cf1f3-cd8d-45ba-aa9a-49b9085b34b7"
"7b8e0c97-5c0d-40a9-8adb-6947ca437c69"
"958a19b2-4980-44a2-853e-b30604331dbc"
"ea973069-8013-4f1d-94ae-aa11cc7a4b5a"
"8554f6ef-998c-41c7-a4b3-368593c8ba09"
"03c6873e-1329-44eb-badc-7d3d498217d2"
"c6a6ee68-06e5-4626-95a8-21735ed7e752"
"0711305a-7983-41b6-adce-9df7517ecdeb"
"af005951-e48d-417c-be6f-ad045eb0137e"
"98ef93ce-a19d-4451-a02f-687b0a0b71d9"
"dad1cbf0-3219-4f1c-80b3-8f9635a08199"
"753064d5-dd04-4dee-bdad-28442751e957"
"b31caf2a-6ef0-41ff-af55-9f1c8f90d1bf"
"b13f9340-9460-418e-a6be-e5381c88c46d"
"d782199d-4882-4b84-9065-7c4347349a31"
"498f1392-28ef-4283-81c6-5c4fd41c93d2"
"c5c6b6d4-908d-4fda-bde2-bdb8bfabf10f"
"4d654619-e073-4051-a998-0a53f4126308"
"0f4cda01-4a6c-4aa7-8f47-8863777f1e24"
"778ac44f-ad2a-47ca-919d-419792892ac8"
"3e176346-db86-44f8-b14d-b908662bbdad"
"f2199516-e741-4eb2-ad94-107b7b5ca1fe"
"5121a767-5b6c-4c9e-a62e-793679b14429"
"540cb236-1f0f-4dd5-afac-d4fd30cf587e"
"70ac7a27-c9b9-4232-8274-9bb22f5a591a"
"c02e0379-0552-4670-8864-9016a51f458d"
"22a65d99-aa68-4e6d-af13-43a761ab46f8"
"ebcfa212-9cad-49ba-820e-02f761256973"
"96da98bb-a414-4195-aa15-d07cf332f47f"
"c374402a-c867-45dc-8d0d-530c4d5395a1"
"61d65093-3689-496d-aa6c-5cde2a5d9922"
"f2b8c722-789e-4fab-83d4-051df6f5a9dc"
"1f35310f-c9b0-42cd-8801-56934f01222a"
"4e97db44-17cc-443d-a4a6-6d9e9fe8012e"
"6cf21e66-4178-4bd8-acfd-2fb060f863d1"
"c5581e34-7ba2-4a57-983c-dea491a36902"
"61c9ac33-6789-4740-a468-6d40b40a3d08"
"7525c06a-cb4d-4a41-9155-64808b740169"
"8c28b9e0-0477-488b-8184-7fd82666c9dd"
"3c7837ad-271a-438b-968d-61eed44e47d2"
"5b3a8acd-c71a-440f-aaf0-99b15e36f7ba"
"3aab20e3-4afe-468d-b2b4-b28bc5fbe9ee"
"d7bfa620-06f5-44ab-b9c1-3c83edd971c9"
"566aa9aa-001f-46ac-a750-f89613f7b436"
"d6ccf319-86f2-4b70-adb9-cae70bb660ac"
"e7ccd106-02fa-46ec-9830-93d522e46ed4"
"68385f66-2484-4f92-9b07-11503578a2c6"
"375e6e86-3fd2-4e14-a3d8-20707efa1d45"
"b174eb6c-5765-49db-8e6a-0779b39b65b4"
"83c15f93-2fbe-4a4d-87c6-6a63742ef96e"
"a9c49151-7893-4fbd-8088-23a57cf80b51"
"8b01d03f-2a4a-4791-9ad9-6c005607e19d"
"a9d2e133-711f-4c94-a229-f6283587e6f5"
"b30d1ee7-b252-4c32-8e3c-b3f04a97dee0"
"1a5a7682-f981-4f86-9266-fb04e740bfc7"
"a36143fa-a506-4eed-8d7b-84b6571949ae"
"4e6168d0-9ab8-43c2-84d7-d23474ada62d"
"29a413f1-7871-4cc0-885c-4eed44597556"
"21fe5379-5eb7-4a5a-85aa-2722e77a342d"
"6e0e57d9-b38a-49da-a689-4ea1ab14c156"
"a3d1f986-4287-4460-95cd-d40f2ae54609"
"deb02259-eea4-4c73-8a81-44e1641c6d10"
]
project_short_name: 'HumanHematopoieticProgenitors'
}
```

prod2-dcp13 malformed projects (one repeated from dcp12):
```
{
source_spec: "tdr:datarepo-7e70b0df:snapshot/hca_prod_6f89a7f38d4a4344aa4feccfe7e91076__20220213_dcp2_20220214_dcp13:/0",
project_uuid: "6f89a7f3-8d4a-4344-aa4f-eccfe7e91076",
bundle_uuid: [
"8105a8c6-2fb6-4f27-9731-1061f2793f1a"
"8105a8c6-2fb6-4f27-9731-1061f2793f1a"
"a788f552-d28d-4b00-8c40-e932369306cd"
"c513ffd0-18cc-49b0-94c3-72543c21ba0c"
"c513ffd0-18cc-49b0-94c3-72543c21ba0c"
"8105a8c6-2fb6-4f27-9731-1061f2793f1a"
"8105a8c6-2fb6-4f27-9731-1061f2793f1a"
"a788f552-d28d-4b00-8c40-e932369306cd"
"aee114e7-5dfc-4d84-9c7f-a28d20fd904e"
"882a6eb1-ea31-4a68-a13c-5cc135c0ce9d"
"a788f552-d28d-4b00-8c40-e932369306cd"
"c702da08-b880-41f7-908b-7356147b56b0"
"c513ffd0-18cc-49b0-94c3-72543c21ba0c"
"96e5d129-0cd5-4a8c-8d94-555f41575994"
"a788f552-d28d-4b00-8c40-e932369306cd"
"c513ffd0-18cc-49b0-94c3-72543c21ba0c"
"205de357-c7af-472b-beba-c210e46e9434"
"205de357-c7af-472b-beba-c210e46e9434"
],
file_uuid: [
"22007d23-eb1e-4426-bb9e-4ce0be7671b6"
"8a2a8733-69ed-43f0-b1f2-e0b81b331701"
"e30b6f69-f7f6-4612-8b67-d71a85230257"
"94b00983-60e5-4910-b3a7-8404cc5c97b5"
"54bb6406-6865-4232-a5bd-14e0145fa4c3"
"93e6e353-f5b4-4bcc-927b-04f4dc467a5c"
"66b86cd0-03c7-4c40-835c-61d8b0a156e1"
"d56a0f0c-c1cf-47e1-906c-14f41442147f"
"d718e10f-839a-4a80-bacb-e19e2aa3a306"
"54ccb2d4-6c57-4927-b94f-c44e406a3abc"
"e0034536-ff8c-4d83-9151-8c024b17d2f8"
"25df1a06-a148-469c-bc0c-1937e645f809"
"f26923b1-788a-4c6c-9ccf-2b38e33db779"
"4dd8e34d-53e5-4b63-a792-9de6f3eee62f"
"495f9b88-e037-4965-ae2f-d13116ac6590"
"22bf81eb-3cb3-48b9-890f-0f6ebb4462f2"
"13bf8703-9510-4020-a0ae-845ee036369e"
"772bb2b9-973f-439c-b246-8864b1dc709e"
],
project_short_name: 'humanDentalPulpCells'
}
{
source_spec: "tdr:datarepo-6ab76705:snapshot/hca_prod_5116c0818be749c58ce073b887328aa9__20220117_dcp2_20220120_dcp12:/0",
project_uuid: "5116c081-8be7-49c5-8ce0-73b887328aa9"
bundle_uuid: [
"55fa7731-932f-4714-8e4b-efc8a1898172"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"06fd9dd9-a81d-4408-82e9-ad2131ab0570"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"5e2fd3a1-6807-47c6-a2c7-4241c10f5420"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"c8bd43b5-226b-45e2-80e2-6eab562f3401"
"2a5b85d2-e9c1-4007-bbcf-3d249b750981"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"1569025c-4924-4322-a415-7e4730937850"
"1569025c-4924-4322-a415-7e4730937850"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"981edc91-dda2-48a2-875f-30c3310d332f"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"1569025c-4924-4322-a415-7e4730937850"
"1569025c-4924-4322-a415-7e4730937850"
"82760519-a2a4-4048-bfbb-94b7b01a72eb"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"9c6d2e1f-403b-4e7b-ac99-dbf830958f8f"
"155a72e2-e6c0-4c7d-a653-79c103bb7205"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"604f4ac7-ecd0-440d-b45b-46ab8e45cee8"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"71255848-8fe5-4c12-8b1b-b34774debb13"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"981edc91-dda2-48a2-875f-30c3310d332f"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"14cd7099-46f6-40d1-81ac-8508182d0bda"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"9f651c57-5c46-44bd-8db0-4719bffc1fa1"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"55fa7731-932f-4714-8e4b-efc8a1898172"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"b2783c3e-7e6f-47ff-99d7-6357a47a1a7a"
"29a1cbc0-1fdb-4eaf-ac75-f92e6e1092e6"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"981edc91-dda2-48a2-875f-30c3310d332f"
"4e0793bc-23a0-41ef-92c9-bf45368ad4fc"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"8899fbf1-a169-4ca7-b95b-8ce10e71d3ca"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"2d7464f3-0130-4b10-8f67-b6aa5da406a7"
"1e1054a3-c923-4f2c-b295-1837d27cbd7e"
"9d1af129-e670-4188-b8fd-bf8beabb6891"
"8ddcb3a8-4d76-4144-981a-85d2015d6b59"
"981edc91-dda2-48a2-875f-30c3310d332f"
"eaf62d57-62d5-498f-abad-4fc3561cb1b6"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"9011e52e-c78f-4913-9f3b-d97abf25d89e"
"a418a11b-cfe7-4cea-9e03-c9cb5d7d2794"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
"16d94ed6-550b-4a48-a3f3-bfd5958d215e"
],
file_uuid: [
"3aab20e3-4afe-468d-b2b4-b28bc5fbe9ee"
"3c7837ad-271a-438b-968d-61eed44e47d2"
"ebcfa212-9cad-49ba-820e-02f761256973"
"4d654619-e073-4051-a998-0a53f4126308"
"21fe5379-5eb7-4a5a-85aa-2722e77a342d"
"0711305a-7983-41b6-adce-9df7517ecdeb"
"af005951-e48d-417c-be6f-ad045eb0137e"
"c653cd16-183a-475b-9497-a5e65298c950"
"3e176346-db86-44f8-b14d-b908662bbdad"
"4e6168d0-9ab8-43c2-84d7-d23474ada62d"
"c6a6ee68-06e5-4626-95a8-21735ed7e752"
"62b36e67-be58-47b2-b976-7c0be535adae"
"deb02259-eea4-4c73-8a81-44e1641c6d10"
"375e6e86-3fd2-4e14-a3d8-20707efa1d45"
"c02e0379-0552-4670-8864-9016a51f458d"
"70ac7a27-c9b9-4232-8274-9bb22f5a591a"
"d7bfa620-06f5-44ab-b9c1-3c83edd971c9"
"753064d5-dd04-4dee-bdad-28442751e957"
"7525c06a-cb4d-4a41-9155-64808b740169"
"22a65d99-aa68-4e6d-af13-43a761ab46f8"
"f2b8c722-789e-4fab-83d4-051df6f5a9dc"
"61d65093-3689-496d-aa6c-5cde2a5d9922"
"8554f6ef-998c-41c7-a4b3-368593c8ba09"
"5121a767-5b6c-4c9e-a62e-793679b14429"
"5b3a8acd-c71a-440f-aaf0-99b15e36f7ba"
"778ac44f-ad2a-47ca-919d-419792892ac8"
"0f4cda01-4a6c-4aa7-8f47-8863777f1e24"
"a36143fa-a506-4eed-8d7b-84b6571949ae"
"540cb236-1f0f-4dd5-afac-d4fd30cf587e"
"68385f66-2484-4f92-9b07-11503578a2c6"
"f2199516-e741-4eb2-ad94-107b7b5ca1fe"
"61c9ac33-6789-4740-a468-6d40b40a3d08"
"c5581e34-7ba2-4a57-983c-dea491a36902"
"6cf21e66-4178-4bd8-acfd-2fb060f863d1"
"1f35310f-c9b0-42cd-8801-56934f01222a"
"118a7c40-f971-4b85-8d19-6e7d056d882c"
"dad1cbf0-3219-4f1c-80b3-8f9635a08199"
"8b01d03f-2a4a-4791-9ad9-6c005607e19d"
"a3d1f986-4287-4460-95cd-d40f2ae54609"
"6e0e57d9-b38a-49da-a689-4ea1ab14c156"
"a9c49151-7893-4fbd-8088-23a57cf80b51"
"566aa9aa-001f-46ac-a750-f89613f7b436"
"958a19b2-4980-44a2-853e-b30604331dbc"
"7b8e0c97-5c0d-40a9-8adb-6947ca437c69"
"6d2cf1f3-cd8d-45ba-aa9a-49b9085b34b7"
"a9d2e133-711f-4c94-a229-f6283587e6f5"
"c374402a-c867-45dc-8d0d-530c4d5395a1"
"74b5e882-d690-414b-a994-095e0e4248f2"
"498f1392-28ef-4283-81c6-5c4fd41c93d2"
"1a5a7682-f981-4f86-9266-fb04e740bfc7"
"b30d1ee7-b252-4c32-8e3c-b3f04a97dee0"
"b174eb6c-5765-49db-8e6a-0779b39b65b4"
"8c28b9e0-0477-488b-8184-7fd82666c9dd"
"d6ccf319-86f2-4b70-adb9-cae70bb660ac"
"4ad13248-78cc-4ddb-b568-2d807d07fb55"
"d782199d-4882-4b84-9065-7c4347349a31"
"c414f4ac-a7dc-4bbe-9f3c-84a1f7a0d004"
"96da98bb-a414-4195-aa15-d07cf332f47f"
"83c15f93-2fbe-4a4d-87c6-6a63742ef96e"
"98ef93ce-a19d-4451-a02f-687b0a0b71d9"
"29a413f1-7871-4cc0-885c-4eed44597556"
"430ad5a9-52dd-415e-830a-8f8c06c4e846"
"2591413e-5629-4f1e-bbbe-8ecd03dc1c4d"
"03c6873e-1329-44eb-badc-7d3d498217d2"
"4e97db44-17cc-443d-a4a6-6d9e9fe8012e"
"b13f9340-9460-418e-a6be-e5381c88c46d"
"b31caf2a-6ef0-41ff-af55-9f1c8f90d1bf"
"e7ccd106-02fa-46ec-9830-93d522e46ed4"
"ea973069-8013-4f1d-94ae-aa11cc7a4b5a"
"c5c6b6d4-908d-4fda-bde2-bdb8bfabf10f"
"b7735c28-6352-4ac6-9b43-d1d4e7e52707"
]
project_short_name: 'HumanHematopoieticProgenitors'
}
```

**Comment by achave11** [comment]
For project

**Comment by achave11** [comment]
@hannes-ucsc: "Let's just disable the assertion, and replace it with a log warning. The use of joiner will become obsolete once we switch Terra Hand Off to use AvroPFB. Also let the wranglers know that they should avoid of `||` moving forward. The current two occurrences in project.json are unlikely to ever cause problems because there will never be two projects per file."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Instead of eliminating the assertion, only assert the absence of the joiner when we actually need to add a joiner to a field. There will not be a need for a log warning in that case."

**Comment by melainalegaspi** [comment]
@hannes-ucsc to notify wranglers about discouraging use of double pipe symbol in metadata.

**Comment by hannes-ucsc** [comment]
Wranglers notified:

https://humancellatlas.slack.com/archives/C01360XN04S/p1645840673788099

It looks like they use the joiner extensively in "array" cells in the spreadsheet. It appears that someone put the joiner in a non-array cell and Ingest just passed it through. I propose that Ingest add a validation rule to prevent joiners in non-array cells.

We will prevent joiners in any property at indexing time (https://github.com/DataBiosphere/azul/issues/3911). For this ticket we'll stick with the solution outlined above.

**Comment by achave11** [comment]
Asserting the joiner isn't present when concatenating more than one field does not prevent the assertion from failing with the current malformed projects, because the current occurrences of the joiner are all in multi-valued fields that we do need to concatenate.

**Comment by achave11** [comment]
@hannes-ucsc: "That's right. I missed that. There really isn't anything we can do in Azul about those occurrences. The metadata needs to be fixed and we should be focusing on #3911 after which the two projects will fail to index. I will notify the wranglers about this. @achave11 could you please post links to the two affected projects."

**Comment by achave11** [comment]
DCP12:
https://service.azul.data.humancellatlas.org/index/projects/5116c081-8be7-49c5-8ce0-73b887328aa9?catalog=dcp12 (repeats for dcp13)

DCP13:
https://service.azul.data.humancellatlas.org/index/projects/5116c081-8be7-49c5-8ce0-73b887328aa9?catalog=dcp13
https://service.azul.data.humancellatlas.org/index/projects/6f89a7f3-8d4a-4344-aa4f-eccfe7e91076?catalog=dcp13

**Comment by theathorn** [comment]
Raised https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/685.

**Comment by theathorn** [comment]
I'm not seeing any issue in prod with downloading project metadata, generating curl manifests, or doing a BdBag-format hand-off to Terra. the `||` is present in the downloaded project metadata tsv file.

**Comment by theathorn** [comment]
@achave11 : "We deployed a temporary hotfix which omitted the assertion, allowing the manifest to complete".

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "We will temporarily disable the assertion in the manifest generation and reintroduce it again as part of #3911."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.

**Comment by achave11** [comment]
```http
GET http://service.azul2.data.humancellatlas.org/manifest/files?catalog=dcp13&format=compact&filters={"projectId"%3A{"is"%3A["5116c081-8be7-49c5-8ce0-73b887328aa9"]}}
Accept: application/json
```
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Connection: keep-alive
Date: Fri, 11 Mar 2022 20:13:19 GMT
x-amzn-RequestId: 05558dfc-3256-4404-a358-6b36e6eacb80
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
x-amz-apigw-id: O1gG9GscoAMFuhg=
X-Amzn-Trace-Id: Root=1-622bad5f-29d00c38232677ed492e906a;Sampled=0
X-Cache: Error from cloudfront
Via: 1.1 48dff86338c4d757c3f0caaf725b5bd4.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LAX50-C4
X-Amz-Cf-Id: mf8SbG7xOFwN1YEHbpmR1a7cT2XKYCd7QngEWR-XUoxueR4Fgj5iXw==

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1536, in file_manifest
    return _file_manifest(fetch=False)
  File "/var/task/app.py", line 1602, in _file_manifest
    return app.manifest_controller.get_manifest_async(self_url=app.self_url(),
  File "/var/task/azul/service/manifest_controller.py", line 137, in get_manifest_async
    token_or_state = self.async_service.inspect_generation(token)
  File "/var/task/azul/service/async_manifest_service.py", line 99, in inspect_generation
    raise StateMachineError(status, output)
azul.service.step_function_helper.StateMachineError: ('Failed to generate manifest', 'FAILED', None)

```
