### ISSUE TITLE
Insufficient access error message lacks snapshot name

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3940]
When the snapshot listing endpoint returns a 401, the error message only includes a link to the endpoint path but does not include the actual snapshot name.

```
2022-03-10 13:16:31,114 DEBUG   ThreadPoolExecutor-0_8: _request(…) -> b'{"id":"564e84c1-bf16-4dad-995b-fbcd6a4bf4d1","name":"hca_prod_cddab57b68684be4806f395ed9dd635a__20220118_dcp2_20220121_dcp12","description":"Create snapshot hca_prod_cddab57b68684be4806f395ed9dd635a__20220118_dcp2_20220121_dcp12","createdDate":"2022-01-...'
Traceback (most recent call last):
  File "/Users/amar/dev/hca/PROD/scripts/post_deploy.py", line 87, in <module>
    main()
  File "/Users/amar/dev/hca/PROD/scripts/post_deploy.py", line 82, in main
    verify_sources()
  File "/Users/amar/dev/hca/PROD/scripts/post_deploy.py", line 55, in verify_sources
    raise e
  File "/Users/amar/.pyenv/versions/3.8.12/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/amar/dev/hca/PROD/src/azul/terra.py", line 436, in check_api_access
    self._lookup_source(source)
  File "/Users/amar/dev/hca/PROD/src/azul/terra.py", line 445, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/Users/amar/dev/hca/PROD/src/azul/terra.py", line 537, in _check_response
    raise self._insufficient_access(endpoint)
azul.RequirementError: The service account (SA) 'azul-ucsc-0-prod@platform-hca-prod.iam.gserviceaccount.com' is not authorized to access https://data.terra.bio/api/repository/v1/snapshots or that resource does not exist. Make sure that it exists, that the SA is registered with SAM and has been granted read access to the resource.
make: *** [post_deploy] Error 1
```

**Comment by amarjandu** [comment]
@hannes-ucsc: "I will reach out to TDR engineering because I think they are raising 401s when SAM does not respond in time, they should be raising 503."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "When the list snapshots endpoint returns 401 or 503, the snapshot name isn't really relevant so fixing this is very low priority."
