### ISSUE TITLE
Transient InternalServerError from BigQuery during IT

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3947]
A recent `develop` [pipeline failed IT in GL](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/41214) due to a  transient error.

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 172, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 353, in test_indexing
    catalogs: List[Catalog] = [
  File "/builds/ucsc/azul/test/integration_test.py", line 355, in <listcomp>
    notifications=self._prepare_notifications(catalog) if index else {})
  File "/builds/ucsc/azul/test/integration_test.py", line 741, in _prepare_notifications
    bundle_fqids = self._list_bundles(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 880, in _list_bundles
    bundle_fqids = super()._list_bundles(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 261, in _list_bundles
    bundle_fqids = reservoir_sample(max_bundles, bundle_fqids, random=self.random)
  File "/builds/ucsc/azul/src/azul/iterators.py", line 91, in reservoir_sample
    for i, item in enumerate(it, start=k + 1):
  File "/builds/ucsc/azul/test/integration_test.py", line 250, in <genexpr>
    self._list_partition_bundles(catalog, source)
  File "/builds/ucsc/azul/test/integration_test.py", line 235, in _list_partition_bundles
    fqids = self.azul_client.list_bundles(catalog, source, prefix)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 213, in list_bundles
    return plugin.list_bundles(source, prefix)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 238, in list_bundles
    bundle_fqids = self._list_links_ids(source, prefix)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 286, in _list_links_ids
    current_bundles = self._query_latest_version(source.spec, f'''
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 299, in _query_latest_version
    iter_rows = self._run_sql(query)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 277, in _run_sql
    return self.tdr.run_sql(query)
  File "/builds/ucsc/azul/src/azul/terra.py", line 494, in run_sql
    result = job.result()
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/build/.venv/lib/python3.8/site-packages/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/build/.venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.InternalServerError: 500 Org policy checker unavailable.
(job ID: 73df4973-51b8-49ed-9a58-aa7906eed9dc)
                                        -----Query Job SQL Follows-----                                        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:            SELECT links_id, version
   3:            FROM `datarepo-dev-10f0610a.hca_dev_f81efc039f564354aabb6ce819c3d414__20210827_20210903.links`
   4:            WHERE STARTS_WITH(links_id, '')
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
----------------------------------------------------------------------
Ran 16 tests in 289.129s
FAILED (errors=1, skipped=4)
make: *** [Makefile:168: integration_test] Error 1
```

**Comment by achave11** [comment]
Again in the `deploy` step. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/41292

**Comment by theathorn** [comment]
@hannes-ucsc : "Add retry on 500 to tdrclient.runsql".

**Comment by achave11** [comment]
Happened again during `post_deploy` step in the GitLab deploy job. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/42062

**Comment by hannes-ucsc** [comment]
For demo, show the modified log message in CloudWatch from a reindex in `dev`. While it may not be possible to demonstrate 500 and 503 errors, we should still observe the Forbidden error with `rate limit exceed` and show that the change didn't introduce a regression of that aspect.
