### ISSUE TITLE
Add support for phantom files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3956]
Currently we get

```
[WARNING] 2022-03-18T00:14:22.172Z 6a94fe05-6c5c-5763-9e88-a4a8bca5fee3 Worker failed to handle message {'catalog': 'lm2-it', 'action': 'add', 'notification': {'source': {'id': 'f9c9ee4f-7e16-411b-b127-781930dc04dd', 'spec': 'tdr:datarepo-df6004c2:snapshot/lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220311_lm2:/0'}, 'transaction_id': '477c950b-6333-4bdf-a7e4-2bc37e1f690d', 'match': {'bundle_uuid': '31244706-60f8-3043-8db7-a39fd7081139', 'bundle_version': '2022-03-11T17:13:52.129998Z'}}}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 174, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 207, in transform
bundle = service.fetch_bundle(catalog, source, bundle_uuid, bundle_version)
File "/var/task/azul/indexer/index_service.py", line 182, in fetch_bundle
return plugin.fetch_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 246, in fetch_bundle
bundle = self._emulate_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 331, in _emulate_bundle
bundle.add_entity(entity_key=f'{entity_type}_{i}.json',
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 653, in add_entity
drs_path=self._parse_file_id_column(entity_row['file_id']))
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 717, in _parse_file_id_column
reject(file_id is None)
File "/var/task/azul/__init__.py", line 1292, in reject
raise exception(*args)
azul.RequirementError
```

Phantom files are defined as files with no data file object in the staging area and `file_descriptor.drs_uri` set to `null`.

https://github.com/HumanCellAtlas/dcp2/pull/55/files
https://github.com/HumanCellAtlas/metadata-schema/pull/1437/files

They will cause the TDR `file_id` column to be `null`. We should allow that if, and only if the `file_descriptor` column contains JSON whose `drs_uri` property is also `null`. If the property is not set, or if it is set to a value other than `null` and RequirementError should be raised. An unset property is invalid, support for non-null values will be added in https://github.com/DataBiosphere/azul/issues/3631. 

Downstream from the indexer, the resulting `None` values in `drs_path` in our index need to be handled gracefully.

**Comment by hannes-ucsc** [comment]
For demo, show /index/files response with phantom files, and a manifest of each format containing at least one phantom file.

**Comment by hannes-ucsc** [comment]
We are generating URLs for the phantom files

```
$ http 'https://service.azul.data.humancellatlas.org/index/files?filters=%7B%22projectId%22%3A%7B%22is%22%3A%5B%22f899709c-ae2c-4bb9-88f0-131142e6c7ec%22%5D%7D%2C%22fileFormat%22%3A%7B%22is%22%3A%5B%22fastq.gz%22%5D%7D%7D&size=25&sort=fileName&order=asc&catalog=lm2' | jq -r '.hits[].files[].url'
https://service.azul.data.humancellatlas.org/repository/files/ef19f156-30a0-474a-9212-dd19bbb9f414?catalog=lm2&version=2022-03-03T19%3A03%3A23.287051Z
https://service.azul.data.humancellatlas.org/repository/files/a8b6b9de-2038-4071-ab06-77038b737d97?catalog=lm2&version=2022-03-03T19%3A02%3A53.832737Z
https://service.azul.data.humancellatlas.org/repository/files/91725512-2e20-4d51-941e-9fc8300b38e3?catalog=lm2&version=2022-03-03T19%3A02%3A58.850275Z
https://service.azul.data.humancellatlas.org/repository/files/b41d9042-4fa9-47cb-8bd0-8e5ff6ae5a6c?catalog=lm2&version=2022-03-03T19%3A02%3A22.144218Z
https://service.azul.data.humancellatlas.org/repository/files/be6014dd-db82-43c5-80b8-b63351d592ef?catalog=lm2&version=2022-03-03T19%3A02%3A55.885409Z
https://service.azul.data.humancellatlas.org/repository/files/8ad47627-46aa-462f-8439-9154fc0da8b2?catalog=lm2&version=2022-03-03T19%3A02%3A48.877288Z
https://service.azul.data.humancellatlas.org/repository/files/c84f8f12-db0d-4b58-915c-82f2c171c6e0?catalog=lm2&version=2022-03-03T19%3A02%3A33.751344Z
https://service.azul.data.humancellatlas.org/repository/files/d1c93252-c0ec-43c2-847c-6ba5144907ed?catalog=lm2&version=2022-03-03T19%3A03%3A09.002129Z
https://service.azul.data.humancellatlas.org/repository/files/059ba534-61dd-46fa-aa3f-c4e2bb87c579?catalog=lm2&version=2022-03-03T19%3A03%3A25.282692Z
https://service.azul.data.humancellatlas.org/repository/files/bf5f20cd-d99f-462f-8151-b037845ad86e?catalog=lm2&version=2022-03-03T19%3A03%3A06.027570Z
https://service.azul.data.humancellatlas.org/repository/files/1ce924c3-1b69-4d1c-808b-85351d4deb28?catalog=lm2&version=2022-03-03T19%3A02%3A54.881200Z
https://service.azul.data.humancellatlas.org/repository/files/6c022767-f781-427f-baa0-f577d86ac0be?catalog=lm2&version=2022-03-03T19%3A02%3A24.078730Z
https://service.azul.data.humancellatlas.org/repository/files/fbc34d0f-8a19-453a-8d0f-2ecdd76396be?catalog=lm2&version=2022-03-03T19%3A01%3A52.073110Z
https://service.azul.data.humancellatlas.org/repository/files/83095fe5-dc66-4720-9334-4d97fd397a56?catalog=lm2&version=2022-03-03T19%3A03%3A04.006295Z
https://service.azul.data.humancellatlas.org/repository/files/c29600a0-38e4-4d42-9bf1-bdbafa2d3b02?catalog=lm2&version=2022-03-03T19%3A03%3A22.288252Z
https://service.azul.data.humancellatlas.org/repository/files/87a25b52-7298-446c-8a24-fc5921acc300?catalog=lm2&version=2022-03-03T19%3A02%3A06.139748Z
https://service.azul.data.humancellatlas.org/repository/files/cd509855-708c-4d0c-9f62-b5b0c7ce6453?catalog=lm2&version=2022-03-03T19%3A01%3A46.112800Z
https://service.azul.data.humancellatlas.org/repository/files/403c9e88-33a6-40cb-a833-95bec87b26c6?catalog=lm2&version=2022-03-03T19%3A01%3A41.120176Z
https://service.azul.data.humancellatlas.org/repository/files/fd125d76-4fa7-471c-9726-99484e9fc6b3?catalog=lm2&version=2022-03-03T19%3A02%3A50.882865Z
https://service.azul.data.humancellatlas.org/repository/files/fc7694e0-ca99-433e-b437-e466fec229f4?catalog=lm2&version=2022-03-03T19%3A02%3A26.742226Z
https://service.azul.data.humancellatlas.org/repository/files/cf9299b2-1705-4ca1-ab3f-41cd0a904fca?catalog=lm2&version=2022-03-03T19%3A02%3A07.131442Z
https://service.azul.data.humancellatlas.org/repository/files/1bdef70d-f7e3-4023-ba56-be7c67e80730?catalog=lm2&version=2022-03-03T19%3A02%3A14.142914Z
https://service.azul.data.humancellatlas.org/repository/files/f28bdbe7-a58a-4e60-a621-4417e4f7651f?catalog=lm2&version=2022-03-03T19%3A01%3A43.098015Z
https://service.azul.data.humancellatlas.org/repository/files/11b2f19d-d938-4a26-9a57-353792d1e43d?catalog=lm2&version=2022-03-03T19%3A01%3A48.099651Z
https://service.azul.data.humancellatlas.org/repository/files/60b02aa3-603c-4b52-ab05-dcc1234414bc?catalog=lm2&version=2022-03-03T19%3A03%3A20.295942Z
```

Requesting any of these URLs leads to a 404. 

```
$ http 'https://service.azul.data.humancellatlas.org/repository/files/fbc34d0f-8a19-453a-8d0f-2ecdd76396be?catalog=lm2&version=2022-03-03T19%3A01%3A52.073110Z'
HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 209
Content-Type: application/json
Date: Fri, 15 Apr 2022 00:34:38 GMT
Via: 1.1 216f781ed7a0653429ac7a72888ca4c4.cloudfront.net (CloudFront)
X-Amz-Cf-Id: efAqlGvPTitm-FibTTa-KYacLgUsgU0Ee9d1snEZc2JpuHBIwm3HPw==
X-Amz-Cf-Pop: SFO5-C1
X-Amzn-Trace-Id: Root=1-6258bd9e-5186e79772ffb744071c393b;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: QmKQ1EbpoAMF6Ug=
x-amzn-RequestId: c8195c5e-5dd3-4ff2-b9db-d66292e31ede

{
    "Code": "NotFoundError",
    "Message": "NotFoundError: File 'fbc34d0f-8a19-453a-8d0f-2ecdd76396be' with version '2022-03-03T19:01:52.073110Z' was found in catalog 'lm2', however no download is currently available"
}
```

We shouldn't generate URLs that we know don't work.

**Comment by hannes-ucsc** [comment]
We'll need a follow-up PR to address this.
