### ISSUE TITLE
IndexError in managed-access IT in `prod`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3960]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/17978
```
…
Use multithreading to simulate multiple users simultaneously modifying ... skipped 'Test would pollute portal DB'
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 282, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1011, in _test_managed_access
    managed_access_file = self.random.choice(self.random.choice(hits)['files'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 282, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1011, in _test_managed_access
    managed_access_file = self.random.choice(self.random.choice(hits)['files'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 282, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1011, in _test_managed_access
    managed_access_file = self.random.choice(self.random.choice(hits)['files'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 282, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1011, in _test_managed_access
    managed_access_file = self.random.choice(self.random.choice(hits)['files'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 282, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1011, in _test_managed_access
    managed_access_file = self.random.choice(self.random.choice(hits)['files'])
  File "/usr/local/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
----------------------------------------------------------------------
Ran 16 tests in 2069.003s
FAILED (errors=5, skipped=4)
make: *** [Makefile:160: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by noah-aviel-dove** [comment]
Looks like yet another occurrence of failing to account for the absence of managed access source on `prod`.
Suggested temporary hotfix (`h`): skip the curl download test if `managed_access_sources` is empty.
Suggested long-term solution (`H`): Exit the managed access subtest early if `managed_access_sources` is empty so new tests don't have to worry about this going forwards.

**Comment by theathorn** [comment]
@hannes-ucsc :"Agreed".
