### ISSUE TITLE
Transient error observed in IntegrationTest._test_managed_access

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4053]
Job: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/42914

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 354, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 970, in _test_managed_access
    first(public_source_ids & indexed_source_ids))
UnboundLocalError: local variable 'public_source_ids' referenced before assignment
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_repository_sources]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 354, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 957, in _test_managed_access
    public_source_ids = self._test_managed_access_repository_sources(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 994, in _test_managed_access_repository_sources
    self.assertEqual(public_source_ids, list_source_ids())
  File "/builds/ucsc/azul/test/integration_test.py", line 986, in list_source_ids
    response = self._get_url_json(url)
  File "/builds/ucsc/azul/test/integration_test.py", line 565, in _get_url_json
    return json.loads(self._get_url_content(url))
  File "/builds/ucsc/azul/test/integration_test.py", line 568, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 582, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 606, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (504, 'Gateway Timeout', b'{"message": "Endpoint request timed out"}')
```

This might be related to https://github.com/HumanCellAtlas/dcp2/issues/57
Retrying this job did not raise the same error.

**Comment by melainalegaspi** [comment]
Spike to verify and diagnose.

**Comment by noah-aviel-dove** [comment]
The `504` is a TDR hiccup (not our responsibility unless we want to implement retrying on 5xx errors from TDR), but the `UnboundLocalError` is a bug stemming from improper subtest nesting. Proposed solution: 

```diff
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision 2d2cab2c8e39c690c72bbc47bee6b12910b704c4)
+++ b/test/integration_test.py	(date 1649278670209)
@@ -953,21 +953,20 @@
                     self.assertNotEqual(catalog, config.it_catalog_for(config.default_catalog))
                 self.skipTest(f'No managed access sources found in catalog {catalog!r}')
 
-            with self.subTest('managed_access_repository_sources'):
-                public_source_ids = self._test_managed_access_repository_sources(catalog,
-                                                                                 indexed_source_ids,
-                                                                                 managed_access_source_ids)
-
             with self.subTest('managed_access_indices'):
                 bundles = self._test_managed_access_indices(catalog, managed_access_source_ids)
                 with self.subTest('managed_access_repository_files'):
                     files = self._test_managed_access_repository_files(bundles)
                     with self.subTest('managed_access_summary'):
                         self._test_managed_access_summary(catalog, files)
-                with self.subTest('managed_access_manifest'):
-                    self._test_managed_access_manifest(catalog,
-                                                       bundles,
-                                                       first(public_source_ids & indexed_source_ids))
+                with self.subTest('managed_access_repository_sources'):
+                    public_source_ids = self._test_managed_access_repository_sources(catalog,
+                                                                                     indexed_source_ids,
+                                                                                     managed_access_source_ids)
+                    with self.subTest('managed_access_manifest'):
+                        self._test_managed_access_manifest(catalog,
+                                                           bundles,
+                                                           first(public_source_ids & indexed_source_ids))
 
     def _test_managed_access_repository_sources(self,
                                                 catalog: CatalogName,
```

**Comment by noah-aviel-dove** [comment]
The `504` was caused by TDR exceeding the configured request timeout of 20 seconds. From CloudWatch (`/aws/lambda/azul-service-sandbox`, requestId=`8c10a120-38ee-447e-90fe-abf4269d4b9a`):
```
[DEBUG] 2022-04-05T18:02:22.404Z azul.terra 8c10a120-38ee-447e-90fe-abf4269d4b9a _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'offset': 0, 'limit': 200, 'sort': 'created_date', 'direction': 'asc'}, headers=None, body=None)

[DEBUG]	 2022-04-05T18:02:22.536Z	azul.terra	8c10a120-38ee-447e-90fe-abf4269d4b9a 	_request(…) -> b'{"message":"","errorDetail":[]}'

[DEBUG] 2022-04-05T18:02:22.596Z azul.terra 8c10a120-38ee-447e-90fe-abf4269d4b9a _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'offset': 0, 'limit': 200, 'sort': 'created_date', 'direction': 'asc'}, headers=None, body=None)

[WARNING]	 2022-04-05T18:02:42.632Z	urllib3.connectionpool	 8c10a120-38ee-447e-90fe-abf4269d4b9a	Retrying (Retry(total=2,  connect=None, read=None, redirect=None, status=None)) after connection  broken by  'ReadTimeoutError("HTTPSConnectionPool(host='jade.datarepo-dev.broadinstitute.org',  port=443): Read timed out. (read timeout=20.0)")':  /api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc

2022-04-05T18:02:53.431Z 8c10a120-38ee-447e-90fe-abf4269d4b9a Task timed out after 31.04 seconds
```

It seems that the PoolManager is retrying the request after it times out, undermining our attempt to timebox the request. I think this is also a bug. `PoolManager` does not document how to control retries but the underlying [HTTPConnectionPool](https://urllib3.readthedocs.io/en/latest/reference/urllib3.connectionpool.html) that implements the actual request says that the default behavior is to retry "until you receive a response". Proposed solution: 

```diff
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 2d2cab2c8e39c690c72bbc47bee6b12910b704c4)
+++ b/src/azul/terra.py	(date 1649286849479)
@@ -299,6 +299,7 @@
                                              url,
                                              fields=fields,
                                              headers=headers,
+                                             retries=False,
                                              # FIXME: Service should return 503 response when Terra client times out
                                              #        https://github.com/DataBiosphere/azul/issues/3968
                                              timeout=config.terra_client_timeout,
```

**Comment by noah-aviel-dove** [comment]
The `504` was caused by TDR exceeding the configured request timeout of 20 seconds. From CloudWatch (`/aws/lambda/azul-service-sandbox`, requestId=`8c10a120-38ee-447e-90fe-abf4269d4b9a`):
```
[DEBUG] 2022-04-05T18:02:22.404Z azul.terra 8c10a120-38ee-447e-90fe-abf4269d4b9a _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'offset': 0, 'limit': 200, 'sort': 'created_date', 'direction': 'asc'}, headers=None, body=None)

[DEBUG]	 2022-04-05T18:02:22.536Z	azul.terra	8c10a120-38ee-447e-90fe-abf4269d4b9a 	_request(…) -> b'{"message":"","errorDetail":[]}'

[DEBUG] 2022-04-05T18:02:22.596Z azul.terra 8c10a120-38ee-447e-90fe-abf4269d4b9a _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'offset': 0, 'limit': 200, 'sort': 'created_date', 'direction': 'asc'}, headers=None, body=None)

[WARNING]	 2022-04-05T18:02:42.632Z	urllib3.connectionpool	 8c10a120-38ee-447e-90fe-abf4269d4b9a	Retrying (Retry(total=2,  connect=None, read=None, redirect=None, status=None)) after connection  broken by  'ReadTimeoutError("HTTPSConnectionPool(host='jade.datarepo-dev.broadinstitute.org',  port=443): Read timed out. (read timeout=20.0)")':  /api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc

2022-04-05T18:02:53.431Z 8c10a120-38ee-447e-90fe-abf4269d4b9a Task timed out after 31.04 seconds
```

It seems that the PoolManager is retrying the request after it times out, undermining our attempt to timebox the request. I think this is also a bug. `PoolManager` does not document how to control retries but the underlying [HTTPConnectionPool](https://urllib3.readthedocs.io/en/latest/reference/urllib3.connectionpool.html) that implements the actual request says that the default behavior is to retry "until you receive a response". Proposed solution: 

```diff
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 2d2cab2c8e39c690c72bbc47bee6b12910b704c4)
+++ b/src/azul/terra.py	(date 1649286849479)
@@ -299,6 +299,7 @@
                                              url,
                                              fields=fields,
                                              headers=headers,
+                                             retries=False,
                                              # FIXME: Service should return 503 response when Terra client times out
                                              #        https://github.com/DataBiosphere/azul/issues/3968
                                              timeout=config.terra_client_timeout,
```

**Comment by noah-aviel-dove** [comment]
This explanation is consistent with the fact that we [observed a `MaxRetriesError` when testing the solution for #3910](https://github.com/DataBiosphere/azul/pull/3943#issuecomment-1074520705)

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review spike results.

**Comment by hannes-ucsc** [comment]
We'll fix the nesting issue in a PR for this issue and the retry issue in #4067.

**Comment by amarjandu** [comment]
Note same error `UnboundLocalError: local variable 'public_source_ids'` was observed in this issue: https://github.com/DataBiosphere/azul/issues/4083
