### ISSUE TITLE
Include all possible fields in API Gateway request logs

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4055]
… either by referencing $context or by mentioning each field explicitly in the format. 
Follow up from #3497.

**Comment by achave11** [comment]
When attempting to use the '$context' variable directly, the following happened:
```
…
Error: Error running command 'python /Users/abrahamchavez/PycharmProjects/Azul/azul.sc/scripts/log_api_gateway.py '65jyknf3ud' abrahamsc 'arn:aws:logs:us-east-1:122796619775:log-group:/aws/apigateway/azul-service-abrahamsc'': exit status 1. Output: Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/scripts/log_api_gateway.py", line 45, in <module>
    add_logging(*sys.argv[1:])
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/scripts/log_api_gateway.py", line 41, in add_logging
    add_field(client, path, value, api_id, stage_name)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/scripts/log_api_gateway.py", line 23, in add_field
    client.update_stage(
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the UpdateStage operation: Access Log format must include either $context.requestId or $context.extendedRequestId : '{"context": "$context"}'



make[1]: *** [apply] Error 1
make: *** [deploy] Error 2

```

Additionally, the documentation for [apigateway-cloudwatch-log-formats](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html#apigateway-cloudwatch-log-formats) indicates "The access log format must include at least $context.requestId. As a best practice, include $context.requestId and $context.extendedRequestId in your log format." and finishes with a note saying that only `$context` variables are supported.

**Comment by hannes-ucsc** [comment]
For demo, https://github.com/DataBiosphere/azul/issues/3497#issuecomment-1085291220
