### ISSUE TITLE
`repository_files` subtest fails during IT

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4074]
See https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/19060

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='dcp15-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 520, in one
    value = next(it)
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 354, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 723, in _test_repository_files
    file_uuid = self._get_one_file_uuid(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 531, in _get_one_file_uuid
    return one(one(hits['hits'])['files'])['uuid']
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 522, in one
    raise too_short or ValueError('too few items in iterable (expected 1)')
ValueError: too few items in iterable (expected 1)
----------------------------------------------------------------------
```

Note that this was the first time the IT was ran after the `dcp15` catalog added to the config. If attempting to reproduce locally consider deleting all catalogs in a personal deployment, then starting an IT.

**Comment by hannes-ucsc** [comment]
The logs of the failed test are

```
2022-04-08 00:12:03,975 INFO    MainThread: Beginning sub-test [repository_files] {'catalog': 'dcp15-it'}
2022-04-08 00:12:03,976 INFO    MainThread: GET https://service.azul.data.humancellatlas.org/index/files?catalog=dcp15-it&filters=%7B%22fileFormat%22%3A+%7B%22is%22%3A+%5B%22fastq.gz%22%2C+%22fastq%22%5D%7D%7D&size=1&order=asc&sort=fileSize ...
2022-04-08 00:12:04,101 INFO    MainThread: ... -> 200
2022-04-08 00:12:04,101 INFO    MainThread: Failed sub-test [repository_files] {'catalog': 'dcp15-it'}
2022-04-08 00:12:04,101 INFO    MainThread: Beginning sub-test [managed_access] {}
2022-04-08 00:12:04,101 INFO    MainThread: Failed sub-test [managed_access] {}
```

Spike to diagnose and determine what the relationship is with https://github.com/DataBiosphere/azul/issues/4053

**Comment by noah-aviel-dove** [comment]
No relation to https://github.com/DataBiosphere/azul/issues/4053 AFAICT

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc: "I think the easiest solution would be to retry the file search without any filter if it yields no results, and to only preform the fastq validation if the downloaded file is a fastq and validate other files by requiring that they are not empty."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "To be demoed as part of #4093."
