### ISSUE TITLE
`lm2` catalog has empty strings for `file format`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4097]
```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=25&catalog=lm2'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1343, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 1077, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 81, in search
    response = self.service.search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 88, in search
    response = self._search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 217, in _search
    return factory.make_response()
  File "/var/task/azul/service/hca_response_v5.py", line 240, in make_response
    hits=self.make_hits())
  File "/var/task/azul/service/hca_response_v5.py", line 444, in make_hits
    return list(map(self.make_hit, self.hits))
  File "/var/task/azul/service/hca_response_v5.py", line 479, in make_hit
    hit['fileTypeSummaries'] = [
  File "/var/task/azul/service/hca_response_v5.py", line 480, in <listcomp>
    file_type_summary(aggregate_file)
  File "/var/task/azul/service/hca_response_v5.py", line 476, in file_type_summary
    assert summary['format']
AssertionError
```

```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/samples?filters=%7B%7D&size=25&catalog=lm2'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1329, in get_sample_data
    return repository_search('samples', sample_id)
  File "/var/task/app.py", line 1077, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 81, in search
    response = self.service.search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 88, in search
    response = self._search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 217, in _search
    return factory.make_response()
  File "/var/task/azul/service/hca_response_v5.py", line 240, in make_response
    hits=self.make_hits())
  File "/var/task/azul/service/hca_response_v5.py", line 444, in make_hits
    return list(map(self.make_hit, self.hits))
  File "/var/task/azul/service/hca_response_v5.py", line 479, in make_hit
    hit['fileTypeSummaries'] = [
  File "/var/task/azul/service/hca_response_v5.py", line 480, in <listcomp>
    file_type_summary(aggregate_file)
  File "/var/task/azul/service/hca_response_v5.py", line 476, in file_type_summary
    assert summary['format']
AssertionError
```

Must be in one or both of the new snapshots, probably the phantom files

- `lungmap_prod_20037472ea1d4ddb9cd356a11a6f0f76__20220307_20220310_lm2`
- `lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220311_lm2`

**Comment by hannes-ucsc** [comment]
Assignee to work around this by removing the assertion in a partial PR. So no `Fix: …` but `Work around …` titles.

**Comment by melainalegaspi** [comment]
Waiting for updated snapshots.

**Comment by theathorn** [comment]
Also see HumanCellAtlas/metadata-schema/#1459.

**Comment by theathorn** [comment]
This issue is fixed in `prod` but not in `dev`.

**Comment by theathorn** [comment]
Issue is now fixed in both `dev` and `prod`.
