### ISSUE TITLE
Research the 35 indexing failures in staging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#412]
The `azul-fail-staging` queue has 35 notifications in it. Plug the bundle UUIDs from those notifications into Kibana and get the backtraces for those failed attempts. Paste results here.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-268)
┆Project Name: azul
┆Issue Number: AZUL-268

**Comment by achave11** [comment]
```
{"bundle_uuid": "3d887cb3-7a24-445f-acbe-9ff7363a18af", "bundle_version": "2018-10-11T171425.076754Z"}
```
```
[WARNING]	2018-10-11T19:00:08.335Z	b0b464da-f537-5bd0-ad47-30e36ac3ccf7	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.donor_organism_json'}}]}}}, 'subscription_id': 'c682cb77-df8d-4f2c-9187-5eef3ad6f850', 'transaction_id': '68c06f48-bf97-481a-8c27-ce32c4bde508', 'match': {'bundle_uuid': '3d887cb3-7a24-445f-acbe-9ff7363a18af', 'bundle_version': '2018-10-11T171425.076754Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 201, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 590, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 482, in __init__
    super().__init__(json, manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 462, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R2.fastq.gz'
```

**Comment by achave11** [comment]
```
{"bundle_uuid": "bf8062f7-0417-466c-9202-5c9342c72bc2", "bundle_version": "2018-10-11T164733.133173Z"}
```
```
[WARNING]	2018-10-11T17:13:57.227Z	c792dd35-5fee-5fc1-8b47-890cd9104ab5	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '7a93ef25-027f-499a-be01-74240ce6812b', 'subscription_id': '5ce9186d-6281-4a8e-9919-732d9c173444', 'es_query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.donor_organism_json'}}]}}}, 'match': {'bundle_uuid': 'bf8062f7-0417-466c-9202-5c9342c72bc2', 'bundle_version': '2018-10-11T164733.133173Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 123, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 170, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 549, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 543, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 512, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 512, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 511, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 441, in __init__
    super().__init__(json, manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 421, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R1.fastq.gz'
```

**Comment by achave11** [comment]
```
{"bundle_uuid": "58c8f697-9fe3-4fe8-8d04-0c8e6ec09cc7", "bundle_version": "2018-10-11T171821.760493Z"}
```
```

**Comment by achave11** [comment]
@hannes-ucsc `KeyError` seems to be recurring issue with failure.

**Comment by achave11** [comment]
```
[WARNING]	2018-10-11T19:43:48.505Z	97a3448f-9545-5e79-968e-10b63f5649ef	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.donor_organism_json'}}]}}}, 'subscription_id': '8f026d27-c7cf-48b4-8b60-0c091296c335', 'transaction_id': 'fb20abf3-af02-4679-b5e4-e2bda26986a3', 'match': {'bundle_uuid': '4d939743-d276-4c78-a392-b2ead842c149', 'bundle_version': '2018-10-09T065905.634949Z'}}}.
Traceback (most recent call last):
  File "/var/task/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/var/task/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/37c562ce-3a5c-40cf-af46-15a7f2c80b56?version=2018-10-03T091920.755000Z&replica=aws (Caused by ResponseError('too many redirects',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 42, in index
    num_workers=config.num_dss_workers)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 81, in download_bundle_metadata
    return bundle['version'], manifest, dict(metadata_files)
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 73, in download_file
    return file_name, client.get_file(uuid=file_uuid, version=file_version, replica='aws')
  File "/var/task/hca/util/__init__.py", line 155, in __call__
    return self._consume_response(self._request(kwargs))
  File "/var/task/hca/util/__init__.py", line 141, in _request
    timeout=self.client.timeout_policy)
  File "/var/task/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/37c562ce-3a5c-40cf-af46-15a7f2c80b56?version=2018-10-03T091920.755000Z&replica=aws (Caused by ResponseError('too many redirects',))
```

**Comment by achave11** [comment]
```
[WARNING]	2018-10-11T23:15:20.193Z	7df7b51c-dc41-5e05-9bb3-e12507f67af3	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.donor_organism_json'}}]}}}, 'subscription_id': '2eafb5dc-a113-415c-9a4a-a5e09209e22e', 'transaction_id': 'cd1f55e7-8013-46a7-9a50-ac909af0a289', 'match': {'bundle_uuid': 'df00a6fc-0015-4ae0-a1b7-d4b08af3c5a6', 'bundle_version': '2018-10-03T224939.551659Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 200, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 588, in __init__
    self.processes = from_json_vx(Process)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 30, in from_json
    content = json.get('content', json)
AttributeError: 'bytes' object has no attribute 'get'
```

**Comment by achave11** [comment]
There is three main reasons why it fails. 
One and the most common:
* KeyValue Error
 ``` Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 201, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 590, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 482, in __init__
    super().__init__(json, manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 462, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R2.fastq.gz'
```
The second occurs three times:
* MaxRetryError & RetryError 
```
Traceback (most recent call last):
  File "/var/task/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/var/task/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/37c562ce-3a5c-40cf-af46-15a7f2c80b56?version=2018-10-03T091920.755000Z&replica=aws (Caused by ResponseError('too many redirects',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 42, in index
    num_workers=config.num_dss_workers)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 81, in download_bundle_metadata
    return bundle['version'], manifest, dict(metadata_files)
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 73, in download_file
    return file_name, client.get_file(uuid=file_uuid, version=file_version, replica='aws')
  File "/var/task/hca/util/__init__.py", line 155, in __call__
    return self._consume_response(self._request(kwargs))
  File "/var/task/hca/util/__init__.py", line 141, in _request
    timeout=self.client.timeout_policy)
  File "/var/task/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/37c562ce-3a5c-40cf-af46-15a7f2c80b56?version=2018-10-03T091920.755000Z&replica=aws (Caused by ResponseError('too many redirects',))
```
And the last, only occurs ones: 
* AttributeError
```
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 200, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 588, in __init__
    self.processes = from_json_vx(Process)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 30, in from_json
    content = json.get('content', json)
AttributeError: 'bytes' object has no attribute 'get'
```

**Comment by hannes-ucsc** [comment]
Can you please produce an exhaustive list? For every type of error, I would like to see all bundle UUIDs and versions that caused it.

**Comment by achave11** [comment]
```
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 201, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 590, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 482, in __init__
    super().__init__(json, manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 462, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R2.fastq.gz'
```
```
'bundle_uuid': '3d887cb3-7a24-445f-acbe-9ff7363a18af' 'bundle_version': '2018-10-11T171425.076754Z'
'bundle_uuid': '58c8f697-9fe3-4fe8-8d04-0c8e6ec09cc7', 'bundle_version': '2018-10-11T171821.760493Z'
'bundle_uuid': '58c8f697-9fe3-4fe8-8d04-0c8e6ec09cc7', 'bundle_version': '2018-10-11T171821.760493Z'
'bundle_uuid': 'b6d77439-842e-491f-aa96-eb1cd47e0ee7', 'bundle_version': '2018-09-05T180319.874463Z'
'bundle_uuid': '627c8a5c-fffc-4c6f-9464-7a69a0a20fd8', 'bundle_version': '2018-09-05T225240.236224Z'
'bundle_uuid': '2c84313c-4a86-46f6-9ab4-4b2117ebc856', 'bundle_version': '2018-09-05T175912.060350Z'
'bundle_uuid': '074a25ec-f3fd-4562-8f8a-607168fb1fce', 'bundle_version': '2018-10-11T171301.250033Z'
'bundle_uuid': '9617439f-e5e5-4429-869d-8e9484624133', 'bundle_version': '2018-10-10T215149.333488Z'
'bundle_uuid': '074a25ec-f3fd-4562-8f8a-607168fb1fce', 'bundle_version': '2018-10-11T171301.250033Z'
```

**Comment by achave11** [comment]
```
Traceback (most recent call last):
  File "/var/task/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/var/task/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/var/task/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/262834ea-1ec8-43b3-afef-38e11fae97f9?version=2018-10-04T020604.161000Z&replica=aws (Caused by ResponseError('too many redirects',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/app.py", line 123, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 42, in index
    num_workers=config.num_dss_workers)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 81, in download_bundle_metadata
    return bundle['version'], manifest, dict(metadata_files)
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/var/lang/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/humancellatlas/data/metadata/helpers/dss.py", line 73, in download_file
    return file_name, client.get_file(uuid=file_uuid, version=file_version, replica='aws')
  File "/var/task/hca/util/__init__.py", line 155, in __call__
    return self._consume_response(self._request(kwargs))
  File "/var/task/hca/util/__init__.py", line 141, in _request
    timeout=self.client.timeout_policy)
  File "/var/task/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 504, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dss.staging.data.humancellatlas.org', port=443): Max retries exceeded with url: /v1/files/262834ea-1ec8-43b3-afef-38e11fae97f9?version=2018-10-04T020604.161000Z&replica=aws (Caused by ResponseError('too many redirects',))
```

```
'bundle_uuid': 'ecf22670-b79c-42c4-9679-07f6b836e940', 'bundle_version': '2018-10-04T031303.814854Z'
'bundle_uuid': '4d939743-d276-4c78-a392-b2ead842c149', 'bundle_version': '2018-10-09T065905.634949Z'
'bundle_uuid': '67b859c2-ab56-457c-9da0-3445c150ce53', 'bundle_version': '2018-10-08T163821.235037Z'
'bundle_uuid': 'ecf22670-b79c-42c4-9679-07f6b836e940', 'bundle_version': '2018-10-04T031303.814854Z'
'bundle_uuid': '4d939743-d276-4c78-a392-b2ead842c149', 'bundle_version': '2018-10-09T065905.634949Z'
'bundle_uuid': '67b859c2-ab56-457c-9da0-3445c150ce53', 'bundle_version': '2018-10-08T163821.235037Z'
'bundle_uuid': '9ded9d19-d690-4928-8d1b-df0f0bb16b2e', 'bundle_version': '2018-09-17T161449.293928Z'
```

**Comment by achave11** [comment]
```
Traceback (most recent call last):
  File "/var/task/app.py", line 128, in index
    indexer.index(notification)
  File "/var/task/azul/indexer.py", line 60, in index
    for es_document in es_documents:
  File "/var/task/azul/project/hca/transformers.py", line 200, in create_documents
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 588, in __init__
    self.processes = from_json_vx(Process)
  File "/var/task/humancellatlas/data/metadata/api.py", line 584, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 553, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 552, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 30, in from_json
    content = json.get('content', json)
AttributeError: 'bytes' object has no attribute 'get'
```
```
'bundle_uuid': 'df00a6fc-0015-4ae0-a1b7-d4b08af3c5a6', 'bundle_version': '2018-10-03T224939.551659Z'
'bundle_uuid': 'df00a6fc-0015-4ae0-a1b7-d4b08af3c5a6', 'bundle_version': '2018-10-03T224939.551659Z'
```

**Comment by hannes-ucsc** [comment]
Filed https://github.com/HumanCellAtlas/ingest-central/issues/220

**Comment by hannes-ucsc** [comment]
Added comment on https://github.com/HumanCellAtlas/ingest-central/issues/215#issuecomment-430427180

**Comment by hannes-ucsc** [comment]
Filed https://github.com/HumanCellAtlas/data-store/issues/1645
