### ISSUE TITLE
/index/{entity_type}/{uuid} is broken

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4130]
```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/projects/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc?catalog=dcp2'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1705, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1340, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 1074, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 81, in search
    response = self.service.search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 246, in search
    response = one(response['hits'], too_short=EntityNotFoundError(entity_type, item_id))
  File "/opt/python/more_itertools/more.py", line 529, in one
    raise too_long or ValueError('too many items in iterable (expected 1)')
ValueError: too many items in iterable (expected 1)
```

Regression from https://github.com/DataBiosphere/azul/commit/5fc9ef23a1b2296e3d05b2a7658433cb60ac7553

**Comment by hannes-ucsc** [comment]
This is the fix: 

```diff
Index: src/azul/service/repository_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/service/repository_service.py b/src/azul/service/repository_service.py
--- a/src/azul/service/repository_service.py	(revision 8c00b81e7e6f61ccb30a23d14a15d83f1d047322)
+++ b/src/azul/service/repository_service.py	(date 1650575409223)
@@ -190,7 +190,7 @@
         """
         if item_id is not None:
             validate_uuid(item_id)
-            filters.update({'entryId': {'is': [item_id]}})
+            filters = filters.update({'entryId': {'is': [item_id]}})
 
         response = self._search(catalog=catalog,
                                 filters=filters,
```
