### ISSUE TITLE
IT in GitLab `prod` failed due to transient ReadTimeoutError

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4133]
Multiple tests in [IT for GitLab `prod`](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/19769) failed with the following stack trace:
```
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 172, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 417, in test_indexing
    notifications, fqids = self._prepare_notifications(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 836, in _prepare_notifications
    list(starmap(update, self._list_bundles(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 314, in _list_bundles
    source, prefix, new_fqids = self._list_partition_bundles(catalog, source)
  File "/builds/ucsc/azul/test/integration_test.py", line 251, in _list_partition_bundles
    source = plugin.resolve_source(source)
  File "/builds/ucsc/azul/src/azul/plugins/__init__.py", line 272, in resolve_source
    id = self.lookup_source_id(spec)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 246, in lookup_source_id
    return self.tdr.lookup_source(spec).id
  File "/builds/ucsc/azul/src/azul/terra.py", line 385, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 408, in _lookup_source
    response = self._request('GET', endpoint, fields=params)
  File "/builds/ucsc/azul/src/azul/terra.py", line 299, in _request
    response = self._http_client.request(method,
  File "/build/.venv/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/build/.venv/lib/python3.8/site-packages/google/auth/transport/urllib3.py", line 388, in urlopen
    response = self.http.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=20.0)
```

**Comment by hannes-ucsc** [comment]
Sigh. OK, given https://humancellatlas.slack.com/archives/C01360XN04S/p1650575714129139?thread_ts=1649867983.880989&cid=C01360XN04S we'll wait until tomorrow and try the IT again.

**Comment by achave11** [comment]
Failure in the deploy job while running `post_deploy` make target https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44287

**Comment by achave11** [comment]
Additional post deploy failure: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44417

**Comment by achave11** [comment]
The re-run for the previous failure ^^ also failed. Same issue, slightly different message for the RequirementError.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/44425
```
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 87, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 82, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 55, in verify_sources
    raise e
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 400, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 417, in _lookup_source
    require(response.status == 200,
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1320, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1339, in reject
    raise exception(*args)
azul.RequirementError: ("Failed to access snapshot 'hca_dev_1cd1f41ff81a486ba05b66ec60f81dcf__20210901_20210903' via the TDR API after resolving its ID to '3d661f98-8742-434a-98de-168dde5b5120'", 500, b'{"message":"java.net.SocketTimeoutException: connect timed out","errorDetail":[]}')
make[1]: *** [Makefile:91: post_deploy] Error 1
make[1]: Leaving directory '/builds/ucsc/azul'
make: *** [Makefile:87: auto_deploy] Error 2
```

**Comment by achave11** [comment]
Timeout during `deploy` job in `dev` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45224

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45488

**Comment by achave11** [comment]
Another ReadTimeoutError that raises an AssertionError at run time https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46825/

**Comment by achave11** [comment]
Timeout during deploy job in sandbox https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/49776

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/49784

**Comment by achave11** [comment]
Timeout during `deploy` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/49795

**Comment by achave11** [comment]
Timeout during `deploy` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/49831

**Comment by achave11** [comment]
Timeout during `deploy` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/49890

**Comment by danielsotirhos** [comment]
Timeout during `IT` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/55645

**Comment by achave11-ucsc** [comment]
It looks like there's another instance of this failure in the `anvildev` IT run https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9838#L1230.

**Comment by hannes-ucsc** [comment]
No recurrences since then.
