### ISSUE TITLE
Transient SignatureDoesNotMatch error from GCS during IT

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4185]
`<edit>`
The build linked to by Abraham below wasn't the first occurrence. Here are earlier ones:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45367#L1896
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45255#L1894

(@hannes-ucsc)
`</edit>`

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45463
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format='terra.bdbag', attempts=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 360, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 523, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 681, in _check_terra_bdbag
    self.assertEqual(200, response.status, response.data)
AssertionError: 200 != 403 : b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>GOOG4-RSA-SHA256\n20220512T161238Z\n20220512/auto/storage/goog4_request\na423786e4f1df59a7e29996f2fc4905411105080af2115871d095419010c18de</StringToSign><CanonicalRequest>GET\n/datarepo-dev-f9f33779-bucket/06cd0da0-2ba1-404c-ae23-6f5b964c67a0/cb08d1c2-deea-41b1-8242-93ed389b36e2/bd9f449d-2d1b-4ad2-8a30-db9f0428a019_2021-02-03T11:13:49.077000Z_B3_bamtofastq_S1_L001_I1_006.fastq.gz\nX-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=jade-k8-sa%40broad-jade-dev.iam.gserviceaccount.com%2F20220512%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20220512T161238Z&amp;X-Goog-Expires=900&amp;X-Goog-SignedHeaders=host\nhost:storage.googleapis.com\n\nhost\nUNSIGNED-PAYLOAD</CanonicalRequest></Error>"
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='dcp2-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 360, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 756, in _test_repository_files
    response = self._get_url(furl(response['Location']), stream=True)
  File "/builds/ucsc/azul/test/integration_test.py", line 597, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 621, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (403, 'Forbidden', b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>GOOG4-RSA-SHA256\n20220512T161244Z\n20220512/auto/storage/goog4_request\nab2146aab6ae7b885b8823f899319790e9bc2a7eba02ae04c73ccdecc7ad4e19</StringToSign><CanonicalRequest>GET\n/datarepo-dev-f9f33779-bucket/06cd0da0-2ba1-404c-ae23-6f5b964c67a0/cb08d1c2-deea-41b1-8242-93ed389b36e2/bd9f449d-2d1b-4ad2-8a30-db9f0428a019_2021-02-03T11:13:49.077000Z_B3_bamtofastq_S1_L001_I1_006.fastq.gz\nX-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=jade-k8-sa%40broad-jade-dev.iam.gserviceaccount.com%2F20220512%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20220512T161244Z&amp;X-Goog-Expires=900&amp;X-Goog-SignedHeaders=host\nhost:storage.googleapis.com\n\nhost\nUNSIGNED-PAYLOAD</CanonicalRequest></Error>")
----------------------------------------------------------------------
Ran 16 tests in 613.138s
FAILED (failures=2, skipped=5)
make: *** [Makefile:160: integration_test] Error 1
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45494

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45563

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45781

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45804

**Comment by achave11** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/21501

**Comment by hannes-ucsc** [comment]
Based on when this first occurred, one hypothesis of the cause is that furl might mangle the signed URL returned by TDR

https://github.com/DataBiosphere/azul/blame/cc7b1e8290ebe32ccb0eaae7b0c8f2ab479460d4/src/azul/drs.py#L140

To confirm/reject that hypothesis we should log the DRS response from TDR and, at the next occurrence of this bug with the logging in place, carefully compare the signed URLs in what the service logs as the DRS response, its own response, and the IT job log.

```diff
Index: src/azul/drs.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/drs.py b/src/azul/drs.py
--- a/src/azul/drs.py	(revision 5f1b30da8538599eebe883e751981cfc9a72f14f)
+++ b/src/azul/drs.py	(date 1653933510492)
@@ -169,8 +169,10 @@
                 raise DRSError(response)
 
     def _request(self, url: str) -> urllib3.HTTPResponse:
-        log.info('GET %s', url)
-        return self.http_client.request('GET', url, redirect=False)
+        log.info('GET %s ...', url)
+        response = self.http_client.request('GET', url, redirect=False)
+        log.info('-> %r %r %r', response.status, response.data, response.headers)
+        return response
 
 
 class DRSError(Exception):
```

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46789

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/47037

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/48233

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/48283

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/48323

**Comment by danielsotirhos** [comment]
The use of `furl` is transforming the signed URL making it invalid. Specifically, `%3A` is being converted to `:`.

Successful example (signed URL does not contain `%3A`):
```
File:
https://service.azul.data.humancellatlas.org/index/files/54cf0f0d-0151-4234-893b-e8a3f0e3ade4?catalog=dcp17

Download URL:
https://service.azul.data.humancellatlas.org/fetch/repository/files/e511acfc-2764-4748-8ea7-643e97430647?catalog=dcp17&version=2021-05-13T22%3A14%3A49.376000Z

Signed URL logged when received:
https://storage.googleapis.com/datarepo-a6e6a252-bucket/8b504553-0300-426e-876c-116772d06c6e/a73ca87b-04d1-4f46-9cec-d1f2003a7dda/W-RB4W_D17PrPzF_BE_S1_L001_R1.fastq.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=datarepo-jade-api%40terra-datarepo-production.iam.gserviceaccount.com%2F20220629%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220629T195925Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=733083c8ba741c666bbf4f10b2dc9bddf9ce7faf3a22f5cb26ec612cd6136e58f397a30a753a87178e9a4582b33812275456ad190a5480423658774d511dc8124ebd9a28e7d99ed3f94e297cea8c0fa3e5cc617ee1ca4b9556f8aef3fc243eb69ca63f9b26d8b9634454100a70b7810d96d13594901489796f8d4844d36c2c2014c0639094390a21ad4e227e2a68ea45361eba7a4204155711703e036ec7a4b0d419e707d958be94cd6872f34b5e11f1daabe4a3ee302252354e504227325dac7ed17eeaa3c497a042355b1d573a5ffb85dee497d9a58fe4bdd30d3e2fa788cd6dbd2af178801f4cd663f3e1af7160ead9e12a798b1fd9e7b533e6dca83d2c83

Signed-URL returned from Azul (matches logged value):
https://storage.googleapis.com/datarepo-a6e6a252-bucket/8b504553-0300-426e-876c-116772d06c6e/a73ca87b-04d1-4f46-9cec-d1f2003a7dda/W-RB4W_D17PrPzF_BE_S1_L001_R1.fastq.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=datarepo-jade-api%40terra-datarepo-production.iam.gserviceaccount.com%2F20220629%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220629T195925Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=733083c8ba741c666bbf4f10b2dc9bddf9ce7faf3a22f5cb26ec612cd6136e58f397a30a753a87178e9a4582b33812275456ad190a5480423658774d511dc8124ebd9a28e7d99ed3f94e297cea8c0fa3e5cc617ee1ca4b9556f8aef3fc243eb69ca63f9b26d8b9634454100a70b7810d96d13594901489796f8d4844d36c2c2014c0639094390a21ad4e227e2a68ea45361eba7a4204155711703e036ec7a4b0d419e707d958be94cd6872f34b5e11f1daabe4a3ee302252354e504227325dac7ed17eeaa3c497a042355b1d573a5ffb85dee497d9a58fe4bdd30d3e2fa788cd6dbd2af178801f4cd663f3e1af7160ead9e12a798b1fd9e7b533e6dca83d2c83
```

Unsuccessful example (signed URL contains `%3A`):
```
File:
https://service.azul.data.humancellatlas.org/index/files/229e0f88-29fb-4345-b767-621e53e42d16?catalog=dcp17

Download URL:
https://service.azul.data.humancellatlas.org/fetch/repository/files/618c9f8e-c03c-4d07-9ea7-bb834af95bfb?catalog=dcp17&version=2021-01-29T15%3A01%3A26.607000Z

Signed URL logged when received:
https://storage.googleapis.com/datarepo-3c303d91-bucket/1110585b-84d8-4910-8cad-758fed623735/2aa96a17-d753-407d-998a-4bfeac33d8ca/618c9f8e-c03c-4d07-9ea7-bb834af95bfb_2021-01-29T15%3A01%3A26.607000Z_SIGAA11_S45_L001_I1_001.fastq.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=datarepo-jade-api%40terra-datarepo-production.iam.gserviceaccount.com%2F20220629%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220629T200122Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=099de501d1e0e5f50fdf7680a9ceb5a930a5a31aad725b42adc0c7c4191680c18fa8c4a7015307ac17ef6b421295fcca986eeb07962d3d533043178688689207ba5d736d89f1939607593741bdc49bbca489cfcf23c548fa3ce256b4aecd35ffdd3445bea0c65fd5f4dc39d469bded4cafe8898dc38b9c3e17f20e96a19863e194a5d4c769a58f366379e6d3bb3e01978af8ab92c4c48c20c19e771bf185154071756ef2b2335fe395a53b73cbfb15c144d89cd9287f7c9fc845579425d918d9ca954a9ea9e49f7ba3349a466870e138a0628a9bf3f6f8067241604b370c788a4b1c8f9a79887111ea02a95a0e9916d3df7d092965d3f856bd2cd1e47f55f2ae

Signed-URL returned from Azul (does not match logged value):
https://storage.googleapis.com/datarepo-3c303d91-bucket/1110585b-84d8-4910-8cad-758fed623735/2aa96a17-d753-407d-998a-4bfeac33d8ca/618c9f8e-c03c-4d07-9ea7-bb834af95bfb_2021-01-29T15:01:26.607000Z_SIGAA11_S45_L001_I1_001.fastq.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=datarepo-jade-api%40terra-datarepo-production.iam.gserviceaccount.com%2F20220629%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220629T200122Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=099de501d1e0e5f50fdf7680a9ceb5a930a5a31aad725b42adc0c7c4191680c18fa8c4a7015307ac17ef6b421295fcca986eeb07962d3d533043178688689207ba5d736d89f1939607593741bdc49bbca489cfcf23c548fa3ce256b4aecd35ffdd3445bea0c65fd5f4dc39d469bded4cafe8898dc38b9c3e17f20e96a19863e194a5d4c769a58f366379e6d3bb3e01978af8ab92c4c48c20c19e771bf185154071756ef2b2335fe395a53b73cbfb15c144d89cd9287f7c9fc845579425d918d9ca954a9ea9e49f7ba3349a466870e138a0628a9bf3f6f8067241604b370c788a4b1c8f9a79887111ea02a95a0e9916d3df7d092965d3f856bd2cd1e47f55f2ae
```

The problem, `furl` un-converts URL encoded characters in the URL:
```
>>> u = furl('https://example.com/a%3Ab%3Ac')
>>> str(u)
'https://example.com/a:b:c'
```

**Comment by achave11** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/23339

**Comment by hannes-ucsc** [comment]
For demo, attempt to [reproduce](https://github.com/DataBiosphere/azul/issues/4185#issuecomment-1170469277).
