### ISSUE TITLE
Deploy step fails in GitLab dev due to TerraStatusException

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4192]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45571
```
2022-05-13 18:25:16,244 DEBUG   ThreadPoolExecutor-0_3: _request(…) -> b'{"id":"d8ee3cfa-32c9-49c2-b1ae-af0a7bb1c98d","name":"hca_dev_955dfc2ca8c64d04aa4d907610545d11__20210831_20210903","description":"Create snapshot hca_dev_955dfc2ca8c64d04aa4d907610545d11__20210831_20210903","createdDate":"2021-09-03T21:49:48.932684Z","co...'
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 87, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 82, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 55, in verify_sources
    raise e
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 431, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 447, in _lookup_source
    require(response.status == 200,
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1321, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1340, in reject
    raise exception(*args)
azul.terra.TerraStatusException: ('Unexpected response from https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots/d8ee3cfa-32c9-49c2-b1ae-af0a7bb1c98d', 500, b'{"message":"java.net.SocketTimeoutException: connect timed out","errorDetail":[]}')
make[1]: Leaving directory '/builds/ucsc/azul'
make[1]: *** [Makefile:91: post_deploy] Error 1
make: *** [Makefile:87: auto_deploy] Error 2
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45572

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45561

**Comment by melainalegaspi** [comment]
see https://github.com/DataBiosphere/azul/issues/4133#issuecomment-1110341132

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45573

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/45574

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46175

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46232

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46642

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/46787

**Comment by achave11** [comment]
Occurred during reindex job https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/47148

**Comment by melainalegaspi** [comment]
See https://humancellatlas.slack.com/archives/C01360XN04S/p1651277817137659

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/51364

**Comment by achave11** [comment]
Happened during `sandox` [IT run](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/51451).

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/51846

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53058

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53064

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53067

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53318

**Comment by achave11** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53499
```
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 86, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 81, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 54, in verify_sources
    raise e
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 460, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 467, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 559, in _check_response
    raise TerraStatusException(endpoint, response)
azul.terra.TerraStatusException: ('Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2%27), 502, b'\n<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n')
make[1]: *** [Makefile:91: post_deploy] Error 1
make[1]: Leaving directory '/builds/ucsc/azul'
make: *** [Makefile:87: auto_deploy] Error 2
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by hannes-ucsc** [comment]
No further occurrences.
