### ISSUE TITLE
`protobuf` > 3.20.1 break `google-cloud*` dependencies

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4249]
```
 Traceback (most recent call last):
  File "/home/runner/work/azul/azul/scripts/generate_openapi_document.py", line 57, in <module>
    main()
  File "/home/runner/work/azul/azul/scripts/generate_openapi_document.py", line 49, in main
    app_module = load_app_module('service')
  File "/home/runner/work/azul/azul/src/azul/modules.py", line 51, in load_app_module
    return load_module(path, f'lambdas.{lambda_name}.app', module_attributes)
  File "/home/runner/work/azul/azul/src/azul/modules.py", line 42, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/azul/azul/lambdas/service/app.py", line 87, in <module>
    from azul.service.drs_controller import (
  File "/home/runner/work/azul/azul/src/azul/service/drs_controller.py", line 57, in <module>
    from azul.service.source_controller import (
  File "/home/runner/work/azul/azul/src/azul/service/source_controller.py", line 26, in <module>
    from azul.terra import (
  File "/home/runner/work/azul/azul/src/azul/terra.py", line 32, in <module>
    from google.cloud import (
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 60, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 40, in <module>
    from google.cloud.bigquery import schema
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery/schema.py", line 19, in <module>
    from google.cloud.bigquery_v2 import types
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery_v2/__init__.py", line 23, in <module>
    from google.cloud.bigquery_v2 import types
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery_v2/types.py", line 23, in <module>
    from google.cloud.bigquery_v2.proto import encryption_config_pb2
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/cloud/bigquery_v2/proto/encryption_config_pb2.py", line 48, in <module>
    _descriptor.FieldDescriptor(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
make: *** [Makefile:190: openapi] Error 1
Error: Process completed with exit code 2.
```

Reading through https://github.com/protocolbuffers/protobuf/issues/10051, some suggestions included [upgrading google packages](https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138293917). However, after upgrading to the recommended versions, protobuf was downgraded to 3.20.1 and the problem was fixed. The same result was achieved when pinning `protobuf`, without updating google cloud packages.

We should consider releasing the pin on `protobuf` or upgrading the google cloud packages.

**Comment by achave11** [comment]
Management of protobuf (as transient dep) is deferred to the `google-cloud-bigquery` dependency. https://github.com/DataBiosphere/azul/pull/4248/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R19

**Comment by kushan-gunasekera** [comment]
For anyone who is looking for a proper solution,

answer:- https://stackoverflow.com/a/72493690/6194097
