### ISSUE TITLE
Compact manifest without filters fails to generate

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4261]
# Repro

```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp2'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 281
Content-Type: application/json
Date: Fri, 24 Jun 2022 02:31:38 GMT
Via: 1.1 51c947a89f81287c4310dda23943d796.cloudfront.net (CloudFront)
X-Amz-Cf-Id: N6c2Ddelnf96MZkYXXiGwwjUPGpWuMDPrwljoj8MfxHDrG0QBN3eNw==
X-Amz-Cf-Pop: LAX50-C2
X-Amzn-Trace-Id: Root=1-62b52205-0a1f8ea55804ff4402e9f91b;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: UNJA6GMUoAMFWIQ=
x-amzn-RequestId: 2673e8da-a21a-4bb3-b24f-e0e6f9d6e022

{
    "CommandLine": {
        "bash": "curl 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMWQyYTI1YjktNWYyMy00MjJjLWJkMDItZDkzYmU1ZjRlZWY1IiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D'",
        "cmd.exe": "curl.exe \"https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMWQyYTI1YjktNWYyMy00MjJjLWJkMDItZDkzYmU1ZjRlZWY1IiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D\""
    },
    "Location": "https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMWQyYTI1YjktNWYyMy00MjJjLWJkMDItZDkzYmU1ZjRlZWY1IiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D",
    "Retry-After": 1,
    "Status": 301
}
```

```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMWQyYTI1YjktNWYyMy00MjJjLWJkMDItZDkzYmU1ZjRlZWY1IiwgInJlcXVlc3RfaW5kZXgiOiAwLCAid2FpdF90aW1lIjogMX0%3D'
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 360
Content-Type: text/plain
Date: Fri, 24 Jun 2022 02:33:24 GMT
Via: 1.1 6152d4e35099aaa5ec23aec50cd7a8c4.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 8zyq_ZSn2wzEMzaO7VR7a_62XAUm638tNo83dLyyyhI5CdufqkQG2Q==
X-Amz-Cf-Pop: LAX50-C2
X-Amzn-Trace-Id: Root=1-62b52274-5ccfdc5c743454d62ddf51b4;Sampled=0
X-Cache: Error from cloudfront
x-amz-apigw-id: UNJSLFZRoAMFrtA=
x-amzn-RequestId: aac8969c-6687-49a7-ba8f-a881d6978bfb

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1752, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1583, in fetch_file_manifest
    return _file_manifest(fetch=True)
  File "/var/task/app.py", line 1603, in _file_manifest
    return app.manifest_controller.get_manifest_async(self_url=app.self_url,
  File "/var/task/azul/service/manifest_controller.py", line 157, in get_manifest_async
    token_or_state = self.async_service.inspect_generation(token)
  File "/var/task/azul/service/async_manifest_service.py", line 100, in inspect_generation
    raise StateMachineError(status, output)
azul.service.async_manifest_service.StateMachineError: ('Failed to generate manifest', 'FAILED', None)
```

# LambdaFunctionFailed stack trace

```
{
  "error": "TypeError",
  "cause": {
    "errorMessage": "unhashable type: 'list'",
    "errorType": "TypeError",
    "requestId": "51abedc2-dda5-4980-874c-c36d4480f0b1",
    "stackTrace": [
      "  File \"/var/task/chalice/app.py\", line 1601, in __call__\n    return self.handler(event_obj)\n",
      "  File \"/var/task/chalice/app.py\", line 1563, in __call__\n    return self.handler(request, self.next_handler)\n",
      "  File \"/var/task/azul/chalice.py\", line 110, in _lambda_context_middleware\n    return get_response(event)\n",
      "  File \"/var/task/chalice/app.py\", line 1554, in __call__\n    return self._original_func(event.to_dict(), event.context)\n",
      "  File \"/var/task/app.py\", line 1614, in generate_manifest\n    return app.manifest_controller.get_manifest(event)\n",
      "  File \"/var/task/azul/service/manifest_controller.py\", line 89, in get_manifest\n    self.partition_state_key: result.to_json()\n",
      "  File \"/var/task/azul/service/manifest_service.py\", line 275, in to_json\n    return attr.asdict(self)\n",
      "  File \"/opt/python/attr/_funcs.py\", line 67, in asdict\n    rv[a.name] = df(\n"
    ]
  }
}
```

**Comment by achave11** [comment]
Also happens for `dcp17` in `prod`.

**Comment by danielsotirhos** [comment]
Spike to diagnose.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "I should take this because I think I introduced it in one of the PRs for #3817."

**Comment by hannes-ucsc** [comment]
Smallest reproduction on `prod` I could come up with based on the reproduction in #4402:

https://service.azul.data.humancellatlas.org/fetch/manifest/files?catalog=dcp19&filters=%7B%22projectId%22%3A%7B%22is%22%3A%5B%2267a3de09-45b9-49c3-a068-ff4665daa50e%22%2C%2290bd6933-40c0-48d4-8d76-778c103bf545%22%5D%7D%2C%22genusSpecies%22%3A%7B%22is%22%3A%5B%22Homo%20sapiens%22%5D%7D%2C%22fileFormat%22%3A%7B%22is%22%3A%5B%22bai%22%2C%22bam%22%5D%7D%7D&format=compact

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
