### ISSUE TITLE
Service rejects organism age ranges of integers

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4330]
```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%22organismAgeRange%22%3A%7B%22intersects%22%3A%5B%5B0%2C1261440000%5D%5D%7D%7D&size=25&catalog=dcp2'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1752, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1321, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 80, in search
    response = self.service.search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 122, in search
    response = self._search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 242, in _search
    request = chain.prepare_request(request)
  File "/var/task/azul/service/elasticsearch_service.py", line 131, in prepare_request
    request = self.inner.prepare_request(request)
  File "/var/task/azul/service/elasticsearch_service.py", line 131, in prepare_request
    request = self.inner.prepare_request(request)
  File "/var/task/azul/service/elasticsearch_service.py", line 131, in prepare_request
    request = self.inner.prepare_request(request)
  [Previous line repeated 2 more times]
  File "/var/task/azul/service/elasticsearch_service.py", line 178, in prepare_request
    query = self.prepare_query()
  File "/var/task/azul/service/elasticsearch_service.py", line 217, in prepare_query
    for field_path, relation_and_values in self.prepared_filters.items():
  File "/var/task/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/var/task/azul/service/elasticsearch_service.py", line 190, in prepared_filters
    return self._translate_filters(self._reify_filters())
  File "/var/task/azul/service/elasticsearch_service.py", line 208, in _translate_filters
    values = field_type.filter(relation, values)
  File "/var/task/azul/indexer/document.py", line 576, in filter
    assert isinstance(gte, self.ends_type.native_type), gte
AssertionError: 0
```

Appending `.0` to each end of the filtering range works:

```
$ curl 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%22organismAgeRange%22%3A%7B%22intersects%22%3A%5B%5B0.0%2C1261440000.0%5D%5D%7D%7D&size=25&catalog=dcp2' | jq .pagination
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  333k  100  333k    0     0   406k      0 --:--:-- --:--:-- --:--:--  406k
{
  "count": 25,
  "total": 56,
  "size": 25,
  "next": "https://service.dev.singlecell.gi.ucsc.edu/index/projects?catalog=dcp2&filters=%7B%22organismAgeRange%22%3A+%7B%22intersects%22%3A+%5B%5B0.0%2C+1261440000.0%5D%5D%7D%7D&search_after=%5B%22Oleic+acid+restores+suppressive+defects+in+tissue-resident+FOXP3+Tregs+from+patients+with+multiple+sclerosis%27%22%2C+%22248fcf03-16c6-4a41-b6cc-aad4d894ca42%22%5D&sort=projectTitle&order=asc&size=25",
  "previous": null,
  "pages": 3,
  "sort": "projectTitle",
  "order": "asc"
}
```

To reproduce using the Data Browser visit

https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22organismAgeRange%22,%22terms%22:%5B%7B%22ageMax%22:1261440000,%22ageMin%22:0,%22ageUnit%22:%22year%22%7D%5D%7D%5D

Alternatively, visit the DB homepage and use the Donor - Age Range facet.

Observe

![image](https://user-images.githubusercontent.com/5143256/180361123-657abd18-4655-4841-9c5f-81738fb5031b.png)

**Comment by hannes-ucsc** [comment]
This is a regression from a9c79d6b which narrowed organism age range to be terminated only by `float` instance, not realizing that it is difficult in JavaScript to force `1.0` in JSON when the value is 1.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
