### ISSUE TITLE
`rename_resources.py` assumes it's running in `terraform` directory

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4368]
Regression from PR #4360 for #4122 

```
$ make -C lambdas clean
make: Entering directory '/home/hannes/workspace/hca/azul/lambdas'
for dir in indexer service layer; do make -C $dir clean; done
make[1]: Entering directory '/home/hannes/workspace/hca/azul/lambdas/indexer'
git clean -Xdf
Removing .chalice/config.json
Removing .chalice/deployments/
Removing .chalice/terraform/
Removing __pycache__/
Removing vendor/__pycache__/
Removing vendor/azul_changes.py
Removing vendor/resources/__pycache__/
Removing vendor/resources/environ.json
make[1]: Leaving directory '/home/hannes/workspace/hca/azul/lambdas/indexer'
make[1]: Entering directory '/home/hannes/workspace/hca/azul/lambdas/service'
git clean -Xdf
Removing .chalice/config.json
Removing .chalice/deployments/
Removing .chalice/terraform/
Removing __pycache__/
Removing vendor/__pycache__/
Removing vendor/azul_changes.py
Removing vendor/resources/__pycache__/
Removing vendor/resources/environ.json
make[1]: Leaving directory '/home/hannes/workspace/hca/azul/lambdas/service'
make[1]: Entering directory '/home/hannes/workspace/hca/azul/lambdas/layer'
git clean -Xdf
Removing .chalice/config.json
Removing .chalice/deployments/
Removing .chalice/terraform/
Removing __pycache__/
Removing requirements.txt
make[1]: Leaving directory '/home/hannes/workspace/hca/azul/lambdas/layer'
make: Leaving directory '/home/hannes/workspace/hca/azul/lambdas'

$ cd terraform/shared/

$ _select dev.shared

$ CI_COMMIT_REF_NAME=develop make rename_resources
python /home/hannes/workspace/hca/azul/scripts/check_branch.py
python backend.tf.json.template.py backend.tf.json
Creating backend.tf.json
python common.tf.json.template.py common.tf.json
Creating common.tf.json
python providers.tf.json.template.py providers.tf.json
Creating providers.tf.json
python shared.tf.json.template.py shared.tf.json
Creating shared.tf.json
terraform init

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
python /home/hannes/workspace/hca/azul/scripts/rename_resources.py
Traceback (most recent call last):
  File "/home/hannes/workspace/hca/azul/scripts/rename_resources.py", line 36, in <module>
    renamed.update(dict(chalice_renamed()))
  File "/home/hannes/workspace/hca/azul/scripts/rename_resources.py", line 28, in chalice_renamed
    with open(tf_config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hannes/workspace/hca/azul/lambdas/indexer/.chalice/terraform/chalice.tf.json'
make: *** [Makefile:35: rename_resources] Error 1

$ 
```

**Comment by hannes-ucsc** [comment]
The PR came back due to an unrelated failure (which is not a regression but a preexisting bug exposed by that PR) so I can fix this on the PR.

**Comment by hannes-ucsc** [comment]
6f69a6d8
