### ISSUE TITLE
IT in GitLab dev failed due to empty manifests

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4392]
Failure in https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/51372 is transient, and the consecutive retry [succeeded](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/51395).
```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/more_itertools/more.py", line 138, in first
    return next(iter(iterable))
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1029, in _test_managed_access
    first(public_source_ids & indexed_source_ids))
  File "/build/.venv/lib/python3.9/site-packages/more_itertools/more.py", line 145, in first
    raise ValueError('first() was called on an empty iterable, and no '
ValueError: first() was called on an empty iterable, and no default value was provided.
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 537, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 647, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 723, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.compact: 'compact'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 537, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 647, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 723, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.terra_bdbag: 'terra.bdbag'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 537, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 654, in _check_terra_bdbag
    rows = self.__check_manifest(file, 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 723, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='dcp2-it', format=<ManifestFormat.curl: 'curl'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 537, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 747, in _check_curl_manifest
    self.assertGreater(num_files, 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='dcp2-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 751, in _test_repository_files
    file = self._get_one_file(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 553, in _get_one_file
    self.fail('No files found')
AssertionError: No files found
----------------------------------------------------------------------
Ran 16 tests in 545.061s
FAILED (failures=5, errors=1, skipped=6)
make: *** [Makefile:160: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by achave11** [comment]
@hannes-ucsc: "Spike to reproduce with pinned seed on `sandbox` using a PR and branch that could become the basis for the resolution."

**Comment by theathorn** [comment]
@hannes-ucsc :"Abraham reports that he wasn't able to reproduce this in sandbox. Extend spike to diagnose."

**Comment by melainalegaspi** [comment]
@achave11 was able to reproduce: https://github.com/DataBiosphere/azul/pull/4396#issuecomment-1234577099

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "continue spike after blocker lands."

**Comment by achave11** [comment]
@hannes-ucsc: "Given @achave11  findings I would like @noah-aviel-dove to diagnose this further and propose a solution."

**Comment by achave11** [comment]
This captures both the incoming service request as well as the step function execution that generates the manifest.
**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-service-abrahamsc, /aws/lambda/azul-service-abrahamsc-manifest  
start-time: 2022-09-28T15:08:03.582Z  
end-time: 2022-09-28T21:10:54.258Z  
query-string:
```
fields @timestamp, @message
| filter @requestId in ["8e0d482e-e12e-4fbe-9411-a2a8262c6845", "b94b3f27-ade3-4961-b023-db2d26bee4a0", "442e3230-b4d8-4940-bbd9-84dc4dce7f5f", "b80bb2f2-aa6f-4c5e-bc9b-79ad8c1eeb8a"]
| sort @timestamp asc
| limit 10
```

**Comment by noah-aviel-dove** [comment]
This was caused by the IT randomly selecting *only* bundles from managed access sources for indexing. The logs from the `catalog_complete` sub-test failed build linked in the ticket show that the indexed bundles were drawn only two unique sources, both of which were managed access. This occurred via the following sequence of events:

1. To ensure managed access coverage, a single bundle was selected from each managed access source, of which there are 2 total (`cddb722a-4229-47bb-ba86-736b7898406f` and `2c4ec571-f489-4277-b215-da8dedd86803`).
2. To reach the target of >=32 total indexed bundles, additional bundles were selected from random sources, with no regard for managed access status.
3. The first source selected was `cddb722a-4229-47bb-ba86-736b7898406f`, one of the managed access sources.
4. The partition `f` was randomly selected from this source. This partition contains 71 bundles.
5. Since 2 + 71 >= 32, no further bundles were selected.

A solution should target the code that selects bundles for indexing in step (2) to ensure that at least one non-managed-access source is always indexed.
