### ISSUE TITLE
Triage Invicti/NetSparker findings for Azul service

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4417]

**Comment by nolunwa** [comment]
for the triaging and remediation of legitimate findings where are we tracking the tickets to ensure the team is closing the finding based on the FedRAMP timeline

**Comment by theathorn** [comment]
Elevating to high priority at @nolunwa's request.

**Comment by theathorn** [comment]
From 12/23/2022 [Detailed Scan Report (AZUL_DATA_PORTAL-SERVICE-0-20221221210206).pdf](https://drive.google.com/file/d/1x7UjR2M3C0f9LbEQjQSdsdAOVje1aAkf/view?usp=share_link) there are 0 Critical, 0 High, 196 Medium, 4 Low, 4 Best Practice and 3 Information findings.

Most of the Medium findings are for "Frame injection".

**Comment by theathorn** [comment]
@hannes-ucsc :'Assignee to consolidate findings into unique issues in the Azul private repo."

**Comment by danielsotirhos** [comment]
Created issues:
- https://github.com/DataBiosphere/azul-private/issues/12
- https://github.com/DataBiosphere/azul-private/issues/13
- https://github.com/DataBiosphere/azul-private/issues/14
- https://github.com/DataBiosphere/azul-private/issues/15
- https://github.com/DataBiosphere/azul-private/issues/16
- https://github.com/DataBiosphere/azul-private/issues/17
- https://github.com/DataBiosphere/azul-private/issues/18

**Comment by hannes-ucsc** [comment]
Reviewed.

**Comment by achave11** [comment]
@hannes-ucsc: "New report came in, assignee to triage Jan 11 scan."

**Comment by danielsotirhos** [comment]
There were no changes in the number of findings between this most recent 2023/01/05 scan and the previous 2022/12/21 scan.

![Screen Shot 2023-01-12 at 9 17 35 AM](https://user-images.githubusercontent.com/46407464/212135958-736afd87-6cc4-42d5-8dbb-444c775e10f5.png)

**Comment by danielsotirhos** [comment]
Assignee to triage report from 2/2/2023

**Comment by danielsotirhos** [comment]
![Screen Shot 2023-02-21 at 10 15 30 AM](https://user-images.githubusercontent.com/46407464/220427875-c0d9a7ae-75aa-4b47-a999-797432584321.png)

Comparing the 1/5/2023 Invicti scan results to the 2/2/2023 results.

## Stack Trace Disclosure (Python)

The 1/5/2023 scan found this issue from a request that specified the `order` param equal to `%27`.

This issue was triaged and fixed as https://github.com/DataBiosphere/azul/issues/4877

The 2/2/2023 scan also reported this issue, this time found by specifying the `search_after` parameter as `%27`.

The new issue has been triaged as https://github.com/DataBiosphere/azul/issues/4996

----

## Internal Server Error

The 1/5/2023 scan found this issue from a request specifying both the mutually exclusive params `search_before` and `search_after`.

This issue was triaged and fixed as https://github.com/DataBiosphere/azul/issues/4879

The 2/2/2023 scan also reported this issue, this time found by specifying the `search_after` parameter as `%27`.

The new issue has been triaged as https://github.com/DataBiosphere/azul/issues/4996

----

## Frame Injection

The 1/5/2023 scan found 193 instances of this finding.
The 2/2/2023 scan found 191, hence the difference of total findings (207 vs 205)

This issue was previously triaged as https://github.com/DataBiosphere/azul-private/issues/12

----

There were no other differences between the two Invicti scan reports.

**Comment by theathorn** [comment]
New [scan from 03/06/2023](https://drive.google.com/drive/folders/1X9FwOQSnCzpMfuclOvEJr28GCT9filRE).

**Comment by danielsotirhos** [comment]
![Screen Shot 2023-03-08 at 10 13 07 AM](https://user-images.githubusercontent.com/46407464/223802341-c264d2bb-d7cb-42f9-9f84-9f836234125e.png)

## Frame Injection

191 `Frame Injection` findings were resolved. These finding in the 2/2/2023 scan embeded html in the `version` parameter (example [URL](https://service.dev.singlecell.gi.ucsc.edu/repository/files/00b29524-af86-4c10-ba36-2d83fea1fbb3?catalog=dcp2&version=%3ciframe%20src%3d%22http%3a%2f%2fr87.com%2f%3f%22%3e%3c%2fiframe%3e)) and complained when the error response returned the given html.

This is no longer a finding due to changes by https://github.com/DataBiosphere/azul/issues/4878

## Stack Trace Disclosure (Python)

The 2/2/2023 scan reported this finding after following a URL which included invalid JSON code in the `search_after` parameter (example [URL](https://service.dev.singlecell.gi.ucsc.edu/index/bundles?catalog=dcp2&filters=%7B%7D&order=desc&search_after=%2527&size=10&sort=bundleVersion))

This is still an open issue https://github.com/DataBiosphere/azul/issues/4996, however the 3/2/2023 scan reported this finding for what seems to be a transient issue:

Requested URL: https://service.dev.singlecell.gi.ucsc.edu/repository/files/swagger.json
Response:
```
Traceback (most recent call last):
File "/var/task/azul/service/source_service.py", line 70, in list_sources
sources = self._get(cache_key)
File "/var/task/azul/service/source_service.py", line 108, in _get
raise Expired(key)
azul.service.source_service.Expired: Entry for key 'dcp2:' is expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1913, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 1634, in repository_files
result = _repository_files(file_uuid, fetch=False)
File "/var/task/app.py", line 1713, in
```

## End

There were no other differences between the 2/2/2023 and 3/2/2023 scan reports.

**Comment by hannes-ucsc** [comment]
> however the 3/2/2023 scan reported this finding for what seems to be a transient issue:

Transient or not, a ticket is needed.

**Comment by danielsotirhos** [comment]
> Transient or not, a ticket is needed.

Ticket created: https://github.com/DataBiosphere/azul/issues/5034

**Comment by dsotirho-ucsc** [comment]
Found an problem with the April 14th report, @hannes-ucsc to coordinate redoing it with Jevan, Nneka, and Fortreum.

**Comment by dsotirho-ucsc** [comment]
![Screen Shot 2023-04-18 at 9 06 23 AM](https://user-images.githubusercontent.com/46407464/232837191-3e693103-7782-41a6-bdcb-a4640254c779.png)

The [2023/04/17 Invicti scan](https://drive.google.com/drive/u/0/folders/1ogPVdPykilw4273fnOOub_GXvH36Z0mS) of https://indexer.prod.anvil.gi.ucsc.edu found zero Critical or High findings, two Medium, and two Low findings.

## HTTP Strict Transport Security (HSTS) Policy Not Enabled -- Risk Level: Medium

Previously triaged as https://github.com/databiosphere/azul-private/issues/13 . The ticket description has been updated to include the indexer URL as a finding.

## Weak Ciphers Enabled -- Risk Level: Medium

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/15 . The ticket description has been updated to include the indexer URL as a finding.

## Misconfigured Access-Control-Allow-Origin Header -- Risk Level: Low

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/17 . The ticket description has been updated to include the indexer URL as a finding.

## Missing X-Frame-Options Header -- Risk Level: Low

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/18 . The ticket description has been updated to include the indexer URL as a finding.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Looks good. Back to Parked."

**Comment by dsotirho-ucsc** [comment]
![Screen Shot 2023-05-09 at 1 27 30 PM](https://github.com/DataBiosphere/azul/assets/46407464/5a68f199-cdb1-41f2-bc32-a4320c9b1743)

The 5/8/2023 Invict scan of https://service.prod.anvil.gi.ucsc.edu/ found 0 critical, 0 high, 2 medium, and 2 low risk findings.

### HTTP Strict Transport Security (HSTS) Errors and Warnings -- Risk Level: Medium

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/13 .

Since the previous ticket was completed, a new issue https://github.com/DataBiosphere/azul-private/issues/81 has been created to address this new finding.

### Weak Ciphers Enabled -- Risk level: Medium

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/15 .

The ticket description has been updated to account for this repeat finding.

### Misconfigured Access-Control-Allow-Origin Header -- Risk level: Low

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/17 .

The ticket description has been updated to account for this repeat finding.

### Missing X-Frame-Options Header -- Risk level: Low

Previously triaged as https://github.com/DataBiosphere/azul-private/issues/18 .

The ticket description has been updated to account for this repeat finding.
