### ISSUE TITLE
Connection to GitHub API refused in canned bundle IT

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4438]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/52327

```
======================================================================
ERROR: test_can_bundle_canned_repository (integration_test.CanBundleScriptIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc0e55c72b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0e55c72b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1621, in test_can_bundle_canned_repository
    self._test_catalog(mock_catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 1560, in _test_catalog
    fqid = self.bundle_fqid(catalog.name)
  File "/builds/ucsc/azul/test/integration_test.py", line 1624, in bundle_fqid
    source, prefix, bundle_fqids = next(self._list_bundles(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 327, in _list_bundles
    source, prefix, new_fqids = self._list_partition_bundles(catalog, source)
  File "/builds/ucsc/azul/test/integration_test.py", line 269, in _list_partition_bundles
    fqids = self.azul_client.list_bundles(catalog, source, partition_prefix)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 227, in list_bundles
    return plugin.list_bundles(source, prefix)
  File "/builds/ucsc/azul/src/azul/plugins/repository/canned/__init__.py", line 119, in list_bundles
    for link in self.staging_area(source.spec).links.values():
  File "/builds/ucsc/azul/src/azul/plugins/repository/canned/__init__.py", line 107, in staging_area
    factory = GitHubStagingAreaFactory.from_url(source_spec.name)
  File "/build/.venv/lib/python3.9/site-packages/humancellatlas/data/metadata/helpers/staging_area.py", line 269, in from_url
    return cls.create(owner=owner, name=name, ref=ref, path=path)
  File "/build/.venv/lib/python3.9/site-packages/humancellatlas/data/metadata/helpers/staging_area.py", line 242, in create
    rate_limit = github_api.get_rate_limit()
  File "/build/.venv/lib/python3.9/site-packages/github/MainClass.py", line 178, in get_rate_limit
    headers, data = self.__requester.requestJsonAndCheck(
  File "/build/.venv/lib/python3.9/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/build/.venv/lib/python3.9/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/build/.venv/lib/python3.9/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/build/.venv/lib/python3.9/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/build/.venv/lib/python3.9/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/build/.venv/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /rate_limit (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0e55c72b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

----------------------------------------------------------------------
Ran 16 tests in 481.425s
```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "I'd like to sit on this for a bit in order to get a better idea of its prevalence."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Similar occurrence of this is in #4757 so overall prevalence is pretty low."

**Comment by achave11-ucsc** [comment]
Related to https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1688062292175629?
Happened again during `anvilbox` IT run. https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/18747.

**Comment by achave11-ucsc** [comment]
`sandbox` IT failure https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/70850#L1549

**Comment by dsotirho-ucsc** [comment]
Freebie of #4757

**Comment by hannes-ucsc** [comment]
To be demoed as part of #4757.
