### ISSUE TITLE
403 from TDR causes managed-access IT to fail

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4460]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53100#L2251

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_repository_sources]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 372, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1053, in _test_managed_access
    public_source_ids = self._test_managed_access_repository_sources(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 1081, in _test_managed_access_repository_sources
    with self._unregistered_service_account_credentials:
  File "/builds/ucsc/azul/test/integration_test.py", line 597, in _unregistered_service_account_credentials
    return self._authorization_context(self._unregistered_tdr_client)
  File "/builds/ucsc/azul/src/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/builds/ucsc/azul/test/integration_test.py", line 230, in _unregistered_tdr_client
    tdr.snapshot_names_by_id()
  File "/builds/ucsc/azul/src/azul/terra.py", line 577, in snapshot_names_by_id
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 557, in _check_response
    raise TerraStatusException(endpoint, response)
azul.terra.TerraStatusException: ('Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc%27), 403, b'{"message":"Google Id 112548165447686760203 not found in sam","errorDetail":[]}')
----------------------------------------------------------------------
```

The following IT jobs failed with the same error:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53067
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53064
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53058

**Comment by achave11** [comment]
Initially I had track this failures in https://github.com/DataBiosphere/azul/issues/4192, but after a closer inspection realized this failure wasn't a timeout.

**Comment by achave11** [comment]
It seems like the response status for `https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc` changed from 401 to a 403 when using credentials from an unregistered service account.
https://github.com/DataBiosphere/azul/blob/develop/src/azul/terra.py#L554

**Comment by danielsotirhos** [comment]
@hannes-ucsc to diagnose and provide design.

**Comment by hannes-ucsc** [comment]
```diff
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 2c209917e2ac0bbe302d126804235dd7aa1efe79)
+++ b/src/azul/terra.py	(date 1663374730177)
@@ -551,7 +551,9 @@
                         ) -> MutableJSON:
         if response.status == 200:
             return json.loads(response.data)
-        elif response.status == 401:
+        # FIXME: Azul sometimes conflates 401 and 403
+        #        https://github.com/DataBiosphere/azul/issues/4463
+        elif response.status in (401, 403):
             raise self._insufficient_access(str(endpoint))
         else:
             raise TerraStatusException(endpoint, response)
```

This fixes IT on `develop` in my personal deployment.

**Comment by hannes-ucsc** [comment]
This blocking everything else.
