### ISSUE TITLE
Transient GitLab failure during post_deploy due to 502 Server Error from Terra

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4475]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/53499
```
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 86, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 81, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy.py", line 54, in verify_sources
    raise e
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 460, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 467, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 559, in _check_response
    raise TerraStatusException(endpoint, response)
azul.terra.TerraStatusException: ('Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2%27), 502, b'\n<html><head>\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n')
make[1]: *** [Makefile:91: post_deploy] Error 1
make[1]: Leaving directory '/builds/ucsc/azul'
make: *** [Makefile:87: auto_deploy] Error 2
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by achave11** [comment]
Closing as duplicate of https://github.com/DataBiosphere/azul/issues/4192.
