### ISSUE TITLE
TDR's getSnapshots endpoint occasionally returns 401

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4552]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/54422

```
2022-10-06 20:36:48,457 INFO    ThreadPoolExecutor-0_0: TDR client is authorized for API access to tdr:datarepo-dev-b2004d1c:snapshot/hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903:/0.
2022-10-06 20:36:48,499 WARNING ThreadPoolExecutor-0_9: Connection pool is full, discarding connection: jade.datarepo-dev.broadinstitute.org
2022-10-06 20:36:48,500 DEBUG   ThreadPoolExecutor-0_9: _request(…) -> 200 b'{"id":"a36cb7cb-0122-40af-8942-1d5ec9372e77","name":"hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903","description":"Create snapshot hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903","createdDate":"2021-09-03T21:45:21.794948Z","co...'
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 86, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 81, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 54, in verify_sources
    raise e
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 460, in check_api_access
    self._lookup_source(source)
  File "/builds/ucsc/azul/src/azul/terra.py", line 473, in _lookup_source
    return self._retrieve_source(SourceRef(id=source_id, spec=source))
  File "/builds/ucsc/azul/src/azul/terra.py", line 454, in _retrieve_source
    return self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 557, in _check_response
    raise self._insufficient_access(str(endpoint))
azul.RequirementError: The service account (SA) 'azul-ucsc-0-sandbox@platform-hca-dev.iam.gserviceaccount.com' is not authorized to access https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots/139ecf31-b6bb-419a-97c8-1245029631bb or that resource does not exist. Make sure that it exists, that the SA is registered with SAM and has been granted read access to the resource.
make[1]: *** [Makefile:93: post_deploy] Error 1
make: *** [Makefile:88: auto_deploy] Error 2
make[1]: Leaving directory '/builds/ucsc/azul'
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by danielsotirhos** [comment]
Job succeeded when retried immediately after the failure.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/54432

**Comment by danielsotirhos** [comment]
Repeat occurrence: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/55801

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "I'd like to sit on this for a while in order to establish how prevalent it is."

**Comment by hannes-ucsc** [comment]
Not prevalent.
