### ISSUE TITLE
The scheduled job sell_unused_slots fails in GitLab `anvildev`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4590]
… due to a regression introduced in PR #4339. It's only affecting `anvilbox` and `anvildev` deployments.
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/2986

```
lrwxr-xr-x  1 abrahamchavez  staff  8 Oct 13 08:57 .active -> anvilbox
$ python3 scripts/sell_unused_slots.py
2022-10-13 08:57:41,963 INFO    MainThread: Found credentials in environment variables.
Traceback (most recent call last):
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 160, in <module>
    main(sys.argv[1:])
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 129, in main
    sell_unused_slots(location, args.dry_run)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 147, in sell_unused_slots
    elif not ReindexDetector(location=location).is_reindex_active():
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 54, in is_reindex_active
    num_invocations) in self._lambda_invocation_counts().items():
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 82, in _lambda_invocation_counts
    lambda_.name: lambda_ for lambda_ in self._list_contribution_lambda_functions()
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/scripts/sell_unused_slots.py", line 74, in _list_contribution_lambda_functions
    for lambda_ in Lambdas().list_lambdas()
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 104, in list_lambdas
    return [
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 105, in <listcomp>
    Lambda.from_response(function)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 84, in from_response
    return cls(name=name,
  File "<attrs generated init azul.lambdas.Lambda>", line 7, in __init__
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 90, in __attrs_post_init__
    assert not self.is_contribution_lambda, self
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 37, in is_contribution_lambda
    for lambda_name in self._contribution_lambda_names():
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 67, in _contribution_lambda_names
    return frozenset((
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 70, in <genexpr>
    if has_notification_queue(handler)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/lambdas.py", line 64, in has_notification_queue
    resource_name, _ = config.unqualified_resource_name(queue)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/__init__.py", line 470, in unqualified_resource_name
    require(self._is_valid_qualifier(deployment_stage),
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/__init__.py", line 1553, in require
    reject(not condition, *args, exception=exception)
  File "/Users/abrahamchavez/AbrahamC/azul.release/azul.stable/src/azul/__init__.py", line 1572, in reject
    raise exception(*args)
azul.RequirementError: ('Invalid deployment name', 'anvilbox.fifo', 'azul-tallies-anvilbox.fifo')

```

**Comment by theathorn** [comment]
@danielsotirhos Spike to diagnose.

**Comment by danielsotirhos** [comment]
The property [Lambda.is_contribution_lambda](https://github.com/DataBiosphere/azul/blob/c3d578f3a0d2d6b149055839382d8c21fdde25b0/src/azul/lambdas.py#L36) indirectly calls `config.unqualified_resource_name()` to parse both the notification & tally queue names, without passing a `suffix` argument.

Previously this bug was benign, however commit 56e4aae added validation of the parsed deployment stage name in `Config.unqualified_resource_name()`, and without the `suffix` argument given a queue like `azul-tallies-anvilbox.fifo` produces a stage name of `anvilbox.fifo` which trips the new validation code.

This issue is not limited to the `anvilbox` deployment.

```
>>> from azul.lambdas import Lambdas
>>> Lambdas().list_lambdas()
Traceback (most recent call last):
...
  File "/Users/daniel/repo/azul3/src/azul/__init__.py", line 470, in unqualified_resource_name
    require(self._is_valid_qualifier(deployment_stage),
  File "/Users/daniel/repo/azul3/src/azul/__init__.py", line 1553, in require
    reject(not condition, *args, exception=exception)
  File "/Users/daniel/repo/azul3/src/azul/__init__.py", line 1572, in reject
    raise exception(*args)
azul.RequirementError: ('Invalid deployment name', 'daniel.fifo', 'azul-tallies-daniel.fifo')
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce. Show that the scheduled pipelines succeed on `anvildev` after this change landed on `develop`.
