### ISSUE TITLE
RuntimeError in MP upload tests

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4678]
Occurred during test of `prod` promotion PR https://github.com/DataBiosphere/azul/pull/4676

https://github.com/DataBiosphere/azul/actions/runs/3381765788/jobs/5616011765

```
======================================================================
ERROR: test_multipart_upload_error_inside_context_with_nothing_pushed (service.test_storage_service.StorageServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/core/models.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/core/models.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/home/runner/work/azul/azul/test/service/test_storage_service.py", line 174, in test_multipart_upload_error_inside_context_with_nothing_pushed
    for part in sample_content_parts:
  File "/home/runner/work/azul/azul/src/azul/service/storage_service.py", line 273, in __exit__
    self.__complete()
  File "/home/runner/work/azul/azul/src/azul/service/storage_service.py", line 283, in __complete
    self.__abort()
  File "/home/runner/work/azul/azul/src/azul/service/storage_service.py", line 300, in __abort
    self.mp_upload.abort()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 307, in _should_retry
    return self._checker(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/core/botocore_stubber.py", line 60, in __call__
    status, headers, body = response_callback(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/responses.py", line 251, in ambiguous_response
    return self.key_response(request, full_url, headers)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/responses.py", line 1123, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/responses.py", line 1220, in _key_response
    return self._key_response_delete(headers, bucket_name, query, key_name)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/responses.py", line 1957, in _key_response_delete
    self.backend.abort_multipart_upload(bucket_name, upload_id)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/models.py", line 1974, in abort_multipart_upload
    del bucket.multiparts[multipart_id]
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/models.py", line 897, in __delitem__
    self[key].dispose()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/moto/s3/models.py", line 435, in dispose
    for part in self.parts.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by achave11** [comment]
Happened again during `anvilbox` test job. https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/4533

**Comment by nadove-ucsc** [comment]
Happened again: https://github.com/DataBiosphere/azul/actions/runs/3521170020/jobs/5902758836

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/actions/runs/3627260308/jobs/6116985903

**Comment by theathorn** [comment]
Spike to investigate cause, be sure to limit spike to 1 hour.

**Comment by nadove-ucsc** [comment]
`azul.service.storage_service.MultipartUploadHandler` uses multithreading...

https://github.com/DataBiosphere/azul/blob/e5c9da2a52727d254cba585b81ca2d8821854447/src/azul/service/storage_service.py#L261

...which `moto` categorically does not support.

https://docs.getmoto.org/en/latest/docs/faq.html#is-moto-concurrency-safe

> **Is Moto concurrency safe?**
> 
> No. Moto is not designed for multithreaded access/multiprocessing.

So, we shouldn't be using multithreading in a test with moto mocks in place.

**Comment by nadove-ucsc** [comment]
The only invocation of `MultipartUploadHandler` outside of the unit tests happens here: 

https://github.com/DataBiosphere/azul/blob/e5c9da2a52727d254cba585b81ca2d8821854447/src/azul/service/manifest_service.py#L995

If we truly want/need multithreading here, we probably need to patch `azul.service.storage_service.MULTIPART_UPLOAD_MAX_WORKERS` in the test so that only one thread is used. This will probably undermine the purpose of some the tests, or make certain tests redundant with each other,

**Comment by hannes-ucsc** [comment]
I will review spike results.

**Comment by achave11-ucsc** [comment]
This happened again for `develop` after merging PR [Update to AnVIL schema v4 (#4617) #4741](https://github.com/DataBiosphere/azul/pull/4741). Interestingly, it occurred in `dev` and `anvildev` GitLab while both instances were running the `develop` pipeline.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/58315 and
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/6389

**Comment by hannes-ucsc** [comment]
The only non-test usage of `MultipartUploadHandler` is in `StreamingManifestGenerator` which is also unused. We can just remove all of that stuff, the tests and the code under test.
