### ISSUE TITLE
There is non-standard file format in Commons Dev instance

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#476]
There is a file format `minimal-file-eba57c70-15fa-4fba-8a54-bd1a7bff11be`. Having it selected leads to an error exporting to FireCloud.

This seems to be a bug and related to a (new) File Format that starts with `minimal-file-...`.

!image-2018-10-19-14-28-54-106.png|thumbnail! 

Could [~lblauvel] and [~mbaumann] please take a look at this?

The stack trace from the `dcc_dashboard-service_1` container, following either `curl` or clicking the `Export to FireCloud` button in the UI, is:

{quote}2018-10-19 21:10:20,474 - dashboardService.elastic_request_builder.ElasticTransformDump - INFO - Creating ManifestResponse object
2018-10-19 21:10:20,479 - dashboardService.api_response.ManifestResponse - INFO - Creating response from array
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webservice.py", line 47, in check_auth
    return f(*args, **kwargs)
  File "./webservice.py", line 373, in get_manifest
    response_bag = bdbag_response(response)
  File "./webservice.py", line 406, in bdbag_response
    zipped_bag = bag.create_bag()  # path to compressed bag
  File "./bagitutils.py", line 126, in create_bag
    self.write_csv_files(data_path)
  File "./bagitutils.py", line 156, in write_csv_files
    participants, samples = self.convert_to_participant_and_sample()
  File "./bagitutils.py", line 185, in convert_to_participant_and_sample
    return list(participants), self.samples(native_protocols, file_types)
  File "./bagitutils.py", line 250, in samples
    suffix = self.get_suffix(row[BoardwalkColumns.FILE_TYPE])
  File "./bagitutils.py", line 351, in get_suffix
    format(repr(s)))
ValueError: 'minimal-file-eba57c70-15fa-4fba-8a54-bd1a7bff11be': unknown file type in manifest
[pid: 27|app: 0|req: 304/543] 172.21.0.5 () {44 vars in 591 bytes} [Fri Oct 19 21:10:20 2018] GET //repository/files/export?&format=bdbag => generated 0 bytes in 165 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 0){quote}

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-317)
┆Project Name: azul
┆Issue Number: AZUL-317
┆Epic: Load TOPMed data
┆Attachments: <a href="https:&#x2F;&#x2F;ucsc-cgl.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10088&#x2F;image-2018-10-19-14-28-54-106.png">image-2018-10-19-14-28-54-106.png</a>

**Comment by cricketsloan** [comment]
➤ Lon commented:

No idea what this is.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

May be fixed by fixing TLP-763

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This errant file (there are more now) are the result of misdirecting the target DSS of the loader tests to the “dev” deployment instead of the “test” deployment. These files should be cleared out.
