### ISSUE TITLE
Cannot index Ingest spreadsheets due to missing `Submitter` item

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4825]
Some notifications in `dcp23` failed to generate a valid contribution when populating the file entity. This was due to a [missing Submitter](https://github.com/DataBiosphere/azul/blob/develop/src/azul/plugins/metadata/hca/indexer/transform.py#L309) being referenced, namely `DCP/2 Ingest`. All failed with the following KeyError:
```
[WARNING] 2022-12-13T09:47:54.158Z bba86f96-3f2a-580f-9576-3384735d4b2f azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '87356846-2e84-495c-a6a8-915b6d2cb671', 'spec': 'tdr:datarepo-c008323e:snapshot/hca_prod_e0c74c7a20a445059cf138dcdd23011b__20220119_dcp2_20221209_dcp23:/0'}, 'transaction_id': '543683f1-4756-4200-87b7-1f60dc486a8e', 'match': {'bundle_uuid': 'e0889100-ad52-5ac4-b928-a47b3e82952f', 'bundle_version': '2022-11-29T12:07:29.566000Z'}}, 'catalog': 'dcp23'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 175, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 209, in transform
results = service.transform(catalog, bundle, partition, delete=delete)
File "/var/task/azul/indexer/index_service.py", line 283, in transform
contributions.extend(transformer.transform(partition))
File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1386, in _transform
files=[self._file(file, related_files=related_files)],
File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 936, in _file
**self._file_base(file),
File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 907, in _file_base
'file_source': Submitter.title_for_file(file),
File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 426, in title_for_file
self = cls.for_file(file)
File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 421, in for_file
self = cls.by_title[file.file_source]
KeyError: 'DCP/2 Ingest'
```
The following snapshots's bundles failed to index:
* hca_prod_258c5e15d1254f2d8b4ce3122548ec9b__20221208_dcp2_20221209_dcp23
    * "bundle_uuid": "d1de0b5d-9fc7-5ebc-99a9-80c72845c6c4", "bundle_version": "2022-12-02T17:11:31.359000Z"

* hca_prod_0751843070314bdfa3ce1bf0917a1923__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "bd1d8b47-bb81-5024-a165-e5616730176e", "bundle_version": "2022-11-23T23:21:43.871000Z"

* hca_prod_cdc2d2706c99414288839bd95c041d05__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "cd5e4c74-9c19-5c2f-a043-1da5f980c8da", "bundle_version": "2022-12-06T15:46:51.443000Z"

* hca_prod_1ebe8c34454e4c28bd713a3e8b127be4__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "2cfe5060-1156-5e5d-b840-326d9dc4e393", "bundle_version": "2022-11-22T22:29:12.511000Z"

* hca_prod_ea9eec5a4fc24c5894d02fcb598732bc__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "07aa8490-e688-5623-abaf-c7cb4729cce1", "bundle_version": "2022-11-24T03:39:24.408000Z"

* hca_prod_b7259878436c4274bfffca76f4cb7892__20220118_dcp2_20221208_dcp23
    * bundle_uuid": "2b3b3411-2e7c-588c-8319-53979aaa5da0",  "bundle_version": "2022-09-02T15:55:16.448000Z"

* hca_prod_48b198ef3d594e57900fdf54c2435669__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "347ec6dd-4aa2-5a13-8af4-c9739830f3ac", "bundle_version": "2022-11-25T22:00:17.561000Z"

* hca_prod_79351583b21244bab473731bdcddb407__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "8de2df78-0192-5272-b48d-e2ca32889235", "bundle_version": "2022-11-21T21:50:07.970000Z"

* hca_prod_fc381e70df1b407d813152ab523270bd__20221208_dcp2_20221208_dcp23
    * "bundle_uuid": "7ee73ab1-e2d8-5ce9-ba29-75d9e05c9d90", "bundle_version": "2022-11-16T18:27:46.676000Z"

* hca_prod_e0c74c7a20a445059cf138dcdd23011b__20220119_dcp2_20221209_dcp23
    * "bundle_uuid": "e0889100-ad52-5ac4-b928-a47b3e82952f", "bundle_version": "2022-11-29T12:07:29.566000Z"

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "@danielsotirhos  to create hotfix against `prod`. Include operator instructions to re-feed failed notifications."
