### ISSUE TITLE
IT in GitLab anvilbox failed due to elasticsearch.exceptions.RequestError

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4882]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/8476
```
ERROR: test_indexing (integration_test.IndexingIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 191, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 431, in test_indexing
    self._reset_indexer()
  File "/builds/ucsc/azul/test/integration_test.py", line 485, in _reset_indexer
    self.azul_client.reset_indexer(catalogs=config.integration_test_catalogs,
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 461, in reset_indexer
    self.delete_all_indices(catalog)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 375, in delete_all_indices
    self.index_service.delete_indices(catalog)
  File "/builds/ucsc/azul/src/azul/indexer/index_service.py", line 379, in delete_indices
    es_client.indices.delete(index=index_name)
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/client/indices.py", line 294, in delete
    return self.transport.perform_request(
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/build/.venv/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'snapshot_in_progress_exception', 'Cannot delete indices that are being snapshotted: [[azul_v2_anvilbox_anvil-it_activities/…id_ommited…]]. Try again after snapshot finishes or cancel the currently running snapshot.')
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Tickets have been opened up in each AWS account to disable the automatic, hourly snapshotting of the ElasticSearch instances.

**Comment by achave11-ucsc** [comment]
Reply to AWS support team.

**Comment by achave11-ucsc** [comment]
Request to give the customer the option to disable snapshotting it. It would be good to give the customer this ability since not all customers use it as their primary database.

**Comment by achave11-ucsc** [comment]
The ElasticSearch domains in anvil and dev AWS account have been disabled. However, there was a message with pending progress at 0%, which I requested them to look at, in addition to the feature request to disable snapshotting on the customer side. A response from them is pending.

**Comment by achave11-ucsc** [comment]
The `azul-index-dev` and `azul-index-sandbox` domains in the AWS `dev` account have the automatic snapshotting feature disabled.
Other AWS accounts still have pending actions in order to mark the support ticket as resolved.

**Comment by achave11-ucsc** [comment]
The following domains have snapshotting disabled:
* `azul-index-sandbox`, no action pending.
* `azul-index-dev`, no action pending.
* `azul-index-anvilbox`, B/G deployment stuck at 0%, pending AWS action.
* `azul-index-anvildev`, B/G deployment stuck at 0%, pending AWS action.

I was unable to verify the status of the `azul-index-prod` ElasticSearch instance due to insufficient viewer role permissions in the AWS console.

**Comment by dsotirho-ucsc** [comment]
@danielsotirhos will take over this ticket as Operator. Do not close the `dev` support request until the Elasticsearch update (#4915) has been applied.

**Comment by dsotirho-ucsc** [comment]
Correction: do not close any support requests until the Elasticsearch update has been applied.

**Comment by dsotirho-ucsc** [comment]
AWS has completed the fix of our ES domains that were stuck at 0%.
All domains now have an `Active` status and are ready to have the `R20220928-P2` software service update applied by #4915.

- azul-index-dev
- azul-index-sandbox
- azul-index-anvilbox
- azul-index-anvildev
- azul-index-prod

**Comment by dsotirho-ucsc** [comment]
<img width="1276" alt="Screen Shot 2023-01-24 at 4 11 37 PM" src="https://user-images.githubusercontent.com/46407464/214450650-b86bcff6-5bee-40f8-b93b-dc0ab0a1ffd3.png">
<img width="1276" alt="Screen Shot 2023-01-24 at 4 11 49 PM" src="https://user-images.githubusercontent.com/46407464/214450612-ea1b7982-e962-4598-ac16-d06bebdae2d8.png">
<img width="1276" alt="Screen Shot 2023-01-24 at 4 12 37 PM" src="https://user-images.githubusercontent.com/46407464/214450620-d5db0712-bd55-4600-b6a9-ef42df5762a9.png">
<img width="1276" alt="Screen Shot 2023-01-24 at 4 12 55 PM" src="https://user-images.githubusercontent.com/46407464/214450637-88577d45-ab79-4581-a4b7-62eb00af11b1.png">
<img width="1276" alt="Screen Shot 2023-01-24 at 4 13 19 PM" src="https://user-images.githubusercontent.com/46407464/214450657-fb725cee-b098-4d60-8cf9-a1f5b2e9fe73.png">

**Comment by dsotirho-ucsc** [comment]
Ran Kibana to verify when the last automatic snapshot was taken (`GET _cat/snapshots/cs-automated`) on all ES domains:

azul-index-dev: Last snapshot Jan 11th
```
2023-01-10t00-54-29.7d8e1067-416f-4f04-95ed-5ee1ff0b0473 SUCCESS 1673312069 00:54:29 1673312075 00:54:35 6s 62 167 0 167
2023-01-11t00-54-29.3d99bdf8-ef31-4b85-bd39-ad9a5cfb9a15 SUCCESS 1673398469 00:54:29 1673398475 00:54:35 6s 62 167 0 167
```

azul-index-sandbox: Last snapshot Jan 11th
```
2023-01-10t00-13-09.2967d6be-21de-4937-b1ee-29bd12c59672 SUCCESS 1673309589 00:13:09 1673309616 00:13:36 26.8s 431 631 0 631
2023-01-11t00-13-10.7b9a564f-6b83-4c12-96d0-a055db9355c4 SUCCESS 1673395989 00:13:09 1673396015 00:13:35 25.8s 431 631 0 631
```

azul-index-anvilbox: Last snapshot Jan 11th
```
2023-01-09t22-26-14.29958329-0e90-42ad-9a57-effcbcca5d4e SUCCESS 1673303174 22:26:14 1673303180 22:26:20 5.6s 61 106 0 106
2023-01-09t23-26-07.94bb5afb-0177-4cb9-b5ec-3be5c424be2d SUCCESS 1673306767 23:26:07 1673306773 23:26:13 5.4s 61 106 0 106
2023-01-10t00-26-14.424c98af-9d16-4f6b-bdd3-341452269d87 SUCCESS 1673310374 00:26:14 1673310384 00:26:24 9.6s 61 106 0 106
2023-01-10t01-26-19.ffa1d090-6c1c-4aa7-bd30-f65af0635373 SUCCESS 1673313979 01:26:19 1673313985 01:26:25 6.2s 61 106 0 106
2023-01-10t02-26-07.39664470-e1ce-43f0-91a9-875b9e4fdb1d SUCCESS 1673317567 02:26:07 1673317575 02:26:15 7.6s 61 106 0 106
2023-01-10t03-26-07.df577375-3f9c-4d33-97b3-52a0758c6385 SUCCESS 1673321167 03:26:07 1673321173 03:26:13 5.6s 61 106 0 106
2023-01-10t04-26-11.063df044-a0eb-4a4f-954b-b63360992352 SUCCESS 1673324771 04:26:11 1673324776 04:26:16 5.4s 61 106 0 106
2023-01-10t05-26-09.5b479936-6cc6-4f20-a549-1f41eb9d6936 SUCCESS 1673328369 05:26:09 1673328375 05:26:15 5.8s 61 106 0 106
2023-01-10t06-26-10.b4c9e85a-0eb6-44da-a09f-99502291a4d8 SUCCESS 1673331970 06:26:10 1673331976 06:26:16 5.8s 61 106 0 106
2023-01-10t07-26-12.1262833f-7b6f-4ebe-b7a1-2c5c80b6f863 SUCCESS 1673335572 07:26:12 1673335577 07:26:17 5.4s 61 106 0 106
2023-01-10t08-26-11.8c694816-6c3b-4714-8575-6b13eb743e72 SUCCESS 1673339171 08:26:11 1673339179 08:26:19 7.4s 61 106 0 106
2023-01-10t09-26-13.fa6a8564-0cdf-49fb-ab8d-9da731ddb130 SUCCESS 1673342773 09:26:13 1673342779 09:26:19 5.6s 61 106 0 106
2023-01-10t10-26-11.37d33eff-dd93-4d76-a203-7bee032ca7a0 SUCCESS 1673346371 10:26:11 1673346376 10:26:16 5.6s 61 106 0 106
2023-01-10t11-26-10.ae9b9bb6-e0aa-4f71-abb3-c06e3bdc5a36 SUCCESS 1673349970 11:26:10 1673349976 11:26:16 5.6s 61 106 0 106
2023-01-10t12-26-05.3ee6162f-27db-4942-bb28-e102830ca280 SUCCESS 1673353565 12:26:05 1673353571 12:26:11 6.2s 61 106 0 106
2023-01-10t13-26-06.48497fbc-a7ff-49f8-b3c1-796847f9498f SUCCESS 1673357166 13:26:06 1673357173 13:26:13 6.6s 61 106 0 106
2023-01-10t14-26-10.a8ed6252-1c58-44f5-9669-58fb4012934f SUCCESS 1673360769 14:26:09 1673360776 14:26:16 6.4s 61 106 0 106
2023-01-10t15-26-07.2443c1c6-e785-4036-9fb6-c5aae4e9726c SUCCESS 1673364367 15:26:07 1673364373 15:26:13 6.8s 61 106 0 106
2023-01-10t16-26-23.8457d464-f779-4130-b57b-fac0f9b8bec6 SUCCESS 1673367983 16:26:23 1673367989 16:26:29 5.8s 61 106 0 106
2023-01-10t17-26-19.e5e59ca9-8740-40d7-a9ce-eadc8d15c56d SUCCESS 1673371579 17:26:19 1673371585 17:26:25 6.2s 61 106 0 106
2023-01-10t18-26-08.de2010f2-f2f5-4aea-a05c-978ab32ef08a SUCCESS 1673375168 18:26:08 1673375174 18:26:14 6.2s 61 106 0 106
2023-01-10t19-26-15.1e0a10d3-c933-4f9d-a315-138be308a4a3 SUCCESS 1673378775 19:26:15 1673378784 19:26:24 8.6s 61 106 0 106
2023-01-10t20-26-11.a0ca911a-b61c-448d-9701-ff7ba12b4564 SUCCESS 1673382371 20:26:11 1673382377 20:26:17   6s 61 106 0 106
2023-01-10t21-26-08.17b133b1-ba39-4892-a916-18aaf2e5183e SUCCESS 1673385968 21:26:08 1673385975 21:26:15 6.4s 61 106 0 106
2023-01-10t22-26-05.f3c7ce8e-412e-44fe-b4d7-03177b393178 SUCCESS 1673389565 22:26:05 1673389571 22:26:11   6s 61 106 0 106
2023-01-10t23-26-16.d3a0a082-cf40-4af2-aa9c-14fd8129b383 SUCCESS 1673393176 23:26:16 1673393182 23:26:22 5.8s 62 107 0 107
2023-01-11t00-26-27.cbf16948-24e2-4ff2-8b2a-2e78062e34b8 SUCCESS 1673396787 00:26:27 1673396794 00:26:34 7.6s 62 107 0 107
2023-01-11t01-26-15.2d4c0ca2-232f-4a1b-9bb0-79f674c522aa SUCCESS 1673400375 01:26:15 1673400382 01:26:22 6.6s 62 107 0 107
2023-01-11t02-26-17.08d9ac3f-8b5a-4711-8542-92a3b67bef5f SUCCESS 1673403977 02:26:17 1673403983 02:26:23 5.8s 62 107 0 107
2023-01-11t03-26-11.b23ad32d-eec9-447f-8d42-367166eed074 SUCCESS 1673407571 03:26:11 1673407577 03:26:17   6s 62 107 0 107
2023-01-11t04-26-06.6aaf86f4-8afc-4d71-b186-976b6655379c SUCCESS 1673411166 04:26:06 1673411172 04:26:12   6s 62 107 0 107
2023-01-11t05-26-13.24d03626-2c05-4bf1-9ea6-83b25c4639ef SUCCESS 1673414773 05:26:13 1673414779 05:26:19 6.4s 62 107 0 107
2023-01-11t06-26-15.38e246cf-36e9-484c-af08-28b5d795a09c SUCCESS 1673418375 06:26:15 1673418381 06:26:21 6.2s 62 107 0 107
2023-01-11t07-26-14.6e7de060-78fd-46c9-b3f8-3469fec5e6bf SUCCESS 1673421974 07:26:14 1673421979 07:26:19 5.6s 62 107 0 107
2023-01-11t08-26-10.ad96faa8-334c-4d57-8d2a-5e309e221ec7 SUCCESS 1673425570 08:26:10 1673425576 08:26:16   6s 62 107 0 107
2023-01-11t09-26-11.559d26a0-8f80-4e10-90d6-d3501100cb50 SUCCESS 1673429171 09:26:11 1673429177 09:26:17 5.4s 62 107 0 107
2023-01-11t10-26-14.9b8f3ca8-7cbc-4597-9de2-a19c90bec1c9 SUCCESS 1673432774 10:26:14 1673432780 10:26:20 5.8s 62 107 0 107
2023-01-11t11-26-10.5613cd8f-d50a-4199-9dac-6d063d0cd21d SUCCESS 1673436370 11:26:10 1673436376 11:26:16 5.8s 62 107 0 107
2023-01-11t12-26-11.10ecf67a-2291-4f96-a2ca-9eec7b72dbcf SUCCESS 1673439971 12:26:11 1673439977 12:26:17   6s 62 107 0 107
2023-01-11t13-26-16.c2bd1d16-eba4-411d-8a2b-4e75d331cf98 SUCCESS 1673443575 13:26:15 1673443582 13:26:22 6.4s 62 107 0 107
2023-01-11t14-26-11.ff747a00-5779-4efe-91b7-2b5ce77a39d1 SUCCESS 1673447171 14:26:11 1673447176 14:26:16 5.4s 62 107 0 107
2023-01-11t15-26-22.f0f80d8d-88b4-456d-96a4-e1294d15dd7a SUCCESS 1673450782 15:26:22 1673450788 15:26:28   6s 62 107 0 107
2023-01-11t16-26-13.4f43bcb1-bc1e-43b2-bc2a-01f98f362d56 SUCCESS 1673454373 16:26:13 1673454379 16:26:19 6.4s 62 107 0 107
```

azul-index-anvildev: Last snapshot Jan 11th
```
2023-01-09t22-53-23.51512060-44e5-45c8-b74b-f0721ece6d0f SUCCESS 1673304803 22:53:23 1673304806 22:53:26 2.8s 22 57 0 57
2023-01-09t23-53-23.d2ce390b-2216-4515-862a-a3680a1a724c SUCCESS 1673308403 23:53:23 1673308405 23:53:25 2.2s 22 57 0 57
2023-01-10t00-53-38.7435cfe8-47e2-40be-b237-b15dc8eeb54f SUCCESS 1673312018 00:53:38 1673312023 00:53:43 5.4s 22 57 0 57
2023-01-10t01-53-24.b5907046-631a-4ba7-9bd9-08da03853856 SUCCESS 1673315604 01:53:24 1673315607 01:53:27   3s 22 57 0 57
2023-01-10t02-53-23.b33e8348-c948-4f0d-bd79-0d8482cb9cdd SUCCESS 1673319203 02:53:23 1673319206 02:53:26 3.2s 22 57 0 57
2023-01-10t03-53-25.6c567d72-84fa-4b85-95ff-6f4b0cfae74f SUCCESS 1673322804 03:53:24 1673322807 03:53:27 2.8s 22 57 0 57
2023-01-10t04-53-23.5449e061-8764-4867-9061-8cbe14ffed05 SUCCESS 1673326403 04:53:23 1673326405 04:53:25 2.4s 22 57 0 57
2023-01-10t05-53-22.f06f4664-98c5-41b4-b86f-db0789136b96 SUCCESS 1673330002 05:53:22 1673330005 05:53:25   3s 22 57 0 57
2023-01-10t06-53-17.e3ea760f-172b-4ee8-bb4f-f9575856803a SUCCESS 1673333597 06:53:17 1673333601 06:53:21 3.2s 22 57 0 57
2023-01-10t07-53-22.08d30869-f753-4667-826a-a99b87323775 SUCCESS 1673337202 07:53:22 1673337206 07:53:26 3.2s 22 57 0 57
2023-01-10t08-53-24.e8e97abd-a310-46e0-afed-6c2bf543db59 SUCCESS 1673340804 08:53:24 1673340806 08:53:26 2.4s 22 57 0 57
2023-01-10t09-53-15.faa758de-ef5c-4565-b5ef-9f92347b1f56 SUCCESS 1673344395 09:53:15 1673344398 09:53:18   3s 22 57 0 57
2023-01-10t10-53-20.a6ef00f1-6cab-4bd0-8d25-a75ed57f7c0a SUCCESS 1673348000 10:53:20 1673348003 10:53:23   3s 22 57 0 57
2023-01-10t11-53-17.fadd8c53-97eb-4650-a9fa-03ff18a38fdb SUCCESS 1673351597 11:53:17 1673351600 11:53:20 3.2s 22 57 0 57
2023-01-10t12-53-24.36891ccb-598d-48f3-9ba9-94e6a815222d SUCCESS 1673355204 12:53:24 1673355207 12:53:27   3s 22 57 0 57
2023-01-10t13-53-20.ad5631b8-06a8-4540-b349-91340970f64d SUCCESS 1673358800 13:53:20 1673358803 13:53:23 3.2s 22 57 0 57
2023-01-10t14-53-23.ea790ec6-ea40-452d-acef-40b118af6b57 SUCCESS 1673362403 14:53:23 1673362406 14:53:26   3s 22 57 0 57
2023-01-10t15-53-28.2dd5124d-e2fe-4c0f-af68-554c65b4a216 SUCCESS 1673366008 15:53:28 1673366012 15:53:32 3.6s 22 57 0 57
2023-01-10t16-53-25.1b2013ae-0885-4775-a15f-98ec5c096562 SUCCESS 1673369605 16:53:25 1673369608 16:53:28   3s 22 57 0 57
2023-01-10t17-53-29.d48ce0ae-0689-4351-8ec4-fcf9a6624c6c SUCCESS 1673373209 17:53:29 1673373212 17:53:32 3.6s 22 57 0 57
2023-01-10t18-53-25.c98d104e-262b-4ef5-8d98-3f748dcd6a07 SUCCESS 1673376805 18:53:25 1673376808 18:53:28 2.4s 22 57 0 57
2023-01-10t19-53-26.ae9967fe-8b90-412f-bcbd-34c8a29033f8 SUCCESS 1673380406 19:53:26 1673380409 19:53:29   3s 22 57 0 57
2023-01-10t20-53-29.5e36c3de-fec4-43a5-be49-3100b97725f0 SUCCESS 1673384009 20:53:29 1673384013 20:53:33 4.4s 22 57 0 57
2023-01-10t21-53-19.67f9836d-6ca0-41a6-b274-fa3d3ce1bd8b SUCCESS 1673387599 21:53:19 1673387602 21:53:22 3.2s 22 57 0 57
2023-01-10t22-53-24.0a77830a-0d9b-42e7-a3de-2e557fad6023 SUCCESS 1673391203 22:53:23 1673391208 22:53:28 4.8s 22 57 0 57
2023-01-10t23-53-22.02e094c1-9c38-48ab-80af-9220671352eb SUCCESS 1673394802 23:53:22 1673394806 23:53:26 3.8s 22 57 0 57
2023-01-11t00-53-38.e3ddef0e-eab8-40b2-bd2c-4a060f86649d SUCCESS 1673398418 00:53:38 1673398421 00:53:41 3.2s 22 57 0 57
2023-01-11t01-53-27.30f5c135-32dd-44f4-9329-5a06ff67c0e3 SUCCESS 1673402007 01:53:27 1673402010 01:53:30 3.2s 22 57 0 57
2023-01-11t02-53-25.1e50ec99-8c5b-4ebf-8bd3-ed978870b6c3 SUCCESS 1673405605 02:53:25 1673405608 02:53:28 3.4s 22 57 0 57
2023-01-11t03-53-22.041fe63f-c6eb-46ad-809f-74b94a6df0d5 SUCCESS 1673409202 03:53:22 1673409205 03:53:25 2.8s 22 57 0 57
2023-01-11t04-53-24.8159bcce-9a07-4e9e-8f83-1377639a493e SUCCESS 1673412804 04:53:24 1673412807 04:53:27 2.8s 22 57 0 57
2023-01-11t05-53-22.d98912c0-f5db-40d1-af54-f3375c66b031 SUCCESS 1673416402 05:53:22 1673416405 05:53:25   3s 22 57 0 57
2023-01-11t06-53-24.fedf157d-0ef6-4518-b285-d4c87bcb8b65 SUCCESS 1673420004 06:53:24 1673420007 06:53:27   3s 22 57 0 57
2023-01-11t07-53-23.16edfa89-7235-45d5-8468-6a62c9f7d037 SUCCESS 1673423603 07:53:23 1673423606 07:53:26   3s 22 57 0 57
2023-01-11t08-53-23.7062bc1a-f79d-47f6-907e-9542af05967b SUCCESS 1673427203 08:53:23 1673427206 08:53:26 3.2s 22 57 0 57
2023-01-11t09-53-29.d11cf862-e488-4563-b827-69f4d900d86a SUCCESS 1673430809 09:53:29 1673430812 09:53:32 2.4s 22 57 0 57
2023-01-11t10-53-17.01d8fdeb-494b-416c-9f48-c14dd347d52d SUCCESS 1673434397 10:53:17 1673434401 10:53:21 3.4s 22 57 0 57
2023-01-11t11-53-23.55854eb1-05ad-42dd-b27b-83d38718ebe2 SUCCESS 1673438003 11:53:23 1673438006 11:53:26 2.8s 22 57 0 57
2023-01-11t12-53-25.142ed9f2-4ac2-44e8-a5cd-01219503ae94 SUCCESS 1673441605 12:53:25 1673441608 12:53:28   3s 22 57 0 57
2023-01-11t13-53-18.9083b52b-f0b8-4cfc-95bd-8bb0e1f5a18b SUCCESS 1673445198 13:53:18 1673445201 13:53:21 3.2s 22 57 0 57
2023-01-11t14-53-21.c17b1404-1fa7-4d6b-b075-ead3f6154898 SUCCESS 1673448801 14:53:21 1673448805 14:53:25   4s 22 57 0 57
2023-01-11t15-53-23.5094197b-8f02-4222-aa59-7a0773ea1c42 SUCCESS 1673452403 15:53:23 1673452406 15:53:26 2.6s 22 57 0 57
2023-01-11t16-53-24.4ed1c336-a861-4281-8404-f7ced2eb648c SUCCESS 1673456004 16:53:24 1673456007 16:53:27 2.8s 22 57 0 57
```

azul-index-prod: Last snapshot Jan 11th
```
2023-01-10t00-52-35.215591db-916c-41de-90fc-94afdba889a5 SUCCESS 1673311955 00:52:35 1673311968 00:52:48 13.4s 81 621 0 621
2023-01-11t00-52-35.c0a7906d-1d14-4c4e-a194-9b86bb96d75c SUCCESS 1673398355 00:52:35 1673398369 00:52:49 13.4s 82 622 0 622
```

**Comment by dsotirho-ucsc** [comment]
@danielsotirhos to leave feedback about slow `prod` response and close all AWS support tickets.
