### ISSUE TITLE
Many caches persist between test cases

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4956]
~An example is~ https://github.com/DataBiosphere/azul/blob/350fe6400a7ad82f05375ae004134349a16dcb66/src/azul/service/repository_controller.py#L65, ~which caused a lot of pain on https://github.com/DataBiosphere/azul/pull/4948~

Edit: wrong link, see https://github.com/DataBiosphere/azul/issues/4956#issuecomment-1426647898

The workaround is/was to use a different catalog name for tests that need a different cached plugin.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to describe solution.

**Comment by hannes-ucsc** [comment]
Class-level caches are difficult to deal with because there is no paper trail to them. Once we cache the RepositoryController instance (#4957), we can hopefully convert its class-level cache of metadata plugins, to a regular instance-level cache. Clearing that cache is then done by discarding the instance.

Then devise a mechanism to unload the app module. It's probably not possible to unload it for tear-down (`importlib` has no `unload(module)` only `reload`), but instead detect during set-up that the module is already loaded and reload it.

One way to prove the effectiveness of this approach is to change the name of the test catalog for the AnVIL from `test-anvil` back to `test` so that it collides with that of the the HCA-based tests. If the caches are successfully evicted between tests, the collision shouldn't matter, as it currently does.

Spike to search for other class-level caches, so that we can convert them, too.

**Comment by hannes-ucsc** [comment]
It's actually 

https://github.com/DataBiosphere/azul/blob/07bcc1ae6ecc0e194084c7d304a9cf872b870a97/src/azul/service/source_service.py#L53

that caused the pain. Same type of class-level cache and same cache key (the catalog name), but different class. Repro


```diff
Index: test/service/test_response_anvil.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/service/test_response_anvil.py b/test/service/test_response_anvil.py
--- a/test/service/test_response_anvil.py	(revision 1d80e3f8fbf7ad5a499eb9a118fcb33ec58ed0aa)
+++ b/test/service/test_response_anvil.py	(date 1676100208639)
@@ -1659,7 +1659,7 @@
                                 )),
                                 'url': str(self.base_url.set(
                                     path='/repository/files/6a85e0ab-2386-4f7e-8503-d72d90b4bc47',
-                                    args=dict(catalog='anvil-test', version='2022-06-01T00:00:00.000000Z')
+                                    args=dict(catalog=self.catalog, version='2022-06-01T00:00:00.000000Z')
                                 ))
                             }
                         ]
@@ -1788,7 +1788,7 @@
                                 )),
                                 'url': str(self.base_url.set(
                                     path='/repository/files/677f207e-2d12-4eca-8f7a-039325af91ad',
-                                    args=dict(catalog='anvil-test', version='2022-06-01T00:00:00.000000Z')
+                                    args=dict(catalog=self.catalog, version='2022-06-01T00:00:00.000000Z')
                                 ))
                             }
                         ]
Index: test/indexer/test_anvil.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/test_anvil.py b/test/indexer/test_anvil.py
--- a/test/indexer/test_anvil.py	(revision 1d80e3f8fbf7ad5a499eb9a118fcb33ec58ed0aa)
+++ b/test/indexer/test_anvil.py	(date 1676100169474)
@@ -36,7 +36,7 @@
     # FIXME: Tests using the AnVIL plugin must use a distinct catalog name to
     #        avoid unwanted cache hits
     #        https://github.com/DataBiosphere/azul/issues/4956
-    catalog = 'anvil-test'
+    catalog = 'test'
 
     @classmethod
     def bundles(cls) -> list[SourcedBundleFQID]:
Index: test/test_foo.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/test_foo.py b/test/test_foo.py
new file mode 100644
--- /dev/null	(date 1676100271172)
+++ b/test/test_foo.py	(date 1676100271172)
@@ -0,0 +1,20 @@
+import unittest
+
+from service.test_response import (
+    TestUnpopulatedIndexResponse,
+)
+from service.test_response_anvil import (
+    TestAnvilResponse,
+)
+
+
+def suite():
+    suite = unittest.TestSuite()
+    suite.addTest(TestAnvilResponse('test_entity_indices'))
+    suite.addTest(TestUnpopulatedIndexResponse('test_empty_response'))
+    return suite
+
+
+if __name__ == '__main__':
+    runner = unittest.TextTestRunner()
+    runner.run(suite())
```

and run test_foo. Expected outcome is a passing test suite. The actual outcome are test errors:

```
======================================================================
ERROR: test_empty_response (service.test_response.TestUnpopulatedIndexResponse) (entity_type='bundles')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/test/service/test_response.py", line 3484, in test_empty_response
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:52441/index/bundles?order=asc
```

caused by server-side exception


```
2023-02-10 23:24:49,300 DEBUG   Thread-12: _request('GET', https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=1000&sort=created_date&direction=asc&filter=snapshot, headers=None, timeout=5.0, body=None)
2023-02-10 23:24:49,482 ERROR   Thread-12: Caught exception for path /index/{entity_type}
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/src/azul/service/source_service.py", line 71, in list_sources
    sources = self._get(cache_key)
  File "/Users/hannes/.pyenv/versions/3.9.12/lib/python3.9/unittest/mock.py", line 1092, in __call__
    return self._mock_call(*args, **kwargs)
  File "/Users/hannes/.pyenv/versions/3.9.12/lib/python3.9/unittest/mock.py", line 1096, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/Users/hannes/.pyenv/versions/3.9.12/lib/python3.9/unittest/mock.py", line 1157, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/test/service/__init__.py", line 300, in not_found
    raise NotFound(key)
azul.service.source_service.NotFound: Key not found: 'test:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/chalice/app.py", line 1913, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/hannes/workspace/hca/azul/lambdas/service/app.py", line 1215, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/Users/hannes/workspace/hca/azul/src/azul/service/repository_controller.py", line 78, in search
    filters = self.get_filters(catalog, authentication, filters)
  File "/Users/hannes/workspace/hca/azul/src/azul/service/source_controller.py", line 69, in get_filters
    source_ids=self._list_source_ids(catalog, authentication))
  File "/Users/hannes/workspace/hca/azul/src/azul/service/source_controller.py", line 60, in _list_source_ids
    sources = self.list_sources(catalog, authentication)
  File "/Users/hannes/workspace/hca/azul/src/azul/service/source_controller.py", line 45, in list_sources
    sources = self._source_service.list_sources(catalog, authentication)
  File "/Users/hannes/workspace/hca/azul/src/azul/service/source_service.py", line 73, in list_sources
    sources = list(plugin.list_sources(authentication))
  File "/Users/hannes/workspace/hca/azul/src/azul/plugins/repository/tdr.py", line 106, in list_sources
    snapshots = tdr.snapshot_names_by_id(filter=filter)
  File "/Users/hannes/workspace/hca/azul/src/azul/terra.py", line 607, in snapshot_names_by_id
    response = self._request('GET', endpoint)
  File "/Users/hannes/workspace/hca/azul/src/azul/terra.py", line 357, in _request
    response = self._http_client.request(method,
  File "/Users/hannes/workspace/hca/azul/src/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/Users/hannes/workspace/hca/azul/src/azul/oauth2.py", line 70, in _http_client
    return AuthorizedHttp(self.credentials, http_client(), refresh_status_codes=())
  File "/Users/hannes/workspace/hca/azul/src/azul/oauth2.py", line 56, in credentials
    return self.credentials_provider.scoped_credentials()
  File "/Users/hannes/workspace/hca/azul/src/azul/terra.py", line 246, in scoped_credentials
    with aws.service_account_credentials(self.service_account) as file_name:
  File "/Users/hannes/.pyenv/versions/3.9.12/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/hannes/workspace/hca/azul/src/azul/deployment.py", line 286, in service_account_credentials
    secret = self._service_account_creds(secret_name)['SecretString']
  File "/Users/hannes/workspace/hca/azul/src/azul/deployment.py", line 76, in wrapper
    return cached_func(self.boto3_session, self, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/src/azul/deployment.py", line 73, in cached_func
    return func(self, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/src/azul/deployment.py", line 271, in _service_account_creds
    creds = sm.get_secret_value(SecretId=secret_name)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetSecretValue operation: The security token included in the request is invalid.
2023-02-10 23:24:49,483 DEBUG   Thread-12: Returning 500 response with headers {"Content-Type": "text/plain", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key"}. See next line for the first 1024 characters of the body.
```

**Comment by hannes-ucsc** [comment]
Slightly quicker reproduction:

```python
import unittest

from service.test_repository_specimen import (
    RepositorySpecimenEndpointTest,
)
from service.test_response_anvil import (
    TestAnvilResponse,
)


def load_tests(_loader, tests, _ignore):
    suite = unittest.TestSuite()
    suite.addTest(TestAnvilResponse('test_summary'))
    suite.addTest(RepositorySpecimenEndpointTest('test_basic_response'))
    tests.addTests(suite)
    return suite


if __name__ == '__main__':
    unittest.main()
```

**Comment by hannes-ucsc** [comment]
Also, it turns out that LocalAppTestCase already does properly reload the module for every test case.  It uses [azul.modules.load_module](https://github.com/DataBiosphere/azul/blob/3ad524443e299adae624ebd2792d0827ba27120d/src/azul/modules.py#L19) which returns a new module instance every time it's called. This means that simply avoiding class-level caches is sufficient to fix this issue.

**Comment by hannes-ucsc** [comment]
I added a split commit with [repro](https://github.com/DataBiosphere/azul/pull/4977/commits/cd3127b710f29906cbe19ea6a923e72a3a9e83da) and [fix](https://github.com/DataBiosphere/azul/pull/4977/commits/9f53ee52f5887751bda2bf1f4a5c195f31129cd1). Note the build status in each of these two commits.
