### ISSUE TITLE
Transient downtime from Terra caused GitLab `dev` IT failure

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5003]
IT on GitLab `dev` failed due to `maintenance downtime or capacity problems` from Terra.
IT passed on a subsequent retry.

```
Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2%27),
503,
b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache Server at jade.datarepo-dev.broadinstitute.org Port 80</address>
</body></html>
```

Full log at https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/62933

```
ERROR: test_can_bundle_configured_catalogs (integration_test.CanBundleScriptIntegrationTest) (catalog='dcp2-it', repository=Config.Catalog.Plugin(name='tdr_hca'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1470, in test_can_bundle_configured_catalogs
    self._test_catalog(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 1431, in _test_catalog
    self._can_bundle(source=str(fqid.source.spec),
  File "/builds/ucsc/azul/test/integration_test.py", line 1509, in _can_bundle
    return self._can_bundle_main(args)
  File "/builds/ucsc/azul/scripts/can_bundle.py", line 73, in main
    bundle = fetch_bundle(args.source, args.uuid, args.version)
  File "/builds/ucsc/azul/scripts/can_bundle.py", line 89, in fetch_bundle
    configured_source = plugin.resolve_source(configured_source)
  File "/builds/ucsc/azul/src/azul/plugins/__init__.py", line 471, in resolve_source
    id = self._lookup_source_id(spec)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr.py", line 151, in _lookup_source_id
    return self.tdr.lookup_source(spec).id
  File "/builds/ucsc/azul/src/azul/terra.py", line 445, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 475, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 570, in _check_response
    raise TerraStatusException(endpoint, response)
azul.terra.TerraStatusException: ('Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=hca_dev_ccef38d7aa9240109621c4c7b1182647__20210831_20210903&limit=2'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=hca_dev_ccef38d7aa9240109621c4c7b1182647__20210831_20210903&limit=2%27), 502, b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache Server at jade.datarepo-dev.broadinstitute.org Port 80</address>\n</body></html>\n')
======================================================================
ERROR: test_can_bundle_configured_catalogs (integration_test.CanBundleScriptIntegrationTest) (catalog='lungmap-it', repository=Config.Catalog.Plugin(name='tdr_hca'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1470, in test_can_bundle_configured_catalogs
    self._test_catalog(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 1428, in _test_catalog
    fqid = self.bundle_fqid(catalog.name)
  File "/builds/ucsc/azul/test/integration_test.py", line 1491, in bundle_fqid
    source, prefix, bundle_fqids = next(self._list_bundles(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 333, in _list_bundles
    source, prefix, new_fqids = self._list_partition_bundles(catalog, source)
  File "/builds/ucsc/azul/test/integration_test.py", line 260, in _list_partition_bundles
    source = plugin.resolve_source(source)
  File "/builds/ucsc/azul/src/azul/plugins/__init__.py", line 471, in resolve_source
    id = self._lookup_source_id(spec)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr.py", line 151, in _lookup_source_id
    return self.tdr.lookup_source(spec).id
  File "/builds/ucsc/azul/src/azul/terra.py", line 445, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 475, in _lookup_source
    response = self._check_response(endpoint, response)
  File "/builds/ucsc/azul/src/azul/terra.py", line 570, in _check_response
    raise TerraStatusException(endpoint, response)
azul.terra.TerraStatusException: ('Unexpected response from [https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2'](https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?filter=lungmap_dev_2620497955a349b28d2b53e0bdfcb176__20220404_20220404&limit=2%27), 503, b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<hr>\n<address>Apache Server at jade.datarepo-dev.broadinstitute.org Port 80</address>\n</body></html>\n')
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to find matching ticket where he suggested retrying TDR requests.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/4684#issuecomment-1304001941

**Comment by achave11-ucsc** [comment]
This is a dup of #4684.
