### ISSUE TITLE
Connection reset when fetching schema in `test_canned_staging_area`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5022]
… during a test build in GH Actios https://github.com/DataBiosphere/azul/actions/runs/4307226400/jobs/7512033686#step:4:8160
```
======================================================================
ERROR: test_canned_staging_area (hca_metadata_api.test.TestAccessorApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 909, in resolve_from_url
    document = self.store[url]
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_utils.py", line 28, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://schema.staging.data.humancellatlas.org/system/1.1.0/provenance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1015, in resolve_remote
    result = requests.get(uri).json()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/test/hca_metadata_api/test.py", line 489, in test_canned_staging_area
    staging_area = factory.load_staging_area()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 279, in load_staging_area
    files = self._get_files(path=self.path + ('metadata', folder))
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 316, in _get_files
    file = JsonFile.from_json(file_name, file_json)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 85, in from_json
    return MetadataFile(uuid=entity_id,
  File "<attrs generated init humancellatlas.data.metadata.helpers.staging_area.MetadataFile>", line 8, in __init__
    self.__attrs_post_init__()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 60, in __attrs_post_init__
    self._validator.validate_json(self.content, self.name)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py", line 34, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 394 tests in 935.556s

FAILED (errors=1, skipped=4)
make: *** [Makefile:224: test] Error 1
Error: Process completed with exit code 2.
```

**Comment by achave11-ucsc** [comment]
Additionally, the build https://github.com/DataBiosphere/azul/actions/runs/4307236496/jobs/7512056296 also failed transiently with JSON schema validation issues.
```
======================================================================
ERROR: test_canned_staging_area (hca_metadata_api.test.TestAccessorApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1015, in resolve_remote
    result = requests.get(uri).json()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/test/hca_metadata_api/test.py", line 489, in test_canned_staging_area
    staging_area = factory.load_staging_area()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 279, in load_staging_area
    files = self._get_files(path=self.path + ('metadata', folder))
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 316, in _get_files
    file = JsonFile.from_json(file_name, file_json)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 85, in from_json
    return MetadataFile(uuid=entity_id,
  File "<attrs generated init humancellatlas.data.metadata.helpers.staging_area.MetadataFile>", line 8, in __init__
    self.__attrs_post_init__()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 60, in __attrs_post_init__
    self._validator.validate_json(self.content, self.name)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py", line 34, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 394 tests in 1346.841s

FAILED (errors=1, skipped=4)
make: *** [Makefile:224: test] Error 1
Error: Process completed with exit code 2.

```

**Comment by achave11-ucsc** [comment]
It appears that all of the failing URLs are pointing at domain https://schema.staging.data.humancellatlas.org/. One failure occurs when the top level schema is fetch, the second failure occurred when a schema referenced by a top level schema was fetched.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "I want to sit on this for a little bit in order to see how prevalent it is. We could always customize schema loading by retrying more aggressively."

**Comment by hannes-ucsc** [comment]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/13420

**Comment by achave11-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/65544

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/13458

**Comment by hannes-ucsc** [comment]
Not very prevalent.

**Comment by achave11-ucsc** [comment]
Same test failed in [GitHub Actions test](https://github.com/DataBiosphere/azul/actions/runs/9895055574/job/27334055266?pr=6372), however the symptoms are slightly different,
```
======================================================================
ERROR: test_canned_staging_area (hca_metadata_api.test.TestAccessorApi.test_canned_staging_area)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/requests/models.py", line 963, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1015, in resolve_remote
    result = requests.get(uri).json()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/test/hca_metadata_api/test.py", line 508, in test_canned_staging_area
    staging_area = factory.load_staging_area(staging_area_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 259, in load_staging_area
    metadata=self._get_metadata_files(path),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 277, in _get_metadata_files
    files.update(self._get_files(path=sub_dir, file_cls=MetadataFile))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 306, in _get_files
    json_file = JsonFile.from_json(file_name, content)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 81, in from_json
    return MetadataFile(uuid=entity_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init humancellatlas.data.metadata.helpers.staging_area.MetadataFile>", line 8, in __init__
    self.__attrs_post_init__()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 56, in __attrs_post_init__
    self._validator.validate_json(self.content, self.name)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py", line 34, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/azul/azul/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 432 tests in 1127.668s

FAILED (errors=1, skipped=3)
make: *** [Makefile:234: test] Error 1
Error: Process completed with exit code 2.

```
