### ISSUE TITLE
Transient IT test_snapshot_listing fails in anvilbox

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5096]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/13044
```
FAIL: test_snapshot_listing (integration_test.IndexingIntegrationTest)
Test with a small page size to be sure paging works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 208, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 410, in test_snapshot_listing
    self.assertEqual(snapshots, paged_snapshots)
AssertionError: {'3ea[59586 chars]6', 'cbbf2f77-3830-435f-81e5-42bf8c8f764d': 'A[83202 chars]613'} != {'3ea[59586 chars]6', '84ca2098-ef4e-4d85-a988-424ccb7e33e6': 'A[83161 chars]613'}
Diff is 146780 characters long. Set self.maxDiff to None to see it.
----------------------------------------------------------------------
Ran 13 tests in 574.327s
FAILED (failures=1, skipped=2)
make: *** [Makefile:238: integration_test] Error 1
```

**Comment by achave11-ucsc** [comment]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/13482#L1428

**Comment by achave11-ucsc** [comment]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/13471

**Comment by dsotirho-ucsc** [comment]
https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22453

**Comment by hannes-ucsc** [comment]
In `prod` and `anvilprod` that test makes ~250 requests to TDR because so many snapshots are accessible. It has a running time of four minutes. If a snapshot is added or becomes accessible during the test, the test will fail. The long running time of the test makes that case significantly more likely.

We should add a filter to limit the number of requests the test makes to, say, 10 or 20.

**Comment by achave11-ucsc** [comment]
Agreed yesterday during parking lot that:
- Test should cover page sizes of one and two
- The following prefixes will be mapped per deployment 
  ```
  dev=hca_dev_5, 
  anvildev=anvil_, 
  prod=_dcp37, 
  anvilprod=anvil_page_
  ```

The prefixes were obtain via the `enumerateSnapshots` TDR Swagger Spec endpoint, and experimentally determining the filter criteria that best matched our desired result count (10~13), with the exception of anvildev (~5), a best efforts basis. This with the goal of reducing the total number of result's used in the test.

**Comment by hannes-ucsc** [comment]
For demo, show the test output from an IT job on GitLab in all main deployments. Show that multiple pages are being requested, and how many.

**Comment by achave11-ucsc** [comment]
Demoed for lower deployments. Still to be demoed in stable deployments.
