### ISSUE TITLE
GitLab `dev` pipeline for `develop` timed out during IT

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5115]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/65557
```
2023-04-05 17:30:05,295 DEBUG   ThreadPoolExecutor-2_0: Retrieving 2 entities of type 'donor_organism' ...
2023-04-05 17:30:05,295 DEBUG   ThreadPoolExecutor-2_0: Query (410 characters total): '\n            SELECT BYTE_LENGTH(content) AS content_size, donor_organism_id, version, content, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type\n            FROM `datarepo-dev-5d9526e0.lungmap_dev_1bdcecde16be420888f478cd2133d11d__20220401_20220404.donor_organism`\n            WHERE (donor_organism_id) IN ((\'834abf06-f34e-4821-9e0a-b8dae5a546f5\'), (\'5b8615be-5a49-4731-a2a7-4f893501129b\'))\n        '
2023-04-05 17:58:10,955 WARNING ThreadPoolExecutor-2_0: BigQuery job error during attempt 1/5. Retrying in 10s.
Traceback (most recent call last):
  File "/builds/ucsc/azul/src/azul/terra.py", line 520, in run_sql
    result = job.result()
  File "/build/.venv/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/build/.venv/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/build/.venv/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/build/.venv/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/build/.venv/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.InternalServerError: 500 An internal error occurred and the request could not be completed. This is usually caused by a transient issue. Retrying the job with back-off as described in the BigQuery SLA should solve the problem: https://cloud.google.com/bigquery/sla. If the error continues to occur please contact support at https://cloud.google.com/support. Error: 76907651
Location: us-central1
Job ID: c9fc6c96-3ef8-4a94-865f-5f6a5708ac31
2023-04-05 17:58:22,009 DEBUG   ThreadPoolExecutor-2_0:
```

**Comment by achave11-ucsc** [comment]
Spike for quick diagnosis, if possible.

**Comment by nadove-ucsc** [comment]
There were two 500 responses from Google during the canned bundle IT. Note that this particular test does not run in a Lambda, so there is no timeout.

Error 1:
```
2023-04-05 17:19:11,002 DEBUG   ThreadPoolExecutor-1_0: Query (379 characters total): ...
2023-04-05 17:29:43,342 WARNING ThreadPoolExecutor-1_0: BigQuery job error during attempt 1/5. Retrying in 10s.
```

Error 2:
```
2023-04-05 17:30:05,295 DEBUG   ThreadPoolExecutor-2_0: Query (410 characters total): ...
2023-04-05 17:58:10,955 WARNING ThreadPoolExecutor-2_0: BigQuery job error during attempt 1/5. Retrying in 10s.
```

Both queries succeeded on the first explicit retry, but it took 10 and 28 minutes respectively for us to attempt a retry. 10 minutes is the default deadline both for failed jobs (via the `job_retry` parameter) and failed RPC calls (via the `retry` parameter). I'm not sure how a delay of 28 minutes was possible.

Clearly, we need to change the current retry/timeout behavior for the call to `job.result()` so we don't spend so long waiting for a response, regardless of whether the job fails or not. Presumably, this will involve overriding the default values for any of `timeout`, `retry`, and `job_retry`. I wasn't able to determine a combination of arguments that would avoid this problem within the timebox of the spike.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Spike again to check if this type of hung request also occurs during a reindex in `prod`"

**Comment by nadove-ucsc** [comment]
I found no occurrences of the 500 error that preceded the hung queries from a reindex on `prod` during the last 8 weeks. Every query that failed with a 500 error during that time period did so due to exceeding the concurrency limit.

**Comment by nadove-ucsc** [comment]
I found an example of a Lambda waiting 10 minutes for a query to complete during a reindex:

```
google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function, last exception: 403 GET https://bigquery.googleapis.com/bigquery/v2/projects/platform-hca-prod/queries/e6f07553-df25-43ba-a89a-9270cf7d800e?fields=jobReference%2CtotalRows%2CpageToken%2Crows&location=US&formatOptions.useInt64Timestamp=True&prettyPrint=false: Exceeded rate limits: too many api requests per user per method for this user_method. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
```

This appears to be a different situation than the one that occurred during the IT on `dev`, but the common thread is that in both cases, it took 10 minutes to exit from `job.result()`. 

| | `dev` | `prod` |
| --- | --- | --- |
| status code | 500 | 403 |
| Exception class | `InternalServerError` | `RetryError` |
| Exception context | when calling `job.result()` | when iterating over the rows returned by `job.result()` |
| Explicit retry attempted | yes | no |
| Outcome | successful retry | Lambda aborted |

There is a case in the explicit retry mechanism intended to handle rate-limit errors, but only in the form of `ForbiddenError`. It looks like the implicit retry is swallowing the 403 and raising `RetryError` instead.

-----

Reproduction:

From log group `/aws/lambda/azul-indexer-prod-contribute_retry`:
```
fields @timestamp, @message
| filter @requestId = 'fe1a1b5b-8c5b-5b40-b0a8-47c1fd8a160a'
| sort @timestamp asc
```

Here is the 10-minute gap:
```
[DEBUG] 2023-03-26T16:15:15.985Z fe1a1b5b-8c5b-5b40-b0a8-47c1fd8a160a azul.terra Job info: ...
[DEBUG] 2023-03-26T16:25:16.072Z fe1a1b5b-8c5b-5b40-b0a8-47c1fd8a160a azul.plugins.repository.tdr_hca Retrieving 2 entities of type 'sequence_file' ...
```

The order of log messages from this Lambda invocation is very confusing due to the usage of `ThreadPoolExecutor`. I spent way too much time trying to figure our the exact order of events. I think the executor's worker thread continued executing even after the exception from the failed future propagated to the main thread.

**Comment by nadove-ucsc** [comment]
Prevalence on `prod` is 1,143 occurrences of `google.api_core.exceptions.RetryError: Deadline of 600.0s exceeded while calling target function` out of 9,082,511 queries during the past 8 weeks. Actual prevalence may be higher as the non-retry Lambda will time out before the exception can be raised.

**Comment by hannes-ucsc** [comment]
We added BQ retries in 2020 (51e4de4590a9347b5630ce8c7bcfbd1033a6a799). Google did so in 2021. I've also noticed that our dashboard graph stopped reporting rate limit trips. I don't know when exactly.

![CleanShot 2024-12-27 at 11 50 57@2x](https://github.com/user-attachments/assets/ab6f9635-b0f4-4520-ae55-24e6ef10aba0)

So evidently, our own retry logic is being circumvented by the client's logic. I think we should disable the client's retry logic by passing `None` to `retry` and `job_retry`. We should pass 10 to `timeout`. For both `client.query()` and `job.result()`.

**Comment by hannes-ucsc** [comment]
Spike to repeat previous spikes. I'd like to understand if this is still an issue.

**Comment by nadove-ucsc** [comment]
I looked at the past 36 months of logs for `contribute` and `contribute_retry` on HCA prod and AnVIL prod. There were zero occurrences of "RetryError".

 On HCA prod, there were three occurrences of "InternalServerError":

- In request `8c947207-8e3b-56a9-ac76-13b0b170677e`, the failed job was retried after 10 seconds and the Lambda succeeded.
- In request `72169d90-1698-5da0-83a4-fcfd6ea083ed`, two jobs failed. Both were retried after 10-15 seconds and the Lambda succeeded.
- In request `8842f47c-e30d-5261-8816-95119b3624ee`, there was a 4:15 delay before the job was retried. The Lambda then timed out after the job succeeded. 

On AnVIL prod, there were 37 occurrences of "InternalServerError", all of which occurred within the span of 6 minutes during the reindex on 2025-11-27. I didn't investigate each one individually but none of them timed out.

**Comment by nadove-ucsc** [comment]
My final judgement is that this no longer an issue.
