### ISSUE TITLE
Login to Swagger UI is broken

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5140]
```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1913, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 433, in oauth2_redirect
    oauth2_redirect_html = app.load_static_resource('oauth2-redirect.html')
  File "/var/task/azul/chalice.py", line 393, in load_static_resource
    return self.load_resource('static', *path)
  File "/var/task/azul/chalice.py", line 397, in load_resource
    with open_resource(*path, package_root=package_root) as f:
  File "/var/task/azul/__init__.py", line 1724, in open_resource
    return open(resource_file, mode='rb' if binary else 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/var/task/resources/static/oauth2-redirect.html'
```

**Comment by nadove-ucsc** [comment]
```diff
Index: lambdas/service/app.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/service/app.py b/lambdas/service/app.py
--- a/lambdas/service/app.py	(revision f6698c121aa781306bdc57e59ba497cbfd100cda)
+++ b/lambdas/service/app.py	(date 1681338368275)
@@ -430,7 +430,7 @@
 
 @app.route('/oauth2_redirect', enabled=config.google_oauth2_client_id is not None)
 def oauth2_redirect():
-    oauth2_redirect_html = app.load_static_resource('oauth2-redirect.html')
+    oauth2_redirect_html = app.load_static_resource('swagger', 'oauth2-redirect.html')
     return Response(status_code=200,
                     headers={"Content-Type": "text/html"},
                     body=oauth2_redirect_html)
```

**Comment by nadove-ucsc** [comment]
I overlooked this during https://github.com/DataBiosphere/azul/pull/5044

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
