### ISSUE TITLE
KeyError: 'is_supplementary' in `azul-service-anvildev`

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5202]
Log Insights: /aws/apigateway/azul-service-anvildev

```
fields @timestamp, @message
| filter @message like /KeyError/
| filter @message like /is_supplementary/
| sort @timestamp desc
| limit 200
```

![Screen Shot 2023-05-10 at 6 52 14 PM](https://github.com/DataBiosphere/azul/assets/46407464/efcdc674-ca1b-491a-ac1b-d73a262c21da)

```
[ERROR]	2023-05-11T01:43:04.536Z	83260573-99b5-468d-9d13-dab40a16a7cb	azul-service-anvildev	Caught exception for path /index/{entity_type}
Traceback (most recent call last):
  File "/var/task/azul/indexer/document.py", line 750, in translate_fields
    field_type = field_types[key]
KeyError: 'is_supplementary'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1913, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1202, in repository_search
    return app.repository_controller.search(catalog=app.catalog,
  File "/var/task/azul/service/repository_controller.py", line 79, in search
    response = self.service.search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 122, in search
    response = self._search(catalog=catalog,
  File "/var/task/azul/service/repository_service.py", line 247, in _search
    response = chain.process_response(response)
  File "/var/task/azul/service/elasticsearch_service.py", line 136, in process_response
    response1: R1 = self.inner.process_response(response0)
  File "/var/task/azul/service/elasticsearch_service.py", line 137, in process_response
    response2: R2 = self.outer.process_response(response1)
  File "/var/task/azul/service/elasticsearch_service.py", line 540, in process_response
    hits = self._translate_hits(hits)
  File "/var/task/azul/service/elasticsearch_service.py", line 553, in _translate_hits
    hits = self.service.translate_fields(self.catalog, hits, forward=False)
  File "/var/task/azul/indexer/document_service.py", line 100, in translate_fields
    return Document.translate_fields(doc, self.field_types(catalog), forward=forward)
  File "/var/task/azul/indexer/document.py", line 762, in translate_fields
    return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
  File "/var/task/azul/indexer/document.py", line 762, in <listcomp>
    return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
  File "/var/task/azul/indexer/document.py", line 755, in translate_fields
    new_doc[key] = cls.translate_fields(val, field_type, forward=forward, path=(*path, key))
  File "/var/task/azul/indexer/document.py", line 755, in translate_fields
    new_doc[key] = cls.translate_fields(val, field_type, forward=forward, path=(*path, key))
  File "/var/task/azul/indexer/document.py", line 762, in translate_fields
    return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
  File "/var/task/azul/indexer/document.py", line 762, in <listcomp>
    return [cls.translate_fields(val, field_types, forward=forward, path=path) for val in doc]
  File "/var/task/azul/indexer/document.py", line 752, in translate_fields
    raise KeyError(f'Key {key!r} not defined in field_types')
KeyError: "Key 'is_supplementary' not defined in field_types"
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
This was caused by the testing going on for https://github.com/DataBiosphere/azul/issues/5200. Previous merge commit branches are being redeployed to `anvildev` to run IT.
The problem is that a branch older than #5000 (PR #5059) was tried, and that PR adds the `is_supplementary` field.
