### ISSUE TITLE
Sporadic DNS resolution errors on GitLab

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5226]
IT on GitLab `dev` failed to establish a connection to indexer.dev.singlecell.gi.ucsc.edu

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68122

```
test_openapi (integration_test.OpenAPIIntegrationTest) ... test_expiration_tagging (integration_test.PortalExpirationIntegrationTest) ... 2023-05-18 20:03:35,420 INFO    MainThread: Using random seed 1182294530784203887
ok
test_concurrent_portal_db_crud (integration_test.PortalRegistrationIntegrationTest)
Use multithreading to simulate multiple users simultaneously modifying ... skipped 'Test disabled. FIXME #4285'
test (integration_test.SwaggerResourceIntegrationTest) ... ok
======================================================================
ERROR: test_openapi (integration_test.OpenAPIIntegrationTest) (component='indexer')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff18e41a340>: Failed to establish a new connection: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='indexer.dev.singlecell.gi.ucsc.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff18e41a340>: Failed to establish a new connection: [Errno -2] Name or service not known'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1394, in test_openapi
    response = requests.get(str(url))
  File "/build/.venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/build/.venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='indexer.dev.singlecell.gi.ucsc.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff18e41a340>: Failed to establish a new connection: [Errno -2] Name or service not known'))
----------------------------------------------------------------------
Ran 14 tests in 660.712s
FAILED (errors=1, skipped=3)
```

IT was retried and a new error was experienced:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128

```
Running with gitlab-runner 15.11.0 (436955cb)
  on Azul #[2](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L2) xHQi2x_S, system ID: r_HXUshJtjLOSP
Preparing the "docker" executor
Using Docker executor with image docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev:2[3](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L3)[4](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L4)44 ...
Authenticating with credentials from job payload (GitLab Registry)
Pulling docker image docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev:23444 ...
Using docker image sha2[5](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L5)[6](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L6):c84cb552b4[7](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L7)80c6bf7fe0726c773f7b13320512aeee3[9](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128#L9)8823119b2b9910ad9c9 for docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev:23444 with digest docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev@sha256:aade0095d49461ff7b95919770d6d5f49257be50976d2be1e24771ad79a951cc ...
Preparing environment
Running on runner-xhqi2xs-project-1-concurrent-0 via 986bfb4bb285...
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/ucsc/azul/.git/
fatal: unable to access 'https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul.git/': Could not resolve host: gitlab.dev.singlecell.gi.ucsc.edu
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

This last error seemed like it might be transient, so IT was retried a number of times and eventually this issue was resolved

Timeline of IT tests run:
12:52 [Job 68122](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68122) ("Failed to establish a new connection" failure)
1:04  [Job 68128](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68128) (1st "Could not resolve host" failure)
1:07 [Job 68129](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68129) (2nd "Could not resolve host" failure)
1:09  [Job 68130](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68130) (3rd "Could not resolve host" failure)
1:12  [Job 68131](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68131) (4th "Could not resolve host" failure)
1:20  [Job 68132](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68132) (success)

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Spike to comb host logs for evidence for problems with local resolver during the timeframe of the first failed test."

**Comment by dsotirho-ucsc** [comment]
From `/var/log/gitlab/gitlab-rails/production_json.log`:
```
{
    "method": "GET",
    "path": "/ucsc/azul.git/'",
    "format": "html",
    "controller": "ApplicationController",
    "action": "route_not_found",
    "status": 404,
    "time": "2023-05-18T20:06:44.881Z",
    "params": [
        {
            "key": "unmatched_route",
            "value": "ucsc/azul.git/'"
        }
    ],
    "correlation_id": "01H0R7HMT0JD57CPVGEVGNXE3S",
    "meta.caller_id": "ApplicationController#route_not_found",
    "meta.remote_ip": "172.71.3.128",
    "meta.user": "dsotirho-ucsc",
    "meta.user_id": 7,
    "meta.client_id": "user/7",
    "remote_ip": "172.71.3.128",
    "user_id": 7,
    "username": "dsotirho-ucsc",
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "queue_duration_s": 0.008494,
    "request_urgency": "default",
    "target_duration_s": 1,
    "redis_calls": 10,
    "redis_allowed_cross_slot_calls": 1,
    "redis_duration_s": 0.0031999999999999997,
    "redis_read_bytes": 1398,
    "redis_write_bytes": 987,
    "redis_cache_calls": 6,
    "redis_cache_duration_s": 0.002055,
    "redis_cache_read_bytes": 1217,
    "redis_cache_write_bytes": 346,
    "redis_sessions_calls": 3,
    "redis_sessions_allowed_cross_slot_calls": 1,
    "redis_sessions_duration_s": 0.000837,
    "redis_sessions_read_bytes": 181,
    "redis_sessions_write_bytes": 588,
    "redis_shared_state_calls": 1,
    "redis_shared_state_duration_s": 0.000308,
    "redis_shared_state_write_bytes": 53,
    "db_count": 3,
    "db_write_count": 0,
    "db_cached_count": 0,
    "db_replica_count": 0,
    "db_primary_count": 3,
    "db_main_count": 3,
    "db_main_replica_count": 0,
    "db_replica_cached_count": 0,
    "db_primary_cached_count": 0,
    "db_main_cached_count": 0,
    "db_main_replica_cached_count": 0,
    "db_replica_wal_count": 0,
    "db_primary_wal_count": 0,
    "db_main_wal_count": 0,
    "db_main_replica_wal_count": 0,
    "db_replica_wal_cached_count": 0,
    "db_primary_wal_cached_count": 0,
    "db_main_wal_cached_count": 0,
    "db_main_replica_wal_cached_count": 0,
    "db_replica_duration_s": 0.0,
    "db_primary_duration_s": 0.002,
    "db_main_duration_s": 0.002,
    "db_main_replica_duration_s": 0.0,
    "cpu_s": 0.070385,
    "mem_objects": 32906,
    "mem_bytes": 3583680,
    "mem_mallocs": 10521,
    "mem_total_bytes": 4899920,
    "pid": 685,
    "worker_id": "puma_0",
    "rate_limiting_gates": [],
    "db_duration_s": 0.00134,
    "view_duration_s": 0.03125,
    "duration_s": 0.05608
}
```

**Comment by achave11-ucsc** [comment]
I'm not sure that this is related but it looks similar.
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/16288
```
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/ucsc/azul/.git/
fatal: unable to access 'https://gitlab.anvil.gi.ucsc.edu/ucsc/azul.git/': Could not resolve host: gitlab.anvil.gi.ucsc.edu
Uploading artifacts for failed job 00:01
```
and
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68378
```
Uploading artifacts...
.gitlab.env: found 1 matching artifact files and directories 
ERROR: Uploading artifacts as "dotenv" to coordinator... error  error=couldn't execute POST against https://gitlab.dev.singlecell.gi.ucsc.edu/api/v4/jobs/68378/artifacts?artifact_format=gzip&artifact_type=dotenv: Post "https://gitlab.dev.singlecell.gi.ucsc.edu/api/v4/jobs/68378/artifacts?artifact_format=gzip&artifact_type=dotenv": dial tcp: lookup gitlab.dev.singlecell.gi.ucsc.edu on 8.8.8.8:53: no such host id=68378 token=64_amw1C
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
Uploading artifacts as "dotenv" to coordinator... 201 Created  id=68378 responseStatus=201 Created token=64_amw1C
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by achave11-ucsc** [comment]
I'm not sure that this is related but it looks similar.
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/16288
```
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/ucsc/azul/.git/
fatal: unable to access 'https://gitlab.anvil.gi.ucsc.edu/ucsc/azul.git/': Could not resolve host: gitlab.anvil.gi.ucsc.edu
Uploading artifacts for failed job 00:01
```
and
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68378
```
Uploading artifacts...
.gitlab.env: found 1 matching artifact files and directories 
ERROR: Uploading artifacts as "dotenv" to coordinator... error  error=couldn't execute POST against https://gitlab.dev.singlecell.gi.ucsc.edu/api/v4/jobs/68378/artifacts?artifact_format=gzip&artifact_type=dotenv: Post "https://gitlab.dev.singlecell.gi.ucsc.edu/api/v4/jobs/68378/artifacts?artifact_format=gzip&artifact_type=dotenv": dial tcp: lookup gitlab.dev.singlecell.gi.ucsc.edu on 8.8.8.8:…: no such host id=68378 token=…
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
Uploading artifacts as "dotenv" to coordinator... 201 Created  id=68378 responseStatus=201 Created
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by achave11-ucsc** [comment]
@dsotirho-ucsc: "Found related entry in /var/log/messages on GitLab dev, saying 'Using default external name servers'."

**Comment by achave11-ucsc** [comment]
Assignee to investigate further.

**Comment by dsotirho-ucsc** [comment]
```
May 21 04:03:06 ip-172-71-0-215 kernel: device vethd7ff752 entered promiscuous mode
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.539575683Z" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4]"
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.539618544Z" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]"
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.583298123Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.583375484Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.583403445Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
May 21 04:03:06 ip-172-71-0-215 docker: time="2023-05-21T04:03:06.583852263Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/e10d535f014b44eb6bd4cf6b829fad0d59e03a0896cb50e02dfb737ed39dffbf pid=23212 runtime=io.containerd.runc.v2
```

Note: this occurs 100's of times a day:
```
[ec2-user@ip-172-71-0-215 ~]$ sudo grep 'No non-localhost DNS' /var/log/messages | grep 'May 21' | wc -l
274
[ec2-user@ip-172-71-0-215 ~]$ sudo grep 'No non-localhost DNS' /var/log/messages | grep 'May 22' | wc -l
326
[ec2-user@ip-172-71-0-215 ~]$ sudo grep 'No non-localhost DNS' /var/log/messages | grep 'May 23' | wc -l
410
```

**Comment by achave11-ucsc** [comment]
This happened again in `dev` and `anvildev` GitLab instances for the same scheduled `sell_unused_slots` job.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68627
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/16525

**Comment by achave11-ucsc** [comment]
Happened again when retrying a failed IT run. https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68902#L15

**Comment by hannes-ucsc** [comment]
This fixes it. I tested it on anvilprod by manually modifying the unit file that launches the dind container

```diff
Index: terraform/gitlab/gitlab.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/gitlab/gitlab.tf.json.template.py b/terraform/gitlab/gitlab.tf.json.template.py
--- a/terraform/gitlab/gitlab.tf.json.template.py	(revision bbc9988d60b7f875a528c91b546d57a497f21b17)
+++ b/terraform/gitlab/gitlab.tf.json.template.py	(date 1686373790383)
@@ -1385,6 +1385,40 @@
                                     # gitlab-runner-net network, so TLS is
                                     # unnecessary.
                                     '--env DOCKER_TLS_CERTDIR=',
+                                    # Containers that attach to a custom
+                                    # network, get an /etc/resolv.conf that
+                                    # configures the container to resolve DNS
+                                    # lookups against a DNS server embedded in
+                                    # the Docker daemon. The host has a DNS
+                                    # server entry in resolv.conf that is set by
+                                    # DHCP. Passing that server via --dns to the
+                                    # DInD container would not affect the
+                                    # resolv.conf in that container. It would
+                                    # only affect the embedded server. The only
+                                    # server entry in the DinD container's
+                                    # resolv.conf will be the 127.0.0.11 entry
+                                    # (a localhost alias) pointing at the DNS
+                                    # server embedded in the Docker daemon
+                                    # running on the host. When the Docker
+                                    # daemon running in the DInD container
+                                    # launches another container, no
+                                    # non-localhost server entries will be
+                                    # present in resolv.conf, so that container
+                                    # falls back to the reckless default
+                                    # hard-coded in the Docker source (8.8.8.8
+                                    # and 8.8.4.4). These servers are operated
+                                    # by Google and are rate-limited, supposedly
+                                    # by source IP. All the VPC's egress traffic
+                                    # is routed through a NAT and all requests
+                                    # to Google DNS servers made within the VPC
+                                    # appear to originate from the same public
+                                    # IP. By mounting the host's resolv.conf
+                                    # into the Dind container, we work around
+                                    # this issue, so that containers launched by
+                                    # the Docker daemon running in the Dind
+                                    # container have a non-local DNS server and
+                                    # don't fall back to the Google ones.
+                                    '--volume /etc/resolv.conf:/etc/resolv.conf',
                                     '--volume /mnt/gitlab/docker:/var/lib/docker',
                                     '--volume /mnt/gitlab/runner/config:/etc/gitlab-runner',
                                     dind_image
```

**Comment by hannes-ucsc** [comment]
For demo, show that the symptom discovered by @dsotirho-ucsc goes away in every AWS account after this change is deployed to the `gitlab` component in that account.
