### ISSUE TITLE
TerraTimeoutException during `deploy` job 

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5227]
(The `deploy` job was retried a couple minutes later and succeeded.)

Failed `deploy` job: https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/39545

```
2023-05-18 23:01:19,539 DEBUG   ThreadPoolExecutor-0_6: _request(…) -> 48.129s 200 b'{"id":"65e7e128-9582-447e-b72d-bb1c32919ba4","name":"hca_prod_d3a4ceac4d66498497042570c0647a56__20220119_dcp2_20220121_dcp12","description":"Create snapshot hca_prod_d3a4ceac4d66498497042570c0647a56__20220119_dcp2_20220121_dcp12","createdDate":"2022-01-...'
2023-05-18 23:01:19,542 INFO    ThreadPoolExecutor-0_6: TDR client is authorized for API access to tdr:datarepo-dac6d601:snapshot/hca_prod_d3a4ceac4d66498497042570c0647a56__20220119_dcp2_20220121_dcp12:/0.
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=20.0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/src/azul/terra.py", line 357, in _request
    response = self._http_client.request(method,
  File "/build/.venv/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/build/.venv/lib/python3.9/site-packages/google/auth/transport/urllib3.py", line 383, in urlopen
    response = self.http.urlopen(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/build/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.terra.bio', port=443): Max retries exceeded with url: /api/repository/v1/snapshots/999a3bf9-9b25-448b-9962-6ab93d56a258 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=20.0)"))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 86, in <module>
    main()
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 81, in main
    verify_sources()
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 54, in verify_sources
    raise e
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/scripts/post_deploy_tdr.py", line 58, in verify_source
    source = tdr.lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 445, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 481, in _lookup_source
    return self._retrieve_source(SourceRef(id=source_id, spec=source))
  File "/builds/ucsc/azul/src/azul/terra.py", line 458, in _retrieve_source
    response = self._request('GET', endpoint)
  File "/builds/ucsc/azul/src/azul/terra.py", line 366, in _request
    raise TerraTimeoutException(url, timeout)
azul.terra.TerraTimeoutException: No response from https://data.terra.bio/api/repository/v1/snapshots/999a3bf9-9b25-448b-9962-6ab93d56a258 within 20.0 seconds
make: *** [Makefile:103: auto_deploy] Error 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
This happened in `hammerbox` during the `deploy` step. https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9173

**Comment by achave11-ucsc** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43581

**Comment by achave11-ucsc** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45747
&
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45756

**Comment by achave11-ucsc** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45761
& 
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45766

**Comment by achave11-ucsc** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45773,
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45806,
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45809, and
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/45960.

**Comment by achave11-ucsc** [comment]
This happened in `anvilprod` and `hammerbox`, 
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/11921
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/11931#L1045

**Comment by dsotirho-ucsc** [comment]
Occurred during IT on `anvilprod`
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14562

**Comment by hannes-ucsc** [comment]
Note that above occurrence is during `integration_test`, not `deploy`.

**Comment by achave11-ucsc** [comment]
This happened again recently [during a `deploy`](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/15341) job in `hammerbox`.

**Comment by achave11-ucsc** [comment]
Degraded performance from Terra caused various errors in Azul.
1) Starting the `reindex` job failed twice in `anvilbox`. 
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/28071, https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/28102.
2) Service cachehealth Lambdas timeout (resulting in alarms going off) in [`anvildev`](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-11-15T16*3a52*3a50.488Z~start~'2023-11-15T16*3a50*3a56.224Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20*40message*0a*23*20*7c*20filter*20*40message*20like*20*2fTask*2f*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20200~queryId~'6230937133f561ef-d03a79bb-41d1ded-8fb2a3e9-9912c852c563f7231a7e~source~(~'*2faws*2flambda*2fazul-service-anvildev-servicecachehealth~'*2faws*2flambda*2fazul-service-anvildev))) and [`dev`](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-10800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*2fTask*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~queryId~'98c911e141df83f5-297af2d1-48461b6-a03d8ef-834d2d4dbb293fed8acfa844~source~(~'arn*3aaws*3alogs*3aus-east-1*3a122796619775*3alog-group*3a*2faws*2flambda*2fazul-service-dev-servicecachehealth))) due to their service request taking longer than the allowed execution time. While most of these service requests eventually succeeded (longer time-frame), the others resulted in 503s from Terra.

**Comment by dsotirho-ucsc** [comment]
This is now tracked in #5766 because the symptom changed (different exception class is raised).
