### ISSUE TITLE
kibana_proxy.py fails with ImageNotFound for aws-signing-proxy

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5350]
Only on Apple silicon.

```
(.venv) hannes-m1bp:azul hannes$ python scripts/kibana_proxy.py 
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/hannes/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 175, in <module>
    main(sys.argv[1:])
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 170, in main
    KibanaProxy(options).run()
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 62, in __init__
    self.docker = docker.from_env()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
(.venv) hannes-m1bp:azul hannes$ python scripts/kibana_proxy.py
2023-06-26 17:00:42,761 INFO    MainThread: Found credentials in environment variables.
2023-06-26 17:00:42,762 INFO    MainThread: Getting domain endpoint
2023-06-26 17:00:43,370 INFO    MainThread: Pulling image '289950828509.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2'
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/containers/create?name=proxy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 67, in create_container
    container = self.docker.containers.create(image, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/models/containers.py", line 905, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.42/containers/create?name=proxy: Not Found ("No such image: 289950828509.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.42/images/289950828509.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 175, in <module>
    main(sys.argv[1:])
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 170, in main
    KibanaProxy(options).run()
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 82, in run
    proxy = self.create_container('docker.io/cllunsford/aws-signing-proxy:0.2.2',
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 70, in create_container
    self.docker.images.pull(image)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/models/images.py", line 474, in pull
    return self.get('{0}{2}{1}'.format(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.42/images/289950828509.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2/json: Not Found ("No such image: 289950828509.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2")
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
One way to work around this is to set `azul_docker_registry` to an empty string. The image will be pulled from docker.io directly, not our ECR.

Alternatively, this patch also works around the issue, but without bypassing our ECR.

```diff
Index: scripts/kibana_proxy.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/kibana_proxy.py b/scripts/kibana_proxy.py
--- a/scripts/kibana_proxy.py	(revision 23bf41b1f2fb6ce88813d94322c2f0d843bed47a)
+++ b/scripts/kibana_proxy.py	(date 1687842013844)
@@ -61,13 +61,13 @@
         self.options = options
         self.docker = docker.from_env()
 
-    def create_container(self, image: str, *args, **kwargs) -> Container:
+    def create_container(self, image: str, *args, platform=None, **kwargs) -> Container:
         image = config.docker_registry + image
         try:
             container = self.docker.containers.create(image, *args, **kwargs)
         except docker.errors.ImageNotFound:
             log.info('Pulling image %r', image)
-            self.docker.images.pull(image)
+            self.docker.images.pull(image, platform=platform)
             container = self.docker.containers.create(image, *args, **kwargs)
         return container
 
@@ -80,6 +80,7 @@
         containers = []
         try:
             proxy = self.create_container('docker.io/cllunsford/aws-signing-proxy:0.2.2',
+                                          platform='linux/amd64',
                                           name='proxy',
                                           auto_remove=True,
                                           command=['-target', self.es_endpoint, '-port', str(proxy_port)],
@@ -93,6 +94,7 @@
                                           ports={port: port for port in (kibana_port, cerebro_port, proxy_port)})
             containers.append(proxy)
             kibana = self.create_container('docker.elastic.co/kibana/kibana-oss:7.10.2',
+                                           platform='linux/amd64',
                                            name='kibana',
                                            auto_remove=True,
                                            detach=True,
@@ -103,6 +105,7 @@
                                            network_mode=f'container:{proxy.name}')
             containers.append(kibana)
             cerebro = self.create_container('docker.io/lmenezes/cerebro:0.9.4',
+                                            platform='linux/amd64',
                                             name='cerebro',
                                             auto_remove=True,
                                             command=[f'-Dhttp.port={cerebro_port}'],
```

I guess it makes a difference if an image is a bare single-arch image (as it is on on docker.io) or a single-arch image wrapped in a multi-arch index (as on ECR). In the former case, dockerd will silently pull the image even if the architecture doesn't match the native arch of the client. The image will run more slowly, using emulation.  In the latter case, dockerd fails outright, leading to this error. Pinning the platform fixes that but makes the client code more brittle:  if at some point in the future an image matching the client's native arch becomes available, the pinned platform would force the use of a mismatched image. That's why the above patch isn't a fix.

**Comment by hannes-ucsc** [comment]
Duplicates #5832
