### ISSUE TITLE
Make requirements_update fails w/ DockerException (M1 Chipset)

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5440]
… the following is the output of the `requirements_update` target, when executing `python scripts/manage_requirements.py` …
```
python scripts/manage_requirements.py \                                                                                                  
               --image=docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/deps:latest \                                                  
               --build-image=docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev-deps:latest
2023-08-01 09:38:53,004 INFO    MainThread: Reading direct pip requirements from /Users/achave11/Pycharm/Azul/azul.stable/requirements.pip.txt
2023-08-01 09:38:53,005 INFO    MainThread: Reading direct runtime requirements from /Users/achave11/Pycharm/Azul/azul.stable/requirements.txt
2023-08-01 09:38:53,009 INFO    MainThread: Reading direct build requirements from /Users/achave11/Pycharm/Azul/azul.stable/requirements.dev.txt
2023-08-01 09:38:53,013 INFO    MainThread: Getting direct and transitive build requirements using 'docker run docker.gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/dev-deps:latest .venv/bin/pip list --format=freeze'
Traceback (most recent call last):
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/achave11/.pyenv/versions/3.9.16/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/achave11/Pycharm/Azul/azul.stable/scripts/manage_requirements.py", line 293, in <module>
    main.run()
  File "/Users/achave11/Pycharm/Azul/azul.stable/scripts/manage_requirements.py", line 196, in run
    all_reqs = self.get_reqs(self.build)
  File "/Users/achave11/Pycharm/Azul/azul.stable/scripts/manage_requirements.py", line 254, in get_reqs
    stdout = self.docker.containers.run(image=qualfier.image,
  File "/Users/achave11/Pycharm/Azul/azul.stable/src/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/Users/achave11/Pycharm/Azul/azul.stable/scripts/manage_requirements.py", line 187, in docker
    return docker.from_env()
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/Users/achave11/Pycharm/Azul/azul.stable/.venv/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
make: *** [requirements_update] Error 1

```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Can't reproduce this. Try restarting Docker on your machine.

**Comment by achave11-ucsc** [comment]
This was due to a misconfiguration of the Docker app I use. The `/var/run/docker.sock` file was not available until the `Allow the default Docker socket to be used` feature was enabled in _Settings > Advance_. After that item was checked, and the Docker app restarted, the problem was solved.
