### ISSUE TITLE
Execution failure due to ConnectionError in `azul-service_servicecachehealth` Lambda

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5466]
[This Log Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-08-13T05*3a05*3a25.000Z~start~'2023-08-13T05*3a03*3a44.000Z~timeType~'ABSOLUTE~tz~'Local~editorString~'fields*20*40timestamp*2c*20*40message*0a*23*20*7c*20filter*20*40requestId*20like*20*2fc12c2eca-d048-452b-911e-a13cbc649d42*2f*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2055~queryId~'f54ff323ae47a714-3ddb83d-44a4e74-fe99e2e-728c2820f0f4b08ee7e77aec~source~(~'*2faws*2flambda*2fazul-service-dev-servicecachehealth~'*2faws*2fapigateway*2fazul-service-dev))) are relevant. The `@requestId` of the executions captured in this logs are of particular interest, aside from the error it self. Two executions, separated by slightly more than a minute share the same `@requestId`.

```
[ERROR] ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/var/task/azul/chalice.py", line 166, in patched_event_source_handler
    return old_handler(self_, event, context)
  File "/var/task/chalice/app.py", line 1752, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1708, in __call__
    return self.handler(request, self.next_handler)
  File "/var/task/azul/chalice.py", line 191, in _lambda_context_middleware
    return get_response(event)
  File "/var/task/app.py", line 498, in update_health_cache
    app.health_controller.update_cache()
  File "/var/task/azul/health.py", line 140, in update_cache
    health_object = dict(time=time.time(), health=self._health.as_json_fast())
  File "/var/task/azul/health.py", line 311, in as_json_fast
    return self.as_json(p.key for p in self.fast_properties[self.lambda_name])
  File "/var/task/azul/health.py", line 182, in as_json
    json = {k: getattr(self, k) for k in keys}
  File "/var/task/azul/health.py", line 182, in <dictcomp>
    json = {k: getattr(self, k) for k in keys}
  File "/var/task/azul/health.py", line 75, in __get__
    return super().__get__(obj, objtype=objtype)
  File "/var/task/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/var/task/azul/health.py", line 266, in api_endpoints
    status = dict(tpe.map(self._api_endpoint, endpoints))
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/azul/health.py", line 244, in _api_endpoint
    response = requests.head(url)
  File "/opt/python/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/opt/python/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@nadove-ucsc: "The one minute gap between the two invocations with the same `requestId` is presumably due to the Lambda automatically retrying the failed request. By default it will make two retry attempts."

**Comment by nadove-ucsc** [comment]
Solution is more complex than I initially assumed because the `ConnectionError` is raised by `requests.head()` instead of `response.raise_for_status()`

**Comment by nadove-ucsc** [comment]
Until we know how pervasive this is, no action is needed.

**Comment by dsotirho-ucsc** [comment]
Reoccurrence on anvildev: [CW Logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-09-06T14*3a40*3a57.311Z~start~'2023-09-06T13*3a15*3a43.443Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*40message*20like*20*2f*28*3fi*29error*2f*20or*20*40requestId*20*3d*20*2764e3a2f3-7c40-4f67-98d0-1f89b45e352d*27*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20500~queryId~'58f5928c68fcd13-50372169-46ce96-b6455e-7228dff4fe6eeef8b8e7057~source~(~'*2faws*2flambda*2fazul-service-anvildev-servicecachehealth)))

```
[ERROR] ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/var/task/azul/chalice.py", line 166, in patched_event_source_handler
    return old_handler(self_, event, context)
  File "/var/task/chalice/app.py", line 1752, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1708, in __call__
    return self.handler(request, self.next_handler)
  File "/var/task/azul/chalice.py", line 191, in _lambda_context_middleware
    return get_response(event)
  File "/var/task/app.py", line 498, in update_health_cache
    app.health_controller.update_cache()
  File "/var/task/azul/health.py", line 140, in update_cache
    health_object = dict(time=time.time(), health=self._health.as_json_fast())
  File "/var/task/azul/health.py", line 311, in as_json_fast
    return self.as_json(p.key for p in self.fast_properties[self.lambda_name])
  File "/var/task/azul/health.py", line 182, in as_json
    json = {k: getattr(self, k) for k in keys}
  File "/var/task/azul/health.py", line 182, in <dictcomp>
    json = {k: getattr(self, k) for k in keys}
  File "/var/task/azul/health.py", line 75, in __get__
    return super().__get__(obj, objtype=objtype)
  File "/var/task/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/var/task/azul/health.py", line 266, in api_endpoints
    status = dict(tpe.map(self._api_endpoint, endpoints))
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/var/lang/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/azul/health.py", line 244, in _api_endpoint
    response = requests.head(url)
  File "/opt/python/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/opt/python/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
```

**Comment by hannes-ucsc** [comment]
It is unclear why this is assigned to me or what the next steps are.
