### ISSUE TITLE
Aggregates do not read sources from ES

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5563]
Two bugs that seem to cancel/hide each other in practice.

```diff
Subject: [PATCH] changes
---
Index: src/azul/indexer/document.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/document.py b/src/azul/indexer/document.py
--- a/src/azul/indexer/document.py	(revision f2694c602bf80d36a4a175a113590dabb71d78da)
+++ b/src/azul/indexer/document.py	(date 1695338686821)
@@ -1057,8 +1057,8 @@
                                  document=document,
                                  version=version,
                                  num_contributions=document['num_contributions'],
-                                 sources=map(DocumentSource.from_json,
-                                             cast(list[SourceJSON], document['sources'])),
+                                 sources=set(map(DocumentSource.from_json,
+                                                 cast(list[SourceJSON], document['sources']))),
                                  bundles=document.get('bundles'))
         assert isinstance(self, Aggregate)
         return self
@@ -1068,7 +1068,7 @@
         return super().mandatory_source_fields() + [
             'num_contributions',
             'sources.id',
-            'sources.name',
+            'sources.spec'
         ]
 
     def to_json(self) -> JSON:
```

Because `sources.spec` is missing from `mandatory_source_fields`, the source specs are absent from the ES response. This goes unnoticed because the sources are never actually parsed from the response due to the laziness of `map`. If the `sources` field is reified, the lazy call to `from_json` fails with:

```
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/test_indexer.py", line 983, in test_bundle_downgrade
    self._index_canned_bundle(self.old_bundle)
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/__init__.py", line 163, in _index_canned_bundle
    cls._index_bundle(bundle, delete=delete)
  File "/home/nadove/PycharmProjects/azul-sc/test/indexer/__init__.py", line 171, in _index_bundle
    cls.index_service.index(cls.catalog, bundle)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 192, in index
    self.aggregate(tallies)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 428, in aggregate
    old_aggregates = self._read_aggregates(tallies)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 505, in _read_aggregates
    return {a.coordinates.entity: a for a in aggregates()}
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 505, in <dictcomp>
    return {a.coordinates.entity: a for a in aggregates()}
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/index_service.py", line 500, in aggregates
    aggregate = aggregate_cls.from_index(self.catalogued_field_types(),
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/document.py", line 862, in from_index
    return cls.from_json(coordinates=coordinates,
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/document.py", line 1060, in from_json
    sources=set(map(DocumentSource.from_json,
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/indexer/__init__.py", line 363, in from_json
    return cls(id=ref['id'], spec=cls.spec_cls().parse(ref['spec']))
KeyError: 'spec'
```

**Comment by achave11-ucsc** [comment]
Spike to consider any additional implications.

**Comment by hannes-ucsc** [comment]
I understand now why this issue does not currently negatively impact the system. While the indexer reads existing aggregations from the index, the aggregation instances that it eventually writes to the index are created from scratch and only the expected document version is propagated from the existing aggregation instances. During aggregation, the `sources` field is never actually accessed. As @nadove-ucsc poits out, the laziness of `map` thereby prevents the KeyError on `develop`.

I might want to add this patch to the ensuing PR:

```diff
Subject: [PATCH] Reduce GCP permissions for developers to Viewer (DataBiosphere/azul-private#25)
---
Index: src/azul/indexer/index_service.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/indexer/index_service.py b/src/azul/indexer/index_service.py
--- a/src/azul/indexer/index_service.py	(revision 62dea740456813a7294531d6c7487121eb0b8549)
+++ b/src/azul/indexer/index_service.py	(date 1695494048763)
@@ -431,7 +431,8 @@
                 old_aggregate.coordinates.entity: old_aggregate.num_contributions
                 for old_aggregate in old_aggregates.values()
             })
-            # Read all contributions from Elasticsearch
+
+            # Read all contributions
             contributions = self._read_contributions(total_tallies)
             actual_tallies = Counter(contribution.coordinates.entity
                                      for contribution in contributions)
@@ -441,26 +442,34 @@
                 raise EventualConsistencyException(message, *args)
             assert all(tallies[entity] <= actual_tally
                        for entity, actual_tally in actual_tallies.items())
-            # Combine the contributions into old_aggregates, one per entity
+
+            # Combine the contributions into new aggregates, one per entity
             new_aggregates = self._aggregate(contributions)
-            # Set the expected document version from the old version
+
+            # Remove old aggregates (leaving over only deletions) while
+            # propagating the expected document version to the corresponding new
+            # aggregate
             for new_aggregate in new_aggregates:
                 old_aggregate = old_aggregates.pop(new_aggregate.coordinates.entity, None)
                 new_aggregate.version = None if old_aggregate is None else old_aggregate.version
-            # Empty out any unreferenced aggregates (can only happen for deletions)
+            
+            # Empty out the left-over, deleted aggregates
             for old_aggregate in old_aggregates.values():
                 old_aggregate.contents = {}
                 new_aggregates.append(old_aggregate)
-            # Write aggregates to Elasticsearch
+
+            # Write new aggregates
             writer.write(new_aggregates)
-            # Retry if necessary
-            if not writer.retries:
-                break
-            tallies: CataloguedTallies = {
-                aggregate.coordinates.entity: tallies[aggregate.coordinates.entity]
-                for aggregate in new_aggregates
-                if aggregate.coordinates in writer.retries
-            }
+            
+            # Retry writes if necessary
+            if writer.retries:
+                tallies: CataloguedTallies = {
+                    aggregate.coordinates.entity: tallies[aggregate.coordinates.entity]
+                    for aggregate in new_aggregates
+                    if aggregate.coordinates in writer.retries
+                }
+            else:
+                break
         writer.raise_on_errors()
 
     def _read_aggregates(self,
```

**Comment by hannes-ucsc** [comment]
In fact, I suspect that the `sources` attribute is never actually read outside of ES, so we may be tempted to skip even reading it. However, the value is always going to be a list of a single object with two properties, so doing so may not be worth the code complexity.
