### ISSUE TITLE
IT on hammerbox failed due to snapshot_in_progress_exception

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5661]
Similar to closed issue https://github.com/DataBiosphere/azul/issues/4882

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14671

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 227, in wrapped
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 460, in test_indexing
    self._reset_indexer()
  File "/builds/ucsc/azul/test/integration_test.py", line 507, in _reset_indexer
    self.azul_client.reset_indexer(catalogs=config.integration_test_catalogs,
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 468, in reset_indexer
    self.delete_all_indices(catalog)
  File "/builds/ucsc/azul/src/azul/azulclient.py", line 380, in delete_all_indices
    self.index_service.delete_indices(catalog)
  File "/builds/ucsc/azul/src/azul/indexer/index_service.py", line 382, in delete_indices
    es_client.indices.delete(index=index_name)
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/client/indices.py", line 294, in delete
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/es.py", line 73, in perform_request
    return super().perform_request(method, url, params, body, timeout, ignore, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/build/.venv/lib/python3.11/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'snapshot_in_progress_exception', 'Cannot delete indices that are being snapshotted: [[azul_v2_hammerbox_anvil1-it_activities/T-XT6vXlTWaidyzi8eIV8g]]. Try again after snapshot finishes or cancel the currently running snapshot.')

```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to file support ticket with AWS.

**Comment by dsotirho-ucsc** [comment]
[Support case 14201887551](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=14201887551&language=en) opened

**Comment by dsotirho-ucsc** [comment]
Support case [14201887551](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=14201887551&language=en) completed, marked resolved, & left positive review feedback.

Snapshots of `anvilprod` and `hammerbox` domains last occurred 2023-11-02

```
daniel@Crispin ~/repo $ cat snapshots-hammerbox.json | jq '.snapshots[].snapshot' | sort | tail -n 6
"2023-11-02t06-27-41.b3975697-5751-2bc4-27c8-a5bc81f824a7"
"2023-11-02t07-27-39.363cb543-6e36-337e-5e19-a0ec722cfa84"
"2023-11-02t08-27-34.381cf4a1-af48-1704-eeb8-07b4c30ef8de"
"2023-11-02t09-27-37.ea8a522f-f599-80ee-9277-9c6716db985b"
"2023-11-02t10-27-29.41c110dc-af59-7318-34d5-8f5c07d25ff6"
"2023-11-02t11-27-26.b260769a-9012-04c4-9483-5914faf72ee5"
daniel@Crispin ~/repo $
daniel@Crispin ~/repo $
daniel@Crispin ~/repo $ cat snapshots-anvilprod.json | jq '.snapshots[].snapshot' | sort | tail -n 6
"2023-11-02t06-21-39.010414da-d0da-7b71-5eb9-32f1daaa05e2"
"2023-11-02t07-21-41.293585f8-acbf-d041-921b-d63ae8abd186"
"2023-11-02t08-21-40.40c4aef7-9a9f-9d45-01eb-89e1e789b7b2"
"2023-11-02t09-21-44.1256cd9f-fdb0-f0ba-56c2-25ddd955c0c0"
"2023-11-02t10-21-41.cae8a5fe-540a-59a9-84f9-ec1c88b82a3e"
"2023-11-02t11-21-33.fafcd701-0351-26d4-2420-041262bc39c2"
```

…and the "Domain status" of both domains has changed from "Preparing to process updates" to "Active".

![Screen Shot 2023-11-07 at 10 19 00 AM](https://github.com/DataBiosphere/azul/assets/46407464/76c5e43a-64f1-47b6-a342-68e84e469c36)
![Screen Shot 2023-11-07 at 10 19 04 AM](https://github.com/DataBiosphere/azul/assets/46407464/409e28cb-4482-4afc-995f-5a742c109578)
