### ISSUE TITLE
`KeyError: 'azul_docker_version'` when running unit tests in PyCharm

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5729]
To reproduce, right-click on `service.test_manifest.TestManifestEndpoints.test_pfb_manifest` and click *Run 'Unittests in …'*

```diff
/Users/hannes/workspace/hca/azul/.venv/bin/python /Users/hannes/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.10227.11/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_unittest_runner.py --target test_manifest.TestManifestEndpoints.test_pfb_manifest 
Testing started at 10:20 PM ...
envhook.py: Setting AWS_DEFAULT_REGION to 'us-east-1'
… snip …
envhook.py: Setting AWS_SESSION_TOKEN to 'REDACTED'
Launching unittests with arguments python -m unittest test_manifest.TestManifestEndpoints.test_pfb_manifest in /Users/hannes/workspace/hca/azul/test/service

2023-11-27 22:20:16,354   DEBUG MainThread azul.deployment: Clearing cache of '_dss_bucket'
2023-11-27 22:20:16,354   DEBUG MainThread azul.deployment: Clearing cache of '_es_domain_status'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of '_service_account_creds'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'client'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'get_hmac_key_and_id'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'permissions_boundary'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'permissions_boundary_arn'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'permissions_boundary_tf'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'region_name'
2023-11-27 22:20:16,355   DEBUG MainThread azul.deployment: Clearing cache of 'resource'


Ran 0 tests in 0.008s

FAILED (errors=1)

Failure
Traceback (most recent call last):
  File "/Users/hannes/.pyenv/versions/3.11.5/lib/python3.11/unittest/suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "/Users/hannes/workspace/hca/azul/test/indexer/__init__.py", line 126, in setUpClass
    super().setUpClass()
  File "/Users/hannes/workspace/hca/azul/src/azul/__init__.py", line 1467, in docker_images
    docker=f'docker.io/library/docker:{self.docker_version}',
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/src/azul/__init__.py", line 1450, in docker_version
    return self.environ['azul_docker_version']
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/.pyenv/versions/3.11.5/lib/python3.11/collections/__init__.py", line 1006, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/.pyenv/versions/3.11.5/lib/python3.11/collections/__init__.py", line 998, in __missing__
    raise KeyError(key)
KeyError: 'azul_docker_version'


Process finished with exit code 1
```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
This is a regression in PR #5706 for #5703. `envhook.py` should load the new `environment.boot` file.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
