### ISSUE TITLE
Aggregation threshold assertion fails on /index/summary

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5827]
The specimen count in the dcp34 catalog exceeds 20000 for the first time and that trips an assertion we have in place to guard against errors of the approximate aggregation algorithm used by ES.

```
$ curl -v 'https://service.azul.data.humancellatlas.org/index/summary?filters=%7B%7D&catalog=dcp34'
*   Trying 18.155.202.98:443...
* Connected to service.azul.data.humancellatlas.org (18.155.202.98) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=service.azul.data.humancellatlas.org
*  start date: Aug 18 00:00:00 2023 GMT
*  expire date: Sep 13 23:59:59 2024 GMT
*  subjectAltName: host "service.azul.data.humancellatlas.org" matched cert's "service.azul.data.humancellatlas.org"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: service.azul.data.humancellatlas.org]
* h2 [:path: /index/summary?filters=%7B%7D&catalog=dcp34]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x150012e00)
> GET /index/summary?filters=%7B%7D&catalog=dcp34 HTTP/2
> Host: service.azul.data.humancellatlas.org
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/2 500
< content-type: text/plain
< content-length: 2346
< date: Wed, 03 Jan 2024 20:05:33 GMT
< x-amzn-requestid: d0a41562-ecdc-482d-a62d-6abeb5581b5d
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000; includeSubDomains
< access-control-allow-headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
< x-amz-apigw-id: Q-qhQENZoAMEKxQ=
< x-amzn-trace-id: Root=1-6595be07-100ca0e142d2a2db1af0b3eb;Sampled=0;lineage=2808a99a:0
< x-cache: Error from cloudfront
< via: 1.1 ab6fdf5fb199d6495c32e485c23f5728.cloudfront.net (CloudFront)
< x-amz-cf-pop: SFO53-P2
< x-amz-cf-id: gO-tbwNiPIj0DNACTyS7miY5QnTk05hCodonEtoDaRNqmGano-KlqA==
<
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1914, in _get_view_function_response
    response = view_function(**function_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/app.py", line 1224, in get_summary
    return app.repository_controller.summary(catalog=app.catalog,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/repository_controller.py", line 107, in summary
    response = self.service.summary(catalog, filters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/repository_service.py", line 274, in summary
    aggs = dict(executor.map(summary, aggs_by_authority))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/repository_service.py", line 269, in summary
    return entity_type, self._summary(catalog=catalog,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/repository_service.py", line 309, in _summary
    result = chain.process_response(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/elasticsearch_service.py", line 142, in process_response
    response2: R2 = self.outer.process_response(response1)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/plugins/metadata/hca/service/aggregation.py", line 151, in process_response
    assert agg_value <= threshold / 2, (agg_name, agg_value, threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ('specimenCount', 20975, 40000)
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-aggregations-metrics-cardinality-aggregation.html

We already specify the maximum allowable threshold of 40000 and have an assertion in place to test for a resulting cardinality exceeding half the threshold. 50% was a guess, and looking at the error diagram from the above ES documentation page, the error rate stays below 2% up to a cardinality of 100000 with a threshold of 10000. So it seems that we can safely relax the check to 90% of the threshold. We may even be able use 100% but I am not sure if the algorithm used by ES strictly yields a lower bound or if it can over-count as well.

This is only a stop gap, in the long run it is unlikely that ES will raise the maximum or switch to a non-approximate algorithm. The reasoning for using an approximation is obvious. We need to live with the fact that some cardinality aggregations return approximate results for high-cardinality items and indicate in our response to clients which results are accurate and which ones are approximate.

**Comment by hannes-ucsc** [comment]
Temporary hotfix was committed & deployed to `prod` and backported to develop.
