### ISSUE TITLE
ImageNotFound error in kibana_proxy.py on Apple Silicon

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5832]
To reproduce, remove the local copies of the affected images:

```
docker image ls --format "table {{.Repository}}:{{.Tag}}" | grep -F $(python -m azul config.docker_registry) | grep -E 'kibana-oss|cerebro|aws-signing-proxy' | xargs docker image rm
```

Make sure you're logged in using `_login`.

Then launch the `kibana_proxy.py` script.

```
$ python scripts/kibana_proxy.py
2024-01-08 10:07:18,338    INFO MainThread __main__: Getting domain endpoint
2024-01-08 10:07:18,984    INFO MainThread __main__: Pulling image '465330168186.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2'
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/create?name=proxy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 67, in create_container
    container = self.docker.containers.create(image, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/models/containers.py", line 917, in create
    resp = self.client.api.create_container(**create_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/containers/create?name=proxy: Not Found ("No such image: 465330168186.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/images/465330168186.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 175, in <module>
    main(sys.argv[1:])
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 170, in main
    KibanaProxy(options).run()
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 82, in run
    proxy = self.create_container(config.docker_images['signing_proxy'],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/scripts/kibana_proxy.py", line 70, in create_container
    self.docker.images.pull(image)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/models/images.py", line 474, in pull
    return self.get('{0}{2}{1}'.format(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
           ^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/465330168186.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2/json: Not Found ("No such image: 465330168186.dkr.ecr.us-east-1.amazonaws.com/docker.io/cllunsford/aws-signing-proxy:0.2.2")
```

None of the three images used by the script is available as `arm64` which I believe leads to the error. There is a multi-platform image on ECR but it only contains a reference to one platform-specific image for `linux/amd64`.

After applying the patch below and running the script again, it starts working.

```diff
Index: scripts/kibana_proxy.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/kibana_proxy.py b/scripts/kibana_proxy.py
--- a/scripts/kibana_proxy.py (revision 6102c1e84536524fa68ecc3f54983a1b44f47a5e)
+++ b/scripts/kibana_proxy.py (date 1704736977352)
@@ -67,7 +67,7 @@
             container = self.docker.containers.create(image, *args, **kwargs)
         except docker.errors.ImageNotFound:
             log.info('Pulling image %r', image)
-            self.docker.images.pull(image)
+            self.docker.images.pull(image, platform=kwargs.get('platform'))
             container = self.docker.containers.create(image, *args, **kwargs)
         return container
 
@@ -81,6 +81,7 @@
         try:
             proxy = self.create_container(config.docker_images['signing_proxy'],
                                           name='proxy',
+                                          platform='linux/amd64',
                                           auto_remove=True,
                                           command=['-target', self.es_endpoint, '-port', str(proxy_port)],
                                           detach=True,
@@ -94,6 +95,7 @@
             containers.append(proxy)
             kibana = self.create_container(config.docker_images['kibana'],
                                            name='kibana',
+                                           platform='linux/amd64',
                                            auto_remove=True,
                                            detach=True,
                                            environment={
@@ -104,6 +106,7 @@
             containers.append(kibana)
             cerebro = self.create_container(config.docker_images['cerebro'],
                                             name='cerebro',
+                                            platform='linux/amd64',
                                             auto_remove=True,
                                             command=[f'-Dhttp.port={cerebro_port}'],
                                             detach=True,
@@ -141,7 +144,10 @@
                     assert f.result() is None
         finally:
             for container in containers:
-                container.kill()
+                # Containers that haven't been started yet can't be killed.
+                # Removing them with force, i.e., killing them if necessary,
+                # handles both running and non-running containers.
+                container.remove(force=True)
 
     @cached_property
     def es_endpoint(self):
```

The last hunk is for an independent bug that may obscure the symptoms in the above reproduction in case one of the images is already present locally.

Once the script succeeds with the patch applied, and the images are cached locally, the patch can be removed, and the script will still succeed. The handling of platform-specific images must be slightly different when the image is present locally compared to when it needs to be fetched from a remote registry. Docker is happy to use an image with a mismatched platform when it is present locally, but rejects it when it's part of a multi-platform index image on a remote registry. If it finds a matching image remotely, Docker does not seem to fetch the index image, only the matching platform-specific image. Once any platform-specific image is present locally, matching platform or not, that image is used.

We create index images on ECR for all images, even if only one platform is available. I implemented it that way for consistency and simplicity (in copy_images_to_ecr.py). As an alternative to the patch above, which would have to be reverted when `arm64` images are available, we could try not creating these "singleton" image indexes when only one platform is available for any given image. This would have to be tested first and may also complicate the removal of unused images, especially when first deploying such a change.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
