### ISSUE TITLE
Transient IT failure for managed_access_repository_files with empty iterable

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5924]
Failure occurred on anvildev during testing of the merge commit for PR https://github.com/DataBiosphere/azul/pull/5879. IT succeeded on 2nd try.

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/33542

```
2024-02-03 00:51:06,258    INFO MainThread test.integration_test: Beginning sub-test [managed_access_repository_files] {'catalog': 'anvil-it'}
2024-02-03 00:51:06,263    INFO MainThread azul.oauth2: Making GET request to '[https://service.anvil.gi.ucsc.edu/index/files?catalog=anvil-it&size=100&filters=%7B%22sourceId%22%3A+%7B%22is%22%3A+%5B%225f55901c-4bfc-4d33-b85d-bd9f812f57cd%22%2C+%227d632e2a-54f1-4021-81fd-dbaf893715cd%22%5D%7D%7D'](https://service.anvil.gi.ucsc.edu/index/files?catalog=anvil-it&size=100&filters=%7B%22sourceId%22%3A+%7B%22is%22%3A+%5B%225f55901c-4bfc-4d33-b85d-bd9f812f57cd%22%2C+%227d632e2a-54f1-4021-81fd-dbaf893715cd%22%5D%7D%7D%27)
2024-02-03 00:51:06,263   DEBUG MainThread azul.oauth2: … without request body
2024-02-03 00:51:06,316    INFO MainThread azul.oauth2: Got 200 response after 0.053s from GET to https://service.anvil.gi.ucsc.edu/index/files?catalog=anvil-it&size=100&filters=%7B%22sourceId%22%3A+%7B%22is%22%3A+%5B%225f55901c-4bfc-4d33-b85d-bd9f812f57cd%22%2C+%227d632e2a-54f1-4021-81fd-dbaf893715cd%22%5D%7D%7D
2024-02-03 00:51:06,316   DEBUG MainThread azul.oauth2: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '1486', 'Connection': 'keep-alive', 'Date': 'Sat, 03 Feb 2024 00:51:06 GMT', 'x-amzn-RequestId': '78a13651-ccc9-48d5-8475-a7496fe22f57', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'x-amz-apigw-id': 'SiMfJE8foAMEK3w=', 'X-Amzn-Trace-Id': 'Root=1-65bd8dfa-00f5804b4b8804d72484cfd5;Parent=5b4e030bbd883cad;Sampled=0;lineage=87986af1:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 f638767bb567304644b370360b61ed30.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD61-P3', 'X-Amz-Cf-Id': 'R9FlFksGnIXxK65lNPW1CTqDlmrJ-H6hhkAIj18z6-U7jSSErq_CDA=='})
2024-02-03 00:51:06,317   DEBUG MainThread azul.oauth2: … with response body b'{"hits":[],"pagination":{"count":0,"total":0,"size":100,"next":null,"previous":null,"pages":0,"sort":"files.file_id","order":...'
2024-02-03 00:51:06,318    INFO MainThread test.integration_test: Failed sub-test [managed_access_repository_files] {'catalog': 'anvil-it'}
  test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [managed_access_repository_files] (catalog='anvil-it') ... ERROR

… 

======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [managed_access_repository_files] (catalog='anvil-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 194, in first
    return next(iter(iterable))
           ^^^^^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 419, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1299, in _test_managed_access
    files = self._test_managed_access_repository_files(catalog, managed_access_source_ids)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 1407, in _test_managed_access_repository_files
    file_url = furl(first(managed_access_file_urls))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 197, in first
    raise ValueError(
ValueError: first() was called on an empty iterable, and no default value was provided.
----------------------------------------------------------------------
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to investigate.

**Comment by nadove-ucsc** [comment]
Logs show that the failure was preceded by a request to `/index/files` (ID `031d6433-d3c1-445c-ac99-94ccd022431e`) using a filter to select managed access sources. The authorization header was accepted and a query containing the source ID filter was submitted to ElasticSearch, but the query returned no hits, resulting in the empty iterable. This is surprising because the `catalog_complete` subtest shows that many supplementary bundles were indexed from the sources used in the filter, each of which should have contributed files to the index even if none of the primary bundles contained files.

I've been unable to reproduce this failure. Steps taken to attempt to reproduce:
 - Checked out commit from the failing pipeline
 - Updated catalog config in personal deployment (`nadove4`) to match `anvildev`
 - Pinned seed from the failing test
 - Ran IT 3x

Thus, my first spike was not successful in determining the underlying cause of the failure.

**Comment by nadove-ucsc** [comment]
> This is surprising because the catalog_complete subtest shows that many supplementary bundles were indexed from the sources used in the filter

I was mistaken about this. The only bundles indexed from these sources were the DUOS bundles. All primary and supplementary bundles were from the public snapshot. Continuing spike to investigate why no primary or supplementary bundles were indexed from the managed access snapshots.

**Comment by nadove-ucsc** [comment]
The IT makes sure to always include at least one bundle from each managed access source. However there is no control over whether that bundle is primary, supplementary, or DUOS. In this case, the singular DUOS bundle (containing no files) was selected for both managed access sources. This can be confirmed by observing that the prefix used to select those bundles matches the UUID of the dataset entities in those snapshots.

Bundle prefixes:
```
024-02-03 00:43:20,309    INFO MainThread azul.plugins.repository.tdr: There are 1 bundle(s) with prefix '95edef18' in source SourceRef(id='7d632e2a-54f1-4021-81fd-dbaf893715cd', spec=TDRSourceSpec(prefix=Prefix(common='', partition=0), project='datarepo-dev-97ad270b', name='ANVIL_CMG_Sample_1_20230225_ANV5_202302281509', is_snapshot=True)).
...
024-02-03 00:43:23,080    INFO MainThread azul.plugins.repository.tdr: There are 1 bundle(s) with prefix '748f9698' in source SourceRef(id='5f55901c-4bfc-4d33-b85d-bd9f812f57cd', spec=TDRSourceSpec(prefix=Prefix(common='', partition=0), project='datarepo-dev-42c70e6a', name='ANVIL_CCDG_Sample_1_20230228_ANV5_202302281520', is_snapshot=True)).
2024-02-03 00:43:23,080    INFO MainThread test.integration_test: Selected 2 bundles to satisfy managed access coverage; selecting at least 30 more
```
Dataset IDs:

```
$ curl -X 'GET'   'https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil&filters=%7B%0A%20%20%22sourceId%22%3A%20%7B%0A%20%20%20%20%22is%22%3A%20%5B%0A%20%20%20%20%20%20%227d632e2a-54f1-4021-81fd-dbaf893715cd%22%2C%0A%20%20%20%20%20%20%225f55901c-4bfc-4d33-b85d-bd9f812f57cd%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&size=10'   -H 'Authorization: Bearer $token' | jq .hits[].datasets[].document_id
"748f9698-8d05-40e8-85de-75c86e959873"
"95edef18-cac2-46c9-b1d1-10f885836490"
```

Therefore, this error could be avoided by filtering out the DUOS bundles before selecting bundles from the managed access sources. This would be done in the `_list_managed_access_bundles` method.

I think my reproduction failure is due to a nondeterminism occurring here:

https://github.com/DataBiosphere/azul/blob/5f7406dd84eb9602e48dfc9f5aed72a1d200f1fe/test/integration_test.py#L390

The _index_ of the selected bundle from within the list of bundles is determined by the seed, but because the list itself is not deterministically ordered prior to selection, the actual choice of bundle FQID remains nondeterministic. To fix this, sort the list before choosing an item.

**Comment by achave11-ucsc** [comment]
This happened again in `anvilprod`, 

https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/22175
