### ISSUE TITLE
Service fails with `elasticsearch.exceptions.SSLError`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5956]
The filters used were `{"query": {"catalog": "dcp34", "filters": "{\"specimenOrgan\":{\"is\":[\"uterus\"]}}"}` against the `indexer/summary` endpoint, and the execution returned a 500 status code response. The execution failed due to the following error,

```
[ERROR] 2024-02-14T15:46:23.243Z af51d20d-140f-4a97-85ef-17693ead14f8 azul-service-prod Caught exception for path /index/summary
Traceback (most recent call last):
File "/opt/python/urllib3/connectionpool.py", line 715, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/opt/python/urllib3/connectionpool.py", line 416, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/opt/python/urllib3/connection.py", line 244, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/var/lang/lib/python3.11/http/client.py", line 1286, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/var/lang/lib/python3.11/http/client.py", line 1332, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.11/http/client.py", line 1281, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/var/lang/lib/python3.11/http/client.py", line 1080, in _send_output
self.send(chunk)
File "/var/lang/lib/python3.11/http/client.py", line 1002, in send
self.sock.sendall(data)
File "/var/lang/lib/python3.11/ssl.py", line 1274, in sendall
v = self.send(byte_view[count:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/ssl.py", line 1243, in send
return self._sslobj.write(data)
^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2427)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/opt/python/urllib3/connectionpool.py", line 799, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/opt/python/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com](http://vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com/)', port=443): Max retries exceeded with url: /azul_v2_prod_dcp34_files_aggregate/_search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2427)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/python/elasticsearch/connection/http_requests.py", line 166, in perform_request
response = self.session.send(prepared_request, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/requests/adapters.py", line 517, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com](http://vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com/)', port=443): Max retries exceeded with url: /azul_v2_prod_dcp34_files_aggregate/_search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2427)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1917, in _get_view_function_response
response = view_function(**function_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/app.py", line 1271, in get_summary
return app.repository_controller.summary(catalog=app.catalog,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/azul/service/repository_controller.py", line 107, in summary
response = self.service.summary(catalog, filters)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/azul/service/repository_service.py", line 274, in summary
aggs = dict(executor.map(summary, aggs_by_authority))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
yield _result_or_cancel(fs.pop())
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
return fut.result(timeout)
^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 456, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "/var/lang/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
raise self._exception
File "/var/lang/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/azul/service/repository_service.py", line 269, in summary
return entity_type, self._summary(catalog=catalog,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/azul/service/repository_service.py", line 303, in _summary
response = request.execute(ignore_cache=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/elasticsearch_dsl/search.py", line 715, in execute
self, es.search(index=self._index, body=self.to_dict(), **self._params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/elasticsearch/client/utils.py", line 347, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/elasticsearch/client/__init__.py", line 1821, in search
return self.transport.perform_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/elasticsearch/transport.py", line 464, in perform_request
raise e
File "/opt/python/elasticsearch/transport.py", line 427, in perform_request
status, headers_response, data = connection.perform_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/task/azul/es.py", line 74, in perform_request
return super().perform_request(method, url, params, body, timeout, ignore, headers)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/elasticsearch/connection/http_requests.py", line 191, in perform_request
raise SSLError("N/A", str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError(HTTPSConnectionPool(host='[vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com](http://vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com/)', port=443): Max retries exceeded with url: /azul_v2_prod_dcp34_files_aggregate/_search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2427)')))) caused by: SSLError(HTTPSConnectionPool(host='[vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com](http://vpc-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com/)', port=443): Max retries exceeded with url: /azul_v2_prod_dcp34_files_aggregate/_search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2427)'))))
```

[CW Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-43200~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*40requestId*20like*20*2faf51d20d*2f*0a*7c*20parse*20*40message*20*27*7b*22Code*22*3a*20*22*2a*22*2c*27*20as*20err*0a*7c*20parse*20*40message*20*27https*3a*2f*2f*2a*2f*2a*2f*2a*2f*2a*2f*2a*20within*27*20as*20domain*2c*20e1*2c*20e2*2c*20*2ce3*2c*20e4*2c*20_*0a*23*20*7c*20count*28*2a*29*20as*20count_*20by*20err*2c*20domain*2c*20concat*28*27*2f*27*2c*20e1*2c*20*27*2f*27*2c*20e2*2c*20*27*2f*27*2c*20e3*2c*20*27*2f*27*29*20as*20endpoint*0a*7c*20sort*20count_*20desc~queryId~'b3cc21e6-e468-4f96-9903-868facdfdb24~source~(~'*2faws*2flambda*2fazul-service-prod)))

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We will sit on this for a while, to determine what its prevalence is."

**Comment by hannes-ucsc** [comment]
Not prevalent.
