### ISSUE TITLE
Cannot locally test azul-docker-pycharm changes

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5986]
Starting with bd7c321f353c05c838f7ceec400029057a0ea8f5, the instructions in the [azul-docker-pycharm](https://github.com/DataBiosphere/azul-docker-pycharm/) repo to test changes locally no longer work.

> \# To test the image in Azul, run:
> (cd ../azul && azul_docker_pycharm_version=2023.2.3-5 azul_docker_registry=localhost:5000/ make format)

```
(.venv) daniel@Crispin ~/repo/azul1 $ azul_docker_pycharm_version=2023.3.3-14 azul_docker_registry=localhost:5000/ make format
docker run \
	    --rm \
	    --volume $(python scripts/resolve_container_path.py /Users/daniel/repo/azul1):/home/developer/azul \
	    --workdir /home/developer/azul \
	    $(AZUL_DEBUG=0 python -m azul 'docker.resolve_docker_image_for_launch("pycharm")') \
	    /opt/pycharm/bin/format.sh -r -settings .pycharm.style.xml -mask '*.py' src scripts test lambdas/layer/app.py lambdas/indexer/app.py lambdas/service/app.py .flake8/azul_flake8.py environment.py deployments/anvilbox/environment.py deployments/anvildev.browser/environment.py deployments/anvildev.gitlab/environment.py deployments/anvildev.shared/environment.py deployments/anvildev/environment.py deployments/anvilprod.browser/environment.py deployments/anvilprod.gitlab/environment.py deployments/anvilprod.shared/environment.py deployments/anvilprod/environment.py deployments/daniel.local/environment.py deployments/daniel2.local/environment.py deployments/dev.gitlab/environment.py deployments/dev.shared/environment.py deployments/dev/environment.py deployments/hammerbox/environment.py deployments/prod.gitlab/environment.py deployments/prod.shared/environment.py deployments/prod/environment.py deployments/sandbox/environment.py .github/workflows/schedule.py terraform/backend.tf.json.template.py terraform/common.tf.json.template.py terraform/step_function.tf.json.template.py terraform/lambda_layer.tf.json.template.py terraform/dynamo.tf.json.template.py terraform/cloudwatch.tf.json.template.py terraform/elasticsearch.tf.json.template.py terraform/api_gateway.tf.json.template.py terraform/providers.tf.json.template.py terraform/authentication.tf.json.template.py terraform/sqs.tf.json.template.py terraform/s3.tf.json.template.py terraform/gitlab/gitlab.tf.json.template.py terraform/shared/shared.tf.json.template.py terraform/browser/browser.tf.json.template.py lambdas/indexer/.chalice/config.json.template.py lambdas/service/.chalice/config.json.template.py .github/pull_request_template.md.template.py
envhook.py: Warning: azul_docker_registry is 'localhost:5000/' but should be '122796619775.dkr.ecr.us-east-1.amazonaws.com/', you must run `source environment`
envhook.py: Warning: AZUL_DEBUG is '0' but should be '1', you must run `source environment`
envhook.py: Warning: azul_docker_registry is 'localhost:5000/' but should be '122796619775.dkr.ecr.us-east-1.amazonaws.com/', you must run `source environment`
2024-02-23 15:04:31,009    INFO MainThread azul.docker: Resolving image 'pycharm' TagImageRef(registry='docker.io', username='ucscgi', repository=('azul-pycharm',), tag='2023.3.2-11') …
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/daniel/repo/azul1/src/azul/__main__.py", line 21, in <module>
    result = str(eval(expression, dict(__builtins__={}), locals))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/daniel/repo/azul1/src/azul/docker.py", line 511, in resolve_docker_image_for_launch
    ref_to_pull, manifest = resolve_docker_image_for_pull(alias)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/repo/azul1/src/azul/docker.py", line 542, in resolve_docker_image_for_pull
    ref_to_pull = TagImageRef.parse(config.docker_registry + str(ref))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/repo/azul1/src/azul/docker.py", line 218, in parse
    name, tag = image_ref.split(':')
    ^^^^^^^^^
ValueError: too many values to unpack (expected 2)
docker: invalid reference format.
See 'docker run --help'.
make: *** [format] Error 125
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Until we fix this, operators are not required to test Pycharm and Elasticsearch images prior to pushing commits to the GitHub repositories that host the respective Dockerfile. Assignee to consider next steps."

**Comment by hannes-ucsc** [comment]
With these changes

```diff
Index: environment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/environment.py b/environment.py
--- a/environment.py	(revision 82110e816896d6d08e9454aa7ab39e32f02c05fc)
+++ b/environment.py	(date 1710178033682)
@@ -273,7 +273,7 @@
                 'ref': 'docker.io/library/python:{azul_python_version}-bullseye'
             },
             'pycharm': {
-                'ref': 'docker.io/ucscgi/azul-pycharm:2023.3.4-15'
+                'ref': 'localhost:5000/docker.io/ucscgi/azul-pycharm:2023.3.4-15'
             },
             'elasticsearch': {
                 'ref': 'docker.io/ucscgi/azul-elasticsearch:7.17.18-13'
Index: src/azul/docker.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/docker.py b/src/azul/docker.py
--- a/src/azul/docker.py	(revision 82110e816896d6d08e9454aa7ab39e32f02c05fc)
+++ b/src/azul/docker.py	(date 1710180029491)
@@ -89,6 +89,12 @@
         TagImageRef(registry='4', username='3', repository=('2',), tag='1')
         >>> ImageRef.parse('5/4/3/2:1')
         TagImageRef(registry='5', username='4', repository=('3', '2'), tag='1')
+        >>> ImageRef.parse('localhost:5000/docker.io/ucscgi/azul-pycharm:2023.3.4-15')
+        ... # doctest: +NORMALIZE_WHITESPACE
+        TagImageRef(registry='localhost:5000',
+                    username='docker.io',
+                    repository=('ucscgi', 'azul-pycharm'),
+                    tag='2023.3.4-15')
         """
         if '@' in image_ref:
             return DigestImageRef.parse(image_ref)
@@ -215,7 +221,8 @@
 
     @classmethod
     def parse(cls, image_ref: str) -> Self:
-        name, tag = image_ref.split(':')
+        # A colon in the first part of the name might separate host and port
+        name, _, tag = image_ref.rpartition(':')
         return cls.create(name, tag)
 
     @classmethod
@@ -437,7 +444,10 @@
 
     @cached_property
     def _client(self):
-        return DXF(host=self.host, repo=self.name, auth=self._auth)
+        return DXF(host=self.host,
+                   repo=self.name,
+                   auth=self._auth,
+                   insecure=self.host.startswith('localhost:') or self.host == 'localhost')
 
     def _auth(self, dxf: DXFBase, response: requests.Response):
         host: str = furl(response.request.url).host
```

and then running ` make image_manifests.json` and `azul_docker_registry="" make format` fixes it.

Assignee to try this approach for https://github.com/DataBiosphere/azul-docker-elasticsearch as well, and, assuming that test is successful, file PRs in https://github.com/DataBiosphere/azul-docker-pycharm and https://github.com/DataBiosphere/azul-docker-elasticsearch that update the READMEs accordingly.

**Comment by dsotirho-ucsc** [comment]
Spike to run the experiment mentioned in the previous comment.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce, for `azul-docker-pycharm` and `azul-docker-elasticsearch`.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Both @dsotirho-ucsc  and @achave11-ucsc report being able to locally test our images. This suffices for demo."
