### ISSUE TITLE
test_replica_update fails in `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6062]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/55184

I reverted 82110e81 on the `prod` branch for the time being. 

```
======================================================================
ERROR: test_replica_update (indexer.test_indexer.TestDCP1IndexerWithIndexesSetUp.test_replica_update) [New replica]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 539, in one
    first_value = next(it)
                  ^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/indexer/test_indexer.py", line 2133, in test_replica_update
    hit = one(self._get_all_hits())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 541, in one
    raise (
ValueError: too few items in iterable (expected 1)
======================================================================
ERROR: test_replica_update (indexer.test_indexer.TestDCP1IndexerWithIndexesSetUp.test_replica_update) [Additional hub IDs]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 539, in one
    first_value = next(it)
                  ^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/indexer/test_indexer.py", line 2133, in test_replica_update
    hit = one(self._get_all_hits())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 541, in one
    raise (
ValueError: too few items in iterable (expected 1)
======================================================================
ERROR: test_replica_update (indexer.test_indexer.TestDCP1IndexerWithIndexesSetUp.test_replica_update) [Redundant hub IDs]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 539, in one
    first_value = next(it)
                  ^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/indexer/test_indexer.py", line 2133, in test_replica_update
    hit = one(self._get_all_hits())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/more_itertools/more.py", line 541, in one
    raise (
ValueError: too few items in iterable (expected 1)
----------------------------------------------------------------------
Ran 419 tests in 2810.963s
FAILED (errors=3, skipped=3)
make: *** [Makefile:231: test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by nadove-ucsc** [comment]
Perhaps this is a symptom of [replicas being disabled on `prod`](https://github.com/DataBiosphere/azul/blob/2639f5bd9f768879e5623113b19f694d86c99686/deployments/prod/environment.py#L1124). I suspect the test ought to mock `config.enable_replicas` to `True`.

**Comment by hannes-ucsc** [comment]
Good catch. Enabling replicas on `prod` did suppress the test failure. I reverted the reversion and reindexed again on Sunday.

I suspect there is more to do. The test should not be sensitive to that configuration piece. We should either skip the test or adjust the assertions to account for replicas being disabled, or additionally mock the configuration dynamically while looping over the two possible cases. We'd have to weigh the coverage gain versus the test code complexity. There might already be other tests that are conditional on replicas being enabled. The same concerns should be taken into account for those tests.

**Comment by nadove-ucsc** [comment]
Note that the observed failure mode is a symptom of https://github.com/DataBiosphere/azul/issues/5675
