### ISSUE TITLE
Response not logged for requests retried implicitly by urllib3

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6083]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/88821

For example, the IT log output for the failed tests at the end of the job shows:
```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [manifest_tagging_race] (catalog='dcp3-it', format=<ManifestFormat.compact: 'compact'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 427, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 663, in _test_manifest_tagging_race
    response = self._get_url(method, manifest_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 863, in _get_url
    response = self._get_url_unchecked(method, url, stream=stream)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 891, in _get_url_unchecked
    response = http.request(method=method,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 81, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 173, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 68, in urlopen
    response = super().urlopen(method, url, body=body, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='service.sandbox.dev.singlecell.gi.ucsc.edu', port=443): Max retries exceeded with url: /manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact (Caused by ResponseError('too many 500 error responses'))
```

And similarly, the full test logs:
```
INFO MainThread test.integration_test: Beginning sub-test [manifest_tagging_race] {'catalog': 'dcp3-it', 'format': <ManifestFormat.compact: 'compact'>}
INFO MainThread test.integration_test: Making PUT request to 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact'
DEBUG MainThread test.integration_test: … without request body
INFO MainThread test.integration_test: Got 301 response after 0.150s from PUT to https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact
DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '4', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Mar 2024 19:17:42 GMT', 'x-amzn-RequestId': '314734c9-bab3-4519-bd3c-efe01e8c1dc4', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'X-Frame-Options': 'DENY', 'x-amz-apigw-id': 'U_opkHMpIAMEsJA=', 'X-Content-Type-Options': 'nosniff', 'Location': 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files/k8QgjplizeaDmhOW8B-KdfrlaY1v9sLROoDfJLzTEoBmr5UAAQ==', 'Retry-After': '1', 'X-Amzn-Trace-Id': 'Root=1-65fc87d6-375c34ec7c88b0b87ad398a6;Parent=5cd202d0a717a17b;Sampled=0;lineage=bf371b33:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c242c974a465288488c7876cabca7752.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C2', 'X-Amz-Cf-Id': '3BlO0HK6da85v7ELgoAR996JOGf1VQK6PQPQBNxIbCaaFGUhzmY19A=='})
DEBUG MainThread test.integration_test: … with response body b'null'
INFO MainThread test.integration_test: Making PUT request to 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact'
DEBUG MainThread test.integration_test: … without request body
INFO MainThread test.integration_test: Got 301 response after 0.124s from PUT to https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact
DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '4', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Mar 2024 19:17:43 GMT', 'x-amzn-RequestId': '20327a34-eb07-4a53-8712-5d36df200780', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'X-Frame-Options': 'DENY', 'x-amz-apigw-id': 'U_opoGKrIAMEZxg=', 'X-Content-Type-Options': 'nosniff', 'Location': 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files/k8QgjplizeaDmhOW8B-KdfrlaY1v9sLROoDfJLzTEoBmr5UAAQ==', 'Retry-After': '1', 'X-Amzn-Trace-Id': 'Root=1-65fc87d6-05b5a08b0cc9bade78c45ffb;Parent=284653c74bfb2cbd;Sampled=0;lineage=bf371b33:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c242c974a465288488c7876cabca7752.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C2', 'X-Amz-Cf-Id': '3I5zzJloaMiBWR-k-20hMOJlMeCLMeTVRVFp9rWS-cmMjkQeY0-6LA=='})
DEBUG MainThread test.integration_test: … with response body b'null'
INFO MainThread test.integration_test: Making PUT request to 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact'
DEBUG MainThread test.integration_test: … without request body
INFO MainThread test.integration_test: Got 301 response after 0.093s from PUT to https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact
DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '4', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Mar 2024 19:17:43 GMT', 'x-amzn-RequestId': 'cf6ae710-9177-4816-a298-e150c4acb05d', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'X-Frame-Options': 'DENY', 'x-amz-apigw-id': 'U_optF8OIAMEfng=', 'X-Content-Type-Options': 'nosniff', 'Location': 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files/k8QgjplizeaDmhOW8B-KdfrlaY1v9sLROoDfJLzTEoBmr5UAAQ==', 'Retry-After': '1', 'X-Amzn-Trace-Id': 'Root=1-65fc87d7-74dc8f685d2ff6e41dd24d0f;Parent=630c92a2ea7f2d8d;Sampled=0;lineage=bf371b33:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c242c974a465288488c7876cabca7752.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C2', 'X-Amz-Cf-Id': 'ocCmtqKFy9jevL8JiAzQa7n-ZbYgo2oc_TlhO5PV9lPvAEYjkJfpsA=='})
DEBUG MainThread test.integration_test: … with response body b'null'
INFO MainThread test.integration_test: Making PUT request to 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact'
DEBUG MainThread test.integration_test: … without request body
INFO MainThread test.integration_test: Got 301 response after 0.108s from PUT to https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact
DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '4', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Mar 2024 19:17:43 GMT', 'x-amzn-RequestId': '1501ae03-9e89-432a-a7e6-244e80cdfe4f', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'X-Frame-Options': 'DENY', 'x-amz-apigw-id': 'U_opxGXToAMECPA=', 'X-Content-Type-Options': 'nosniff', 'Location': 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files/k8QgjplizeaDmhOW8B-KdfrlaY1v9sLROoDfJLzTEoBmr5UAAQ==', 'Retry-After': '1', 'X-Amzn-Trace-Id': 'Root=1-65fc87d7-386f41f333660d520c48665f;Parent=24f30b9c41a3699e;Sampled=0;lineage=bf371b33:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 c242c974a465288488c7876cabca7752.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C2', 'X-Amz-Cf-Id': 'nuH85sMcSF3hJghIwH4XREsXUf9xfoH9g3jAiELdlr768FGSVV1GvQ=='})
DEBUG MainThread test.integration_test: … with response body b'null'
INFO MainThread test.integration_test: Making PUT request to 'https://service.sandbox.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp3-it&filters=%7B%22fileSize%22%3A+%7B%22within%22%3A+%5B%5B0%2C+1802587988638%5D%5D%7D%7D&format=compact'
DEBUG MainThread test.integration_test: … without request body
INFO MainThread test.integration_test: Failed sub-test [manifest_tagging_race] {'catalog': 'dcp3-it', 'format': <ManifestFormat.compact: 'compact'>}
```

One can observe that no response body is logged for requests that cause the test to fail.

**Comment by achave11-ucsc** [comment]
A response body resulting from, say a 500 status response, should be included as part of this logs.

**Comment by hannes-ucsc** [comment]
Add unit test to reproduce, using an actual HTTP server as a fixture.

For the fix, provide a decorating HTTP client `ServerErrorRetryClient` that retries on 500, 502 and 503 status codes. Modify the default `http_client` factory function to wrap the logging client with `ServerErrorRetryClient`. 

This will introduce tension with the `LimitedRetryClient`, which specifies `status_force_list={500, 502, 503}`, and any other use of `http_client().request()` that uses a non-empty `status_force_list`. Consider, changing `LimitedRetryClient` to pass `status_force_list={}` and wrapping every instance of `LimitedRetryClient` in an instance of `ServerErrorRetryClient`. `ServerErrorRetryClient.request()` should ensure that `status_force_list` is None or the empty set, and pass `status_force_list={}` to the decorated client's `request()` method.
