### ISSUE TITLE
Transient ServiceUnavailableError from registry.api.identifiers.org causes IT failure

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6120]
https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/25287

```
…
2024-04-03 08:20:13,447    INFO MainThread test.integration_test: Beginning sub-test [repository_files] {'catalog': 'anvil5-it'}
2024-04-03 08:20:13,448    INFO MainThread test.integration_test: Making GET request to '[https://service.hammerbox.explore.anvilproject.org/fetch/repository/files/27b72219-2683-46e2-be7f-1126beb39822?catalog=anvil5-it&version=2022-06-01T00%3A00%3A00.000000Z'](https://service.hammerbox.explore.anvilproject.org/fetch/repository/files/27b72219-2683-46e2-be7f-1126beb39822?catalog=anvil5-it&version=2022-06-01T00%3A00%3A00.000000Z%27)
2024-04-03 08:20:13,448   DEBUG MainThread test.integration_test: … without request body
2024-04-03 08:20:48,540    INFO MainThread test.integration_test: Failed sub-test [repository_files] {'catalog': 'anvil5-it'}
  test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [repository_files] (catalog='anvil5-it') ... ERROR
…
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [repository_files] (catalog='anvil5-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 427, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1021, in _test_repository_files
    response = self._get_url_unchecked(GET, file_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 848, in _get_url_unchecked
    response = http.request(method=method,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 77, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/request.py", line 99, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 68, in urlopen
    response = super().urlopen(method, url, body=body, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/build/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='service.hammerbox.explore.anvilproject.org', port=443): Max retries exceeded with url: /fetch/repository/files/27b72219-2683-46e2-be7f-1126beb39822?catalog=anvil5-it&version=2022-06-01T00%3A00%3A00.000000Z (Caused by ResponseError('too many 503 error responses'))
----------------------------------------------------------------------
```

[CloudWatch logs (anvildev)](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-86400~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*0a*23*20*7c*20filter*20*40message*20like*20*2f27b72219-2683-46e2-be7f-1126beb39822*2f*0a*7c*20filter*20*40requestId*20in*20*5b*27846e8709-f2ba-4113-a923-b0e0fb865f75*27*2c*20*271de51dc9-916c-4fd7-8438-84e94739211b*27*2c*20*27d609e6ce-2132-4047-bc83-286b08097780*27*2c*20*2782e0f91f-1474-488b-984b-6d98fc0bd82f*27*2c*20*2775fcf8e2-a59f-4475-b52a-078fc8886115*27*2c*20*276cf04ba9-b3d6-489c-8508-284be8833822*27*5d*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20200~queryId~'c02b64b9-528c-411d-a80e-ad4f7333eeb8~source~(~'*2faws*2flambda*2fazul-service-hammerbox))):

```
# /aws/lambda/azul-service-hammerbox

fields @timestamp, @message
# | filter @message like /27b72219-2683-46e2-be7f-1126beb39822/
| filter @requestId in ['846e8709-f2ba-4113-a923-b0e0fb865f75', '1de51dc9-916c-4fd7-8438-84e94739211b', 'd609e6ce-2132-4047-bc83-286b08097780', '82e0f91f-1474-488b-984b-6d98fc0bd82f', '75fcf8e2-a59f-4475-b52a-078fc8886115', '6cf04ba9-b3d6-489c-8508-284be8833822']
| sort @timestamp asc
| limit 200
```

```
[
    {
        "@timestamp": "2024-04-03 08:20:13.476",
        "@message": "START RequestId: 846e8709-f2ba-4113-a923-b0e0fb865f75 Version: $LATEST\n"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.477",
        "@message": "[INFO]\t2024-04-03T08:20:13.476Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.chalice\tReceived GET request for '/fetch/repository/files/27b72219-2683-46e2-be7f-1126beb39822', with {\"query\": {\"catalog\": \"anvil5-it\", \"version\": \"2022-06-01T00:00:00.000000Z\"}, \"headers\": {\"accept-encoding\": \"identity\", \"cloudfront-forwarded-proto\": \"https\", \"cloudfront-is-desktop-viewer\": \"true\", \"cloudfront-is-mobile-viewer\": \"false\", \"cloudfront-is-smarttv-viewer\": \"false\", \"cloudfront-is-tablet-viewer\": \"false\", \"cloudfront-viewer-asn\": \"14618\", \"cloudfront-viewer-country\": \"US\", \"host\": \"service.hammerbox.explore.anvilproject.org\", \"user-agent\": \"python-urllib3/1.26.18\", \"via\": \"1.1 e6c353101750d150139bda8d95719802.cloudfront.net (CloudFront)\", \"x-amz-cf-id\": \"Q6KvBy5lo7auDfBxWh2_ap263jk9xabtNmOlASeiRvdRyjUzdj5yIA==\", \"x-amzn-trace-id\": \"Root=1-660d113d-752e642a6dbb1a2f689ab316\", \"x-forwarded-for\": \"35.168.152.160, 15.158.50.53\", \"x-forwarded-port\": \"443\", \"x-forwarded-proto\": \"https\"}}."
    },
    {
        "@timestamp": "2024-04-03 08:20:13.477",
        "@message": "[INFO]\t2024-04-03T08:20:13.477Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.chalice\tDid not authenticate request."
    },
    {
        "@timestamp": "2024-04-03 08:20:13.489",
        "@message": "[INFO]\t2024-04-03T08:20:13.489Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.boto3\tdynamodb.GetItem:\tMaking POST request to https://dynamodb.us-east-1.amazonaws.com/"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.489",
        "@message": "[INFO]\t2024-04-03T08:20:13.489Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.boto3\tdynamodb.GetItem:\t… with request body b'{\"TableName\": \"azul-sources_cache_by_auth-hammerbox\", \"Key\": {\"identity\": {\"S\": \"anvil5-it:\"}}, \"ProjectionExpression\": \"sour...'"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.495",
        "@message": "[INFO]\t2024-04-03T08:20:13.495Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.boto3\tdynamodb.GetItem:\tGot 200 response"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.495",
        "@message": "[INFO]\t2024-04-03T08:20:13.495Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.boto3\tdynamodb.GetItem:\t… with response body b'{\"Item\":{\"expiration\":{\"N\":\"1712132429\"},\"sources\":{\"S\":\"[\\\\\"1d28b559-e71f-49c7-a94d-4caa5d7892c1\\\\\", \\\\\"9a362ef6-abbb-4094-97fb...'"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.497",
        "@message": "[INFO]\t2024-04-03T08:20:13.497Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\telasticsearch\tMaking POST request to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil5-it_files_aggregate/_search"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.497",
        "@message": "[INFO]\t2024-04-03T08:20:13.497Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\telasticsearch\t… with request body b'{\"query\":{\"bool\":{\"must\":[{\"constant_score\":{\"filter\":{\"terms\":{\"contents.files.uuid.keyword\":[\"27b72219-2683-46e2-be7f-1126b...'"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.508",
        "@message": "[INFO]\t2024-04-03T08:20:13.508Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\telasticsearch\tGot 200 response after 0.011s from POST to https://vpc-azul-index-hammerbox-srwikb4z42wnpzxq2f56y36icu.us-east-1.es.amazonaws.com:443/azul_v2_hammerbox_anvil5-it_files_aggregate/_search"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.508",
        "@message": "[INFO]\t2024-04-03T08:20:13.508Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\telasticsearch\t… with response body '{\"took\":2,\"timed_out\":false,\"_shards\":{\"total\":1,\"successful\":1,\"skipped\":0,\"failed\":0},\"hits\":{\"total\":{\"value\":1,\"relation\":\"…'"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.510",
        "@message": "[INFO]\t2024-04-03T08:20:13.510Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.drs\tMaking GET request to 'https://registry.api.identifiers.org/restApi/namespaces/search/findByPrefix?prefix=drs.anv0'"
    },
    {
        "@timestamp": "2024-04-03 08:20:13.510",
        "@message": "[DEBUG]\t2024-04-03T08:20:13.510Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.drs\t… without request body"
    },
    {
        "@timestamp": "2024-04-03 08:20:18.553",
        "@message": "[DEBUG]\t2024-04-03T08:20:18.553Z\t846e8709-f2ba-4113-a923-b0e0fb865f75\tazul.chalice\tReturning 503 response with headers {\"Access-Control-Allow-Origin\": \"*\", \"Access-Control-Allow-Headers\": \"Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key\", \"Strict-Transport-Security\": \"max-age=31536000; includeSubDomains\", \"X-Content-Type-Options\": \"nosniff\", \"X-Frame-Options\": \"DENY\"}. See next line for the first 1024 characters of the body.\n{\"Code\": \"ServiceUnavailableError\", \"Message\": \"No response from https://registry.api.identifiers.org/restApi/namespaces/search/findByPrefix?prefix=drs.anv0 within 5 seconds\"}"
    },
    {
        "@timestamp": "2024-04-03 08:20:18.554",
        "@message": "END RequestId: 846e8709-f2ba-4113-a923-b0e0fb865f75\n"
    },
    {
        "@timestamp": "2024-04-03 08:20:18.554",
        "@message": "REPORT RequestId: 846e8709-f2ba-4113-a923-b0e0fb865f75\tDuration: 5078.70 ms\tBilled Duration: 5079 ms\tMemory Size: 2048 MB\tMax Memory Used: 181 MB\t\n"
    },
…
]
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Let's wait and see what the prevalence is."

**Comment by achave11-ucsc** [comment]
This happened again during `hammebox` build https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/26295
for the service request URL:
```
https://service.hammerbox.explore.anvilproject.org/fetch/repository/files/166c17ab-03ab-410c-8450-40475e4cd4b2?catalog=anvil4-it&version=2022-06-01T00%3A00%3A00.000000Z
```

**Comment by achave11-ucsc** [comment]
Recurrence for `anvilprod`:
https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/26312

[CW](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-04-19T05*3a54*3a40.229Z~start~'2024-04-19T05*3a40*3a47.811Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40requestId*20like*20*2f6cfcc937*7cb4f63c0d*7c2909eb9b*7c24e6446a*7c509078f3*7cf5e88340*7cb41d7025*2f*0a*7c*20filter*20*40message*20like*20*2fReturning*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*201000~queryId~'fe8b3a7e63edcce-be78b8dd-41284-ddcca192-51e228ecfdd3657e5caf1f~source~(~'*2faws*2flambda*2fazul-service-anvilprod))) (for request IDs matching `/fetch/repository/files/02643ddd-7264-4af5-ad87-528363d5beb4?catalog=anvil5-it&version=2022-06-01T00%3A00%3A00.000000Z`):
```
{"Code": "ServiceUnavailableError", "Message": "No response from https://registry.api.identifiers.org/restApi/resources/search/findAllByNamespaceId?id=3571 within 5 seconds"}
```

**Comment by hannes-ucsc** [comment]
Rare.

**Comment by achave11-ucsc** [comment]
`anvildev` IT:
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/59262/raw
