### ISSUE TITLE
TDR's enumerateSnapshots endpoint occasionally returns 401

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6177]
This happened for `integration_test.IndexingIntegrationTest.test_snapshot_listing` failing  in a recent [develop build](https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/) in the `anvilprod` GitLab.

```
test_snapshot_listing (integration_test.IndexingIntegrationTest.test_snapshot_listing)
Test with a small page size to be sure paging works ... 2024-04-19 01:55:37,818    INFO MainThread test.integration_test: Using random seed 6124664024619706652
2024-04-19 01:55:37,819    INFO MainThread azul.terra: Making GET request to 'https://data.terra.bio/api/repository/v1/snapshots?offset=0&limit=5&sort=created_date&direction=asc'
2024-04-19 01:55:37,820   DEBUG MainThread azul.terra: … without request body
…
2024-04-19 01:58:39,208    INFO MainThread azul.terra: Got 200 response after 1.721s from GET to https://data.terra.bio/api/repository/v1/snapshots?offset=970&limit=5&sort=created_date&direction=asc
2024-04-19 01:58:39,208   DEBUG MainThread azul.terra: … with response headers HTTPHeaderDict({'Date': 'Fri, 19 Apr 2024 01:58:38 GMT', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Referer,X-App-Id,Origin', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT,PATCH,OPTIONS,HEAD', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000;includeSubDomains', 'Cache-Control': 'no-cache,no-store,must-revalidate', 'X-Request-ID': 'eyYxKZDe', 'Content-Type': 'application/json', 'Content-Length': '4317', 'Vary': 'Accept-Encoding,Origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
2024-04-19 01:58:39,208   DEBUG MainThread azul.terra: … with response body b'{"total":984,"filteredTotal":984,"items":[{"id":"8c5552fc-2837-4f84-86bb-2775ef5f205a","name":"hca_prod_750b455ae3cf472195818...'
2024-04-19 01:58:39,209    INFO MainThread azul.terra: Making GET request to 'https://data.terra.bio/api/repository/v1/snapshots?offset=975&limit=5&sort=created_date&direction=asc'
2024-04-19 01:58:39,209   DEBUG MainThread azul.terra: … without request body
2024-04-19 01:58:54,313    INFO MainThread azul.terra: Got 401 response after 15.104s from GET to https://data.terra.bio/api/repository/v1/snapshots?offset=975&limit=5&sort=created_date&direction=asc
2024-04-19 01:58:54,313   DEBUG MainThread azul.terra: … with response headers HTTPHeaderDict({'Date': 'Fri, 19 Apr 2024 01:58:53 GMT', 'Server': 'Apache', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Referer,X-App-Id,Origin', 'Access-Control-Allow-Methods': 'GET,POST,DELETE,PUT,PATCH,OPTIONS,HEAD', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000;includeSubDomains', 'Cache-Control': 'no-cache,no-store,must-revalidate', 'X-Request-ID': '6dnwBrwd', 'Content-Type': 'application/json', 'Content-Length': '1516', 'Vary': 'Origin', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
2024-04-19 01:58:54,313   DEBUG MainThread azul.terra: … with response body b'{"message":"Message: \\nHTTP response code: 401\\nHTTP response body: <!DOCTYPE HTML PUBLIC \\"-//IETF//DTD HTML 2.0//EN\\">\\n<ht...'
ERROR
…
======================================================================
ERROR: test_snapshot_listing (integration_test.IndexingIntegrationTest.test_snapshot_listing)
Test with a small page size to be sure paging works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 233, in wrapped
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/test/integration_test.py", line 458, in test_snapshot_listing
    paged_snapshots = self._public_tdr_client.snapshot_names_by_id()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/terra.py", line 594, in snapshot_names_by_id
    response = self._check_response(endpoint, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builds/ucsc/azul/src/azul/terra.py", line 544, in _check_response
    raise self._insufficient_access(str(endpoint))
azul.RequirementError: The service account (SA) 'azul-ucsc-1-public-anvilprod@platform-anvil-prod.iam.gserviceaccount.com' is not authorized to access https://data.terra.bio/api/repository/v1/snapshots?offset=975&limit=5&sort=created_date&direction=asc or that resource does not exist. Make sure that it exists, that the SA is registered with SAM and has been granted read access to the resource.

----------------------------------------------------------------------
```

**Comment by achave11-ucsc** [comment]
This seems like a different version of #4552

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "I'd like to sit on this for a while in order to establish how prevalent it is."
