### ISSUE TITLE
BigQuery slot purchase fails in `tempdev`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6263]
https://gitlab.temp.gi.ucsc.edu/ucsc/azul/-/jobs/68

```
2024-05-15 03:42:40,522    INFO MainThread __main__: Queuing notifications for reindexing ...
2024-05-15 03:42:40,533    INFO MainThread azul.deployment: Allocated new Boto3 client for 'secretsmanager' with ID 140436782882640
2024-05-15 03:42:41,100    INFO MainThread azul.bigquery_reservation: Purchasing 100 BigQuery slots in location 'us-central1'
Traceback (most recent call last):
  File "/build/.venv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "The specified flat rate commitment plan is beyond end of sale and no longer available. Please use an Editions commitment plan."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.115.95:443 {created_time:"2024-05-15T03:42:41.382229115+00:00", grpc_status:9, grpc_message:"The specified flat rate commitment plan is beyond end of sale and no longer available. Please use an Editions commitment plan."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/builds/ucsc/azul/scripts/reindex.py", line 206, in <module>
    main(sys.argv[1:])
  File "/builds/ucsc/azul/scripts/reindex.py", line 189, in main
    reservation.activate()
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 123, in activate
    self._ensure_capacity_commitment()
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 142, in _ensure_capacity_commitment
    self._create_capacity_commitment(self.slots)
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 192, in _create_capacity_commitment
    commitment = self._client.create_capacity_commitment(capacity_commitment=commitment,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/google/cloud/bigquery_reservation_v1/services/reservation_service/client.py", line 1206, in create_capacity_commitment
    response = rpc(
               ^^^^
  File "/build/.venv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/build/.venv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.FailedPrecondition: 400 The specified flat rate commitment plan is beyond end of sale and no longer available. Please use an Editions commitment plan.
make: *** [Makefile:128: reindex] Error 1
```

**Comment by hannes-ucsc** [comment]
BigQuery changed their BigQuery pricing model last year which essentially eliminated flat rate pricing and replaced it with what they call "Editions" pricing. Commitments can now only be purchased for one year or longer. On-demand pricing went up by 25%. Reservations can still be made and with the patch below, the `.activate()` method succeeds:

```diff
Index: src/azul/bigquery_reservation.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/bigquery_reservation.py b/src/azul/bigquery_reservation.py
--- a/src/azul/bigquery_reservation.py	(revision 73dd7dcca8d3054a55b662ab72ca238fd9a45e5b)
+++ b/src/azul/bigquery_reservation.py	(date 1715793425774)
@@ -120,7 +120,6 @@
             return self.reservation.update_time.timestamp()
 
     def activate(self) -> None:
-        self._ensure_capacity_commitment()
         self._create_reservation()
         self._assign_slots()
         self.refresh()
```

The GCP project for `tempdev` (`platform-temp-dev`) was created recently. I suspect this is the reason we are observing this behavior only in that deployment. It appears that our existing GCP projects were somehow grand-fathered in but I couldn't find any documentation by Google about that distinction with respect to BigQuery pricing.

I am currently running a reindex with this patch in order to determine what the cost impact of not having a commitment is.

Update: AS of now the BQ cost is $6.65 for 05/14 and $91 for 05/15. The reindex ran for an hour and a half from 05/14 22:45 to 05/15 00:15. The slot utilization was averaging 20% during that time. It looks like having a reservation is continually accruing charges, whether the slots are utilized or not. Also, the reservation seems to default to "Enterprise edition", which is $6 for 100 slot hours. The old flex slot commitment was $4 for 100 slot hours. The "Standard edition" plan is $4 for 100 slot hours.

https://cloud.google.com/bigquery/pricing

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
The Google Cloud billing page indicates that our capacity purchasing code has been inadvertently creating a reservation under the more expensive "Enterprise edition" plan by default since Google changed their pricing, and apparently the default. 

Spike to verify that claim by purchasing slots (on `develop`) in `dev` and `anvildev`. The plan type is evident in the Google Cloud console for BigQuery. Please collect evidence, e.g., screenshots, as ususal.

Spike to confirm whether the patch above works in `anvildev` and `dev` and what plan the resulting reservation is for.

Spike to investigate what change would be needed to create a reservation using the cheaper "Standard edition" plan.

Don't forget to any sell slots, reservations and commitments when done.

**Comment by nadove-ucsc** [comment]
> Spike to verify that claim by purchasing slots (on develop) in dev and anvildev. The plan type is evident in the Google Cloud console for BigQuery. Please collect evidence, e.g., screenshots, as ususal.

Confirmed that we are purchasing slots under the "Enterprise edition" plan.

Purchased slots by running 
```
>>> from azul.bigquery_reservation import BigQueryReservation
>>> b = BigQueryReservation()
>>> b.is_active
>>> b.activate()
```

Result in `dev`:

![Screenshot from 2024-05-22 13-53-38](https://github.com/DataBiosphere/azul/assets/48401926/ce681b05-3848-45c5-bb1e-aa57fed0dbc2)

Result in `anvildev`:

![image](https://github.com/DataBiosphere/azul/assets/48401926/89d29c0f-ca3a-4240-938e-f7aa48ac6da9)

**Comment by nadove-ucsc** [comment]
> Spike to confirm whether the patch above works in anvildev and dev and what plan the resulting reservation is for.

The patch fails because `BigQueryReservation` raises an exception when it detects that no capacity commitment has been created:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/bigquery_reservation.py", line 128, in activate
    raise RuntimeError('Failed to activate slots')
RuntimeError: Failed to activate slots
```

The reservation and assignment are created successfully however. It still uses the Enterprise Edition:

![image](https://github.com/DataBiosphere/azul/assets/48401926/a886b2a9-6e2d-4646-a800-51ff21597a2e)

```
>>> b.reservation
name: "projects/platform-hca-dev/locations/us-central1/reservations/default"
slot_capacity: 100
creation_time {
  seconds: 1716411934
  nanos: 422662000
}
update_time {
  seconds: 1716411934
  nanos: 422662000
}
edition: ENTERPRISE
```

Same results in `anvildev`.

**Comment by nadove-ucsc** [comment]
> Spike to investigate what change would be needed to create a reservation using the cheaper "Standard edition" plan.

Specifying the edition is as simple as 

```diff
diff --git a/src/azul/bigquery_reservation.py b/src/azul/bigquery_reservation.py
index 0998441b..8e1a765a 100644
--- a/src/azul/bigquery_reservation.py
+++ b/src/azul/bigquery_reservation.py
@@ -6,6 +6,7 @@ from typing import (
 
 from google.cloud.bigquery_reservation_v1 import (
     Assignment,
+    Edition,
     Reservation,
     ReservationServiceClient,
 )
@@ -132,6 +133,7 @@ class BigQueryReservation:
         self._refresh('reservation')
         if self.reservation is None:
             reservation = Reservation(dict(slot_capacity=self.slots,
+                                           edition=Edition.STANDARD,
                                            ignore_idle_slots=False))
             if self.dry_run:
                 log.info('Would reserve %d BigQuery slots in location %r, reservation ID: %r',
```

However this forces a chain reaction of other configuration changes to avoid 400 errors due to restrictions placed on the standard edition. We can't directly specify a slot capacity for the reservation:

```
>>> b.activate();
Traceback (most recent call last):
...
google.api_core.exceptions.InvalidArgument: 400 STANDARD Reservation can not have baseline slot capacity.
```

... or share idle slots:

```
google.api_core.exceptions.InvalidArgument: 400 STANDARD Reservation can not share idle slots, please set ignore_idle_slots to true.
```

...and must instead use the [`autoscale` feature](https://cloud.google.com/bigquery/docs/slots-autoscaling-intro):

```
google.api_core.exceptions.InvalidArgument: 400 Reservation slot capacity and autoscale max slots are both 0. This is only allowed if ignore_idle_slots is false.
```

This appears to work:

```diff
Subject: [PATCH] Purchase slots using standard edition
---
Index: src/azul/bigquery_reservation.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/bigquery_reservation.py b/src/azul/bigquery_reservation.py
--- a/src/azul/bigquery_reservation.py	(revision daf9aa696d0e20f1962d6df2f185291e65b36e39)
+++ b/src/azul/bigquery_reservation.py	(date 1716414233588)
@@ -8,6 +8,7 @@
 from google.cloud.bigquery_reservation_v1 import (
     Assignment,
     CapacityCommitment,
+    Edition,
     Reservation,
     ReservationServiceClient,
 )
@@ -120,16 +121,15 @@
             return self.reservation.update_time.timestamp()
 
     def activate(self) -> None:
-        self._ensure_capacity_commitment()
         self._create_reservation()
         self._assign_slots()
         self.refresh()
         if not self.dry_run:
             if not self.is_active:
                 raise RuntimeError('Failed to activate slots')
-            if self.capacity_commitment.slot_count < self.slots:
+            if self.reservation.autoscale.max_slots < self.slots:
                 raise RuntimeError('Failed to acquire enough slots',
-                                   self.capacity_commitment.slot_count,
+                                   self.reservation.autoscale.max_slots,
                                    self.slots)
 
     def _ensure_capacity_commitment(self) -> None:
@@ -237,22 +237,23 @@
         """
         self._refresh('reservation')
         if self.reservation is None:
-            reservation = Reservation(dict(slot_capacity=self.slots,
-                                           ignore_idle_slots=False))
+            reservation = Reservation(dict(edition=Edition.STANDARD,
+                                           autoscale=Reservation.Autoscale(dict(max_slots=self.slots)),
+                                           ignore_idle_slots=True))
             if self.dry_run:
                 log.info('Would reserve %d BigQuery slots in location %r, reservation ID: %r',
-                         reservation.slot_capacity, self.location, self._reservation_id)
+                         reservation.autoscale.max_slots, self.location, self._reservation_id)
             else:
                 log.info('Reserving %d BigQuery slots in location %r, reservation ID: %r',
-                         reservation.slot_capacity, self.location, self._reservation_id)
+                         reservation.autoscale.max_slots, self.location, self._reservation_id)
                 reservation = self._client.create_reservation(reservation=reservation,
                                                               reservation_id=self._reservation_id,
                                                               parent=self._reservation_parent_path)
                 log.info('Reserved %d BigQuery slots in location %r, reservation name: %r',
-                         reservation.slot_capacity, self.location, reservation.name)
+                         reservation.autoscale.max_slots, self.location, reservation.name)
                 self.reservation = reservation
         else:
-            current_capacity = self.reservation.slot_capacity
+            current_capacity = self.reservation.autoscale.max_slots
             log.info('Reservation with capacity %d already created in location %r',
                      current_capacity, self.location)
             if current_capacity < self.slots:
@@ -261,12 +262,12 @@
                     log.info('Would increase reservation capacity to %d', self.slots)
                 else:
                     log.info('Increasing reservation capacity to %d', self.slots)
-                    self.reservation.slot_capacity = self.slots
+                    self.reservation.autoscale.max_slots = self.slots
                     self.reservation = self._client.update_reservation(
                         reservation=self.reservation,
-                        update_mask='slotCapacity'
+                        update_mask='autoscale'
                     )
-                    log.info('Reservation now has capacity %d', self.reservation.slot_capacity)
+                    log.info('Reservation now has capacity %d', self.reservation.autoscale.max_slots)
 
     def _assign_slots(self) -> None:
         """
```

![image](https://github.com/DataBiosphere/azul/assets/48401926/6d35a159-2de9-4bf1-884e-f5df31dfb1f1)

**Comment by nadove-ucsc** [comment]
> Don't forget to any sell slots, reservations and commitments when done.

Done.

**Comment by achave11-ucsc** [comment]
Assignee to continue spike in tempdev deployment.

**Comment by hannes-ucsc** [comment]
Can't spike this until pen test is over.

**Comment by hannes-ucsc** [comment]
I'm getting

```
from azul.bigquery_reservation import BigQueryReservation
r = BigQueryReservation()
r.activate()
Traceback (most recent call last):
  File "/Users/hannes/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Users/hannes/workspace/hca/azul.hannes2.local/src/azul/bigquery_reservation.py", line 129, in activate
    raise RuntimeError('Failed to activate slots')
RuntimeError: Failed to activate slots
```

It seems like the patch is incomplete. The `is_active` property returns `None` because `capacity_commitment` attribute is `None` because the patch removes the method call that provisions that attribute.

<img width="1073" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/10054e36-f598-4513-be1f-81cc95c46910">

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by nadove-ucsc** [comment]
I agree that the above patch was incomplete. Now that we no longer create a capacity commitment, we can remove all references to it from the class. This patch was tested by purchasing and selling slots, verbatim:

```diff
Subject: [PATCH] Purchase slots using standard edition
---
Index: src/azul/bigquery_reservation.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/bigquery_reservation.py b/src/azul/bigquery_reservation.py
--- a/src/azul/bigquery_reservation.py	(revision de54dcb6841362843f0b90cf9bd5a251155db1a6)
+++ b/src/azul/bigquery_reservation.py	(date 1719558150608)
@@ -1,5 +1,4 @@
 import logging
-import time
 from typing import (
     Optional,
     Union,
@@ -8,6 +7,7 @@
 from google.cloud.bigquery_reservation_v1 import (
     Assignment,
     CapacityCommitment,
+    Edition,
     Reservation,
     ReservationServiceClient,
 )
@@ -48,7 +48,6 @@
         'assignment': '/reservations/-'
     }
 
-    capacity_commitment: Optional[CapacityCommitment]
     reservation: Optional[Reservation]
     assignment: Optional[Assignment]
     location: str
@@ -99,7 +98,6 @@
     @property
     def is_active(self) -> Optional[bool]:
         resource_statuses = {
-            self.capacity_commitment is not None,
             self.reservation is not None,
             self.assignment is not None
         }
@@ -120,139 +118,40 @@
             return self.reservation.update_time.timestamp()
 
     def activate(self) -> None:
-        self._ensure_capacity_commitment()
         self._create_reservation()
         self._assign_slots()
         self.refresh()
         if not self.dry_run:
             if not self.is_active:
                 raise RuntimeError('Failed to activate slots')
-            if self.capacity_commitment.slot_count < self.slots:
+            if self.reservation.autoscale.max_slots < self.slots:
                 raise RuntimeError('Failed to acquire enough slots',
-                                   self.capacity_commitment.slot_count,
+                                   self.reservation.autoscale.max_slots,
                                    self.slots)
 
-    def _ensure_capacity_commitment(self) -> None:
-        """
-        Idempotently purchase capacity commitment, ensuring that the number of
-        reserved slots is sufficient for the current configuration.
-        """
-        self._refresh('capacity_commitment')
-        if self.capacity_commitment is None:
-            self._create_capacity_commitment(self.slots)
-        else:
-            current_capacity = self.capacity_commitment.slot_count
-            log.info('Slot commitment with %d slots already purchased in location %r',
-                     current_capacity, self.location)
-            if current_capacity < self.slots:
-                deficit = self.slots - current_capacity
-                log.info('Slot deficit is %d', deficit)
-                # To increase the capacity of an existing commitment, we must
-                # create a new commitment and then merge it with the old one.
-                old_commitment = self.capacity_commitment
-                self._create_capacity_commitment(deficit)
-                new_commitment = self.capacity_commitment
-                if self.dry_run:
-                    assert old_commitment is new_commitment
-                    log.info('Would merge capacity commitments in location %r', self.location)
-                else:
-                    assert old_commitment.name != new_commitment.name
-                    log.info('Merging capacity commitments {%r, %r}',
-                             old_commitment.name, new_commitment.name)
-
-                    def extract_id(commitment: CapacityCommitment) -> str:
-                        parent, resource_type, id = commitment.name.rsplit('/', 2)
-                        assert parent == self._reservation_parent_path
-                        assert resource_type == 'capacityCommitments'
-                        return id
-
-                    self.capacity_commitment = self._client.merge_capacity_commitments(
-                        parent=self._reservation_parent_path,
-                        capacity_commitment_ids=list(map(extract_id, [old_commitment, new_commitment]))
-                    )
-                    log.info('Merged capacity commitments {%r, %r} to create %r with %d total slots',
-                             old_commitment.name, new_commitment.name, self.capacity_commitment.name,
-                             self.capacity_commitment.slot_count)
-            elif current_capacity > self.slots:
-                log.warning('Existing slot commitment has more slots than requested; '
-                            'excessive costs may be incurred. If a smaller capacity '
-                            'is desired, it must be reduced manually.')
-            else:
-                log.info('No purchase necessary')
-
-    def _create_capacity_commitment(self, slots: int) -> None:
-        commitment = CapacityCommitment(dict(slot_count=slots,
-                                             plan=CapacityCommitment.CommitmentPlan.FLEX))
-        if self.dry_run:
-            log.info('Would purchase %d BigQuery slots in location %r',
-                     commitment.slot_count, self.location)
-        else:
-            log.info('Purchasing %d BigQuery slots in location %r',
-                     commitment.slot_count, self.location)
-            commitment = self._client.create_capacity_commitment(capacity_commitment=commitment,
-                                                                 parent=self._reservation_parent_path)
-            log.info('Purchased %d BigQuery slots in location %r, commitment name: %r',
-                     commitment.slot_count, self.location, commitment.name)
-            # Record state before waiting for activation so that we can delete it on failure
-            self.capacity_commitment = commitment
-            self.capacity_commitment = self._await_active_commitment(commitment)
-
-    def _await_active_commitment(self,
-                                 commitment: CapacityCommitment
-                                 ) -> CapacityCommitment:
-        """
-        Poll for a minute or until commitment is active. Fail gracefully if we
-        are unable to get commitment. See Google's docs for more info:
-        https://cloud.google.com/bigquery/docs/reservations-tasks#purchased_slots_are_pending
-        """
-        start = time.time()
-        deadline = start + 60
-        now = start
-        while commitment.state != commitment.State.ACTIVE:
-            if now > deadline:
-                self.deactivate()
-                log.error('Commitment %r in state %r after %.3fs seconds. '
-                          'Commitment was deleted. Try again later.',
-                          commitment.name, commitment.state.name, now - start)
-                raise RuntimeError('Slot commitment not active in time')
-            elif commitment.state == commitment.State.FAILED:
-                self.deactivate()
-                raise RuntimeError('Slot commitment failed to activate',
-                                   commitment.failure_status)
-            elif commitment.state == commitment.State.PENDING:
-                log.info('Commitment %r pending. Trying again in 10 seconds...',
-                         commitment.name)
-                time.sleep(10)
-                commitment = self._client.get_capacity_commitment(name=commitment.name)
-                now = time.time()
-            else:
-                assert False, commitment.state
-        log.info('Commitment %r is active after %.3fs seconds',
-                 commitment.name, now - start)
-        return commitment
-
     def _create_reservation(self) -> None:
         """
         Idempotently create reservation.
         """
         self._refresh('reservation')
         if self.reservation is None:
-            reservation = Reservation(dict(slot_capacity=self.slots,
-                                           ignore_idle_slots=False))
+            reservation = Reservation(dict(edition=Edition.STANDARD,
+                                           autoscale=Reservation.Autoscale(dict(max_slots=self.slots)),
+                                           ignore_idle_slots=True))
             if self.dry_run:
                 log.info('Would reserve %d BigQuery slots in location %r, reservation ID: %r',
-                         reservation.slot_capacity, self.location, self._reservation_id)
+                         reservation.autoscale.max_slots, self.location, self._reservation_id)
             else:
                 log.info('Reserving %d BigQuery slots in location %r, reservation ID: %r',
-                         reservation.slot_capacity, self.location, self._reservation_id)
+                         reservation.autoscale.max_slots, self.location, self._reservation_id)
                 reservation = self._client.create_reservation(reservation=reservation,
                                                               reservation_id=self._reservation_id,
                                                               parent=self._reservation_parent_path)
                 log.info('Reserved %d BigQuery slots in location %r, reservation name: %r',
-                         reservation.slot_capacity, self.location, reservation.name)
+                         reservation.autoscale.max_slots, self.location, reservation.name)
                 self.reservation = reservation
         else:
-            current_capacity = self.reservation.slot_capacity
+            current_capacity = self.reservation.autoscale.max_slots
             log.info('Reservation with capacity %d already created in location %r',
                      current_capacity, self.location)
             if current_capacity < self.slots:
@@ -261,12 +160,12 @@
                     log.info('Would increase reservation capacity to %d', self.slots)
                 else:
                     log.info('Increasing reservation capacity to %d', self.slots)
-                    self.reservation.slot_capacity = self.slots
+                    self.reservation.autoscale.max_slots = self.slots
                     self.reservation = self._client.update_reservation(
                         reservation=self.reservation,
-                        update_mask='slotCapacity'
+                        update_mask='autoscale'
                     )
-                    log.info('Reservation now has capacity %d', self.reservation.slot_capacity)
+                    log.info('Reservation now has capacity %d', self.reservation.autoscale.max_slots)
 
     def _assign_slots(self) -> None:
         """
```

**Comment by dsotirho-ucsc** [comment]
Assignee to repeat experiment in `tempdev`.

**Comment by hannes-ucsc** [comment]
With the new patch:

<img width="1300" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/0366bfbc-ada3-4498-b170-f936aead26e8">

<img width="1463" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/82ea81cf-c210-46bd-9102-4e24e6238e3f">

<img width="1417" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/802effb5-af81-4f6b-83ba-61fc5f9373be">

<img width="1315" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/8fbe9c72-4d63-4ee7-9dd8-96c57d5deebe">

<img width="1474" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/15e603be-cb9f-4ccd-910f-88f695146952">

<img width="1468" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/2d39271e-d837-4062-92ea-27e9b90face8">

**Comment by hannes-ucsc** [comment]
For demo, review the results of the test described in https://github.com/DataBiosphere/azul/pull/6386#pullrequestreview-2161348425
