### ISSUE TITLE
ReadTimeoutError from TDR causes 500 instead of 503

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6300]
```
[ERROR]	2024-05-28T17:34:23.474Z	16e9350c-4073-4d21-a2c9-282430c9a437	azul-service-prod	Caught exception for path /repository/files/{file_uuid}
Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/python/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/var/lang/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/python/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1917, in _get_view_function_response
    response = view_function(**function_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/app.py", line 1763, in repository_files
    result = _repository_files(file_uuid, fetch=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/app.py", line 1848, in _repository_files
    return app.repository_controller.download_file(catalog=catalog,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/service/repository_controller.py", line 245, in download_file
    download.update(plugin, authentication)
  File "/var/task/azul/plugins/repository/tdr.py", line 268, in update
    access = drs_client.get_object(self.drs_uri,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/drs.py", line 243, in get_object
    return self._get_object(drs_uri, access_method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/drs.py", line 248, in _get_object
    response = self._request(url)
               ^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/drs.py", line 302, in _request
    return self._http_client.request('GET', str(url), redirect=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/request.py", line 77, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/request.py", line 99, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 224, in urlopen
    response = super().urlopen(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 207, in urlopen
    response = super().urlopen(method,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/google/auth/transport/urllib3.py", line 385, in urlopen
    response = self.http.urlopen(
               ^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 68, in urlopen
    response = super().urlopen(method, url, body=body, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/http.py", line 42, in urlopen
    return self._inner.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.terra.bio', port=443): Max retries exceeded with url: /ga4gh/drs/v1/objects/v1_9ed39fa0-d608-4523-91e6-085929becf0d_b47861fc-c439-412f-bb3c-12fd3d5ddacb (Caused by ReadTimeoutError("HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=5)"))
```

```
[DEBUG]	2024-05-28T17:34:23.485Z	16e9350c-4073-4d21-a2c9-282430c9a437	azul.chalice	Returning 500 response with headers {"Content-Type": "text/plain", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key", "Strict-Transport-Security": "max-age=31536000; includeSubDomains", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY", "Cache-Control": "no-store"}. See next line for the first 1024 characters of the body.
Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/python/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/var/lang/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffe
```

**Comment by hannes-ucsc** [comment]
```diff
---
Index: src/azul/http.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/http.py b/src/azul/http.py
--- a/src/azul/http.py	(revision 0e1ced0c37b06c89c6e5da615e25732e6b66f9e5)
+++ b/src/azul/http.py	(date 1716942284315)
@@ -209,7 +209,16 @@
                                        retries=retry,
                                        timeout=timeout,
                                        **kwargs)
-        except urllib3.exceptions.TimeoutError:
+        except (
+            # Many errors deemed retryable by urllib3 appears to be wrapped up
+            # in a MaxRetryError. This design quirk makes it necessary to catch
+            # the underlying TimeoutException as well as the wrapper, since we
+            # can't be sure that every timeout is caught and wrapped. Note that
+            # we've already disabled the raising of MaxRetryError on potentially
+            # retryable HTTP statuses, via `raise_on_status` above.
+            urllib3.exceptions.TimeoutError,
+            urllib3.exceptions.MaxRetryError
+        ):
             raise LimitedTimeoutException(url, timeout)
         else:
             if response.status in retry.status_forcelist:
```

**Comment by hannes-ucsc** [comment]
I recently revamped this code as part of #6083, effectively applying the above patch: https://github.com/DataBiosphere/azul/blame/a25cef4467000857b256d07e7218a5fa5d655939/src/azul/http.py#L244

There is no proof that this will fix the issue but I am happy to speculate in this case. We will get an alarm if a 500 error is returned.
