### ISSUE TITLE
Clamscan service entered failed state

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6599]
[CloudWatch Logs Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-09-23T13*3a20*3a36.000Z~start~'2024-09-23T13*3a20*3a33.000Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20*40message*0a*23*20*7c*20filter*20*40message*20like*20*27clamscan.service*20failed*27*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2010000~queryId~'dced2cde-201b-489a-b2cd-a5dd3765dc90~source~(~'*2faws*2fcwagent*2fazul-gitlab)))
region: us-east-1    
log-group-names: /aws/cwagent/azul-gitlab    
start-time: 2024-09-23T13:20:33.000Z    
end-time: 2024-09-23T13:20:36.000Z    
query-string:
  ```
  fields @timestamp, @message
# | filter @message like 'clamscan.service failed'
| sort @timestamp asc
| limit 10000
  ```
---
| @timestamp | @message |
| --- | --- |
| 2024-09-23 13:20:33.459 | 172.23.3.205 - - [23/Sep/2024:13:20:32 +0000] "POST /api/v4/jobs/request HTTP/1.1" 204 0 "" "gitlab-runner 17.3.1 (17-3-stable; go1.22.5; linux/amd64)" - |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: panic: runtime error: floating point error |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: [signal SIGFPE: floating-point exception code=0x6 addr=0x425b92 pc=0x425b92] |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: goroutine 6 [running]: |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: runtime.GC() |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: /usr/lib/golang/src/runtime/mgc.go:466 +0x3e |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: runtime/debug.freeOSMemory() |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: /usr/lib/golang/src/runtime/mheap.go:1673 +0x13 |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: runtime/debug.FreeOSMemory(...) |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: /usr/lib/golang/src/runtime/debug/garbage.go:104 |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: github.com/containerd/containerd/runtime/v2/shim.setRuntime.func1() |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: /builddir/build/BUILD/containerd-1.7.20-1.amzn2.0.1/src/github.com/containerd/containerd/runtime/v2/shim/shim.go:176 +0x4b |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: created by github.com/containerd/containerd/runtime/v2/shim.setRuntime in goroutine 1 |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: /builddir/build/BUILD/containerd-1.7.20-1.amzn2.0.1/src/github.com/containerd/containerd/runtime/v2/shim/shim.go:174 +0x25 |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: time="2024-09-23T13:20:33.876956320Z" level=info msg="shim disconnected" id=ad68b0f8a88b5242b78b0aa6fef050e9a7d312094ec2d2a63a63b7863f7fc499 namespace=moby |
| 2024-09-23 13:20:33.973 | Sep 23 13:20:33 ip-172-23-0-207 containerd: time="2024-09-23T13:20:33.877056230Z" level=warning msg="cleaning up after shim disconnected" id=ad68b0f8a88b5242b78b0aa6fef050e9a7d312094ec2d2a63a63b7863f7fc499 namespace=moby |
| 2024-09-23 13:20:34.325 | type=CRYPTO_KEY_USER msg=audit(1727097630.800:73203): pid=31923 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:8f:a8:f9:8b:45:27:cb:f7:2f:c5:f0:1f:cb:0b:0a:ff:3b:21:d4:09:f7:f2:04:5d:ac:0f:79:65:2a:e5:41:f2 direction=? spid=31923 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? terminal=? res=success' |
| 2024-09-23 13:20:34.461 | 172.23.1.178 - - [23/Sep/2024:13:20:33 +0000] "POST /api/v4/jobs/request HTTP/1.1" 204 0 "" "gitlab-runner 17.3.1 (17-3-stable; go1.22.5; linux/amd64)" - |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:33 ip-172-23-0-207 containerd: time="2024-09-23T13:20:33.877071250Z" level=info msg="cleaning up dead shim" namespace=moby |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 dockerd: time="2024-09-23T13:20:34.223900391Z" level=info msg="ignoring event" container=ad68b0f8a88b5242b78b0aa6fef050e9a7d312094ec2d2a63a63b7863f7fc499 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 dockerd: time="2024-09-23T13:20:34.225303337Z" level=warning msg="failed to delete container from containerd" container=ad68b0f8a88b5242b78b0aa6fef050e9a7d312094ec2d2a63a63b7863f7fc499 error="task ad68b0f8a88b5242b78b0aa6fef050e9a7d312094ec2d2a63a63b7863f7fc499 not found: not found" |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 kernel: docker0: port 2(vethe8a8519) entered disabled state |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 kernel: veth36cde5f: renamed from eth0 |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 kernel: docker0: port 2(vethe8a8519) entered disabled state |
| 2024-09-23 13:20:34.477 | Sep 23 13:20:34 ip-172-23-0-207 kernel: device vethe8a8519 left promiscuous mode |
| 2024-09-23 13:20:34.575 | type=ANOM_PROMISCUOUS msg=audit(1727097634.300:73204): dev=vethe8a8519 prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295 |
| 2024-09-23 13:20:34.575 | type=SYSCALL msg=audit(1727097634.300:73204): arch=c000003e syscall=44 success=yes exit=32 a0=d a1=c000995ec0 a2=20 a3=0 items=0 ppid=1 pid=4265 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="dockerd" exe="/usr/bin/dockerd" subj=system_u:system_r:unconfined_service_t:s0 key=(null) |
| 2024-09-23 13:20:34.575 | type=PROCTITLE msg=audit(1727097634.300:73204): proctitle=2F7573722F62696E2F646F636B657264002D480066643A2F2F002D2D636F6E7461696E6572643D2F72756E2F636F6E7461696E6572642F636F6E7461696E6572642E736F636B002D2D64656661756C742D756C696D6974006E6F66696C653D33323736383A3635353336 |
| 2024-09-23 13:20:34.728 | Sep 23 13:20:34 ip-172-23-0-207 kernel: docker0: port 2(vethe8a8519) entered disabled state |
| 2024-09-23 13:20:34.728 | Sep 23 13:20:34 ip-172-23-0-207 systemd: clamscan.service: main process exited, code=exited, status=137/n/a |
| 2024-09-23 13:20:34.728 | Sep 23 13:20:34 ip-172-23-0-207 systemd: Unit clamscan.service entered failed state. |
| 2024-09-23 13:20:34.728 | Sep 23 13:20:34 ip-172-23-0-207 systemd: clamscan.service failed. |
| 2024-09-23 13:20:34.728 | Sep 23 13:20:34 ip-172-23-0-207 systemd: Cannot add dependency job for unit rpcbind.socket, ignoring: Unit is masked. |
| 2024-09-23 13:20:34.978 | Sep 23 13:20:34 ip-172-23-0-207 systemd: Starting ClamAV malware scan of entire file system... |
| 2024-09-23 13:20:35.076 | type=SERVICE_STOP msg=audit(1727097634.500:73205): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=clamscan comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed' |
| 2024-09-23 13:20:35.230 | Sep 23 13:20:34 ip-172-23-0-207 systemd: Started ClamAV malware scan of entire file system. |
---

**Comment by achave11-ucsc** [comment]
@dsotirho-ucsc: "This only happened once on September 23rd and it hasn't reoccurred."
