### ISSUE TITLE
`make test` fails on test_dss_files_proxy with aws credentials in place

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#668]
With `AWS_PROFILE=hca` and `~/.aws` in place, the following error occurs when running make test

```
======================================================================
FAIL: test_dss_files_proxy (service.test_dss_proxy.TestDssProxy) (file_name='foo&bar.txt')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daniel/azul/test/service/test_dss_proxy.py", line 137, in test_dss_files_proxy
    self.assertUrlEqual(re_pre_signed_s3_url, body['Location'])
  File "/Users/daniel/azul/test/service/test_dss_proxy.py", line 49, in assertUrlEqual
    self.assertEqual(sorted(a.args.allitems()), sorted(b.args.allitems()))
AssertionError: Lists differ: [('AWSAccessKeyId', 'test-key'), ('Expires', '1547694853'), ('[156 chars]en')] != [('AWSAccessKeyId', 'AKIAIOSFODNN7EXAMPLE'), ('Expires', '1547[389 chars]AE')]

First differing element 0:
('AWSAccessKeyId', 'test-key')
('AWSAccessKeyId', 'AKIAIOSFODNN7EXAMPLE')

- [('AWSAccessKeyId', 'test-key'),
+ [('AWSAccessKeyId', 'AKIAIOSFODNN7EXAMPLE'),
   ('Expires', '1547694853'),
-  ('Signature', 'bu8ATMDQ6qeZj9SbygF0bgK5tUU='),
+  ('Signature', 'OMiR6lLzWpunHtvGNlWAOEAC/fs='),
   ('response-content-disposition', 'attachment;filename=foo&bar.txt'),
-  ('x-amz-security-token', 'test-session-token')]
+  ('x-amz-security-token',
+   'BQoEXAMPLEH4aoAH0gNCAPyJxz4BlCFFxWNE1OPTgk5TthT+FvwqnKwRcOIfrRh3c/LTo6UDdyJwOOvEVPvLXCrrrUtdnniCEXAMPLE/IvU1dYUg2RVAJBanLiHb4IgRmpRV3zrkuWJOgQs8IZZaIv2BXIa2R4OlgkBN9bkUDNCJiBeb/AXlzBBko7b15fjrBs2+cTQtpZ3CYWFXG8C5zqx37wnOE49mRl/+OtkIKGO7fAE')]

----------------------------------------------------------------------
Ran 5 tests in 13.524s

FAILED (failures=4)
make: *** [test] Error 1
```

To get the error quicker when running `make test`, modify Makefile as below:
```
(.venv) daniel@Daniels-Mac ~/azul $ git diff -c
diff --git a/Makefile b/Makefile
index b81a892..f4c3667 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,7 @@ clean:
        for d in lambdas terraform; do $(MAKE) -C $$d clean; done
 
 test:
-       PYTHONWARNINGS=ignore:ResourceWarning coverage run -m unittest discover test --verbose
+       PYTHONWARNINGS=ignore:ResourceWarning coverage run -m unittest indexer.test_health_check service.test_dss_proxy --verbose
 
 tag:
        @tag_name="$$(date '+deployed/$(AZUL_DEPLOYMENT_STAGE)/%Y-%m-%d__%H-%M')" ; \
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-419)
┆Project Name: azul
┆Issue Number: AZUL-419

**Comment by danielsotirhos** [comment]
Verified issue is now resolved. Closing ticket.
