### ISSUE TITLE
IT fails with `no_index` in `azul_it_flags`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6765]
Bug manifests before and after #6441 but the [PR](https://github.com/DataBiosphere/azul/pull/6760) for that issue affects the concrete steps to reproduce it.

To reproduce, in a functional deployment,

1. Set `azul_it_flags` to `'no_delete'`
2. Run IT (it succeeds)
3. Set `'azul_it_flags'` to `'no_index no_delete'`
4. Run IT again

The IT fails with

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest.test_indexing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul.hannes.local/test/azul_test_case.py", line 259, in wrapped
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul.hannes.local/test/integration_test.py", line 437, in test_indexing
    public_source = one(s for s in indexed_sources if s not in ma_sources)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannes/workspace/hca/azul.hannes.local/.venv/lib/python3.12/site-packages/more_itertools/more.py", line 575, in one
    raise too_long or ValueError(msg)
ValueError: Expected exactly one item in iterable, but got TDRSourceRef(id='cc6e85e6-6e30-4bf0-8c52-56fbd8a1bdaf', spec=TDRSourceSpec(prefix=Prefix(common='1', partition=1), type=<Type.bigquery: 'bigquery'>, domain=<Domain.gcp: 'gcp'>, subdomain='datarepo-dev-6fdac3db', name='hca_dev_e8808cc84ca0409680f2bba73600cba6__20210902_20210907')), TDRSourceRef(id='2c4ec571-f489-4277-b215-da8dedd86803', spec=TDRSourceSpec(prefix=Prefix(common='', partition=1), type=<Type.bigquery: 'bigquery'>, domain=<Domain.gcp: 'gcp'>, subdomain='datarepo-dev-d4b988d6', name='hca_dev_a004b1501c364af69bbd070c06dbc17d__20210830_20210903')), and perhaps more.

----------------------------------------------------------------------
Ran 18 tests in 79.707s

FAILED (errors=1, skipped=1)
make: *** [integration_test] Error 1
```

**Comment by achave11-ucsc** [comment]
Spike to diagnose and propose solution.

**Comment by achave11-ucsc** [comment]
Blocker landed.

**Comment by nadove-ucsc** [comment]
The condition [`if s not in ma_sources`](https://github.com/DataBiosphere/azul/blob/817a054f29c3a621485f75c5cd5ece0f92e9af63/test/integration_test.py#L437) always returns false because the sources in `ma_sources` do not have a prefix while those is `indexed_sources` do:

```
>>> source_id = 'cddb722a-4229-47bb-ba86-736b7898406f'
>>> s1 = one(s for s in ma_sources if s.id == source_id)
>>> s2 = one(s for s in indexed_sources if s.id == source_id)
>>> s1 == s2
False
>>> s1.spec.prefix
>>> s2.spec.prefix
Prefix(common='5a', partition=1)
```

There is [an outstanding FIXME](https://github.com/DataBiosphere/azul/issues/3250) to disallow instances of `SourceRef` with the same Id from having different specs. The [class docstring for `SourceRef`](https://github.com/DataBiosphere/azul/blob/817a054f29c3a621485f75c5cd5ece0f92e9af63/src/azul/indexer/__init__.py#L473) and the [method docstring for `SourceRef.__new__`](https://github.com/DataBiosphere/azul/blob/817a054f29c3a621485f75c5cd5ece0f92e9af63/src/azul/indexer/__init__.py#L500) falsely claim that this is already enforced. We may need to rethink how the interning should work now that prefixes are optional.

**Comment by nadove-ucsc** [comment]
This solves the immediate problem with the IT:

```diff
Subject: [PATCH] CHANGES
---
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision 72ec3eef3b18ba3709c94c774bebb9ab969e2f44)
+++ b/test/integration_test.py	(date 1734577395802)
@@ -433,9 +433,9 @@
                 with self._service_account_credentials:
                     fqids = self._get_indexed_bundles(catalog)
                 indexed_sources = {fqid.source for fqid in fqids}
-                ma_sources = self.managed_access_sources_by_catalog[catalog]
-                public_source = one(s for s in indexed_sources if s not in ma_sources)
-                ma_source = only(s for s in indexed_sources if s in ma_sources)
+                ma_source_ids = {s.id for s in self.managed_access_sources_by_catalog[catalog]}
+                public_source = one(s for s in indexed_sources if s.id not in ma_source_ids)
+                ma_source = only(s for s in indexed_sources if s.id in ma_source_ids)
                 notifications = []
             catalogs.append(Catalog(name=catalog,
                                     bundles=fqids,
```

**Comment by hannes-ucsc** [comment]
> This solves the immediate problem with the IT:

Assignee to address that in a PR.

> The [class docstring for SourceRef](https://github.com/DataBiosphere/azul/blob/817a054f29c3a621485f75c5cd5ece0f92e9af63/src/azul/indexer/__init__.py#L473) and the [method docstring for SourceRef.__new__](https://github.com/DataBiosphere/azul/blob/817a054f29c3a621485f75c5cd5ece0f92e9af63/src/azul/indexer/__init__.py#L500) falsely claim that this is already enforced.

Assignee to fix the docstrings so that they reflect reality. The outdated term *source name* or just *name* should be replaced with `spec`.

**Comment by hannes-ucsc** [comment]
I closed #3250 and replaced it with #6778 to address the interning and equality issues with `SourceRef` and `SourceSpec`.

Two `SourceRef` instances should be equal if and only if their `.id` is equal. There should be no two `SourceRef` instances with equal `.id` and unequal `.spec`. I'm unsure if this should be enforced via interning or in the `__eq__` override. The enforcement via interning would be deterministic. Detecting a discrepancy in the `__eq__` override would be probabilistic. However, the interning involves a lock which could limit concurrency. I also doubt that the memory savings obtained by interning are significant. More thought and/or experimentation needs to go into this.

Two `SourceSpec` instances should be equal if an only if they're of the same class and and equal in the value of all of their attributes. Instead of having an optional prefix in the `SourceSpec` base class, there should be a decorator class called `SourcePartition` with a mandatory `prefix` attribute, and another attribute called `spec` for the `SourceSpec` instance that it decorates. I'm not sure if `SourcePartition` would be a subclass of `SourceSpec` or not. If not, the `SOURCE_SPEC` type parameter to the `SourceRef` type would not have a bound. But either way, a `SourcePartition` instance would never be equal to another `SourceSpec` instance that is not a `SourcePartition`. That's what would make the `.id` indirection in the fix for #67651 redundant.

**Comment by hannes-ucsc** [comment]
Assignee to remove FIXME comment(s) for #3250 and add FIXME comment for #6778 instead.

Assignee to add FIXME comment for #6778 above the [immediate fix](https://github.com/DataBiosphere/azul/issues/6765#issuecomment-2552684563) for this issue.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce. And also tend to https://github.com/DataBiosphere/azul/issues/4598#issuecomment-2576113253.
