### ISSUE TITLE
Error requesting specimens: 'No mapping found for [contents.files.name.keyword] in order to sort on')

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#702]
https://service.dev.explore.data.humancellatlas.org/repository/specimens?filters=%7B%22file%22%3A%7B%22disease%22%3A%7B%22is%22%3A%5B%22glioblastoma%22%2C%22H%20syndrome%22%5D%7D%2C%22libraryConstructionApproach%22%3A%7B%22is%22%3A%5B%22Smart-seq2%22%5D%7D%7D%7D&size=15&sort=fileName&order=asc

Requesting the above gives me a 500 error

Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 272, in get_specimen_data
    entity_type='specimens')
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 514, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'No mapping found for [contents.files.name.keyword] in order to sort on')

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-435)
┆Project Name: azul
┆Issue Number: AZUL-435

**Comment by NoopDog** [comment]
This is causing the hanging "loading" on specimens. Will also create a ticket in the browser repo to show an error page when we get an api error instead of hanging.

**Comment by hannes-ucsc** [comment]
The URL in the OP is `/repository/specimens` while the sort is set to `fileName`. Specimens can't be sorted by file name at the moment. If that is desired we would need to 
define the specifics of that non-trivial sort since specimens can be associated with more than file.

The error should be a 4xx error, not a 5xx errror but that's tracked in #280.
