### ISSUE TITLE
Integration test fails on fresh deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#751]
Running integration test immediately after standing up a deployment fails with 

```
Traceback (most recent call last):
  File "/build/.venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/build/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/build/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='service.sandbox.dev.explore.data.humancellatlas.org', port=443): Max retries exceeded with url: /repository/files?filters=%7B%22file%22%3A%7B%22project%22%3A%7B%22is%22%3A%5B%22integration-test_fdde5c90-c5bb-42b0-a12c-d79454b4da06_fcd%22%5D%7D%7D%7D&order=desc&sort=entryId&size=100 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f48744a5668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Poking around on the Gitlab instance:

```
$ ssh SNIP -p SNAP
[rancher@ip-172-71-0-156 ~]$ ping service.sandbox.dev.explore.data.humancellatlas.org
ping: bad address 'service.sandbox.dev.explore.data.humancellatlas.org'
[rancher@ip-172-71-0-156 ~]$ ping service.dev.explore.data.humancellatlas.org
PING service.dev.explore.data.humancellatlas.org (99.84.104.29): 56 data bytes
64 bytes from 99.84.104.29: seq=0 ttl=242 time=2.754 ms
^C
```

10min later it's fixed.

```
[rancher@ip-172-71-0-156 ~]$ nslookup service.sandbox.dev.explore.data.humancellatlas.org
Server:    172.71.0.2
Address 1: 172.71.0.2

Name:      service.sandbox.dev.explore.data.humancellatlas.org
Address 1: 13.249.39.9 server-13-249-39-9.iad89.r.cloudfront.net
Address 2: 13.249.39.11 server-13-249-39-11.iad89.r.cloudfront.net
Address 3: 13.249.39.128 server-13-249-39-128.iad89.r.cloudfront.net
Address 4: 13.249.39.207 server-13-249-39-207.iad89.r.cloudfront.net
[rancher@ip-172-71-0-156 ~]$ ping service.dev.explore.data.humancellatlas.org
PING service.dev.explore.data.humancellatlas.org (99.84.181.9): 56 data bytes
64 bytes from 99.84.181.9: seq=0 ttl=242 time=1.802 ms
64 bytes from 99.84.181.9: seq=1 ttl=242 time=1.434 ms
^C
--- service.dev.explore.data.humancellatlas.org ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 1.434/1.618/1.802 ms
[rancher@ip-172-71-0-156 ~]$
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-464)
┆Project Name: azul
┆Issue Number: AZUL-464

**Comment by hannes-ucsc** [comment]
Can't reproduce.
