### ISSUE TITLE
Possible intermittent failure in integration tests

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#877]
This came up while Promoting to staging. This is the failed run https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/599

and the stack trace for convenience:
```

======================================================================
ERROR: test_webservice_and_indexer (local_integration_test.IntegrationTest) (filter={'file': {'organ': {'is': ['brain']}, 'fileFormat': {'is': ['bai']}}}, format=None, path='/manifest/files')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/azul/azul/test/local_integration_test.py", line 86, in test_webservice_and_indexer
    response = self.check_endpoint_is_working(config.service_endpoint(), path, query)
  File "/builds/azul/azul/test/local_integration_test.py", line 107, in check_endpoint_is_working
    response.raise_for_status()
  File "/build/.venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://service.staging.explore.data.humancellatlas.org/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMjc4YmEzMGMtZTY2MS00Y2ZkLTkxN2YtZTI4OTJjYzI0YjNkIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ==

----------------------------------------------------------------------
Ran 1 test in 148.446s
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-545)
┆Project Name: azul
┆Issue Number: AZUL-545

**Comment by mjkrause** [comment]
I think this is related to changed added in #565. Is it _intermittent_ because the tests passed previously? Or is this the first time to promote to staging after #565 had been merged and it failed?

**Comment by jessebrennan** [comment]
@mjkrause this change was probably tested in the sandbox and then tested again in integration. The first time it ran in staging it failed. It's possible I suppose that running it again in staging could result in a failure.
