### ISSUE TITLE
Support for imaging bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#881]
When indexing `94f2ba52-30c8-4de0-a78e-f95a3f8deb9c.2019-04-03T103426.471000Z` in staging, we currently get 

```
Traceback (most recent call last):
  File "/var/task/app.py", line 182, in index
    contributions = indexer.transform(notification)
  File "/var/task/azul/indexer.py", line 101, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 339, in transform
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 636, in __init__
    core_cls = core_types[entity_cls]
KeyError: None
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-548)
┆Project Name: azul
┆Issue Number: AZUL-548
┆Epic: Imaging support

**Comment by hannes-ucsc** [comment]
Demoed on 5/28/2019
