### ISSUE TITLE
Integration test succeeds even if two bundles fail to be indexed

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#969]
https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/1255

Note the queue levels never reach zero because two bundles fail to be indexed. These appear to be the two known bundles in DSS staging that produce a KeyError when loading them from the DSS. To reproduce, set prefix to `a44`.

Please investigate ASAP.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-600)
┆Project Name: azul
┆Issue Number: AZUL-600

**Comment by hannes-ucsc** [comment]
```
[WARNING]	2019-05-08T08:48:06.115Z	8829519f-2bd3-5636-8683-04d3b2295d4b	Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': '6b839669-eee0-487c-8125-75e3ccdbc601', 'subscription_id': '8cbcbb9a-be6c-4a7e-8919-45a5ba18a9e9', 'es_query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'bool': {'should': [{'terms': {'files.project_json.provenance.document_id': ['2c4724a4-7252-409e-b008-ff5c127c7e89', '08e7b6ba-5825-47e9-be2d-7978533c5f8c', '019a935b-ea35-4d83-be75-e1a688179328', 'a5ae0428-476c-46d2-a9f2-aad955b149aa', 'adabd2bd-3968-4e77-b0df-f200f7351661', '67bc798b-a34a-4104-8cab-cad648471f69', '81b5f43d-3c20-4575-9efa-bfb0b070a6e3', '519b58ef-6462-4ed3-8c0d-375b54f53c31', '2cd14cf5-f8e0-4c97-91a2-9e8957f41ea8', '1f9a699a-262c-40a0-8b2c-7ba960ca388c', '62aa3211-bf52-4873-9029-0bcc1d09e553', 'a71dee10-9a4d-4ea2-a6f3-ae7314112cf1', 'adb384b2-cd5e-4cf5-9205-5f066474005f', '46c58e08-4518-4e45-acfe-bdab2434975d', '3eaad325-3666-4b65-a4ed-e23ff71222c1']}}, {'range': {'manifest.version': {'gte': '2019-04-03'}}}]}}]}}}, 'match': {'bundle_uuid': 'e8f5ec35-688e-49b7-a2ed-1848321da136', 'bundle_version': '2019-05-08T063816.935984Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 182, in index
    contributions = indexer.transform(notification)
  File "/var/task/azul/indexer.py", line 103, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 435, in transform
    metadata_files=metadata_files)
  File "/var/task/humancellatlas/data/metadata/api.py", line 720, in __init__
    self.files = from_json_vx(File, manifest=self.manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 714, in from_json_vx
    return from_json(core_cls, json_entities, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 683, in from_json
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 683, in <dictcomp>
    return {entity.document_id: entity for entity in entities}
  File "/var/task/humancellatlas/data/metadata/api.py", line 682, in <genexpr>
    entities = (core_cls.from_json(entity, **kwargs) for entity in json_entities)
  File "/var/task/humancellatlas/data/metadata/api.py", line 37, in from_json
    return sub_cls(json, **kwargs)
  File "/var/task/humancellatlas/data/metadata/api.py", line 601, in __init__
    super().__init__(json, manifest)
  File "/var/task/humancellatlas/data/metadata/api.py", line 575, in __init__
    self.manifest_entry = manifest[core['file_name']]
KeyError: 'R1.fastq.gz'
```

**Comment by hannes-ucsc** [comment]
The bundles don't start with the prefix and their versions are newer, so they must be from the DCP test running concurrently. Need to investigate.
